// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "digitrec_knn_vote.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic digitrec_knn_vote::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic digitrec_knn_vote::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<4> digitrec_knn_vote::ap_ST_st1_fsm_0 = "1";
const sc_lv<4> digitrec_knn_vote::ap_ST_st2_fsm_1 = "10";
const sc_lv<4> digitrec_knn_vote::ap_ST_st3_fsm_2 = "100";
const sc_lv<4> digitrec_knn_vote::ap_ST_st4_fsm_3 = "1000";
const sc_lv<32> digitrec_knn_vote::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> digitrec_knn_vote::ap_const_lv1_1 = "1";
const sc_lv<32> digitrec_knn_vote::ap_const_lv32_1 = "1";
const sc_lv<32> digitrec_knn_vote::ap_const_lv32_2 = "10";
const sc_lv<32> digitrec_knn_vote::ap_const_lv32_3 = "11";
const sc_lv<2> digitrec_knn_vote::ap_const_lv2_3 = "11";
const sc_lv<2> digitrec_knn_vote::ap_const_lv2_2 = "10";
const sc_lv<3> digitrec_knn_vote::ap_const_lv3_5 = "101";
const sc_lv<3> digitrec_knn_vote::ap_const_lv3_4 = "100";
const sc_lv<3> digitrec_knn_vote::ap_const_lv3_7 = "111";
const sc_lv<3> digitrec_knn_vote::ap_const_lv3_6 = "110";
const sc_lv<4> digitrec_knn_vote::ap_const_lv4_9 = "1001";
const sc_lv<4> digitrec_knn_vote::ap_const_lv4_8 = "1000";
const sc_lv<4> digitrec_knn_vote::ap_const_lv4_0 = "0000";

digitrec_knn_vote::digitrec_knn_vote(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_agg_result_V_0_agg_result_V_02_1_fu_654_p1);
    sensitive << ( agg_result_V_0_agg_result_V_02_3_fu_646_p3 );

    SC_METHOD(thread_agg_result_V_0_agg_result_V_02_2_fu_635_p3);
    sensitive << ( tmp_6_3_reg_980 );

    SC_METHOD(thread_agg_result_V_0_agg_result_V_02_3_fu_646_p3);
    sensitive << ( tmp_s_fu_642_p2 );
    sensitive << ( agg_result_V_0_agg_result_V_02_2_fu_635_p3 );
    sensitive << ( agg_result_V_0_agg_result_V_s_fu_632_p1 );

    SC_METHOD(thread_agg_result_V_0_agg_result_V_02_4_fu_668_p3);
    sensitive << ( tmp_6_5_fu_663_p2 );

    SC_METHOD(thread_agg_result_V_0_agg_result_V_02_5_fu_681_p3);
    sensitive << ( tmp_1_fu_676_p2 );
    sensitive << ( agg_result_V_0_agg_result_V_02_4_fu_668_p3 );
    sensitive << ( agg_result_V_0_agg_result_V_02_1_fu_654_p1 );

    SC_METHOD(thread_agg_result_V_0_agg_result_V_02_6_fu_860_p1);
    sensitive << ( agg_result_V_0_agg_result_V_02_7_fu_853_p3 );

    SC_METHOD(thread_agg_result_V_0_agg_result_V_02_7_fu_853_p3);
    sensitive << ( agg_result_V_0_agg_result_V_02_5_reg_1008 );
    sensitive << ( tmp_2_fu_848_p2 );
    sensitive << ( agg_result_V_0_agg_result_V_02_fu_840_p3 );

    SC_METHOD(thread_agg_result_V_0_agg_result_V_02_8_fu_930_p3);
    sensitive << ( tmp_6_9_fu_924_p2 );

    SC_METHOD(thread_agg_result_V_0_agg_result_V_02_9_fu_944_p3);
    sensitive << ( tmp_3_fu_938_p2 );
    sensitive << ( agg_result_V_0_agg_result_V_02_8_fu_930_p3 );
    sensitive << ( agg_result_V_0_agg_result_V_02_6_fu_860_p1 );

    SC_METHOD(thread_agg_result_V_0_agg_result_V_02_fu_840_p3);
    sensitive << ( tmp_6_7_fu_836_p2 );

    SC_METHOD(thread_agg_result_V_0_agg_result_V_s_fu_632_p1);
    sensitive << ( tmp_6_1_reg_952 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );

    SC_METHOD(thread_ap_return);
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( agg_result_V_0_agg_result_V_02_9_fu_944_p3 );
    sensitive << ( ap_return_preg );

    SC_METHOD(thread_ap_sig_104);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_156);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_21);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_85);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_cseq_ST_st1_fsm_0);
    sensitive << ( ap_sig_21 );

    SC_METHOD(thread_ap_sig_cseq_ST_st2_fsm_1);
    sensitive << ( ap_sig_85 );

    SC_METHOD(thread_ap_sig_cseq_ST_st3_fsm_2);
    sensitive << ( ap_sig_104 );

    SC_METHOD(thread_ap_sig_cseq_ST_st4_fsm_3);
    sensitive << ( ap_sig_156 );

    SC_METHOD(thread_min_2_min_1_fu_428_p3);
    sensitive << ( tmp_6_1_fu_422_p2 );
    sensitive << ( sum_1_3_fu_416_p2 );
    sensitive << ( sum_0_3_fu_374_p2 );

    SC_METHOD(thread_min_2_min_2_fu_524_p3);
    sensitive << ( min_2_min_1_reg_957 );
    sensitive << ( sum_2_3_reg_963 );
    sensitive << ( tmp_6_2_fu_520_p2 );

    SC_METHOD(thread_min_2_min_3_fu_535_p3);
    sensitive << ( sum_3_3_reg_969 );
    sensitive << ( tmp_6_3_fu_530_p2 );
    sensitive << ( min_2_min_2_fu_524_p3 );

    SC_METHOD(thread_min_2_min_4_fu_658_p3);
    sensitive << ( min_2_min_3_reg_986 );
    sensitive << ( sum_4_3_reg_991 );
    sensitive << ( tmp_6_4_reg_996 );

    SC_METHOD(thread_min_2_min_5_fu_689_p3);
    sensitive << ( sum_5_3_reg_1002 );
    sensitive << ( min_2_min_4_fu_658_p3 );
    sensitive << ( tmp_6_5_fu_663_p2 );

    SC_METHOD(thread_min_2_min_6_fu_744_p3);
    sensitive << ( tmp_6_6_fu_738_p2 );
    sensitive << ( sum_6_3_fu_732_p2 );
    sensitive << ( min_2_min_5_fu_689_p3 );

    SC_METHOD(thread_min_2_min_7_fu_864_p3);
    sensitive << ( min_2_min_6_reg_1018 );
    sensitive << ( sum_7_3_reg_1024 );
    sensitive << ( tmp_6_7_fu_836_p2 );

    SC_METHOD(thread_min_2_min_8_fu_875_p3);
    sensitive << ( sum_8_3_reg_1030 );
    sensitive << ( min_2_min_7_fu_864_p3 );
    sensitive << ( tmp_6_8_fu_870_p2 );

    SC_METHOD(thread_sum_0_3_fu_374_p2);
    sensitive << ( tmp1_cast_fu_360_p1 );
    sensitive << ( tmp2_cast_fu_370_p1 );

    SC_METHOD(thread_sum_1_3_fu_416_p2);
    sensitive << ( tmp4_cast_fu_402_p1 );
    sensitive << ( tmp5_cast_fu_412_p1 );

    SC_METHOD(thread_sum_2_3_fu_472_p2);
    sensitive << ( tmp7_cast_fu_458_p1 );
    sensitive << ( tmp8_cast_fu_468_p1 );

    SC_METHOD(thread_sum_3_3_fu_514_p2);
    sensitive << ( tmp10_cast_fu_500_p1 );
    sensitive << ( tmp11_cast_fu_510_p1 );

    SC_METHOD(thread_sum_4_3_fu_578_p2);
    sensitive << ( tmp13_cast_fu_564_p1 );
    sensitive << ( tmp14_cast_fu_574_p1 );

    SC_METHOD(thread_sum_5_3_fu_626_p2);
    sensitive << ( tmp16_cast_fu_612_p1 );
    sensitive << ( tmp17_cast_fu_622_p1 );

    SC_METHOD(thread_sum_6_3_fu_732_p2);
    sensitive << ( tmp19_cast_fu_718_p1 );
    sensitive << ( tmp20_cast_fu_728_p1 );

    SC_METHOD(thread_sum_7_3_fu_788_p2);
    sensitive << ( tmp22_cast_fu_774_p1 );
    sensitive << ( tmp23_cast_fu_784_p1 );

    SC_METHOD(thread_sum_8_3_fu_830_p2);
    sensitive << ( tmp25_cast_fu_816_p1 );
    sensitive << ( tmp26_cast_fu_826_p1 );

    SC_METHOD(thread_sum_9_3_fu_918_p2);
    sensitive << ( tmp27_cast_fu_904_p1 );
    sensitive << ( tmp28_cast_fu_914_p1 );

    SC_METHOD(thread_tmp10_cast_fu_500_p1);
    sensitive << ( tmp_fu_494_p2 );

    SC_METHOD(thread_tmp10_fu_606_p2);
    sensitive << ( tmp_8_5_2_cast_fu_598_p1 );
    sensitive << ( tmp_8_5_1_cast_fu_594_p1 );

    SC_METHOD(thread_tmp11_cast_fu_510_p1);
    sensitive << ( tmp3_fu_504_p2 );

    SC_METHOD(thread_tmp11_fu_616_p2);
    sensitive << ( tmp_8_5_3_cast_fu_602_p1 );
    sensitive << ( tmp_8_5_cast_fu_590_p1 );

    SC_METHOD(thread_tmp12_fu_712_p2);
    sensitive << ( tmp_8_6_2_cast_fu_704_p1 );
    sensitive << ( tmp_8_6_1_cast_fu_700_p1 );

    SC_METHOD(thread_tmp13_cast_fu_564_p1);
    sensitive << ( tmp6_fu_558_p2 );

    SC_METHOD(thread_tmp13_fu_722_p2);
    sensitive << ( tmp_8_6_3_cast_fu_708_p1 );
    sensitive << ( tmp_8_6_cast_fu_696_p1 );

    SC_METHOD(thread_tmp14_cast_fu_574_p1);
    sensitive << ( tmp9_fu_568_p2 );

    SC_METHOD(thread_tmp14_fu_768_p2);
    sensitive << ( tmp_8_7_2_cast_fu_760_p1 );
    sensitive << ( tmp_8_7_1_cast_fu_756_p1 );

    SC_METHOD(thread_tmp15_fu_778_p2);
    sensitive << ( tmp_8_7_3_cast_fu_764_p1 );
    sensitive << ( tmp_8_7_cast_fu_752_p1 );

    SC_METHOD(thread_tmp16_cast_fu_612_p1);
    sensitive << ( tmp10_fu_606_p2 );

    SC_METHOD(thread_tmp16_fu_810_p2);
    sensitive << ( tmp_8_8_2_cast_fu_802_p1 );
    sensitive << ( tmp_8_8_1_cast_fu_798_p1 );

    SC_METHOD(thread_tmp17_cast_fu_622_p1);
    sensitive << ( tmp11_fu_616_p2 );

    SC_METHOD(thread_tmp17_fu_820_p2);
    sensitive << ( tmp_8_8_3_cast_fu_806_p1 );
    sensitive << ( tmp_8_8_cast_fu_794_p1 );

    SC_METHOD(thread_tmp18_fu_898_p2);
    sensitive << ( tmp_8_9_1_cast_fu_886_p1 );
    sensitive << ( tmp_8_9_cast_fu_882_p1 );

    SC_METHOD(thread_tmp19_cast_fu_718_p1);
    sensitive << ( tmp12_fu_712_p2 );

    SC_METHOD(thread_tmp19_fu_908_p2);
    sensitive << ( tmp_8_9_3_cast_fu_894_p1 );
    sensitive << ( tmp_8_9_2_cast_fu_890_p1 );

    SC_METHOD(thread_tmp1_cast_fu_360_p1);
    sensitive << ( tmp1_fu_354_p2 );

    SC_METHOD(thread_tmp1_fu_354_p2);
    sensitive << ( tmp_8_0_2_cast_fu_346_p1 );
    sensitive << ( tmp_8_0_1_cast_fu_342_p1 );

    SC_METHOD(thread_tmp20_cast_fu_728_p1);
    sensitive << ( tmp13_fu_722_p2 );

    SC_METHOD(thread_tmp22_cast_fu_774_p1);
    sensitive << ( tmp14_fu_768_p2 );

    SC_METHOD(thread_tmp23_cast_fu_784_p1);
    sensitive << ( tmp15_fu_778_p2 );

    SC_METHOD(thread_tmp25_cast_fu_816_p1);
    sensitive << ( tmp16_fu_810_p2 );

    SC_METHOD(thread_tmp26_cast_fu_826_p1);
    sensitive << ( tmp17_fu_820_p2 );

    SC_METHOD(thread_tmp27_cast_fu_904_p1);
    sensitive << ( tmp18_fu_898_p2 );

    SC_METHOD(thread_tmp28_cast_fu_914_p1);
    sensitive << ( tmp19_fu_908_p2 );

    SC_METHOD(thread_tmp2_cast_fu_370_p1);
    sensitive << ( tmp2_fu_364_p2 );

    SC_METHOD(thread_tmp2_fu_364_p2);
    sensitive << ( tmp_8_0_3_cast_fu_350_p1 );
    sensitive << ( tmp_8_cast_fu_338_p1 );

    SC_METHOD(thread_tmp3_fu_504_p2);
    sensitive << ( tmp_8_3_3_cast_fu_490_p1 );
    sensitive << ( tmp_8_3_cast_fu_478_p1 );

    SC_METHOD(thread_tmp4_cast_fu_402_p1);
    sensitive << ( tmp4_fu_396_p2 );

    SC_METHOD(thread_tmp4_fu_396_p2);
    sensitive << ( tmp_8_1_2_cast_fu_388_p1 );
    sensitive << ( tmp_8_1_1_cast_fu_384_p1 );

    SC_METHOD(thread_tmp5_cast_fu_412_p1);
    sensitive << ( tmp5_fu_406_p2 );

    SC_METHOD(thread_tmp5_fu_406_p2);
    sensitive << ( tmp_8_1_3_cast_fu_392_p1 );
    sensitive << ( tmp_8_1_cast_fu_380_p1 );

    SC_METHOD(thread_tmp6_fu_558_p2);
    sensitive << ( tmp_8_4_2_cast_fu_550_p1 );
    sensitive << ( tmp_8_4_1_cast_fu_546_p1 );

    SC_METHOD(thread_tmp7_cast_fu_458_p1);
    sensitive << ( tmp7_fu_452_p2 );

    SC_METHOD(thread_tmp7_fu_452_p2);
    sensitive << ( tmp_8_2_2_cast_fu_444_p1 );
    sensitive << ( tmp_8_2_1_cast_fu_440_p1 );

    SC_METHOD(thread_tmp8_cast_fu_468_p1);
    sensitive << ( tmp8_fu_462_p2 );

    SC_METHOD(thread_tmp8_fu_462_p2);
    sensitive << ( tmp_8_2_3_cast_fu_448_p1 );
    sensitive << ( tmp_8_2_cast_fu_436_p1 );

    SC_METHOD(thread_tmp9_fu_568_p2);
    sensitive << ( tmp_8_4_3_cast_fu_554_p1 );
    sensitive << ( tmp_8_4_cast_fu_542_p1 );

    SC_METHOD(thread_tmp_1_fu_676_p2);
    sensitive << ( tmp_6_4_reg_996 );
    sensitive << ( tmp_6_5_fu_663_p2 );

    SC_METHOD(thread_tmp_2_fu_848_p2);
    sensitive << ( tmp_6_6_reg_1013 );
    sensitive << ( tmp_6_7_fu_836_p2 );

    SC_METHOD(thread_tmp_3_fu_938_p2);
    sensitive << ( tmp_6_8_fu_870_p2 );
    sensitive << ( tmp_6_9_fu_924_p2 );

    SC_METHOD(thread_tmp_6_1_fu_422_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( sum_1_3_fu_416_p2 );
    sensitive << ( sum_0_3_fu_374_p2 );

    SC_METHOD(thread_tmp_6_2_fu_520_p2);
    sensitive << ( min_2_min_1_reg_957 );
    sensitive << ( sum_2_3_reg_963 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_tmp_6_3_fu_530_p2);
    sensitive << ( sum_3_3_reg_969 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( min_2_min_2_fu_524_p3 );

    SC_METHOD(thread_tmp_6_4_fu_584_p2);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( min_2_min_3_fu_535_p3 );
    sensitive << ( sum_4_3_fu_578_p2 );

    SC_METHOD(thread_tmp_6_5_fu_663_p2);
    sensitive << ( sum_5_3_reg_1002 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( min_2_min_4_fu_658_p3 );

    SC_METHOD(thread_tmp_6_6_fu_738_p2);
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( sum_6_3_fu_732_p2 );
    sensitive << ( min_2_min_5_fu_689_p3 );

    SC_METHOD(thread_tmp_6_7_fu_836_p2);
    sensitive << ( min_2_min_6_reg_1018 );
    sensitive << ( sum_7_3_reg_1024 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );

    SC_METHOD(thread_tmp_6_8_fu_870_p2);
    sensitive << ( sum_8_3_reg_1030 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( min_2_min_7_fu_864_p3 );

    SC_METHOD(thread_tmp_6_9_fu_924_p2);
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( sum_9_3_fu_918_p2 );
    sensitive << ( min_2_min_8_fu_875_p3 );

    SC_METHOD(thread_tmp_8_0_1_cast_fu_342_p1);
    sensitive << ( knn_set_0_1_V_read );

    SC_METHOD(thread_tmp_8_0_2_cast_fu_346_p1);
    sensitive << ( knn_set_0_2_V_read );

    SC_METHOD(thread_tmp_8_0_3_cast_fu_350_p1);
    sensitive << ( knn_set_0_3_V_read );

    SC_METHOD(thread_tmp_8_1_1_cast_fu_384_p1);
    sensitive << ( knn_set_1_1_V_read );

    SC_METHOD(thread_tmp_8_1_2_cast_fu_388_p1);
    sensitive << ( knn_set_1_2_V_read );

    SC_METHOD(thread_tmp_8_1_3_cast_fu_392_p1);
    sensitive << ( knn_set_1_3_V_read );

    SC_METHOD(thread_tmp_8_1_cast_fu_380_p1);
    sensitive << ( knn_set_1_0_V_read );

    SC_METHOD(thread_tmp_8_2_1_cast_fu_440_p1);
    sensitive << ( knn_set_2_1_V_read );

    SC_METHOD(thread_tmp_8_2_2_cast_fu_444_p1);
    sensitive << ( knn_set_2_2_V_read );

    SC_METHOD(thread_tmp_8_2_3_cast_fu_448_p1);
    sensitive << ( knn_set_2_3_V_read );

    SC_METHOD(thread_tmp_8_2_cast_fu_436_p1);
    sensitive << ( knn_set_2_0_V_read );

    SC_METHOD(thread_tmp_8_3_1_cast_fu_482_p1);
    sensitive << ( knn_set_3_1_V_read );

    SC_METHOD(thread_tmp_8_3_2_cast_fu_486_p1);
    sensitive << ( knn_set_3_2_V_read );

    SC_METHOD(thread_tmp_8_3_3_cast_fu_490_p1);
    sensitive << ( knn_set_3_3_V_read );

    SC_METHOD(thread_tmp_8_3_cast_fu_478_p1);
    sensitive << ( knn_set_3_0_V_read );

    SC_METHOD(thread_tmp_8_4_1_cast_fu_546_p1);
    sensitive << ( knn_set_4_1_V_read );

    SC_METHOD(thread_tmp_8_4_2_cast_fu_550_p1);
    sensitive << ( knn_set_4_2_V_read );

    SC_METHOD(thread_tmp_8_4_3_cast_fu_554_p1);
    sensitive << ( knn_set_4_3_V_read );

    SC_METHOD(thread_tmp_8_4_cast_fu_542_p1);
    sensitive << ( knn_set_4_0_V_read );

    SC_METHOD(thread_tmp_8_5_1_cast_fu_594_p1);
    sensitive << ( knn_set_5_1_V_read );

    SC_METHOD(thread_tmp_8_5_2_cast_fu_598_p1);
    sensitive << ( knn_set_5_2_V_read );

    SC_METHOD(thread_tmp_8_5_3_cast_fu_602_p1);
    sensitive << ( knn_set_5_3_V_read );

    SC_METHOD(thread_tmp_8_5_cast_fu_590_p1);
    sensitive << ( knn_set_5_0_V_read );

    SC_METHOD(thread_tmp_8_6_1_cast_fu_700_p1);
    sensitive << ( knn_set_6_1_V_read );

    SC_METHOD(thread_tmp_8_6_2_cast_fu_704_p1);
    sensitive << ( knn_set_6_2_V_read );

    SC_METHOD(thread_tmp_8_6_3_cast_fu_708_p1);
    sensitive << ( knn_set_6_3_V_read );

    SC_METHOD(thread_tmp_8_6_cast_fu_696_p1);
    sensitive << ( knn_set_6_0_V_read );

    SC_METHOD(thread_tmp_8_7_1_cast_fu_756_p1);
    sensitive << ( knn_set_7_1_V_read );

    SC_METHOD(thread_tmp_8_7_2_cast_fu_760_p1);
    sensitive << ( knn_set_7_2_V_read );

    SC_METHOD(thread_tmp_8_7_3_cast_fu_764_p1);
    sensitive << ( knn_set_7_3_V_read );

    SC_METHOD(thread_tmp_8_7_cast_fu_752_p1);
    sensitive << ( knn_set_7_0_V_read );

    SC_METHOD(thread_tmp_8_8_1_cast_fu_798_p1);
    sensitive << ( knn_set_8_1_V_read );

    SC_METHOD(thread_tmp_8_8_2_cast_fu_802_p1);
    sensitive << ( knn_set_8_2_V_read );

    SC_METHOD(thread_tmp_8_8_3_cast_fu_806_p1);
    sensitive << ( knn_set_8_3_V_read );

    SC_METHOD(thread_tmp_8_8_cast_fu_794_p1);
    sensitive << ( knn_set_8_0_V_read );

    SC_METHOD(thread_tmp_8_9_1_cast_fu_886_p1);
    sensitive << ( knn_set_9_1_V_read );

    SC_METHOD(thread_tmp_8_9_2_cast_fu_890_p1);
    sensitive << ( knn_set_9_2_V_read );

    SC_METHOD(thread_tmp_8_9_3_cast_fu_894_p1);
    sensitive << ( knn_set_9_3_V_read );

    SC_METHOD(thread_tmp_8_9_cast_fu_882_p1);
    sensitive << ( knn_set_9_0_V_read );

    SC_METHOD(thread_tmp_8_cast_fu_338_p1);
    sensitive << ( knn_set_0_0_V_read );

    SC_METHOD(thread_tmp_fu_494_p2);
    sensitive << ( tmp_8_3_2_cast_fu_486_p1 );
    sensitive << ( tmp_8_3_1_cast_fu_482_p1 );

    SC_METHOD(thread_tmp_s_fu_642_p2);
    sensitive << ( tmp_6_2_reg_975 );
    sensitive << ( tmp_6_3_reg_980 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );

    ap_CS_fsm = "0001";
    ap_return_preg = "0000";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "digitrec_knn_vote_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, knn_set_0_0_V_read, "(port)knn_set_0_0_V_read");
    sc_trace(mVcdFile, knn_set_0_1_V_read, "(port)knn_set_0_1_V_read");
    sc_trace(mVcdFile, knn_set_0_2_V_read, "(port)knn_set_0_2_V_read");
    sc_trace(mVcdFile, knn_set_0_3_V_read, "(port)knn_set_0_3_V_read");
    sc_trace(mVcdFile, knn_set_1_0_V_read, "(port)knn_set_1_0_V_read");
    sc_trace(mVcdFile, knn_set_1_1_V_read, "(port)knn_set_1_1_V_read");
    sc_trace(mVcdFile, knn_set_1_2_V_read, "(port)knn_set_1_2_V_read");
    sc_trace(mVcdFile, knn_set_1_3_V_read, "(port)knn_set_1_3_V_read");
    sc_trace(mVcdFile, knn_set_2_0_V_read, "(port)knn_set_2_0_V_read");
    sc_trace(mVcdFile, knn_set_2_1_V_read, "(port)knn_set_2_1_V_read");
    sc_trace(mVcdFile, knn_set_2_2_V_read, "(port)knn_set_2_2_V_read");
    sc_trace(mVcdFile, knn_set_2_3_V_read, "(port)knn_set_2_3_V_read");
    sc_trace(mVcdFile, knn_set_3_0_V_read, "(port)knn_set_3_0_V_read");
    sc_trace(mVcdFile, knn_set_3_1_V_read, "(port)knn_set_3_1_V_read");
    sc_trace(mVcdFile, knn_set_3_2_V_read, "(port)knn_set_3_2_V_read");
    sc_trace(mVcdFile, knn_set_3_3_V_read, "(port)knn_set_3_3_V_read");
    sc_trace(mVcdFile, knn_set_4_0_V_read, "(port)knn_set_4_0_V_read");
    sc_trace(mVcdFile, knn_set_4_1_V_read, "(port)knn_set_4_1_V_read");
    sc_trace(mVcdFile, knn_set_4_2_V_read, "(port)knn_set_4_2_V_read");
    sc_trace(mVcdFile, knn_set_4_3_V_read, "(port)knn_set_4_3_V_read");
    sc_trace(mVcdFile, knn_set_5_0_V_read, "(port)knn_set_5_0_V_read");
    sc_trace(mVcdFile, knn_set_5_1_V_read, "(port)knn_set_5_1_V_read");
    sc_trace(mVcdFile, knn_set_5_2_V_read, "(port)knn_set_5_2_V_read");
    sc_trace(mVcdFile, knn_set_5_3_V_read, "(port)knn_set_5_3_V_read");
    sc_trace(mVcdFile, knn_set_6_0_V_read, "(port)knn_set_6_0_V_read");
    sc_trace(mVcdFile, knn_set_6_1_V_read, "(port)knn_set_6_1_V_read");
    sc_trace(mVcdFile, knn_set_6_2_V_read, "(port)knn_set_6_2_V_read");
    sc_trace(mVcdFile, knn_set_6_3_V_read, "(port)knn_set_6_3_V_read");
    sc_trace(mVcdFile, knn_set_7_0_V_read, "(port)knn_set_7_0_V_read");
    sc_trace(mVcdFile, knn_set_7_1_V_read, "(port)knn_set_7_1_V_read");
    sc_trace(mVcdFile, knn_set_7_2_V_read, "(port)knn_set_7_2_V_read");
    sc_trace(mVcdFile, knn_set_7_3_V_read, "(port)knn_set_7_3_V_read");
    sc_trace(mVcdFile, knn_set_8_0_V_read, "(port)knn_set_8_0_V_read");
    sc_trace(mVcdFile, knn_set_8_1_V_read, "(port)knn_set_8_1_V_read");
    sc_trace(mVcdFile, knn_set_8_2_V_read, "(port)knn_set_8_2_V_read");
    sc_trace(mVcdFile, knn_set_8_3_V_read, "(port)knn_set_8_3_V_read");
    sc_trace(mVcdFile, knn_set_9_0_V_read, "(port)knn_set_9_0_V_read");
    sc_trace(mVcdFile, knn_set_9_1_V_read, "(port)knn_set_9_1_V_read");
    sc_trace(mVcdFile, knn_set_9_2_V_read, "(port)knn_set_9_2_V_read");
    sc_trace(mVcdFile, knn_set_9_3_V_read, "(port)knn_set_9_3_V_read");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st1_fsm_0, "ap_sig_cseq_ST_st1_fsm_0");
    sc_trace(mVcdFile, ap_sig_21, "ap_sig_21");
    sc_trace(mVcdFile, tmp_6_1_fu_422_p2, "tmp_6_1_fu_422_p2");
    sc_trace(mVcdFile, tmp_6_1_reg_952, "tmp_6_1_reg_952");
    sc_trace(mVcdFile, min_2_min_1_fu_428_p3, "min_2_min_1_fu_428_p3");
    sc_trace(mVcdFile, min_2_min_1_reg_957, "min_2_min_1_reg_957");
    sc_trace(mVcdFile, sum_2_3_fu_472_p2, "sum_2_3_fu_472_p2");
    sc_trace(mVcdFile, sum_2_3_reg_963, "sum_2_3_reg_963");
    sc_trace(mVcdFile, sum_3_3_fu_514_p2, "sum_3_3_fu_514_p2");
    sc_trace(mVcdFile, sum_3_3_reg_969, "sum_3_3_reg_969");
    sc_trace(mVcdFile, tmp_6_2_fu_520_p2, "tmp_6_2_fu_520_p2");
    sc_trace(mVcdFile, tmp_6_2_reg_975, "tmp_6_2_reg_975");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st2_fsm_1, "ap_sig_cseq_ST_st2_fsm_1");
    sc_trace(mVcdFile, ap_sig_85, "ap_sig_85");
    sc_trace(mVcdFile, tmp_6_3_fu_530_p2, "tmp_6_3_fu_530_p2");
    sc_trace(mVcdFile, tmp_6_3_reg_980, "tmp_6_3_reg_980");
    sc_trace(mVcdFile, min_2_min_3_fu_535_p3, "min_2_min_3_fu_535_p3");
    sc_trace(mVcdFile, min_2_min_3_reg_986, "min_2_min_3_reg_986");
    sc_trace(mVcdFile, sum_4_3_fu_578_p2, "sum_4_3_fu_578_p2");
    sc_trace(mVcdFile, sum_4_3_reg_991, "sum_4_3_reg_991");
    sc_trace(mVcdFile, tmp_6_4_fu_584_p2, "tmp_6_4_fu_584_p2");
    sc_trace(mVcdFile, tmp_6_4_reg_996, "tmp_6_4_reg_996");
    sc_trace(mVcdFile, sum_5_3_fu_626_p2, "sum_5_3_fu_626_p2");
    sc_trace(mVcdFile, sum_5_3_reg_1002, "sum_5_3_reg_1002");
    sc_trace(mVcdFile, agg_result_V_0_agg_result_V_02_5_fu_681_p3, "agg_result_V_0_agg_result_V_02_5_fu_681_p3");
    sc_trace(mVcdFile, agg_result_V_0_agg_result_V_02_5_reg_1008, "agg_result_V_0_agg_result_V_02_5_reg_1008");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st3_fsm_2, "ap_sig_cseq_ST_st3_fsm_2");
    sc_trace(mVcdFile, ap_sig_104, "ap_sig_104");
    sc_trace(mVcdFile, tmp_6_6_fu_738_p2, "tmp_6_6_fu_738_p2");
    sc_trace(mVcdFile, tmp_6_6_reg_1013, "tmp_6_6_reg_1013");
    sc_trace(mVcdFile, min_2_min_6_fu_744_p3, "min_2_min_6_fu_744_p3");
    sc_trace(mVcdFile, min_2_min_6_reg_1018, "min_2_min_6_reg_1018");
    sc_trace(mVcdFile, sum_7_3_fu_788_p2, "sum_7_3_fu_788_p2");
    sc_trace(mVcdFile, sum_7_3_reg_1024, "sum_7_3_reg_1024");
    sc_trace(mVcdFile, sum_8_3_fu_830_p2, "sum_8_3_fu_830_p2");
    sc_trace(mVcdFile, sum_8_3_reg_1030, "sum_8_3_reg_1030");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st4_fsm_3, "ap_sig_cseq_ST_st4_fsm_3");
    sc_trace(mVcdFile, ap_sig_156, "ap_sig_156");
    sc_trace(mVcdFile, tmp_8_0_2_cast_fu_346_p1, "tmp_8_0_2_cast_fu_346_p1");
    sc_trace(mVcdFile, tmp_8_0_1_cast_fu_342_p1, "tmp_8_0_1_cast_fu_342_p1");
    sc_trace(mVcdFile, tmp1_fu_354_p2, "tmp1_fu_354_p2");
    sc_trace(mVcdFile, tmp_8_0_3_cast_fu_350_p1, "tmp_8_0_3_cast_fu_350_p1");
    sc_trace(mVcdFile, tmp_8_cast_fu_338_p1, "tmp_8_cast_fu_338_p1");
    sc_trace(mVcdFile, tmp2_fu_364_p2, "tmp2_fu_364_p2");
    sc_trace(mVcdFile, tmp1_cast_fu_360_p1, "tmp1_cast_fu_360_p1");
    sc_trace(mVcdFile, tmp2_cast_fu_370_p1, "tmp2_cast_fu_370_p1");
    sc_trace(mVcdFile, tmp_8_1_2_cast_fu_388_p1, "tmp_8_1_2_cast_fu_388_p1");
    sc_trace(mVcdFile, tmp_8_1_1_cast_fu_384_p1, "tmp_8_1_1_cast_fu_384_p1");
    sc_trace(mVcdFile, tmp4_fu_396_p2, "tmp4_fu_396_p2");
    sc_trace(mVcdFile, tmp_8_1_3_cast_fu_392_p1, "tmp_8_1_3_cast_fu_392_p1");
    sc_trace(mVcdFile, tmp_8_1_cast_fu_380_p1, "tmp_8_1_cast_fu_380_p1");
    sc_trace(mVcdFile, tmp5_fu_406_p2, "tmp5_fu_406_p2");
    sc_trace(mVcdFile, tmp4_cast_fu_402_p1, "tmp4_cast_fu_402_p1");
    sc_trace(mVcdFile, tmp5_cast_fu_412_p1, "tmp5_cast_fu_412_p1");
    sc_trace(mVcdFile, sum_1_3_fu_416_p2, "sum_1_3_fu_416_p2");
    sc_trace(mVcdFile, sum_0_3_fu_374_p2, "sum_0_3_fu_374_p2");
    sc_trace(mVcdFile, tmp_8_2_2_cast_fu_444_p1, "tmp_8_2_2_cast_fu_444_p1");
    sc_trace(mVcdFile, tmp_8_2_1_cast_fu_440_p1, "tmp_8_2_1_cast_fu_440_p1");
    sc_trace(mVcdFile, tmp7_fu_452_p2, "tmp7_fu_452_p2");
    sc_trace(mVcdFile, tmp_8_2_3_cast_fu_448_p1, "tmp_8_2_3_cast_fu_448_p1");
    sc_trace(mVcdFile, tmp_8_2_cast_fu_436_p1, "tmp_8_2_cast_fu_436_p1");
    sc_trace(mVcdFile, tmp8_fu_462_p2, "tmp8_fu_462_p2");
    sc_trace(mVcdFile, tmp7_cast_fu_458_p1, "tmp7_cast_fu_458_p1");
    sc_trace(mVcdFile, tmp8_cast_fu_468_p1, "tmp8_cast_fu_468_p1");
    sc_trace(mVcdFile, tmp_8_3_2_cast_fu_486_p1, "tmp_8_3_2_cast_fu_486_p1");
    sc_trace(mVcdFile, tmp_8_3_1_cast_fu_482_p1, "tmp_8_3_1_cast_fu_482_p1");
    sc_trace(mVcdFile, tmp_fu_494_p2, "tmp_fu_494_p2");
    sc_trace(mVcdFile, tmp_8_3_3_cast_fu_490_p1, "tmp_8_3_3_cast_fu_490_p1");
    sc_trace(mVcdFile, tmp_8_3_cast_fu_478_p1, "tmp_8_3_cast_fu_478_p1");
    sc_trace(mVcdFile, tmp3_fu_504_p2, "tmp3_fu_504_p2");
    sc_trace(mVcdFile, tmp10_cast_fu_500_p1, "tmp10_cast_fu_500_p1");
    sc_trace(mVcdFile, tmp11_cast_fu_510_p1, "tmp11_cast_fu_510_p1");
    sc_trace(mVcdFile, min_2_min_2_fu_524_p3, "min_2_min_2_fu_524_p3");
    sc_trace(mVcdFile, tmp_8_4_2_cast_fu_550_p1, "tmp_8_4_2_cast_fu_550_p1");
    sc_trace(mVcdFile, tmp_8_4_1_cast_fu_546_p1, "tmp_8_4_1_cast_fu_546_p1");
    sc_trace(mVcdFile, tmp6_fu_558_p2, "tmp6_fu_558_p2");
    sc_trace(mVcdFile, tmp_8_4_3_cast_fu_554_p1, "tmp_8_4_3_cast_fu_554_p1");
    sc_trace(mVcdFile, tmp_8_4_cast_fu_542_p1, "tmp_8_4_cast_fu_542_p1");
    sc_trace(mVcdFile, tmp9_fu_568_p2, "tmp9_fu_568_p2");
    sc_trace(mVcdFile, tmp13_cast_fu_564_p1, "tmp13_cast_fu_564_p1");
    sc_trace(mVcdFile, tmp14_cast_fu_574_p1, "tmp14_cast_fu_574_p1");
    sc_trace(mVcdFile, tmp_8_5_2_cast_fu_598_p1, "tmp_8_5_2_cast_fu_598_p1");
    sc_trace(mVcdFile, tmp_8_5_1_cast_fu_594_p1, "tmp_8_5_1_cast_fu_594_p1");
    sc_trace(mVcdFile, tmp10_fu_606_p2, "tmp10_fu_606_p2");
    sc_trace(mVcdFile, tmp_8_5_3_cast_fu_602_p1, "tmp_8_5_3_cast_fu_602_p1");
    sc_trace(mVcdFile, tmp_8_5_cast_fu_590_p1, "tmp_8_5_cast_fu_590_p1");
    sc_trace(mVcdFile, tmp11_fu_616_p2, "tmp11_fu_616_p2");
    sc_trace(mVcdFile, tmp16_cast_fu_612_p1, "tmp16_cast_fu_612_p1");
    sc_trace(mVcdFile, tmp17_cast_fu_622_p1, "tmp17_cast_fu_622_p1");
    sc_trace(mVcdFile, tmp_s_fu_642_p2, "tmp_s_fu_642_p2");
    sc_trace(mVcdFile, agg_result_V_0_agg_result_V_02_2_fu_635_p3, "agg_result_V_0_agg_result_V_02_2_fu_635_p3");
    sc_trace(mVcdFile, agg_result_V_0_agg_result_V_s_fu_632_p1, "agg_result_V_0_agg_result_V_s_fu_632_p1");
    sc_trace(mVcdFile, agg_result_V_0_agg_result_V_02_3_fu_646_p3, "agg_result_V_0_agg_result_V_02_3_fu_646_p3");
    sc_trace(mVcdFile, min_2_min_4_fu_658_p3, "min_2_min_4_fu_658_p3");
    sc_trace(mVcdFile, tmp_6_5_fu_663_p2, "tmp_6_5_fu_663_p2");
    sc_trace(mVcdFile, tmp_1_fu_676_p2, "tmp_1_fu_676_p2");
    sc_trace(mVcdFile, agg_result_V_0_agg_result_V_02_4_fu_668_p3, "agg_result_V_0_agg_result_V_02_4_fu_668_p3");
    sc_trace(mVcdFile, agg_result_V_0_agg_result_V_02_1_fu_654_p1, "agg_result_V_0_agg_result_V_02_1_fu_654_p1");
    sc_trace(mVcdFile, tmp_8_6_2_cast_fu_704_p1, "tmp_8_6_2_cast_fu_704_p1");
    sc_trace(mVcdFile, tmp_8_6_1_cast_fu_700_p1, "tmp_8_6_1_cast_fu_700_p1");
    sc_trace(mVcdFile, tmp12_fu_712_p2, "tmp12_fu_712_p2");
    sc_trace(mVcdFile, tmp_8_6_3_cast_fu_708_p1, "tmp_8_6_3_cast_fu_708_p1");
    sc_trace(mVcdFile, tmp_8_6_cast_fu_696_p1, "tmp_8_6_cast_fu_696_p1");
    sc_trace(mVcdFile, tmp13_fu_722_p2, "tmp13_fu_722_p2");
    sc_trace(mVcdFile, tmp19_cast_fu_718_p1, "tmp19_cast_fu_718_p1");
    sc_trace(mVcdFile, tmp20_cast_fu_728_p1, "tmp20_cast_fu_728_p1");
    sc_trace(mVcdFile, sum_6_3_fu_732_p2, "sum_6_3_fu_732_p2");
    sc_trace(mVcdFile, min_2_min_5_fu_689_p3, "min_2_min_5_fu_689_p3");
    sc_trace(mVcdFile, tmp_8_7_2_cast_fu_760_p1, "tmp_8_7_2_cast_fu_760_p1");
    sc_trace(mVcdFile, tmp_8_7_1_cast_fu_756_p1, "tmp_8_7_1_cast_fu_756_p1");
    sc_trace(mVcdFile, tmp14_fu_768_p2, "tmp14_fu_768_p2");
    sc_trace(mVcdFile, tmp_8_7_3_cast_fu_764_p1, "tmp_8_7_3_cast_fu_764_p1");
    sc_trace(mVcdFile, tmp_8_7_cast_fu_752_p1, "tmp_8_7_cast_fu_752_p1");
    sc_trace(mVcdFile, tmp15_fu_778_p2, "tmp15_fu_778_p2");
    sc_trace(mVcdFile, tmp22_cast_fu_774_p1, "tmp22_cast_fu_774_p1");
    sc_trace(mVcdFile, tmp23_cast_fu_784_p1, "tmp23_cast_fu_784_p1");
    sc_trace(mVcdFile, tmp_8_8_2_cast_fu_802_p1, "tmp_8_8_2_cast_fu_802_p1");
    sc_trace(mVcdFile, tmp_8_8_1_cast_fu_798_p1, "tmp_8_8_1_cast_fu_798_p1");
    sc_trace(mVcdFile, tmp16_fu_810_p2, "tmp16_fu_810_p2");
    sc_trace(mVcdFile, tmp_8_8_3_cast_fu_806_p1, "tmp_8_8_3_cast_fu_806_p1");
    sc_trace(mVcdFile, tmp_8_8_cast_fu_794_p1, "tmp_8_8_cast_fu_794_p1");
    sc_trace(mVcdFile, tmp17_fu_820_p2, "tmp17_fu_820_p2");
    sc_trace(mVcdFile, tmp25_cast_fu_816_p1, "tmp25_cast_fu_816_p1");
    sc_trace(mVcdFile, tmp26_cast_fu_826_p1, "tmp26_cast_fu_826_p1");
    sc_trace(mVcdFile, tmp_6_7_fu_836_p2, "tmp_6_7_fu_836_p2");
    sc_trace(mVcdFile, tmp_2_fu_848_p2, "tmp_2_fu_848_p2");
    sc_trace(mVcdFile, agg_result_V_0_agg_result_V_02_fu_840_p3, "agg_result_V_0_agg_result_V_02_fu_840_p3");
    sc_trace(mVcdFile, agg_result_V_0_agg_result_V_02_7_fu_853_p3, "agg_result_V_0_agg_result_V_02_7_fu_853_p3");
    sc_trace(mVcdFile, min_2_min_7_fu_864_p3, "min_2_min_7_fu_864_p3");
    sc_trace(mVcdFile, tmp_6_8_fu_870_p2, "tmp_6_8_fu_870_p2");
    sc_trace(mVcdFile, tmp_8_9_1_cast_fu_886_p1, "tmp_8_9_1_cast_fu_886_p1");
    sc_trace(mVcdFile, tmp_8_9_cast_fu_882_p1, "tmp_8_9_cast_fu_882_p1");
    sc_trace(mVcdFile, tmp18_fu_898_p2, "tmp18_fu_898_p2");
    sc_trace(mVcdFile, tmp_8_9_3_cast_fu_894_p1, "tmp_8_9_3_cast_fu_894_p1");
    sc_trace(mVcdFile, tmp_8_9_2_cast_fu_890_p1, "tmp_8_9_2_cast_fu_890_p1");
    sc_trace(mVcdFile, tmp19_fu_908_p2, "tmp19_fu_908_p2");
    sc_trace(mVcdFile, tmp27_cast_fu_904_p1, "tmp27_cast_fu_904_p1");
    sc_trace(mVcdFile, tmp28_cast_fu_914_p1, "tmp28_cast_fu_914_p1");
    sc_trace(mVcdFile, sum_9_3_fu_918_p2, "sum_9_3_fu_918_p2");
    sc_trace(mVcdFile, min_2_min_8_fu_875_p3, "min_2_min_8_fu_875_p3");
    sc_trace(mVcdFile, tmp_6_9_fu_924_p2, "tmp_6_9_fu_924_p2");
    sc_trace(mVcdFile, tmp_3_fu_938_p2, "tmp_3_fu_938_p2");
    sc_trace(mVcdFile, agg_result_V_0_agg_result_V_02_8_fu_930_p3, "agg_result_V_0_agg_result_V_02_8_fu_930_p3");
    sc_trace(mVcdFile, agg_result_V_0_agg_result_V_02_6_fu_860_p1, "agg_result_V_0_agg_result_V_02_6_fu_860_p1");
    sc_trace(mVcdFile, agg_result_V_0_agg_result_V_02_9_fu_944_p3, "agg_result_V_0_agg_result_V_02_9_fu_944_p3");
    sc_trace(mVcdFile, ap_return_preg, "ap_return_preg");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

digitrec_knn_vote::~digitrec_knn_vote() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void digitrec_knn_vote::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_preg = ap_const_lv4_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
            ap_return_preg = agg_result_V_0_agg_result_V_02_9_fu_944_p3.read();
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        agg_result_V_0_agg_result_V_02_5_reg_1008 = agg_result_V_0_agg_result_V_02_5_fu_681_p3.read();
        min_2_min_6_reg_1018 = min_2_min_6_fu_744_p3.read();
        sum_7_3_reg_1024 = sum_7_3_fu_788_p2.read();
        sum_8_3_reg_1030 = sum_8_3_fu_830_p2.read();
        tmp_6_6_reg_1013 = tmp_6_6_fu_738_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        min_2_min_1_reg_957 = min_2_min_1_fu_428_p3.read();
        sum_2_3_reg_963 = sum_2_3_fu_472_p2.read();
        sum_3_3_reg_969 = sum_3_3_fu_514_p2.read();
        tmp_6_1_reg_952 = tmp_6_1_fu_422_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        min_2_min_3_reg_986 = min_2_min_3_fu_535_p3.read();
        sum_4_3_reg_991 = sum_4_3_fu_578_p2.read();
        sum_5_3_reg_1002 = sum_5_3_fu_626_p2.read();
        tmp_6_2_reg_975 = tmp_6_2_fu_520_p2.read();
        tmp_6_3_reg_980 = tmp_6_3_fu_530_p2.read();
        tmp_6_4_reg_996 = tmp_6_4_fu_584_p2.read();
    }
}

void digitrec_knn_vote::thread_agg_result_V_0_agg_result_V_02_1_fu_654_p1() {
    agg_result_V_0_agg_result_V_02_1_fu_654_p1 = esl_zext<3,2>(agg_result_V_0_agg_result_V_02_3_fu_646_p3.read());
}

void digitrec_knn_vote::thread_agg_result_V_0_agg_result_V_02_2_fu_635_p3() {
    agg_result_V_0_agg_result_V_02_2_fu_635_p3 = (!tmp_6_3_reg_980.read()[0].is_01())? sc_lv<2>(): ((tmp_6_3_reg_980.read()[0].to_bool())? ap_const_lv2_3: ap_const_lv2_2);
}

void digitrec_knn_vote::thread_agg_result_V_0_agg_result_V_02_3_fu_646_p3() {
    agg_result_V_0_agg_result_V_02_3_fu_646_p3 = (!tmp_s_fu_642_p2.read()[0].is_01())? sc_lv<2>(): ((tmp_s_fu_642_p2.read()[0].to_bool())? agg_result_V_0_agg_result_V_02_2_fu_635_p3.read(): agg_result_V_0_agg_result_V_s_fu_632_p1.read());
}

void digitrec_knn_vote::thread_agg_result_V_0_agg_result_V_02_4_fu_668_p3() {
    agg_result_V_0_agg_result_V_02_4_fu_668_p3 = (!tmp_6_5_fu_663_p2.read()[0].is_01())? sc_lv<3>(): ((tmp_6_5_fu_663_p2.read()[0].to_bool())? ap_const_lv3_5: ap_const_lv3_4);
}

void digitrec_knn_vote::thread_agg_result_V_0_agg_result_V_02_5_fu_681_p3() {
    agg_result_V_0_agg_result_V_02_5_fu_681_p3 = (!tmp_1_fu_676_p2.read()[0].is_01())? sc_lv<3>(): ((tmp_1_fu_676_p2.read()[0].to_bool())? agg_result_V_0_agg_result_V_02_4_fu_668_p3.read(): agg_result_V_0_agg_result_V_02_1_fu_654_p1.read());
}

void digitrec_knn_vote::thread_agg_result_V_0_agg_result_V_02_6_fu_860_p1() {
    agg_result_V_0_agg_result_V_02_6_fu_860_p1 = esl_zext<4,3>(agg_result_V_0_agg_result_V_02_7_fu_853_p3.read());
}

void digitrec_knn_vote::thread_agg_result_V_0_agg_result_V_02_7_fu_853_p3() {
    agg_result_V_0_agg_result_V_02_7_fu_853_p3 = (!tmp_2_fu_848_p2.read()[0].is_01())? sc_lv<3>(): ((tmp_2_fu_848_p2.read()[0].to_bool())? agg_result_V_0_agg_result_V_02_fu_840_p3.read(): agg_result_V_0_agg_result_V_02_5_reg_1008.read());
}

void digitrec_knn_vote::thread_agg_result_V_0_agg_result_V_02_8_fu_930_p3() {
    agg_result_V_0_agg_result_V_02_8_fu_930_p3 = (!tmp_6_9_fu_924_p2.read()[0].is_01())? sc_lv<4>(): ((tmp_6_9_fu_924_p2.read()[0].to_bool())? ap_const_lv4_9: ap_const_lv4_8);
}

void digitrec_knn_vote::thread_agg_result_V_0_agg_result_V_02_9_fu_944_p3() {
    agg_result_V_0_agg_result_V_02_9_fu_944_p3 = (!tmp_3_fu_938_p2.read()[0].is_01())? sc_lv<4>(): ((tmp_3_fu_938_p2.read()[0].to_bool())? agg_result_V_0_agg_result_V_02_8_fu_930_p3.read(): agg_result_V_0_agg_result_V_02_6_fu_860_p1.read());
}

void digitrec_knn_vote::thread_agg_result_V_0_agg_result_V_02_fu_840_p3() {
    agg_result_V_0_agg_result_V_02_fu_840_p3 = (!tmp_6_7_fu_836_p2.read()[0].is_01())? sc_lv<3>(): ((tmp_6_7_fu_836_p2.read()[0].to_bool())? ap_const_lv3_7: ap_const_lv3_6);
}

void digitrec_knn_vote::thread_agg_result_V_0_agg_result_V_s_fu_632_p1() {
    agg_result_V_0_agg_result_V_s_fu_632_p1 = esl_zext<2,1>(tmp_6_1_reg_952.read());
}

void digitrec_knn_vote::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void digitrec_knn_vote::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void digitrec_knn_vote::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void digitrec_knn_vote::thread_ap_return() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        ap_return = agg_result_V_0_agg_result_V_02_9_fu_944_p3.read();
    } else {
        ap_return = ap_return_preg.read();
    }
}

void digitrec_knn_vote::thread_ap_sig_104() {
    ap_sig_104 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(2, 2));
}

void digitrec_knn_vote::thread_ap_sig_156() {
    ap_sig_156 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(3, 3));
}

void digitrec_knn_vote::thread_ap_sig_21() {
    ap_sig_21 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void digitrec_knn_vote::thread_ap_sig_85() {
    ap_sig_85 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(1, 1));
}

void digitrec_knn_vote::thread_ap_sig_cseq_ST_st1_fsm_0() {
    if (ap_sig_21.read()) {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    }
}

void digitrec_knn_vote::thread_ap_sig_cseq_ST_st2_fsm_1() {
    if (ap_sig_85.read()) {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    }
}

void digitrec_knn_vote::thread_ap_sig_cseq_ST_st3_fsm_2() {
    if (ap_sig_104.read()) {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_0;
    }
}

void digitrec_knn_vote::thread_ap_sig_cseq_ST_st4_fsm_3() {
    if (ap_sig_156.read()) {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_0;
    }
}

void digitrec_knn_vote::thread_min_2_min_1_fu_428_p3() {
    min_2_min_1_fu_428_p3 = (!tmp_6_1_fu_422_p2.read()[0].is_01())? sc_lv<8>(): ((tmp_6_1_fu_422_p2.read()[0].to_bool())? sum_1_3_fu_416_p2.read(): sum_0_3_fu_374_p2.read());
}

void digitrec_knn_vote::thread_min_2_min_2_fu_524_p3() {
    min_2_min_2_fu_524_p3 = (!tmp_6_2_fu_520_p2.read()[0].is_01())? sc_lv<8>(): ((tmp_6_2_fu_520_p2.read()[0].to_bool())? sum_2_3_reg_963.read(): min_2_min_1_reg_957.read());
}

void digitrec_knn_vote::thread_min_2_min_3_fu_535_p3() {
    min_2_min_3_fu_535_p3 = (!tmp_6_3_fu_530_p2.read()[0].is_01())? sc_lv<8>(): ((tmp_6_3_fu_530_p2.read()[0].to_bool())? sum_3_3_reg_969.read(): min_2_min_2_fu_524_p3.read());
}

void digitrec_knn_vote::thread_min_2_min_4_fu_658_p3() {
    min_2_min_4_fu_658_p3 = (!tmp_6_4_reg_996.read()[0].is_01())? sc_lv<8>(): ((tmp_6_4_reg_996.read()[0].to_bool())? sum_4_3_reg_991.read(): min_2_min_3_reg_986.read());
}

void digitrec_knn_vote::thread_min_2_min_5_fu_689_p3() {
    min_2_min_5_fu_689_p3 = (!tmp_6_5_fu_663_p2.read()[0].is_01())? sc_lv<8>(): ((tmp_6_5_fu_663_p2.read()[0].to_bool())? sum_5_3_reg_1002.read(): min_2_min_4_fu_658_p3.read());
}

void digitrec_knn_vote::thread_min_2_min_6_fu_744_p3() {
    min_2_min_6_fu_744_p3 = (!tmp_6_6_fu_738_p2.read()[0].is_01())? sc_lv<8>(): ((tmp_6_6_fu_738_p2.read()[0].to_bool())? sum_6_3_fu_732_p2.read(): min_2_min_5_fu_689_p3.read());
}

void digitrec_knn_vote::thread_min_2_min_7_fu_864_p3() {
    min_2_min_7_fu_864_p3 = (!tmp_6_7_fu_836_p2.read()[0].is_01())? sc_lv<8>(): ((tmp_6_7_fu_836_p2.read()[0].to_bool())? sum_7_3_reg_1024.read(): min_2_min_6_reg_1018.read());
}

void digitrec_knn_vote::thread_min_2_min_8_fu_875_p3() {
    min_2_min_8_fu_875_p3 = (!tmp_6_8_fu_870_p2.read()[0].is_01())? sc_lv<8>(): ((tmp_6_8_fu_870_p2.read()[0].to_bool())? sum_8_3_reg_1030.read(): min_2_min_7_fu_864_p3.read());
}

void digitrec_knn_vote::thread_sum_0_3_fu_374_p2() {
    sum_0_3_fu_374_p2 = (!tmp1_cast_fu_360_p1.read().is_01() || !tmp2_cast_fu_370_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(tmp1_cast_fu_360_p1.read()) + sc_biguint<8>(tmp2_cast_fu_370_p1.read()));
}

void digitrec_knn_vote::thread_sum_1_3_fu_416_p2() {
    sum_1_3_fu_416_p2 = (!tmp4_cast_fu_402_p1.read().is_01() || !tmp5_cast_fu_412_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(tmp4_cast_fu_402_p1.read()) + sc_biguint<8>(tmp5_cast_fu_412_p1.read()));
}

void digitrec_knn_vote::thread_sum_2_3_fu_472_p2() {
    sum_2_3_fu_472_p2 = (!tmp7_cast_fu_458_p1.read().is_01() || !tmp8_cast_fu_468_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(tmp7_cast_fu_458_p1.read()) + sc_biguint<8>(tmp8_cast_fu_468_p1.read()));
}

void digitrec_knn_vote::thread_sum_3_3_fu_514_p2() {
    sum_3_3_fu_514_p2 = (!tmp10_cast_fu_500_p1.read().is_01() || !tmp11_cast_fu_510_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(tmp10_cast_fu_500_p1.read()) + sc_biguint<8>(tmp11_cast_fu_510_p1.read()));
}

void digitrec_knn_vote::thread_sum_4_3_fu_578_p2() {
    sum_4_3_fu_578_p2 = (!tmp13_cast_fu_564_p1.read().is_01() || !tmp14_cast_fu_574_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(tmp13_cast_fu_564_p1.read()) + sc_biguint<8>(tmp14_cast_fu_574_p1.read()));
}

void digitrec_knn_vote::thread_sum_5_3_fu_626_p2() {
    sum_5_3_fu_626_p2 = (!tmp16_cast_fu_612_p1.read().is_01() || !tmp17_cast_fu_622_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(tmp16_cast_fu_612_p1.read()) + sc_biguint<8>(tmp17_cast_fu_622_p1.read()));
}

void digitrec_knn_vote::thread_sum_6_3_fu_732_p2() {
    sum_6_3_fu_732_p2 = (!tmp19_cast_fu_718_p1.read().is_01() || !tmp20_cast_fu_728_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(tmp19_cast_fu_718_p1.read()) + sc_biguint<8>(tmp20_cast_fu_728_p1.read()));
}

void digitrec_knn_vote::thread_sum_7_3_fu_788_p2() {
    sum_7_3_fu_788_p2 = (!tmp22_cast_fu_774_p1.read().is_01() || !tmp23_cast_fu_784_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(tmp22_cast_fu_774_p1.read()) + sc_biguint<8>(tmp23_cast_fu_784_p1.read()));
}

void digitrec_knn_vote::thread_sum_8_3_fu_830_p2() {
    sum_8_3_fu_830_p2 = (!tmp25_cast_fu_816_p1.read().is_01() || !tmp26_cast_fu_826_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(tmp25_cast_fu_816_p1.read()) + sc_biguint<8>(tmp26_cast_fu_826_p1.read()));
}

void digitrec_knn_vote::thread_sum_9_3_fu_918_p2() {
    sum_9_3_fu_918_p2 = (!tmp27_cast_fu_904_p1.read().is_01() || !tmp28_cast_fu_914_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(tmp27_cast_fu_904_p1.read()) + sc_biguint<8>(tmp28_cast_fu_914_p1.read()));
}

void digitrec_knn_vote::thread_tmp10_cast_fu_500_p1() {
    tmp10_cast_fu_500_p1 = esl_zext<8,7>(tmp_fu_494_p2.read());
}

void digitrec_knn_vote::thread_tmp10_fu_606_p2() {
    tmp10_fu_606_p2 = (!tmp_8_5_2_cast_fu_598_p1.read().is_01() || !tmp_8_5_1_cast_fu_594_p1.read().is_01())? sc_lv<7>(): (sc_biguint<7>(tmp_8_5_2_cast_fu_598_p1.read()) + sc_biguint<7>(tmp_8_5_1_cast_fu_594_p1.read()));
}

void digitrec_knn_vote::thread_tmp11_cast_fu_510_p1() {
    tmp11_cast_fu_510_p1 = esl_zext<8,7>(tmp3_fu_504_p2.read());
}

void digitrec_knn_vote::thread_tmp11_fu_616_p2() {
    tmp11_fu_616_p2 = (!tmp_8_5_3_cast_fu_602_p1.read().is_01() || !tmp_8_5_cast_fu_590_p1.read().is_01())? sc_lv<7>(): (sc_biguint<7>(tmp_8_5_3_cast_fu_602_p1.read()) + sc_biguint<7>(tmp_8_5_cast_fu_590_p1.read()));
}

void digitrec_knn_vote::thread_tmp12_fu_712_p2() {
    tmp12_fu_712_p2 = (!tmp_8_6_2_cast_fu_704_p1.read().is_01() || !tmp_8_6_1_cast_fu_700_p1.read().is_01())? sc_lv<7>(): (sc_biguint<7>(tmp_8_6_2_cast_fu_704_p1.read()) + sc_biguint<7>(tmp_8_6_1_cast_fu_700_p1.read()));
}

void digitrec_knn_vote::thread_tmp13_cast_fu_564_p1() {
    tmp13_cast_fu_564_p1 = esl_zext<8,7>(tmp6_fu_558_p2.read());
}

void digitrec_knn_vote::thread_tmp13_fu_722_p2() {
    tmp13_fu_722_p2 = (!tmp_8_6_3_cast_fu_708_p1.read().is_01() || !tmp_8_6_cast_fu_696_p1.read().is_01())? sc_lv<7>(): (sc_biguint<7>(tmp_8_6_3_cast_fu_708_p1.read()) + sc_biguint<7>(tmp_8_6_cast_fu_696_p1.read()));
}

void digitrec_knn_vote::thread_tmp14_cast_fu_574_p1() {
    tmp14_cast_fu_574_p1 = esl_zext<8,7>(tmp9_fu_568_p2.read());
}

void digitrec_knn_vote::thread_tmp14_fu_768_p2() {
    tmp14_fu_768_p2 = (!tmp_8_7_2_cast_fu_760_p1.read().is_01() || !tmp_8_7_1_cast_fu_756_p1.read().is_01())? sc_lv<7>(): (sc_biguint<7>(tmp_8_7_2_cast_fu_760_p1.read()) + sc_biguint<7>(tmp_8_7_1_cast_fu_756_p1.read()));
}

void digitrec_knn_vote::thread_tmp15_fu_778_p2() {
    tmp15_fu_778_p2 = (!tmp_8_7_3_cast_fu_764_p1.read().is_01() || !tmp_8_7_cast_fu_752_p1.read().is_01())? sc_lv<7>(): (sc_biguint<7>(tmp_8_7_3_cast_fu_764_p1.read()) + sc_biguint<7>(tmp_8_7_cast_fu_752_p1.read()));
}

void digitrec_knn_vote::thread_tmp16_cast_fu_612_p1() {
    tmp16_cast_fu_612_p1 = esl_zext<8,7>(tmp10_fu_606_p2.read());
}

void digitrec_knn_vote::thread_tmp16_fu_810_p2() {
    tmp16_fu_810_p2 = (!tmp_8_8_2_cast_fu_802_p1.read().is_01() || !tmp_8_8_1_cast_fu_798_p1.read().is_01())? sc_lv<7>(): (sc_biguint<7>(tmp_8_8_2_cast_fu_802_p1.read()) + sc_biguint<7>(tmp_8_8_1_cast_fu_798_p1.read()));
}

void digitrec_knn_vote::thread_tmp17_cast_fu_622_p1() {
    tmp17_cast_fu_622_p1 = esl_zext<8,7>(tmp11_fu_616_p2.read());
}

void digitrec_knn_vote::thread_tmp17_fu_820_p2() {
    tmp17_fu_820_p2 = (!tmp_8_8_3_cast_fu_806_p1.read().is_01() || !tmp_8_8_cast_fu_794_p1.read().is_01())? sc_lv<7>(): (sc_biguint<7>(tmp_8_8_3_cast_fu_806_p1.read()) + sc_biguint<7>(tmp_8_8_cast_fu_794_p1.read()));
}

void digitrec_knn_vote::thread_tmp18_fu_898_p2() {
    tmp18_fu_898_p2 = (!tmp_8_9_1_cast_fu_886_p1.read().is_01() || !tmp_8_9_cast_fu_882_p1.read().is_01())? sc_lv<7>(): (sc_biguint<7>(tmp_8_9_1_cast_fu_886_p1.read()) + sc_biguint<7>(tmp_8_9_cast_fu_882_p1.read()));
}

void digitrec_knn_vote::thread_tmp19_cast_fu_718_p1() {
    tmp19_cast_fu_718_p1 = esl_zext<8,7>(tmp12_fu_712_p2.read());
}

void digitrec_knn_vote::thread_tmp19_fu_908_p2() {
    tmp19_fu_908_p2 = (!tmp_8_9_3_cast_fu_894_p1.read().is_01() || !tmp_8_9_2_cast_fu_890_p1.read().is_01())? sc_lv<7>(): (sc_biguint<7>(tmp_8_9_3_cast_fu_894_p1.read()) + sc_biguint<7>(tmp_8_9_2_cast_fu_890_p1.read()));
}

void digitrec_knn_vote::thread_tmp1_cast_fu_360_p1() {
    tmp1_cast_fu_360_p1 = esl_zext<8,7>(tmp1_fu_354_p2.read());
}

void digitrec_knn_vote::thread_tmp1_fu_354_p2() {
    tmp1_fu_354_p2 = (!tmp_8_0_2_cast_fu_346_p1.read().is_01() || !tmp_8_0_1_cast_fu_342_p1.read().is_01())? sc_lv<7>(): (sc_biguint<7>(tmp_8_0_2_cast_fu_346_p1.read()) + sc_biguint<7>(tmp_8_0_1_cast_fu_342_p1.read()));
}

void digitrec_knn_vote::thread_tmp20_cast_fu_728_p1() {
    tmp20_cast_fu_728_p1 = esl_zext<8,7>(tmp13_fu_722_p2.read());
}

void digitrec_knn_vote::thread_tmp22_cast_fu_774_p1() {
    tmp22_cast_fu_774_p1 = esl_zext<8,7>(tmp14_fu_768_p2.read());
}

void digitrec_knn_vote::thread_tmp23_cast_fu_784_p1() {
    tmp23_cast_fu_784_p1 = esl_zext<8,7>(tmp15_fu_778_p2.read());
}

void digitrec_knn_vote::thread_tmp25_cast_fu_816_p1() {
    tmp25_cast_fu_816_p1 = esl_zext<8,7>(tmp16_fu_810_p2.read());
}

void digitrec_knn_vote::thread_tmp26_cast_fu_826_p1() {
    tmp26_cast_fu_826_p1 = esl_zext<8,7>(tmp17_fu_820_p2.read());
}

void digitrec_knn_vote::thread_tmp27_cast_fu_904_p1() {
    tmp27_cast_fu_904_p1 = esl_zext<8,7>(tmp18_fu_898_p2.read());
}

void digitrec_knn_vote::thread_tmp28_cast_fu_914_p1() {
    tmp28_cast_fu_914_p1 = esl_zext<8,7>(tmp19_fu_908_p2.read());
}

void digitrec_knn_vote::thread_tmp2_cast_fu_370_p1() {
    tmp2_cast_fu_370_p1 = esl_zext<8,7>(tmp2_fu_364_p2.read());
}

void digitrec_knn_vote::thread_tmp2_fu_364_p2() {
    tmp2_fu_364_p2 = (!tmp_8_0_3_cast_fu_350_p1.read().is_01() || !tmp_8_cast_fu_338_p1.read().is_01())? sc_lv<7>(): (sc_biguint<7>(tmp_8_0_3_cast_fu_350_p1.read()) + sc_biguint<7>(tmp_8_cast_fu_338_p1.read()));
}

void digitrec_knn_vote::thread_tmp3_fu_504_p2() {
    tmp3_fu_504_p2 = (!tmp_8_3_3_cast_fu_490_p1.read().is_01() || !tmp_8_3_cast_fu_478_p1.read().is_01())? sc_lv<7>(): (sc_biguint<7>(tmp_8_3_3_cast_fu_490_p1.read()) + sc_biguint<7>(tmp_8_3_cast_fu_478_p1.read()));
}

void digitrec_knn_vote::thread_tmp4_cast_fu_402_p1() {
    tmp4_cast_fu_402_p1 = esl_zext<8,7>(tmp4_fu_396_p2.read());
}

void digitrec_knn_vote::thread_tmp4_fu_396_p2() {
    tmp4_fu_396_p2 = (!tmp_8_1_2_cast_fu_388_p1.read().is_01() || !tmp_8_1_1_cast_fu_384_p1.read().is_01())? sc_lv<7>(): (sc_biguint<7>(tmp_8_1_2_cast_fu_388_p1.read()) + sc_biguint<7>(tmp_8_1_1_cast_fu_384_p1.read()));
}

void digitrec_knn_vote::thread_tmp5_cast_fu_412_p1() {
    tmp5_cast_fu_412_p1 = esl_zext<8,7>(tmp5_fu_406_p2.read());
}

void digitrec_knn_vote::thread_tmp5_fu_406_p2() {
    tmp5_fu_406_p2 = (!tmp_8_1_3_cast_fu_392_p1.read().is_01() || !tmp_8_1_cast_fu_380_p1.read().is_01())? sc_lv<7>(): (sc_biguint<7>(tmp_8_1_3_cast_fu_392_p1.read()) + sc_biguint<7>(tmp_8_1_cast_fu_380_p1.read()));
}

void digitrec_knn_vote::thread_tmp6_fu_558_p2() {
    tmp6_fu_558_p2 = (!tmp_8_4_2_cast_fu_550_p1.read().is_01() || !tmp_8_4_1_cast_fu_546_p1.read().is_01())? sc_lv<7>(): (sc_biguint<7>(tmp_8_4_2_cast_fu_550_p1.read()) + sc_biguint<7>(tmp_8_4_1_cast_fu_546_p1.read()));
}

void digitrec_knn_vote::thread_tmp7_cast_fu_458_p1() {
    tmp7_cast_fu_458_p1 = esl_zext<8,7>(tmp7_fu_452_p2.read());
}

void digitrec_knn_vote::thread_tmp7_fu_452_p2() {
    tmp7_fu_452_p2 = (!tmp_8_2_2_cast_fu_444_p1.read().is_01() || !tmp_8_2_1_cast_fu_440_p1.read().is_01())? sc_lv<7>(): (sc_biguint<7>(tmp_8_2_2_cast_fu_444_p1.read()) + sc_biguint<7>(tmp_8_2_1_cast_fu_440_p1.read()));
}

void digitrec_knn_vote::thread_tmp8_cast_fu_468_p1() {
    tmp8_cast_fu_468_p1 = esl_zext<8,7>(tmp8_fu_462_p2.read());
}

void digitrec_knn_vote::thread_tmp8_fu_462_p2() {
    tmp8_fu_462_p2 = (!tmp_8_2_3_cast_fu_448_p1.read().is_01() || !tmp_8_2_cast_fu_436_p1.read().is_01())? sc_lv<7>(): (sc_biguint<7>(tmp_8_2_3_cast_fu_448_p1.read()) + sc_biguint<7>(tmp_8_2_cast_fu_436_p1.read()));
}

void digitrec_knn_vote::thread_tmp9_fu_568_p2() {
    tmp9_fu_568_p2 = (!tmp_8_4_3_cast_fu_554_p1.read().is_01() || !tmp_8_4_cast_fu_542_p1.read().is_01())? sc_lv<7>(): (sc_biguint<7>(tmp_8_4_3_cast_fu_554_p1.read()) + sc_biguint<7>(tmp_8_4_cast_fu_542_p1.read()));
}

void digitrec_knn_vote::thread_tmp_1_fu_676_p2() {
    tmp_1_fu_676_p2 = (tmp_6_5_fu_663_p2.read() | tmp_6_4_reg_996.read());
}

void digitrec_knn_vote::thread_tmp_2_fu_848_p2() {
    tmp_2_fu_848_p2 = (tmp_6_7_fu_836_p2.read() | tmp_6_6_reg_1013.read());
}

void digitrec_knn_vote::thread_tmp_3_fu_938_p2() {
    tmp_3_fu_938_p2 = (tmp_6_9_fu_924_p2.read() | tmp_6_8_fu_870_p2.read());
}

void digitrec_knn_vote::thread_tmp_6_1_fu_422_p2() {
    tmp_6_1_fu_422_p2 = (!sum_1_3_fu_416_p2.read().is_01() || !sum_0_3_fu_374_p2.read().is_01())? sc_lv<1>(): (sc_biguint<8>(sum_1_3_fu_416_p2.read()) < sc_biguint<8>(sum_0_3_fu_374_p2.read()));
}

void digitrec_knn_vote::thread_tmp_6_2_fu_520_p2() {
    tmp_6_2_fu_520_p2 = (!sum_2_3_reg_963.read().is_01() || !min_2_min_1_reg_957.read().is_01())? sc_lv<1>(): (sc_biguint<8>(sum_2_3_reg_963.read()) < sc_biguint<8>(min_2_min_1_reg_957.read()));
}

void digitrec_knn_vote::thread_tmp_6_3_fu_530_p2() {
    tmp_6_3_fu_530_p2 = (!sum_3_3_reg_969.read().is_01() || !min_2_min_2_fu_524_p3.read().is_01())? sc_lv<1>(): (sc_biguint<8>(sum_3_3_reg_969.read()) < sc_biguint<8>(min_2_min_2_fu_524_p3.read()));
}

void digitrec_knn_vote::thread_tmp_6_4_fu_584_p2() {
    tmp_6_4_fu_584_p2 = (!sum_4_3_fu_578_p2.read().is_01() || !min_2_min_3_fu_535_p3.read().is_01())? sc_lv<1>(): (sc_biguint<8>(sum_4_3_fu_578_p2.read()) < sc_biguint<8>(min_2_min_3_fu_535_p3.read()));
}

void digitrec_knn_vote::thread_tmp_6_5_fu_663_p2() {
    tmp_6_5_fu_663_p2 = (!sum_5_3_reg_1002.read().is_01() || !min_2_min_4_fu_658_p3.read().is_01())? sc_lv<1>(): (sc_biguint<8>(sum_5_3_reg_1002.read()) < sc_biguint<8>(min_2_min_4_fu_658_p3.read()));
}

void digitrec_knn_vote::thread_tmp_6_6_fu_738_p2() {
    tmp_6_6_fu_738_p2 = (!sum_6_3_fu_732_p2.read().is_01() || !min_2_min_5_fu_689_p3.read().is_01())? sc_lv<1>(): (sc_biguint<8>(sum_6_3_fu_732_p2.read()) < sc_biguint<8>(min_2_min_5_fu_689_p3.read()));
}

void digitrec_knn_vote::thread_tmp_6_7_fu_836_p2() {
    tmp_6_7_fu_836_p2 = (!sum_7_3_reg_1024.read().is_01() || !min_2_min_6_reg_1018.read().is_01())? sc_lv<1>(): (sc_biguint<8>(sum_7_3_reg_1024.read()) < sc_biguint<8>(min_2_min_6_reg_1018.read()));
}

void digitrec_knn_vote::thread_tmp_6_8_fu_870_p2() {
    tmp_6_8_fu_870_p2 = (!sum_8_3_reg_1030.read().is_01() || !min_2_min_7_fu_864_p3.read().is_01())? sc_lv<1>(): (sc_biguint<8>(sum_8_3_reg_1030.read()) < sc_biguint<8>(min_2_min_7_fu_864_p3.read()));
}

void digitrec_knn_vote::thread_tmp_6_9_fu_924_p2() {
    tmp_6_9_fu_924_p2 = (!sum_9_3_fu_918_p2.read().is_01() || !min_2_min_8_fu_875_p3.read().is_01())? sc_lv<1>(): (sc_biguint<8>(sum_9_3_fu_918_p2.read()) < sc_biguint<8>(min_2_min_8_fu_875_p3.read()));
}

void digitrec_knn_vote::thread_tmp_8_0_1_cast_fu_342_p1() {
    tmp_8_0_1_cast_fu_342_p1 = esl_zext<7,6>(knn_set_0_1_V_read.read());
}

void digitrec_knn_vote::thread_tmp_8_0_2_cast_fu_346_p1() {
    tmp_8_0_2_cast_fu_346_p1 = esl_zext<7,6>(knn_set_0_2_V_read.read());
}

void digitrec_knn_vote::thread_tmp_8_0_3_cast_fu_350_p1() {
    tmp_8_0_3_cast_fu_350_p1 = esl_zext<7,6>(knn_set_0_3_V_read.read());
}

void digitrec_knn_vote::thread_tmp_8_1_1_cast_fu_384_p1() {
    tmp_8_1_1_cast_fu_384_p1 = esl_zext<7,6>(knn_set_1_1_V_read.read());
}

void digitrec_knn_vote::thread_tmp_8_1_2_cast_fu_388_p1() {
    tmp_8_1_2_cast_fu_388_p1 = esl_zext<7,6>(knn_set_1_2_V_read.read());
}

void digitrec_knn_vote::thread_tmp_8_1_3_cast_fu_392_p1() {
    tmp_8_1_3_cast_fu_392_p1 = esl_zext<7,6>(knn_set_1_3_V_read.read());
}

void digitrec_knn_vote::thread_tmp_8_1_cast_fu_380_p1() {
    tmp_8_1_cast_fu_380_p1 = esl_zext<7,6>(knn_set_1_0_V_read.read());
}

void digitrec_knn_vote::thread_tmp_8_2_1_cast_fu_440_p1() {
    tmp_8_2_1_cast_fu_440_p1 = esl_zext<7,6>(knn_set_2_1_V_read.read());
}

void digitrec_knn_vote::thread_tmp_8_2_2_cast_fu_444_p1() {
    tmp_8_2_2_cast_fu_444_p1 = esl_zext<7,6>(knn_set_2_2_V_read.read());
}

void digitrec_knn_vote::thread_tmp_8_2_3_cast_fu_448_p1() {
    tmp_8_2_3_cast_fu_448_p1 = esl_zext<7,6>(knn_set_2_3_V_read.read());
}

void digitrec_knn_vote::thread_tmp_8_2_cast_fu_436_p1() {
    tmp_8_2_cast_fu_436_p1 = esl_zext<7,6>(knn_set_2_0_V_read.read());
}

void digitrec_knn_vote::thread_tmp_8_3_1_cast_fu_482_p1() {
    tmp_8_3_1_cast_fu_482_p1 = esl_zext<7,6>(knn_set_3_1_V_read.read());
}

void digitrec_knn_vote::thread_tmp_8_3_2_cast_fu_486_p1() {
    tmp_8_3_2_cast_fu_486_p1 = esl_zext<7,6>(knn_set_3_2_V_read.read());
}

void digitrec_knn_vote::thread_tmp_8_3_3_cast_fu_490_p1() {
    tmp_8_3_3_cast_fu_490_p1 = esl_zext<7,6>(knn_set_3_3_V_read.read());
}

void digitrec_knn_vote::thread_tmp_8_3_cast_fu_478_p1() {
    tmp_8_3_cast_fu_478_p1 = esl_zext<7,6>(knn_set_3_0_V_read.read());
}

void digitrec_knn_vote::thread_tmp_8_4_1_cast_fu_546_p1() {
    tmp_8_4_1_cast_fu_546_p1 = esl_zext<7,6>(knn_set_4_1_V_read.read());
}

void digitrec_knn_vote::thread_tmp_8_4_2_cast_fu_550_p1() {
    tmp_8_4_2_cast_fu_550_p1 = esl_zext<7,6>(knn_set_4_2_V_read.read());
}

void digitrec_knn_vote::thread_tmp_8_4_3_cast_fu_554_p1() {
    tmp_8_4_3_cast_fu_554_p1 = esl_zext<7,6>(knn_set_4_3_V_read.read());
}

void digitrec_knn_vote::thread_tmp_8_4_cast_fu_542_p1() {
    tmp_8_4_cast_fu_542_p1 = esl_zext<7,6>(knn_set_4_0_V_read.read());
}

void digitrec_knn_vote::thread_tmp_8_5_1_cast_fu_594_p1() {
    tmp_8_5_1_cast_fu_594_p1 = esl_zext<7,6>(knn_set_5_1_V_read.read());
}

void digitrec_knn_vote::thread_tmp_8_5_2_cast_fu_598_p1() {
    tmp_8_5_2_cast_fu_598_p1 = esl_zext<7,6>(knn_set_5_2_V_read.read());
}

void digitrec_knn_vote::thread_tmp_8_5_3_cast_fu_602_p1() {
    tmp_8_5_3_cast_fu_602_p1 = esl_zext<7,6>(knn_set_5_3_V_read.read());
}

void digitrec_knn_vote::thread_tmp_8_5_cast_fu_590_p1() {
    tmp_8_5_cast_fu_590_p1 = esl_zext<7,6>(knn_set_5_0_V_read.read());
}

void digitrec_knn_vote::thread_tmp_8_6_1_cast_fu_700_p1() {
    tmp_8_6_1_cast_fu_700_p1 = esl_zext<7,6>(knn_set_6_1_V_read.read());
}

void digitrec_knn_vote::thread_tmp_8_6_2_cast_fu_704_p1() {
    tmp_8_6_2_cast_fu_704_p1 = esl_zext<7,6>(knn_set_6_2_V_read.read());
}

void digitrec_knn_vote::thread_tmp_8_6_3_cast_fu_708_p1() {
    tmp_8_6_3_cast_fu_708_p1 = esl_zext<7,6>(knn_set_6_3_V_read.read());
}

void digitrec_knn_vote::thread_tmp_8_6_cast_fu_696_p1() {
    tmp_8_6_cast_fu_696_p1 = esl_zext<7,6>(knn_set_6_0_V_read.read());
}

void digitrec_knn_vote::thread_tmp_8_7_1_cast_fu_756_p1() {
    tmp_8_7_1_cast_fu_756_p1 = esl_zext<7,6>(knn_set_7_1_V_read.read());
}

void digitrec_knn_vote::thread_tmp_8_7_2_cast_fu_760_p1() {
    tmp_8_7_2_cast_fu_760_p1 = esl_zext<7,6>(knn_set_7_2_V_read.read());
}

void digitrec_knn_vote::thread_tmp_8_7_3_cast_fu_764_p1() {
    tmp_8_7_3_cast_fu_764_p1 = esl_zext<7,6>(knn_set_7_3_V_read.read());
}

void digitrec_knn_vote::thread_tmp_8_7_cast_fu_752_p1() {
    tmp_8_7_cast_fu_752_p1 = esl_zext<7,6>(knn_set_7_0_V_read.read());
}

void digitrec_knn_vote::thread_tmp_8_8_1_cast_fu_798_p1() {
    tmp_8_8_1_cast_fu_798_p1 = esl_zext<7,6>(knn_set_8_1_V_read.read());
}

void digitrec_knn_vote::thread_tmp_8_8_2_cast_fu_802_p1() {
    tmp_8_8_2_cast_fu_802_p1 = esl_zext<7,6>(knn_set_8_2_V_read.read());
}

void digitrec_knn_vote::thread_tmp_8_8_3_cast_fu_806_p1() {
    tmp_8_8_3_cast_fu_806_p1 = esl_zext<7,6>(knn_set_8_3_V_read.read());
}

void digitrec_knn_vote::thread_tmp_8_8_cast_fu_794_p1() {
    tmp_8_8_cast_fu_794_p1 = esl_zext<7,6>(knn_set_8_0_V_read.read());
}

void digitrec_knn_vote::thread_tmp_8_9_1_cast_fu_886_p1() {
    tmp_8_9_1_cast_fu_886_p1 = esl_zext<7,6>(knn_set_9_1_V_read.read());
}

void digitrec_knn_vote::thread_tmp_8_9_2_cast_fu_890_p1() {
    tmp_8_9_2_cast_fu_890_p1 = esl_zext<7,6>(knn_set_9_2_V_read.read());
}

void digitrec_knn_vote::thread_tmp_8_9_3_cast_fu_894_p1() {
    tmp_8_9_3_cast_fu_894_p1 = esl_zext<7,6>(knn_set_9_3_V_read.read());
}

void digitrec_knn_vote::thread_tmp_8_9_cast_fu_882_p1() {
    tmp_8_9_cast_fu_882_p1 = esl_zext<7,6>(knn_set_9_0_V_read.read());
}

void digitrec_knn_vote::thread_tmp_8_cast_fu_338_p1() {
    tmp_8_cast_fu_338_p1 = esl_zext<7,6>(knn_set_0_0_V_read.read());
}

void digitrec_knn_vote::thread_tmp_fu_494_p2() {
    tmp_fu_494_p2 = (!tmp_8_3_2_cast_fu_486_p1.read().is_01() || !tmp_8_3_1_cast_fu_482_p1.read().is_01())? sc_lv<7>(): (sc_biguint<7>(tmp_8_3_2_cast_fu_486_p1.read()) + sc_biguint<7>(tmp_8_3_1_cast_fu_482_p1.read()));
}

void digitrec_knn_vote::thread_tmp_s_fu_642_p2() {
    tmp_s_fu_642_p2 = (tmp_6_3_reg_980.read() | tmp_6_2_reg_975.read());
}

void digitrec_knn_vote::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 2 : 
            ap_NS_fsm = ap_ST_st3_fsm_2;
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_st4_fsm_3;
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_st1_fsm_0;
            break;
        default : 
            ap_NS_fsm = "XXXX";
            break;
    }
}

}

