// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "digitrec.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic digitrec::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic digitrec::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<4> digitrec::ap_ST_st1_fsm_0 = "1";
const sc_lv<4> digitrec::ap_ST_pp0_stg0_fsm_1 = "10";
const sc_lv<4> digitrec::ap_ST_st5_fsm_2 = "100";
const sc_lv<4> digitrec::ap_ST_st6_fsm_3 = "1000";
const sc_lv<32> digitrec::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> digitrec::ap_const_lv1_1 = "1";
const bool digitrec::ap_true = true;
const sc_lv<32> digitrec::ap_const_lv32_1 = "1";
const sc_lv<1> digitrec::ap_const_lv1_0 = "0";
const sc_lv<32> digitrec::ap_const_lv32_2 = "10";
const sc_lv<11> digitrec::ap_const_lv11_0 = "00000000000";
const sc_lv<32> digitrec::ap_const_lv32_3 = "11";
const sc_lv<6> digitrec::ap_const_lv6_32 = "110010";
const sc_lv<11> digitrec::ap_const_lv11_708 = "11100001000";
const sc_lv<11> digitrec::ap_const_lv11_1 = "1";
const sc_lv<12> digitrec::ap_const_lv12_708 = "11100001000";
const sc_lv<13> digitrec::ap_const_lv13_E10 = "111000010000";
const sc_lv<13> digitrec::ap_const_lv13_1518 = "1010100011000";
const sc_lv<14> digitrec::ap_const_lv14_1C20 = "1110000100000";
const sc_lv<14> digitrec::ap_const_lv14_2328 = "10001100101000";
const sc_lv<14> digitrec::ap_const_lv14_2A30 = "10101000110000";
const sc_lv<13> digitrec::ap_const_lv13_1138 = "1000100111000";
const sc_lv<12> digitrec::ap_const_lv12_840 = "100001000000";
const sc_lv<15> digitrec::ap_const_lv15_3F48 = "11111101001000";

digitrec::digitrec(sc_module_name name) : sc_module(name), mVcdFile(0) {
    training_data_V_U = new digitrec_training_data_V("training_data_V_U");
    training_data_V_U->clk(ap_clk);
    training_data_V_U->reset(ap_rst);
    training_data_V_U->address0(training_data_V_address0);
    training_data_V_U->ce0(training_data_V_ce0);
    training_data_V_U->q0(training_data_V_q0);
    training_data_V_U->address1(training_data_V_address1);
    training_data_V_U->ce1(training_data_V_ce1);
    training_data_V_U->q1(training_data_V_q1);
    training_data_V_U->address2(training_data_V_address2);
    training_data_V_U->ce2(training_data_V_ce2);
    training_data_V_U->q2(training_data_V_q2);
    training_data_V_U->address3(training_data_V_address3);
    training_data_V_U->ce3(training_data_V_ce3);
    training_data_V_U->q3(training_data_V_q3);
    training_data_V_U->address4(training_data_V_address4);
    training_data_V_U->ce4(training_data_V_ce4);
    training_data_V_U->q4(training_data_V_q4);
    training_data_V_U->address5(training_data_V_address5);
    training_data_V_U->ce5(training_data_V_ce5);
    training_data_V_U->q5(training_data_V_q5);
    training_data_V_U->address6(training_data_V_address6);
    training_data_V_U->ce6(training_data_V_ce6);
    training_data_V_U->q6(training_data_V_q6);
    training_data_V_U->address7(training_data_V_address7);
    training_data_V_U->ce7(training_data_V_ce7);
    training_data_V_U->q7(training_data_V_q7);
    training_data_V_U->address8(training_data_V_address8);
    training_data_V_U->ce8(training_data_V_ce8);
    training_data_V_U->q8(training_data_V_q8);
    training_data_V_U->address9(training_data_V_address9);
    training_data_V_U->ce9(training_data_V_ce9);
    training_data_V_U->q9(training_data_V_q9);
    grp_digitrec_knn_vote_fu_318 = new digitrec_knn_vote("grp_digitrec_knn_vote_fu_318");
    grp_digitrec_knn_vote_fu_318->ap_clk(ap_clk);
    grp_digitrec_knn_vote_fu_318->ap_rst(ap_rst);
    grp_digitrec_knn_vote_fu_318->ap_start(grp_digitrec_knn_vote_fu_318_ap_start);
    grp_digitrec_knn_vote_fu_318->ap_done(grp_digitrec_knn_vote_fu_318_ap_done);
    grp_digitrec_knn_vote_fu_318->ap_idle(grp_digitrec_knn_vote_fu_318_ap_idle);
    grp_digitrec_knn_vote_fu_318->ap_ready(grp_digitrec_knn_vote_fu_318_ap_ready);
    grp_digitrec_knn_vote_fu_318->knn_set_0_0_V_read(knn_set_0_0_V_fu_70);
    grp_digitrec_knn_vote_fu_318->knn_set_0_1_V_read(knn_set_0_1_V_fu_74);
    grp_digitrec_knn_vote_fu_318->knn_set_0_2_V_read(knn_set_0_2_V_fu_78);
    grp_digitrec_knn_vote_fu_318->knn_set_1_0_V_read(knn_set_1_0_V_fu_82);
    grp_digitrec_knn_vote_fu_318->knn_set_1_1_V_read(knn_set_1_1_V_fu_86);
    grp_digitrec_knn_vote_fu_318->knn_set_1_2_V_read(knn_set_1_2_V_fu_90);
    grp_digitrec_knn_vote_fu_318->knn_set_2_0_V_read(knn_set_2_0_V_fu_94);
    grp_digitrec_knn_vote_fu_318->knn_set_2_1_V_read(knn_set_2_1_V_fu_98);
    grp_digitrec_knn_vote_fu_318->knn_set_2_2_V_read(knn_set_2_2_V_fu_102);
    grp_digitrec_knn_vote_fu_318->knn_set_3_0_V_read(knn_set_3_0_V_fu_106);
    grp_digitrec_knn_vote_fu_318->knn_set_3_1_V_read(knn_set_3_1_V_fu_110);
    grp_digitrec_knn_vote_fu_318->knn_set_3_2_V_read(knn_set_3_2_V_fu_114);
    grp_digitrec_knn_vote_fu_318->knn_set_4_0_V_read(knn_set_4_0_V_fu_118);
    grp_digitrec_knn_vote_fu_318->knn_set_4_1_V_read(knn_set_4_1_V_fu_122);
    grp_digitrec_knn_vote_fu_318->knn_set_4_2_V_read(knn_set_4_2_V_fu_126);
    grp_digitrec_knn_vote_fu_318->knn_set_5_0_V_read(knn_set_5_0_V_fu_130);
    grp_digitrec_knn_vote_fu_318->knn_set_5_1_V_read(knn_set_5_1_V_fu_134);
    grp_digitrec_knn_vote_fu_318->knn_set_5_2_V_read(knn_set_5_2_V_fu_138);
    grp_digitrec_knn_vote_fu_318->knn_set_6_0_V_read(knn_set_6_0_V_fu_142);
    grp_digitrec_knn_vote_fu_318->knn_set_6_1_V_read(knn_set_6_1_V_fu_146);
    grp_digitrec_knn_vote_fu_318->knn_set_6_2_V_read(knn_set_6_2_V_fu_150);
    grp_digitrec_knn_vote_fu_318->knn_set_7_0_V_read(knn_set_7_0_V_fu_154);
    grp_digitrec_knn_vote_fu_318->knn_set_7_1_V_read(knn_set_7_1_V_fu_158);
    grp_digitrec_knn_vote_fu_318->knn_set_7_2_V_read(knn_set_7_2_V_fu_162);
    grp_digitrec_knn_vote_fu_318->knn_set_8_0_V_read(knn_set_8_0_V_fu_166);
    grp_digitrec_knn_vote_fu_318->knn_set_8_1_V_read(knn_set_8_1_V_fu_170);
    grp_digitrec_knn_vote_fu_318->knn_set_8_2_V_read(knn_set_8_2_V_fu_174);
    grp_digitrec_knn_vote_fu_318->knn_set_9_0_V_read(knn_set_9_0_V_fu_178);
    grp_digitrec_knn_vote_fu_318->knn_set_9_1_V_read(knn_set_9_1_V_fu_182);
    grp_digitrec_knn_vote_fu_318->knn_set_9_2_V_read(knn_set_9_2_V_fu_186);
    grp_digitrec_knn_vote_fu_318->ap_return(grp_digitrec_knn_vote_fu_318_ap_return);
    stg_135_digitrec_update_knn_fu_352 = new digitrec_update_knn("stg_135_digitrec_update_knn_fu_352");
    stg_135_digitrec_update_knn_fu_352->test_inst_V(input_V);
    stg_135_digitrec_update_knn_fu_352->train_inst_V(training_data_V_load_reg_1135);
    stg_135_digitrec_update_knn_fu_352->min_distances_0_V_i(knn_set_0_0_V_fu_70);
    stg_135_digitrec_update_knn_fu_352->min_distances_0_V_o(stg_135_digitrec_update_knn_fu_352_min_distances_0_V_o);
    stg_135_digitrec_update_knn_fu_352->min_distances_0_V_o_ap_vld(stg_135_digitrec_update_knn_fu_352_min_distances_0_V_o_ap_vld);
    stg_135_digitrec_update_knn_fu_352->min_distances_1_V_i(knn_set_0_1_V_fu_74);
    stg_135_digitrec_update_knn_fu_352->min_distances_1_V_o(stg_135_digitrec_update_knn_fu_352_min_distances_1_V_o);
    stg_135_digitrec_update_knn_fu_352->min_distances_1_V_o_ap_vld(stg_135_digitrec_update_knn_fu_352_min_distances_1_V_o_ap_vld);
    stg_135_digitrec_update_knn_fu_352->min_distances_2_V_i(knn_set_0_2_V_fu_78);
    stg_135_digitrec_update_knn_fu_352->min_distances_2_V_o(stg_135_digitrec_update_knn_fu_352_min_distances_2_V_o);
    stg_135_digitrec_update_knn_fu_352->min_distances_2_V_o_ap_vld(stg_135_digitrec_update_knn_fu_352_min_distances_2_V_o_ap_vld);
    stg_136_digitrec_update_knn_fu_361 = new digitrec_update_knn("stg_136_digitrec_update_knn_fu_361");
    stg_136_digitrec_update_knn_fu_361->test_inst_V(input_V);
    stg_136_digitrec_update_knn_fu_361->train_inst_V(training_data_V_load_1_reg_1140);
    stg_136_digitrec_update_knn_fu_361->min_distances_0_V_i(knn_set_1_0_V_fu_82);
    stg_136_digitrec_update_knn_fu_361->min_distances_0_V_o(stg_136_digitrec_update_knn_fu_361_min_distances_0_V_o);
    stg_136_digitrec_update_knn_fu_361->min_distances_0_V_o_ap_vld(stg_136_digitrec_update_knn_fu_361_min_distances_0_V_o_ap_vld);
    stg_136_digitrec_update_knn_fu_361->min_distances_1_V_i(knn_set_1_1_V_fu_86);
    stg_136_digitrec_update_knn_fu_361->min_distances_1_V_o(stg_136_digitrec_update_knn_fu_361_min_distances_1_V_o);
    stg_136_digitrec_update_knn_fu_361->min_distances_1_V_o_ap_vld(stg_136_digitrec_update_knn_fu_361_min_distances_1_V_o_ap_vld);
    stg_136_digitrec_update_knn_fu_361->min_distances_2_V_i(knn_set_1_2_V_fu_90);
    stg_136_digitrec_update_knn_fu_361->min_distances_2_V_o(stg_136_digitrec_update_knn_fu_361_min_distances_2_V_o);
    stg_136_digitrec_update_knn_fu_361->min_distances_2_V_o_ap_vld(stg_136_digitrec_update_knn_fu_361_min_distances_2_V_o_ap_vld);
    stg_137_digitrec_update_knn_fu_370 = new digitrec_update_knn("stg_137_digitrec_update_knn_fu_370");
    stg_137_digitrec_update_knn_fu_370->test_inst_V(input_V);
    stg_137_digitrec_update_knn_fu_370->train_inst_V(training_data_V_load_2_reg_1145);
    stg_137_digitrec_update_knn_fu_370->min_distances_0_V_i(knn_set_2_0_V_fu_94);
    stg_137_digitrec_update_knn_fu_370->min_distances_0_V_o(stg_137_digitrec_update_knn_fu_370_min_distances_0_V_o);
    stg_137_digitrec_update_knn_fu_370->min_distances_0_V_o_ap_vld(stg_137_digitrec_update_knn_fu_370_min_distances_0_V_o_ap_vld);
    stg_137_digitrec_update_knn_fu_370->min_distances_1_V_i(knn_set_2_1_V_fu_98);
    stg_137_digitrec_update_knn_fu_370->min_distances_1_V_o(stg_137_digitrec_update_knn_fu_370_min_distances_1_V_o);
    stg_137_digitrec_update_knn_fu_370->min_distances_1_V_o_ap_vld(stg_137_digitrec_update_knn_fu_370_min_distances_1_V_o_ap_vld);
    stg_137_digitrec_update_knn_fu_370->min_distances_2_V_i(knn_set_2_2_V_fu_102);
    stg_137_digitrec_update_knn_fu_370->min_distances_2_V_o(stg_137_digitrec_update_knn_fu_370_min_distances_2_V_o);
    stg_137_digitrec_update_knn_fu_370->min_distances_2_V_o_ap_vld(stg_137_digitrec_update_knn_fu_370_min_distances_2_V_o_ap_vld);
    stg_138_digitrec_update_knn_fu_379 = new digitrec_update_knn("stg_138_digitrec_update_knn_fu_379");
    stg_138_digitrec_update_knn_fu_379->test_inst_V(input_V);
    stg_138_digitrec_update_knn_fu_379->train_inst_V(training_data_V_load_3_reg_1150);
    stg_138_digitrec_update_knn_fu_379->min_distances_0_V_i(knn_set_3_0_V_fu_106);
    stg_138_digitrec_update_knn_fu_379->min_distances_0_V_o(stg_138_digitrec_update_knn_fu_379_min_distances_0_V_o);
    stg_138_digitrec_update_knn_fu_379->min_distances_0_V_o_ap_vld(stg_138_digitrec_update_knn_fu_379_min_distances_0_V_o_ap_vld);
    stg_138_digitrec_update_knn_fu_379->min_distances_1_V_i(knn_set_3_1_V_fu_110);
    stg_138_digitrec_update_knn_fu_379->min_distances_1_V_o(stg_138_digitrec_update_knn_fu_379_min_distances_1_V_o);
    stg_138_digitrec_update_knn_fu_379->min_distances_1_V_o_ap_vld(stg_138_digitrec_update_knn_fu_379_min_distances_1_V_o_ap_vld);
    stg_138_digitrec_update_knn_fu_379->min_distances_2_V_i(knn_set_3_2_V_fu_114);
    stg_138_digitrec_update_knn_fu_379->min_distances_2_V_o(stg_138_digitrec_update_knn_fu_379_min_distances_2_V_o);
    stg_138_digitrec_update_knn_fu_379->min_distances_2_V_o_ap_vld(stg_138_digitrec_update_knn_fu_379_min_distances_2_V_o_ap_vld);
    stg_139_digitrec_update_knn_fu_388 = new digitrec_update_knn("stg_139_digitrec_update_knn_fu_388");
    stg_139_digitrec_update_knn_fu_388->test_inst_V(input_V);
    stg_139_digitrec_update_knn_fu_388->train_inst_V(training_data_V_load_4_reg_1155);
    stg_139_digitrec_update_knn_fu_388->min_distances_0_V_i(knn_set_4_0_V_fu_118);
    stg_139_digitrec_update_knn_fu_388->min_distances_0_V_o(stg_139_digitrec_update_knn_fu_388_min_distances_0_V_o);
    stg_139_digitrec_update_knn_fu_388->min_distances_0_V_o_ap_vld(stg_139_digitrec_update_knn_fu_388_min_distances_0_V_o_ap_vld);
    stg_139_digitrec_update_knn_fu_388->min_distances_1_V_i(knn_set_4_1_V_fu_122);
    stg_139_digitrec_update_knn_fu_388->min_distances_1_V_o(stg_139_digitrec_update_knn_fu_388_min_distances_1_V_o);
    stg_139_digitrec_update_knn_fu_388->min_distances_1_V_o_ap_vld(stg_139_digitrec_update_knn_fu_388_min_distances_1_V_o_ap_vld);
    stg_139_digitrec_update_knn_fu_388->min_distances_2_V_i(knn_set_4_2_V_fu_126);
    stg_139_digitrec_update_knn_fu_388->min_distances_2_V_o(stg_139_digitrec_update_knn_fu_388_min_distances_2_V_o);
    stg_139_digitrec_update_knn_fu_388->min_distances_2_V_o_ap_vld(stg_139_digitrec_update_knn_fu_388_min_distances_2_V_o_ap_vld);
    stg_140_digitrec_update_knn_fu_397 = new digitrec_update_knn("stg_140_digitrec_update_knn_fu_397");
    stg_140_digitrec_update_knn_fu_397->test_inst_V(input_V);
    stg_140_digitrec_update_knn_fu_397->train_inst_V(training_data_V_load_5_reg_1160);
    stg_140_digitrec_update_knn_fu_397->min_distances_0_V_i(knn_set_5_0_V_fu_130);
    stg_140_digitrec_update_knn_fu_397->min_distances_0_V_o(stg_140_digitrec_update_knn_fu_397_min_distances_0_V_o);
    stg_140_digitrec_update_knn_fu_397->min_distances_0_V_o_ap_vld(stg_140_digitrec_update_knn_fu_397_min_distances_0_V_o_ap_vld);
    stg_140_digitrec_update_knn_fu_397->min_distances_1_V_i(knn_set_5_1_V_fu_134);
    stg_140_digitrec_update_knn_fu_397->min_distances_1_V_o(stg_140_digitrec_update_knn_fu_397_min_distances_1_V_o);
    stg_140_digitrec_update_knn_fu_397->min_distances_1_V_o_ap_vld(stg_140_digitrec_update_knn_fu_397_min_distances_1_V_o_ap_vld);
    stg_140_digitrec_update_knn_fu_397->min_distances_2_V_i(knn_set_5_2_V_fu_138);
    stg_140_digitrec_update_knn_fu_397->min_distances_2_V_o(stg_140_digitrec_update_knn_fu_397_min_distances_2_V_o);
    stg_140_digitrec_update_knn_fu_397->min_distances_2_V_o_ap_vld(stg_140_digitrec_update_knn_fu_397_min_distances_2_V_o_ap_vld);
    stg_141_digitrec_update_knn_fu_406 = new digitrec_update_knn("stg_141_digitrec_update_knn_fu_406");
    stg_141_digitrec_update_knn_fu_406->test_inst_V(input_V);
    stg_141_digitrec_update_knn_fu_406->train_inst_V(training_data_V_load_6_reg_1165);
    stg_141_digitrec_update_knn_fu_406->min_distances_0_V_i(knn_set_6_0_V_fu_142);
    stg_141_digitrec_update_knn_fu_406->min_distances_0_V_o(stg_141_digitrec_update_knn_fu_406_min_distances_0_V_o);
    stg_141_digitrec_update_knn_fu_406->min_distances_0_V_o_ap_vld(stg_141_digitrec_update_knn_fu_406_min_distances_0_V_o_ap_vld);
    stg_141_digitrec_update_knn_fu_406->min_distances_1_V_i(knn_set_6_1_V_fu_146);
    stg_141_digitrec_update_knn_fu_406->min_distances_1_V_o(stg_141_digitrec_update_knn_fu_406_min_distances_1_V_o);
    stg_141_digitrec_update_knn_fu_406->min_distances_1_V_o_ap_vld(stg_141_digitrec_update_knn_fu_406_min_distances_1_V_o_ap_vld);
    stg_141_digitrec_update_knn_fu_406->min_distances_2_V_i(knn_set_6_2_V_fu_150);
    stg_141_digitrec_update_knn_fu_406->min_distances_2_V_o(stg_141_digitrec_update_knn_fu_406_min_distances_2_V_o);
    stg_141_digitrec_update_knn_fu_406->min_distances_2_V_o_ap_vld(stg_141_digitrec_update_knn_fu_406_min_distances_2_V_o_ap_vld);
    stg_142_digitrec_update_knn_fu_415 = new digitrec_update_knn("stg_142_digitrec_update_knn_fu_415");
    stg_142_digitrec_update_knn_fu_415->test_inst_V(input_V);
    stg_142_digitrec_update_knn_fu_415->train_inst_V(training_data_V_load_7_reg_1170);
    stg_142_digitrec_update_knn_fu_415->min_distances_0_V_i(knn_set_7_0_V_fu_154);
    stg_142_digitrec_update_knn_fu_415->min_distances_0_V_o(stg_142_digitrec_update_knn_fu_415_min_distances_0_V_o);
    stg_142_digitrec_update_knn_fu_415->min_distances_0_V_o_ap_vld(stg_142_digitrec_update_knn_fu_415_min_distances_0_V_o_ap_vld);
    stg_142_digitrec_update_knn_fu_415->min_distances_1_V_i(knn_set_7_1_V_fu_158);
    stg_142_digitrec_update_knn_fu_415->min_distances_1_V_o(stg_142_digitrec_update_knn_fu_415_min_distances_1_V_o);
    stg_142_digitrec_update_knn_fu_415->min_distances_1_V_o_ap_vld(stg_142_digitrec_update_knn_fu_415_min_distances_1_V_o_ap_vld);
    stg_142_digitrec_update_knn_fu_415->min_distances_2_V_i(knn_set_7_2_V_fu_162);
    stg_142_digitrec_update_knn_fu_415->min_distances_2_V_o(stg_142_digitrec_update_knn_fu_415_min_distances_2_V_o);
    stg_142_digitrec_update_knn_fu_415->min_distances_2_V_o_ap_vld(stg_142_digitrec_update_knn_fu_415_min_distances_2_V_o_ap_vld);
    stg_143_digitrec_update_knn_fu_424 = new digitrec_update_knn("stg_143_digitrec_update_knn_fu_424");
    stg_143_digitrec_update_knn_fu_424->test_inst_V(input_V);
    stg_143_digitrec_update_knn_fu_424->train_inst_V(training_data_V_load_8_reg_1175);
    stg_143_digitrec_update_knn_fu_424->min_distances_0_V_i(knn_set_8_0_V_fu_166);
    stg_143_digitrec_update_knn_fu_424->min_distances_0_V_o(stg_143_digitrec_update_knn_fu_424_min_distances_0_V_o);
    stg_143_digitrec_update_knn_fu_424->min_distances_0_V_o_ap_vld(stg_143_digitrec_update_knn_fu_424_min_distances_0_V_o_ap_vld);
    stg_143_digitrec_update_knn_fu_424->min_distances_1_V_i(knn_set_8_1_V_fu_170);
    stg_143_digitrec_update_knn_fu_424->min_distances_1_V_o(stg_143_digitrec_update_knn_fu_424_min_distances_1_V_o);
    stg_143_digitrec_update_knn_fu_424->min_distances_1_V_o_ap_vld(stg_143_digitrec_update_knn_fu_424_min_distances_1_V_o_ap_vld);
    stg_143_digitrec_update_knn_fu_424->min_distances_2_V_i(knn_set_8_2_V_fu_174);
    stg_143_digitrec_update_knn_fu_424->min_distances_2_V_o(stg_143_digitrec_update_knn_fu_424_min_distances_2_V_o);
    stg_143_digitrec_update_knn_fu_424->min_distances_2_V_o_ap_vld(stg_143_digitrec_update_knn_fu_424_min_distances_2_V_o_ap_vld);
    stg_144_digitrec_update_knn_fu_433 = new digitrec_update_knn("stg_144_digitrec_update_knn_fu_433");
    stg_144_digitrec_update_knn_fu_433->test_inst_V(input_V);
    stg_144_digitrec_update_knn_fu_433->train_inst_V(training_data_V_load_9_reg_1180);
    stg_144_digitrec_update_knn_fu_433->min_distances_0_V_i(knn_set_9_0_V_fu_178);
    stg_144_digitrec_update_knn_fu_433->min_distances_0_V_o(stg_144_digitrec_update_knn_fu_433_min_distances_0_V_o);
    stg_144_digitrec_update_knn_fu_433->min_distances_0_V_o_ap_vld(stg_144_digitrec_update_knn_fu_433_min_distances_0_V_o_ap_vld);
    stg_144_digitrec_update_knn_fu_433->min_distances_1_V_i(knn_set_9_1_V_fu_182);
    stg_144_digitrec_update_knn_fu_433->min_distances_1_V_o(stg_144_digitrec_update_knn_fu_433_min_distances_1_V_o);
    stg_144_digitrec_update_knn_fu_433->min_distances_1_V_o_ap_vld(stg_144_digitrec_update_knn_fu_433_min_distances_1_V_o_ap_vld);
    stg_144_digitrec_update_knn_fu_433->min_distances_2_V_i(knn_set_9_2_V_fu_186);
    stg_144_digitrec_update_knn_fu_433->min_distances_2_V_o(stg_144_digitrec_update_knn_fu_433_min_distances_2_V_o);
    stg_144_digitrec_update_knn_fu_433->min_distances_2_V_o_ap_vld(stg_144_digitrec_update_knn_fu_433_min_distances_2_V_o_ap_vld);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_done);
    sensitive << ( grp_digitrec_knn_vote_fu_318_ap_done );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_3 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( grp_digitrec_knn_vote_fu_318_ap_done );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_3 );

    SC_METHOD(thread_ap_return);
    sensitive << ( grp_digitrec_knn_vote_fu_318_ap_done );
    sensitive << ( grp_digitrec_knn_vote_fu_318_ap_return );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_3 );

    SC_METHOD(thread_ap_sig_141);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_19);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_372);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_85);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_cseq_ST_pp0_stg0_fsm_1);
    sensitive << ( ap_sig_85 );

    SC_METHOD(thread_ap_sig_cseq_ST_st1_fsm_0);
    sensitive << ( ap_sig_19 );

    SC_METHOD(thread_ap_sig_cseq_ST_st5_fsm_2);
    sensitive << ( ap_sig_141 );

    SC_METHOD(thread_ap_sig_cseq_ST_st6_fsm_3);
    sensitive << ( ap_sig_372 );

    SC_METHOD(thread_exitcond3_fu_592_p2);
    sensitive << ( i4_reg_307 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );

    SC_METHOD(thread_grp_digitrec_knn_vote_fu_318_ap_start);
    sensitive << ( ap_reg_grp_digitrec_knn_vote_fu_318_ap_start );

    SC_METHOD(thread_i4_cast3_cast7_fu_612_p1);
    sensitive << ( i4_reg_307 );

    SC_METHOD(thread_i4_cast3_cast_fu_616_p1);
    sensitive << ( i4_reg_307 );

    SC_METHOD(thread_i4_cast3_fu_608_p1);
    sensitive << ( i4_reg_307 );

    SC_METHOD(thread_i4_cast4_fu_604_p1);
    sensitive << ( i4_reg_307 );

    SC_METHOD(thread_i_fu_598_p2);
    sensitive << ( i4_reg_307 );

    SC_METHOD(thread_tmp_2_1_fu_625_p2);
    sensitive << ( i4_cast3_cast7_fu_612_p1 );

    SC_METHOD(thread_tmp_2_2_fu_636_p2);
    sensitive << ( i4_cast3_cast_fu_616_p1 );

    SC_METHOD(thread_tmp_2_3_fu_647_p2);
    sensitive << ( i4_cast3_cast_fu_616_p1 );

    SC_METHOD(thread_tmp_2_4_fu_658_p2);
    sensitive << ( i4_cast3_fu_608_p1 );

    SC_METHOD(thread_tmp_2_5_fu_669_p2);
    sensitive << ( i4_cast3_fu_608_p1 );

    SC_METHOD(thread_tmp_2_6_fu_680_p2);
    sensitive << ( i4_cast3_fu_608_p1 );

    SC_METHOD(thread_tmp_2_7_cast6_fu_697_p1);
    sensitive << ( tmp_2_7_fu_691_p2 );

    SC_METHOD(thread_tmp_2_7_fu_691_p2);
    sensitive << ( i4_cast3_cast_fu_616_p1 );

    SC_METHOD(thread_tmp_2_8_cast5_fu_712_p1);
    sensitive << ( tmp_2_8_fu_706_p2 );

    SC_METHOD(thread_tmp_2_8_fu_706_p2);
    sensitive << ( i4_cast3_cast7_fu_612_p1 );

    SC_METHOD(thread_tmp_2_9_fu_721_p2);
    sensitive << ( i4_cast4_fu_604_p1 );

    SC_METHOD(thread_tmp_3_1_fu_631_p1);
    sensitive << ( tmp_2_1_fu_625_p2 );

    SC_METHOD(thread_tmp_3_2_fu_642_p1);
    sensitive << ( tmp_2_2_fu_636_p2 );

    SC_METHOD(thread_tmp_3_3_fu_653_p1);
    sensitive << ( tmp_2_3_fu_647_p2 );

    SC_METHOD(thread_tmp_3_4_fu_664_p1);
    sensitive << ( tmp_2_4_fu_658_p2 );

    SC_METHOD(thread_tmp_3_5_fu_675_p1);
    sensitive << ( tmp_2_5_fu_669_p2 );

    SC_METHOD(thread_tmp_3_6_fu_686_p1);
    sensitive << ( tmp_2_6_fu_680_p2 );

    SC_METHOD(thread_tmp_3_7_fu_701_p1);
    sensitive << ( tmp_2_7_cast6_fu_697_p1 );

    SC_METHOD(thread_tmp_3_8_fu_716_p1);
    sensitive << ( tmp_2_8_cast5_fu_712_p1 );

    SC_METHOD(thread_tmp_3_9_fu_727_p1);
    sensitive << ( tmp_2_9_fu_721_p2 );

    SC_METHOD(thread_tmp_3_fu_620_p1);
    sensitive << ( i4_reg_307 );

    SC_METHOD(thread_training_data_V_address0);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( tmp_3_fu_620_p1 );

    SC_METHOD(thread_training_data_V_address1);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( tmp_3_1_fu_631_p1 );

    SC_METHOD(thread_training_data_V_address2);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( tmp_3_2_fu_642_p1 );

    SC_METHOD(thread_training_data_V_address3);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( tmp_3_3_fu_653_p1 );

    SC_METHOD(thread_training_data_V_address4);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( tmp_3_4_fu_664_p1 );

    SC_METHOD(thread_training_data_V_address5);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( tmp_3_5_fu_675_p1 );

    SC_METHOD(thread_training_data_V_address6);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( tmp_3_6_fu_686_p1 );

    SC_METHOD(thread_training_data_V_address7);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( tmp_3_7_fu_701_p1 );

    SC_METHOD(thread_training_data_V_address8);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( tmp_3_8_fu_716_p1 );

    SC_METHOD(thread_training_data_V_address9);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( tmp_3_9_fu_727_p1 );

    SC_METHOD(thread_training_data_V_ce0);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );

    SC_METHOD(thread_training_data_V_ce1);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );

    SC_METHOD(thread_training_data_V_ce2);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );

    SC_METHOD(thread_training_data_V_ce3);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );

    SC_METHOD(thread_training_data_V_ce4);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );

    SC_METHOD(thread_training_data_V_ce5);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );

    SC_METHOD(thread_training_data_V_ce6);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );

    SC_METHOD(thread_training_data_V_ce7);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );

    SC_METHOD(thread_training_data_V_ce8);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );

    SC_METHOD(thread_training_data_V_ce9);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond3_fu_592_p2 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppiten_pp0_it2 );
    sensitive << ( grp_digitrec_knn_vote_fu_318_ap_done );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    ap_CS_fsm = "0001";
    ap_reg_ppiten_pp0_it0 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it1 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it2 = SC_LOGIC_0;
    ap_reg_grp_digitrec_knn_vote_fu_318_ap_start = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "digitrec_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, input_V, "(port)input_V");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st1_fsm_0, "ap_sig_cseq_ST_st1_fsm_0");
    sc_trace(mVcdFile, ap_sig_19, "ap_sig_19");
    sc_trace(mVcdFile, training_data_V_address0, "training_data_V_address0");
    sc_trace(mVcdFile, training_data_V_ce0, "training_data_V_ce0");
    sc_trace(mVcdFile, training_data_V_q0, "training_data_V_q0");
    sc_trace(mVcdFile, training_data_V_address1, "training_data_V_address1");
    sc_trace(mVcdFile, training_data_V_ce1, "training_data_V_ce1");
    sc_trace(mVcdFile, training_data_V_q1, "training_data_V_q1");
    sc_trace(mVcdFile, training_data_V_address2, "training_data_V_address2");
    sc_trace(mVcdFile, training_data_V_ce2, "training_data_V_ce2");
    sc_trace(mVcdFile, training_data_V_q2, "training_data_V_q2");
    sc_trace(mVcdFile, training_data_V_address3, "training_data_V_address3");
    sc_trace(mVcdFile, training_data_V_ce3, "training_data_V_ce3");
    sc_trace(mVcdFile, training_data_V_q3, "training_data_V_q3");
    sc_trace(mVcdFile, training_data_V_address4, "training_data_V_address4");
    sc_trace(mVcdFile, training_data_V_ce4, "training_data_V_ce4");
    sc_trace(mVcdFile, training_data_V_q4, "training_data_V_q4");
    sc_trace(mVcdFile, training_data_V_address5, "training_data_V_address5");
    sc_trace(mVcdFile, training_data_V_ce5, "training_data_V_ce5");
    sc_trace(mVcdFile, training_data_V_q5, "training_data_V_q5");
    sc_trace(mVcdFile, training_data_V_address6, "training_data_V_address6");
    sc_trace(mVcdFile, training_data_V_ce6, "training_data_V_ce6");
    sc_trace(mVcdFile, training_data_V_q6, "training_data_V_q6");
    sc_trace(mVcdFile, training_data_V_address7, "training_data_V_address7");
    sc_trace(mVcdFile, training_data_V_ce7, "training_data_V_ce7");
    sc_trace(mVcdFile, training_data_V_q7, "training_data_V_q7");
    sc_trace(mVcdFile, training_data_V_address8, "training_data_V_address8");
    sc_trace(mVcdFile, training_data_V_ce8, "training_data_V_ce8");
    sc_trace(mVcdFile, training_data_V_q8, "training_data_V_q8");
    sc_trace(mVcdFile, training_data_V_address9, "training_data_V_address9");
    sc_trace(mVcdFile, training_data_V_ce9, "training_data_V_ce9");
    sc_trace(mVcdFile, training_data_V_q9, "training_data_V_q9");
    sc_trace(mVcdFile, i4_reg_307, "i4_reg_307");
    sc_trace(mVcdFile, exitcond3_fu_592_p2, "exitcond3_fu_592_p2");
    sc_trace(mVcdFile, exitcond3_reg_1076, "exitcond3_reg_1076");
    sc_trace(mVcdFile, ap_sig_cseq_ST_pp0_stg0_fsm_1, "ap_sig_cseq_ST_pp0_stg0_fsm_1");
    sc_trace(mVcdFile, ap_sig_85, "ap_sig_85");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it0, "ap_reg_ppiten_pp0_it0");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it1, "ap_reg_ppiten_pp0_it1");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it2, "ap_reg_ppiten_pp0_it2");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond3_reg_1076_pp0_iter1, "ap_reg_ppstg_exitcond3_reg_1076_pp0_iter1");
    sc_trace(mVcdFile, i_fu_598_p2, "i_fu_598_p2");
    sc_trace(mVcdFile, training_data_V_load_reg_1135, "training_data_V_load_reg_1135");
    sc_trace(mVcdFile, training_data_V_load_1_reg_1140, "training_data_V_load_1_reg_1140");
    sc_trace(mVcdFile, training_data_V_load_2_reg_1145, "training_data_V_load_2_reg_1145");
    sc_trace(mVcdFile, training_data_V_load_3_reg_1150, "training_data_V_load_3_reg_1150");
    sc_trace(mVcdFile, training_data_V_load_4_reg_1155, "training_data_V_load_4_reg_1155");
    sc_trace(mVcdFile, training_data_V_load_5_reg_1160, "training_data_V_load_5_reg_1160");
    sc_trace(mVcdFile, training_data_V_load_6_reg_1165, "training_data_V_load_6_reg_1165");
    sc_trace(mVcdFile, training_data_V_load_7_reg_1170, "training_data_V_load_7_reg_1170");
    sc_trace(mVcdFile, training_data_V_load_8_reg_1175, "training_data_V_load_8_reg_1175");
    sc_trace(mVcdFile, training_data_V_load_9_reg_1180, "training_data_V_load_9_reg_1180");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st5_fsm_2, "ap_sig_cseq_ST_st5_fsm_2");
    sc_trace(mVcdFile, ap_sig_141, "ap_sig_141");
    sc_trace(mVcdFile, grp_digitrec_knn_vote_fu_318_ap_start, "grp_digitrec_knn_vote_fu_318_ap_start");
    sc_trace(mVcdFile, grp_digitrec_knn_vote_fu_318_ap_done, "grp_digitrec_knn_vote_fu_318_ap_done");
    sc_trace(mVcdFile, grp_digitrec_knn_vote_fu_318_ap_idle, "grp_digitrec_knn_vote_fu_318_ap_idle");
    sc_trace(mVcdFile, grp_digitrec_knn_vote_fu_318_ap_ready, "grp_digitrec_knn_vote_fu_318_ap_ready");
    sc_trace(mVcdFile, grp_digitrec_knn_vote_fu_318_ap_return, "grp_digitrec_knn_vote_fu_318_ap_return");
    sc_trace(mVcdFile, stg_135_digitrec_update_knn_fu_352_min_distances_0_V_o, "stg_135_digitrec_update_knn_fu_352_min_distances_0_V_o");
    sc_trace(mVcdFile, stg_135_digitrec_update_knn_fu_352_min_distances_0_V_o_ap_vld, "stg_135_digitrec_update_knn_fu_352_min_distances_0_V_o_ap_vld");
    sc_trace(mVcdFile, stg_135_digitrec_update_knn_fu_352_min_distances_1_V_o, "stg_135_digitrec_update_knn_fu_352_min_distances_1_V_o");
    sc_trace(mVcdFile, stg_135_digitrec_update_knn_fu_352_min_distances_1_V_o_ap_vld, "stg_135_digitrec_update_knn_fu_352_min_distances_1_V_o_ap_vld");
    sc_trace(mVcdFile, stg_135_digitrec_update_knn_fu_352_min_distances_2_V_o, "stg_135_digitrec_update_knn_fu_352_min_distances_2_V_o");
    sc_trace(mVcdFile, stg_135_digitrec_update_knn_fu_352_min_distances_2_V_o_ap_vld, "stg_135_digitrec_update_knn_fu_352_min_distances_2_V_o_ap_vld");
    sc_trace(mVcdFile, stg_136_digitrec_update_knn_fu_361_min_distances_0_V_o, "stg_136_digitrec_update_knn_fu_361_min_distances_0_V_o");
    sc_trace(mVcdFile, stg_136_digitrec_update_knn_fu_361_min_distances_0_V_o_ap_vld, "stg_136_digitrec_update_knn_fu_361_min_distances_0_V_o_ap_vld");
    sc_trace(mVcdFile, stg_136_digitrec_update_knn_fu_361_min_distances_1_V_o, "stg_136_digitrec_update_knn_fu_361_min_distances_1_V_o");
    sc_trace(mVcdFile, stg_136_digitrec_update_knn_fu_361_min_distances_1_V_o_ap_vld, "stg_136_digitrec_update_knn_fu_361_min_distances_1_V_o_ap_vld");
    sc_trace(mVcdFile, stg_136_digitrec_update_knn_fu_361_min_distances_2_V_o, "stg_136_digitrec_update_knn_fu_361_min_distances_2_V_o");
    sc_trace(mVcdFile, stg_136_digitrec_update_knn_fu_361_min_distances_2_V_o_ap_vld, "stg_136_digitrec_update_knn_fu_361_min_distances_2_V_o_ap_vld");
    sc_trace(mVcdFile, stg_137_digitrec_update_knn_fu_370_min_distances_0_V_o, "stg_137_digitrec_update_knn_fu_370_min_distances_0_V_o");
    sc_trace(mVcdFile, stg_137_digitrec_update_knn_fu_370_min_distances_0_V_o_ap_vld, "stg_137_digitrec_update_knn_fu_370_min_distances_0_V_o_ap_vld");
    sc_trace(mVcdFile, stg_137_digitrec_update_knn_fu_370_min_distances_1_V_o, "stg_137_digitrec_update_knn_fu_370_min_distances_1_V_o");
    sc_trace(mVcdFile, stg_137_digitrec_update_knn_fu_370_min_distances_1_V_o_ap_vld, "stg_137_digitrec_update_knn_fu_370_min_distances_1_V_o_ap_vld");
    sc_trace(mVcdFile, stg_137_digitrec_update_knn_fu_370_min_distances_2_V_o, "stg_137_digitrec_update_knn_fu_370_min_distances_2_V_o");
    sc_trace(mVcdFile, stg_137_digitrec_update_knn_fu_370_min_distances_2_V_o_ap_vld, "stg_137_digitrec_update_knn_fu_370_min_distances_2_V_o_ap_vld");
    sc_trace(mVcdFile, stg_138_digitrec_update_knn_fu_379_min_distances_0_V_o, "stg_138_digitrec_update_knn_fu_379_min_distances_0_V_o");
    sc_trace(mVcdFile, stg_138_digitrec_update_knn_fu_379_min_distances_0_V_o_ap_vld, "stg_138_digitrec_update_knn_fu_379_min_distances_0_V_o_ap_vld");
    sc_trace(mVcdFile, stg_138_digitrec_update_knn_fu_379_min_distances_1_V_o, "stg_138_digitrec_update_knn_fu_379_min_distances_1_V_o");
    sc_trace(mVcdFile, stg_138_digitrec_update_knn_fu_379_min_distances_1_V_o_ap_vld, "stg_138_digitrec_update_knn_fu_379_min_distances_1_V_o_ap_vld");
    sc_trace(mVcdFile, stg_138_digitrec_update_knn_fu_379_min_distances_2_V_o, "stg_138_digitrec_update_knn_fu_379_min_distances_2_V_o");
    sc_trace(mVcdFile, stg_138_digitrec_update_knn_fu_379_min_distances_2_V_o_ap_vld, "stg_138_digitrec_update_knn_fu_379_min_distances_2_V_o_ap_vld");
    sc_trace(mVcdFile, stg_139_digitrec_update_knn_fu_388_min_distances_0_V_o, "stg_139_digitrec_update_knn_fu_388_min_distances_0_V_o");
    sc_trace(mVcdFile, stg_139_digitrec_update_knn_fu_388_min_distances_0_V_o_ap_vld, "stg_139_digitrec_update_knn_fu_388_min_distances_0_V_o_ap_vld");
    sc_trace(mVcdFile, stg_139_digitrec_update_knn_fu_388_min_distances_1_V_o, "stg_139_digitrec_update_knn_fu_388_min_distances_1_V_o");
    sc_trace(mVcdFile, stg_139_digitrec_update_knn_fu_388_min_distances_1_V_o_ap_vld, "stg_139_digitrec_update_knn_fu_388_min_distances_1_V_o_ap_vld");
    sc_trace(mVcdFile, stg_139_digitrec_update_knn_fu_388_min_distances_2_V_o, "stg_139_digitrec_update_knn_fu_388_min_distances_2_V_o");
    sc_trace(mVcdFile, stg_139_digitrec_update_knn_fu_388_min_distances_2_V_o_ap_vld, "stg_139_digitrec_update_knn_fu_388_min_distances_2_V_o_ap_vld");
    sc_trace(mVcdFile, stg_140_digitrec_update_knn_fu_397_min_distances_0_V_o, "stg_140_digitrec_update_knn_fu_397_min_distances_0_V_o");
    sc_trace(mVcdFile, stg_140_digitrec_update_knn_fu_397_min_distances_0_V_o_ap_vld, "stg_140_digitrec_update_knn_fu_397_min_distances_0_V_o_ap_vld");
    sc_trace(mVcdFile, stg_140_digitrec_update_knn_fu_397_min_distances_1_V_o, "stg_140_digitrec_update_knn_fu_397_min_distances_1_V_o");
    sc_trace(mVcdFile, stg_140_digitrec_update_knn_fu_397_min_distances_1_V_o_ap_vld, "stg_140_digitrec_update_knn_fu_397_min_distances_1_V_o_ap_vld");
    sc_trace(mVcdFile, stg_140_digitrec_update_knn_fu_397_min_distances_2_V_o, "stg_140_digitrec_update_knn_fu_397_min_distances_2_V_o");
    sc_trace(mVcdFile, stg_140_digitrec_update_knn_fu_397_min_distances_2_V_o_ap_vld, "stg_140_digitrec_update_knn_fu_397_min_distances_2_V_o_ap_vld");
    sc_trace(mVcdFile, stg_141_digitrec_update_knn_fu_406_min_distances_0_V_o, "stg_141_digitrec_update_knn_fu_406_min_distances_0_V_o");
    sc_trace(mVcdFile, stg_141_digitrec_update_knn_fu_406_min_distances_0_V_o_ap_vld, "stg_141_digitrec_update_knn_fu_406_min_distances_0_V_o_ap_vld");
    sc_trace(mVcdFile, stg_141_digitrec_update_knn_fu_406_min_distances_1_V_o, "stg_141_digitrec_update_knn_fu_406_min_distances_1_V_o");
    sc_trace(mVcdFile, stg_141_digitrec_update_knn_fu_406_min_distances_1_V_o_ap_vld, "stg_141_digitrec_update_knn_fu_406_min_distances_1_V_o_ap_vld");
    sc_trace(mVcdFile, stg_141_digitrec_update_knn_fu_406_min_distances_2_V_o, "stg_141_digitrec_update_knn_fu_406_min_distances_2_V_o");
    sc_trace(mVcdFile, stg_141_digitrec_update_knn_fu_406_min_distances_2_V_o_ap_vld, "stg_141_digitrec_update_knn_fu_406_min_distances_2_V_o_ap_vld");
    sc_trace(mVcdFile, stg_142_digitrec_update_knn_fu_415_min_distances_0_V_o, "stg_142_digitrec_update_knn_fu_415_min_distances_0_V_o");
    sc_trace(mVcdFile, stg_142_digitrec_update_knn_fu_415_min_distances_0_V_o_ap_vld, "stg_142_digitrec_update_knn_fu_415_min_distances_0_V_o_ap_vld");
    sc_trace(mVcdFile, stg_142_digitrec_update_knn_fu_415_min_distances_1_V_o, "stg_142_digitrec_update_knn_fu_415_min_distances_1_V_o");
    sc_trace(mVcdFile, stg_142_digitrec_update_knn_fu_415_min_distances_1_V_o_ap_vld, "stg_142_digitrec_update_knn_fu_415_min_distances_1_V_o_ap_vld");
    sc_trace(mVcdFile, stg_142_digitrec_update_knn_fu_415_min_distances_2_V_o, "stg_142_digitrec_update_knn_fu_415_min_distances_2_V_o");
    sc_trace(mVcdFile, stg_142_digitrec_update_knn_fu_415_min_distances_2_V_o_ap_vld, "stg_142_digitrec_update_knn_fu_415_min_distances_2_V_o_ap_vld");
    sc_trace(mVcdFile, stg_143_digitrec_update_knn_fu_424_min_distances_0_V_o, "stg_143_digitrec_update_knn_fu_424_min_distances_0_V_o");
    sc_trace(mVcdFile, stg_143_digitrec_update_knn_fu_424_min_distances_0_V_o_ap_vld, "stg_143_digitrec_update_knn_fu_424_min_distances_0_V_o_ap_vld");
    sc_trace(mVcdFile, stg_143_digitrec_update_knn_fu_424_min_distances_1_V_o, "stg_143_digitrec_update_knn_fu_424_min_distances_1_V_o");
    sc_trace(mVcdFile, stg_143_digitrec_update_knn_fu_424_min_distances_1_V_o_ap_vld, "stg_143_digitrec_update_knn_fu_424_min_distances_1_V_o_ap_vld");
    sc_trace(mVcdFile, stg_143_digitrec_update_knn_fu_424_min_distances_2_V_o, "stg_143_digitrec_update_knn_fu_424_min_distances_2_V_o");
    sc_trace(mVcdFile, stg_143_digitrec_update_knn_fu_424_min_distances_2_V_o_ap_vld, "stg_143_digitrec_update_knn_fu_424_min_distances_2_V_o_ap_vld");
    sc_trace(mVcdFile, stg_144_digitrec_update_knn_fu_433_min_distances_0_V_o, "stg_144_digitrec_update_knn_fu_433_min_distances_0_V_o");
    sc_trace(mVcdFile, stg_144_digitrec_update_knn_fu_433_min_distances_0_V_o_ap_vld, "stg_144_digitrec_update_knn_fu_433_min_distances_0_V_o_ap_vld");
    sc_trace(mVcdFile, stg_144_digitrec_update_knn_fu_433_min_distances_1_V_o, "stg_144_digitrec_update_knn_fu_433_min_distances_1_V_o");
    sc_trace(mVcdFile, stg_144_digitrec_update_knn_fu_433_min_distances_1_V_o_ap_vld, "stg_144_digitrec_update_knn_fu_433_min_distances_1_V_o_ap_vld");
    sc_trace(mVcdFile, stg_144_digitrec_update_knn_fu_433_min_distances_2_V_o, "stg_144_digitrec_update_knn_fu_433_min_distances_2_V_o");
    sc_trace(mVcdFile, stg_144_digitrec_update_knn_fu_433_min_distances_2_V_o_ap_vld, "stg_144_digitrec_update_knn_fu_433_min_distances_2_V_o_ap_vld");
    sc_trace(mVcdFile, ap_reg_grp_digitrec_knn_vote_fu_318_ap_start, "ap_reg_grp_digitrec_knn_vote_fu_318_ap_start");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st6_fsm_3, "ap_sig_cseq_ST_st6_fsm_3");
    sc_trace(mVcdFile, ap_sig_372, "ap_sig_372");
    sc_trace(mVcdFile, knn_set_0_0_V_fu_70, "knn_set_0_0_V_fu_70");
    sc_trace(mVcdFile, knn_set_0_1_V_fu_74, "knn_set_0_1_V_fu_74");
    sc_trace(mVcdFile, knn_set_0_2_V_fu_78, "knn_set_0_2_V_fu_78");
    sc_trace(mVcdFile, knn_set_1_0_V_fu_82, "knn_set_1_0_V_fu_82");
    sc_trace(mVcdFile, knn_set_1_1_V_fu_86, "knn_set_1_1_V_fu_86");
    sc_trace(mVcdFile, knn_set_1_2_V_fu_90, "knn_set_1_2_V_fu_90");
    sc_trace(mVcdFile, knn_set_2_0_V_fu_94, "knn_set_2_0_V_fu_94");
    sc_trace(mVcdFile, knn_set_2_1_V_fu_98, "knn_set_2_1_V_fu_98");
    sc_trace(mVcdFile, knn_set_2_2_V_fu_102, "knn_set_2_2_V_fu_102");
    sc_trace(mVcdFile, knn_set_3_0_V_fu_106, "knn_set_3_0_V_fu_106");
    sc_trace(mVcdFile, knn_set_3_1_V_fu_110, "knn_set_3_1_V_fu_110");
    sc_trace(mVcdFile, knn_set_3_2_V_fu_114, "knn_set_3_2_V_fu_114");
    sc_trace(mVcdFile, knn_set_4_0_V_fu_118, "knn_set_4_0_V_fu_118");
    sc_trace(mVcdFile, knn_set_4_1_V_fu_122, "knn_set_4_1_V_fu_122");
    sc_trace(mVcdFile, knn_set_4_2_V_fu_126, "knn_set_4_2_V_fu_126");
    sc_trace(mVcdFile, knn_set_5_0_V_fu_130, "knn_set_5_0_V_fu_130");
    sc_trace(mVcdFile, knn_set_5_1_V_fu_134, "knn_set_5_1_V_fu_134");
    sc_trace(mVcdFile, knn_set_5_2_V_fu_138, "knn_set_5_2_V_fu_138");
    sc_trace(mVcdFile, knn_set_6_0_V_fu_142, "knn_set_6_0_V_fu_142");
    sc_trace(mVcdFile, knn_set_6_1_V_fu_146, "knn_set_6_1_V_fu_146");
    sc_trace(mVcdFile, knn_set_6_2_V_fu_150, "knn_set_6_2_V_fu_150");
    sc_trace(mVcdFile, knn_set_7_0_V_fu_154, "knn_set_7_0_V_fu_154");
    sc_trace(mVcdFile, knn_set_7_1_V_fu_158, "knn_set_7_1_V_fu_158");
    sc_trace(mVcdFile, knn_set_7_2_V_fu_162, "knn_set_7_2_V_fu_162");
    sc_trace(mVcdFile, knn_set_8_0_V_fu_166, "knn_set_8_0_V_fu_166");
    sc_trace(mVcdFile, knn_set_8_1_V_fu_170, "knn_set_8_1_V_fu_170");
    sc_trace(mVcdFile, knn_set_8_2_V_fu_174, "knn_set_8_2_V_fu_174");
    sc_trace(mVcdFile, knn_set_9_0_V_fu_178, "knn_set_9_0_V_fu_178");
    sc_trace(mVcdFile, knn_set_9_1_V_fu_182, "knn_set_9_1_V_fu_182");
    sc_trace(mVcdFile, knn_set_9_2_V_fu_186, "knn_set_9_2_V_fu_186");
    sc_trace(mVcdFile, tmp_3_fu_620_p1, "tmp_3_fu_620_p1");
    sc_trace(mVcdFile, tmp_3_1_fu_631_p1, "tmp_3_1_fu_631_p1");
    sc_trace(mVcdFile, tmp_3_2_fu_642_p1, "tmp_3_2_fu_642_p1");
    sc_trace(mVcdFile, tmp_3_3_fu_653_p1, "tmp_3_3_fu_653_p1");
    sc_trace(mVcdFile, tmp_3_4_fu_664_p1, "tmp_3_4_fu_664_p1");
    sc_trace(mVcdFile, tmp_3_5_fu_675_p1, "tmp_3_5_fu_675_p1");
    sc_trace(mVcdFile, tmp_3_6_fu_686_p1, "tmp_3_6_fu_686_p1");
    sc_trace(mVcdFile, tmp_3_7_fu_701_p1, "tmp_3_7_fu_701_p1");
    sc_trace(mVcdFile, tmp_3_8_fu_716_p1, "tmp_3_8_fu_716_p1");
    sc_trace(mVcdFile, tmp_3_9_fu_727_p1, "tmp_3_9_fu_727_p1");
    sc_trace(mVcdFile, i4_cast3_cast7_fu_612_p1, "i4_cast3_cast7_fu_612_p1");
    sc_trace(mVcdFile, tmp_2_1_fu_625_p2, "tmp_2_1_fu_625_p2");
    sc_trace(mVcdFile, i4_cast3_cast_fu_616_p1, "i4_cast3_cast_fu_616_p1");
    sc_trace(mVcdFile, tmp_2_2_fu_636_p2, "tmp_2_2_fu_636_p2");
    sc_trace(mVcdFile, tmp_2_3_fu_647_p2, "tmp_2_3_fu_647_p2");
    sc_trace(mVcdFile, i4_cast3_fu_608_p1, "i4_cast3_fu_608_p1");
    sc_trace(mVcdFile, tmp_2_4_fu_658_p2, "tmp_2_4_fu_658_p2");
    sc_trace(mVcdFile, tmp_2_5_fu_669_p2, "tmp_2_5_fu_669_p2");
    sc_trace(mVcdFile, tmp_2_6_fu_680_p2, "tmp_2_6_fu_680_p2");
    sc_trace(mVcdFile, tmp_2_7_fu_691_p2, "tmp_2_7_fu_691_p2");
    sc_trace(mVcdFile, tmp_2_7_cast6_fu_697_p1, "tmp_2_7_cast6_fu_697_p1");
    sc_trace(mVcdFile, tmp_2_8_fu_706_p2, "tmp_2_8_fu_706_p2");
    sc_trace(mVcdFile, tmp_2_8_cast5_fu_712_p1, "tmp_2_8_cast5_fu_712_p1");
    sc_trace(mVcdFile, i4_cast4_fu_604_p1, "i4_cast4_fu_604_p1");
    sc_trace(mVcdFile, tmp_2_9_fu_721_p2, "tmp_2_9_fu_721_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("digitrec.hdltvin.dat");
    mHdltvoutHandle.open("digitrec.hdltvout.dat");
}

digitrec::~digitrec() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete training_data_V_U;
    delete grp_digitrec_knn_vote_fu_318;
    delete stg_135_digitrec_update_knn_fu_352;
    delete stg_136_digitrec_update_knn_fu_361;
    delete stg_137_digitrec_update_knn_fu_370;
    delete stg_138_digitrec_update_knn_fu_379;
    delete stg_139_digitrec_update_knn_fu_388;
    delete stg_140_digitrec_update_knn_fu_397;
    delete stg_141_digitrec_update_knn_fu_406;
    delete stg_142_digitrec_update_knn_fu_415;
    delete stg_143_digitrec_update_knn_fu_424;
    delete stg_144_digitrec_update_knn_fu_433;
}

void digitrec::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_grp_digitrec_knn_vote_fu_318_ap_start = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_2.read())) {
            ap_reg_grp_digitrec_knn_vote_fu_318_ap_start = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_digitrec_knn_vote_fu_318_ap_ready.read())) {
            ap_reg_grp_digitrec_knn_vote_fu_318_ap_start = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
             !esl_seteq<1,1,1>(exitcond3_fu_592_p2.read(), ap_const_lv1_0))) {
            ap_reg_ppiten_pp0_it0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                    !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_reg_ppiten_pp0_it0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
             esl_seteq<1,1,1>(exitcond3_fu_592_p2.read(), ap_const_lv1_0))) {
            ap_reg_ppiten_pp0_it1 = ap_const_logic_1;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                     !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
                     !esl_seteq<1,1,1>(exitcond3_fu_592_p2.read(), ap_const_lv1_0)))) {
            ap_reg_ppiten_pp0_it1 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it2 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_true, ap_true)) {
            ap_reg_ppiten_pp0_it2 = ap_reg_ppiten_pp0_it1.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                    !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_reg_ppiten_pp0_it2 = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
         !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        i4_reg_307 = ap_const_lv11_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
                esl_seteq<1,1,1>(exitcond3_fu_592_p2.read(), ap_const_lv1_0))) {
        i4_reg_307 = i_fu_598_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
         !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        knn_set_0_0_V_fu_70 = ap_const_lv6_32;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && 
                esl_seteq<1,1,1>(ap_reg_ppstg_exitcond3_reg_1076_pp0_iter1.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, stg_135_digitrec_update_knn_fu_352_min_distances_0_V_o_ap_vld.read()))) {
        knn_set_0_0_V_fu_70 = stg_135_digitrec_update_knn_fu_352_min_distances_0_V_o.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
         !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        knn_set_0_1_V_fu_74 = ap_const_lv6_32;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && 
                esl_seteq<1,1,1>(ap_reg_ppstg_exitcond3_reg_1076_pp0_iter1.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, stg_135_digitrec_update_knn_fu_352_min_distances_1_V_o_ap_vld.read()))) {
        knn_set_0_1_V_fu_74 = stg_135_digitrec_update_knn_fu_352_min_distances_1_V_o.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
         !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        knn_set_0_2_V_fu_78 = ap_const_lv6_32;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && 
                esl_seteq<1,1,1>(ap_reg_ppstg_exitcond3_reg_1076_pp0_iter1.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, stg_135_digitrec_update_knn_fu_352_min_distances_2_V_o_ap_vld.read()))) {
        knn_set_0_2_V_fu_78 = stg_135_digitrec_update_knn_fu_352_min_distances_2_V_o.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
         !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        knn_set_1_0_V_fu_82 = ap_const_lv6_32;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && 
                esl_seteq<1,1,1>(ap_reg_ppstg_exitcond3_reg_1076_pp0_iter1.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, stg_136_digitrec_update_knn_fu_361_min_distances_0_V_o_ap_vld.read()))) {
        knn_set_1_0_V_fu_82 = stg_136_digitrec_update_knn_fu_361_min_distances_0_V_o.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
         !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        knn_set_1_1_V_fu_86 = ap_const_lv6_32;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && 
                esl_seteq<1,1,1>(ap_reg_ppstg_exitcond3_reg_1076_pp0_iter1.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, stg_136_digitrec_update_knn_fu_361_min_distances_1_V_o_ap_vld.read()))) {
        knn_set_1_1_V_fu_86 = stg_136_digitrec_update_knn_fu_361_min_distances_1_V_o.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
         !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        knn_set_1_2_V_fu_90 = ap_const_lv6_32;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && 
                esl_seteq<1,1,1>(ap_reg_ppstg_exitcond3_reg_1076_pp0_iter1.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, stg_136_digitrec_update_knn_fu_361_min_distances_2_V_o_ap_vld.read()))) {
        knn_set_1_2_V_fu_90 = stg_136_digitrec_update_knn_fu_361_min_distances_2_V_o.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
         !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        knn_set_2_0_V_fu_94 = ap_const_lv6_32;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && 
                esl_seteq<1,1,1>(ap_reg_ppstg_exitcond3_reg_1076_pp0_iter1.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, stg_137_digitrec_update_knn_fu_370_min_distances_0_V_o_ap_vld.read()))) {
        knn_set_2_0_V_fu_94 = stg_137_digitrec_update_knn_fu_370_min_distances_0_V_o.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
         !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        knn_set_2_1_V_fu_98 = ap_const_lv6_32;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && 
                esl_seteq<1,1,1>(ap_reg_ppstg_exitcond3_reg_1076_pp0_iter1.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, stg_137_digitrec_update_knn_fu_370_min_distances_1_V_o_ap_vld.read()))) {
        knn_set_2_1_V_fu_98 = stg_137_digitrec_update_knn_fu_370_min_distances_1_V_o.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
         !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        knn_set_2_2_V_fu_102 = ap_const_lv6_32;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && 
                esl_seteq<1,1,1>(ap_reg_ppstg_exitcond3_reg_1076_pp0_iter1.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, stg_137_digitrec_update_knn_fu_370_min_distances_2_V_o_ap_vld.read()))) {
        knn_set_2_2_V_fu_102 = stg_137_digitrec_update_knn_fu_370_min_distances_2_V_o.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
         !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        knn_set_3_0_V_fu_106 = ap_const_lv6_32;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && 
                esl_seteq<1,1,1>(ap_reg_ppstg_exitcond3_reg_1076_pp0_iter1.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, stg_138_digitrec_update_knn_fu_379_min_distances_0_V_o_ap_vld.read()))) {
        knn_set_3_0_V_fu_106 = stg_138_digitrec_update_knn_fu_379_min_distances_0_V_o.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
         !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        knn_set_3_1_V_fu_110 = ap_const_lv6_32;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && 
                esl_seteq<1,1,1>(ap_reg_ppstg_exitcond3_reg_1076_pp0_iter1.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, stg_138_digitrec_update_knn_fu_379_min_distances_1_V_o_ap_vld.read()))) {
        knn_set_3_1_V_fu_110 = stg_138_digitrec_update_knn_fu_379_min_distances_1_V_o.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
         !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        knn_set_3_2_V_fu_114 = ap_const_lv6_32;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && 
                esl_seteq<1,1,1>(ap_reg_ppstg_exitcond3_reg_1076_pp0_iter1.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, stg_138_digitrec_update_knn_fu_379_min_distances_2_V_o_ap_vld.read()))) {
        knn_set_3_2_V_fu_114 = stg_138_digitrec_update_knn_fu_379_min_distances_2_V_o.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
         !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        knn_set_4_0_V_fu_118 = ap_const_lv6_32;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && 
                esl_seteq<1,1,1>(ap_reg_ppstg_exitcond3_reg_1076_pp0_iter1.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, stg_139_digitrec_update_knn_fu_388_min_distances_0_V_o_ap_vld.read()))) {
        knn_set_4_0_V_fu_118 = stg_139_digitrec_update_knn_fu_388_min_distances_0_V_o.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
         !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        knn_set_4_1_V_fu_122 = ap_const_lv6_32;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && 
                esl_seteq<1,1,1>(ap_reg_ppstg_exitcond3_reg_1076_pp0_iter1.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, stg_139_digitrec_update_knn_fu_388_min_distances_1_V_o_ap_vld.read()))) {
        knn_set_4_1_V_fu_122 = stg_139_digitrec_update_knn_fu_388_min_distances_1_V_o.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
         !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        knn_set_4_2_V_fu_126 = ap_const_lv6_32;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && 
                esl_seteq<1,1,1>(ap_reg_ppstg_exitcond3_reg_1076_pp0_iter1.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, stg_139_digitrec_update_knn_fu_388_min_distances_2_V_o_ap_vld.read()))) {
        knn_set_4_2_V_fu_126 = stg_139_digitrec_update_knn_fu_388_min_distances_2_V_o.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
         !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        knn_set_5_0_V_fu_130 = ap_const_lv6_32;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && 
                esl_seteq<1,1,1>(ap_reg_ppstg_exitcond3_reg_1076_pp0_iter1.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, stg_140_digitrec_update_knn_fu_397_min_distances_0_V_o_ap_vld.read()))) {
        knn_set_5_0_V_fu_130 = stg_140_digitrec_update_knn_fu_397_min_distances_0_V_o.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
         !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        knn_set_5_1_V_fu_134 = ap_const_lv6_32;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && 
                esl_seteq<1,1,1>(ap_reg_ppstg_exitcond3_reg_1076_pp0_iter1.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, stg_140_digitrec_update_knn_fu_397_min_distances_1_V_o_ap_vld.read()))) {
        knn_set_5_1_V_fu_134 = stg_140_digitrec_update_knn_fu_397_min_distances_1_V_o.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
         !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        knn_set_5_2_V_fu_138 = ap_const_lv6_32;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && 
                esl_seteq<1,1,1>(ap_reg_ppstg_exitcond3_reg_1076_pp0_iter1.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, stg_140_digitrec_update_knn_fu_397_min_distances_2_V_o_ap_vld.read()))) {
        knn_set_5_2_V_fu_138 = stg_140_digitrec_update_knn_fu_397_min_distances_2_V_o.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
         !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        knn_set_6_0_V_fu_142 = ap_const_lv6_32;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && 
                esl_seteq<1,1,1>(ap_reg_ppstg_exitcond3_reg_1076_pp0_iter1.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, stg_141_digitrec_update_knn_fu_406_min_distances_0_V_o_ap_vld.read()))) {
        knn_set_6_0_V_fu_142 = stg_141_digitrec_update_knn_fu_406_min_distances_0_V_o.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
         !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        knn_set_6_1_V_fu_146 = ap_const_lv6_32;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && 
                esl_seteq<1,1,1>(ap_reg_ppstg_exitcond3_reg_1076_pp0_iter1.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, stg_141_digitrec_update_knn_fu_406_min_distances_1_V_o_ap_vld.read()))) {
        knn_set_6_1_V_fu_146 = stg_141_digitrec_update_knn_fu_406_min_distances_1_V_o.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
         !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        knn_set_6_2_V_fu_150 = ap_const_lv6_32;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && 
                esl_seteq<1,1,1>(ap_reg_ppstg_exitcond3_reg_1076_pp0_iter1.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, stg_141_digitrec_update_knn_fu_406_min_distances_2_V_o_ap_vld.read()))) {
        knn_set_6_2_V_fu_150 = stg_141_digitrec_update_knn_fu_406_min_distances_2_V_o.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
         !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        knn_set_7_0_V_fu_154 = ap_const_lv6_32;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && 
                esl_seteq<1,1,1>(ap_reg_ppstg_exitcond3_reg_1076_pp0_iter1.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, stg_142_digitrec_update_knn_fu_415_min_distances_0_V_o_ap_vld.read()))) {
        knn_set_7_0_V_fu_154 = stg_142_digitrec_update_knn_fu_415_min_distances_0_V_o.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
         !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        knn_set_7_1_V_fu_158 = ap_const_lv6_32;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && 
                esl_seteq<1,1,1>(ap_reg_ppstg_exitcond3_reg_1076_pp0_iter1.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, stg_142_digitrec_update_knn_fu_415_min_distances_1_V_o_ap_vld.read()))) {
        knn_set_7_1_V_fu_158 = stg_142_digitrec_update_knn_fu_415_min_distances_1_V_o.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
         !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        knn_set_7_2_V_fu_162 = ap_const_lv6_32;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && 
                esl_seteq<1,1,1>(ap_reg_ppstg_exitcond3_reg_1076_pp0_iter1.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, stg_142_digitrec_update_knn_fu_415_min_distances_2_V_o_ap_vld.read()))) {
        knn_set_7_2_V_fu_162 = stg_142_digitrec_update_knn_fu_415_min_distances_2_V_o.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
         !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        knn_set_8_0_V_fu_166 = ap_const_lv6_32;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && 
                esl_seteq<1,1,1>(ap_reg_ppstg_exitcond3_reg_1076_pp0_iter1.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, stg_143_digitrec_update_knn_fu_424_min_distances_0_V_o_ap_vld.read()))) {
        knn_set_8_0_V_fu_166 = stg_143_digitrec_update_knn_fu_424_min_distances_0_V_o.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
         !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        knn_set_8_1_V_fu_170 = ap_const_lv6_32;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && 
                esl_seteq<1,1,1>(ap_reg_ppstg_exitcond3_reg_1076_pp0_iter1.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, stg_143_digitrec_update_knn_fu_424_min_distances_1_V_o_ap_vld.read()))) {
        knn_set_8_1_V_fu_170 = stg_143_digitrec_update_knn_fu_424_min_distances_1_V_o.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
         !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        knn_set_8_2_V_fu_174 = ap_const_lv6_32;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && 
                esl_seteq<1,1,1>(ap_reg_ppstg_exitcond3_reg_1076_pp0_iter1.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, stg_143_digitrec_update_knn_fu_424_min_distances_2_V_o_ap_vld.read()))) {
        knn_set_8_2_V_fu_174 = stg_143_digitrec_update_knn_fu_424_min_distances_2_V_o.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
         !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        knn_set_9_0_V_fu_178 = ap_const_lv6_32;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && 
                esl_seteq<1,1,1>(ap_reg_ppstg_exitcond3_reg_1076_pp0_iter1.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, stg_144_digitrec_update_knn_fu_433_min_distances_0_V_o_ap_vld.read()))) {
        knn_set_9_0_V_fu_178 = stg_144_digitrec_update_knn_fu_433_min_distances_0_V_o.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
         !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        knn_set_9_1_V_fu_182 = ap_const_lv6_32;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && 
                esl_seteq<1,1,1>(ap_reg_ppstg_exitcond3_reg_1076_pp0_iter1.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, stg_144_digitrec_update_knn_fu_433_min_distances_1_V_o_ap_vld.read()))) {
        knn_set_9_1_V_fu_182 = stg_144_digitrec_update_knn_fu_433_min_distances_1_V_o.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
         !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        knn_set_9_2_V_fu_186 = ap_const_lv6_32;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && 
                esl_seteq<1,1,1>(ap_reg_ppstg_exitcond3_reg_1076_pp0_iter1.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, stg_144_digitrec_update_knn_fu_433_min_distances_2_V_o_ap_vld.read()))) {
        knn_set_9_2_V_fu_186 = stg_144_digitrec_update_knn_fu_433_min_distances_2_V_o.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read())) {
        ap_reg_ppstg_exitcond3_reg_1076_pp0_iter1 = exitcond3_reg_1076.read();
        exitcond3_reg_1076 = exitcond3_fu_592_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && esl_seteq<1,1,1>(exitcond3_reg_1076.read(), ap_const_lv1_0))) {
        training_data_V_load_1_reg_1140 = training_data_V_q1.read();
        training_data_V_load_2_reg_1145 = training_data_V_q2.read();
        training_data_V_load_3_reg_1150 = training_data_V_q3.read();
        training_data_V_load_4_reg_1155 = training_data_V_q4.read();
        training_data_V_load_5_reg_1160 = training_data_V_q5.read();
        training_data_V_load_6_reg_1165 = training_data_V_q6.read();
        training_data_V_load_7_reg_1170 = training_data_V_q7.read();
        training_data_V_load_8_reg_1175 = training_data_V_q8.read();
        training_data_V_load_9_reg_1180 = training_data_V_q9.read();
        training_data_V_load_reg_1135 = training_data_V_q0.read();
    }
}

void digitrec::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_3.read()) && 
         !esl_seteq<1,1,1>(ap_const_logic_0, grp_digitrec_knn_vote_fu_318_ap_done.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void digitrec::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void digitrec::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_3.read()) && 
         !esl_seteq<1,1,1>(ap_const_logic_0, grp_digitrec_knn_vote_fu_318_ap_done.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void digitrec::thread_ap_return() {
    ap_return = grp_digitrec_knn_vote_fu_318_ap_return.read();
}

void digitrec::thread_ap_sig_141() {
    ap_sig_141 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(2, 2));
}

void digitrec::thread_ap_sig_19() {
    ap_sig_19 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void digitrec::thread_ap_sig_372() {
    ap_sig_372 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(3, 3));
}

void digitrec::thread_ap_sig_85() {
    ap_sig_85 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(1, 1));
}

void digitrec::thread_ap_sig_cseq_ST_pp0_stg0_fsm_1() {
    if (ap_sig_85.read()) {
        ap_sig_cseq_ST_pp0_stg0_fsm_1 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_pp0_stg0_fsm_1 = ap_const_logic_0;
    }
}

void digitrec::thread_ap_sig_cseq_ST_st1_fsm_0() {
    if (ap_sig_19.read()) {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    }
}

void digitrec::thread_ap_sig_cseq_ST_st5_fsm_2() {
    if (ap_sig_141.read()) {
        ap_sig_cseq_ST_st5_fsm_2 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st5_fsm_2 = ap_const_logic_0;
    }
}

void digitrec::thread_ap_sig_cseq_ST_st6_fsm_3() {
    if (ap_sig_372.read()) {
        ap_sig_cseq_ST_st6_fsm_3 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st6_fsm_3 = ap_const_logic_0;
    }
}

void digitrec::thread_exitcond3_fu_592_p2() {
    exitcond3_fu_592_p2 = (!i4_reg_307.read().is_01() || !ap_const_lv11_708.is_01())? sc_lv<1>(): sc_lv<1>(i4_reg_307.read() == ap_const_lv11_708);
}

void digitrec::thread_grp_digitrec_knn_vote_fu_318_ap_start() {
    grp_digitrec_knn_vote_fu_318_ap_start = ap_reg_grp_digitrec_knn_vote_fu_318_ap_start.read();
}

void digitrec::thread_i4_cast3_cast7_fu_612_p1() {
    i4_cast3_cast7_fu_612_p1 = esl_zext<12,11>(i4_reg_307.read());
}

void digitrec::thread_i4_cast3_cast_fu_616_p1() {
    i4_cast3_cast_fu_616_p1 = esl_zext<13,11>(i4_reg_307.read());
}

void digitrec::thread_i4_cast3_fu_608_p1() {
    i4_cast3_fu_608_p1 = esl_zext<14,11>(i4_reg_307.read());
}

void digitrec::thread_i4_cast4_fu_604_p1() {
    i4_cast4_fu_604_p1 = esl_zext<15,11>(i4_reg_307.read());
}

void digitrec::thread_i_fu_598_p2() {
    i_fu_598_p2 = (!i4_reg_307.read().is_01() || !ap_const_lv11_1.is_01())? sc_lv<11>(): (sc_biguint<11>(i4_reg_307.read()) + sc_biguint<11>(ap_const_lv11_1));
}

void digitrec::thread_tmp_2_1_fu_625_p2() {
    tmp_2_1_fu_625_p2 = (!i4_cast3_cast7_fu_612_p1.read().is_01() || !ap_const_lv12_708.is_01())? sc_lv<12>(): (sc_biguint<12>(i4_cast3_cast7_fu_612_p1.read()) + sc_biguint<12>(ap_const_lv12_708));
}

void digitrec::thread_tmp_2_2_fu_636_p2() {
    tmp_2_2_fu_636_p2 = (!i4_cast3_cast_fu_616_p1.read().is_01() || !ap_const_lv13_E10.is_01())? sc_lv<13>(): (sc_biguint<13>(i4_cast3_cast_fu_616_p1.read()) + sc_biguint<13>(ap_const_lv13_E10));
}

void digitrec::thread_tmp_2_3_fu_647_p2() {
    tmp_2_3_fu_647_p2 = (!i4_cast3_cast_fu_616_p1.read().is_01() || !ap_const_lv13_1518.is_01())? sc_lv<13>(): (sc_biguint<13>(i4_cast3_cast_fu_616_p1.read()) + sc_bigint<13>(ap_const_lv13_1518));
}

void digitrec::thread_tmp_2_4_fu_658_p2() {
    tmp_2_4_fu_658_p2 = (!i4_cast3_fu_608_p1.read().is_01() || !ap_const_lv14_1C20.is_01())? sc_lv<14>(): (sc_biguint<14>(i4_cast3_fu_608_p1.read()) + sc_biguint<14>(ap_const_lv14_1C20));
}

void digitrec::thread_tmp_2_5_fu_669_p2() {
    tmp_2_5_fu_669_p2 = (!i4_cast3_fu_608_p1.read().is_01() || !ap_const_lv14_2328.is_01())? sc_lv<14>(): (sc_biguint<14>(i4_cast3_fu_608_p1.read()) + sc_bigint<14>(ap_const_lv14_2328));
}

void digitrec::thread_tmp_2_6_fu_680_p2() {
    tmp_2_6_fu_680_p2 = (!i4_cast3_fu_608_p1.read().is_01() || !ap_const_lv14_2A30.is_01())? sc_lv<14>(): (sc_biguint<14>(i4_cast3_fu_608_p1.read()) + sc_bigint<14>(ap_const_lv14_2A30));
}

void digitrec::thread_tmp_2_7_cast6_fu_697_p1() {
    tmp_2_7_cast6_fu_697_p1 = esl_sext<14,13>(tmp_2_7_fu_691_p2.read());
}

void digitrec::thread_tmp_2_7_fu_691_p2() {
    tmp_2_7_fu_691_p2 = (!i4_cast3_cast_fu_616_p1.read().is_01() || !ap_const_lv13_1138.is_01())? sc_lv<13>(): (sc_biguint<13>(i4_cast3_cast_fu_616_p1.read()) + sc_bigint<13>(ap_const_lv13_1138));
}

void digitrec::thread_tmp_2_8_cast5_fu_712_p1() {
    tmp_2_8_cast5_fu_712_p1 = esl_sext<14,12>(tmp_2_8_fu_706_p2.read());
}

void digitrec::thread_tmp_2_8_fu_706_p2() {
    tmp_2_8_fu_706_p2 = (!i4_cast3_cast7_fu_612_p1.read().is_01() || !ap_const_lv12_840.is_01())? sc_lv<12>(): (sc_biguint<12>(i4_cast3_cast7_fu_612_p1.read()) + sc_bigint<12>(ap_const_lv12_840));
}

void digitrec::thread_tmp_2_9_fu_721_p2() {
    tmp_2_9_fu_721_p2 = (!i4_cast4_fu_604_p1.read().is_01() || !ap_const_lv15_3F48.is_01())? sc_lv<15>(): (sc_biguint<15>(i4_cast4_fu_604_p1.read()) + sc_biguint<15>(ap_const_lv15_3F48));
}

void digitrec::thread_tmp_3_1_fu_631_p1() {
    tmp_3_1_fu_631_p1 = esl_zext<64,12>(tmp_2_1_fu_625_p2.read());
}

void digitrec::thread_tmp_3_2_fu_642_p1() {
    tmp_3_2_fu_642_p1 = esl_zext<64,13>(tmp_2_2_fu_636_p2.read());
}

void digitrec::thread_tmp_3_3_fu_653_p1() {
    tmp_3_3_fu_653_p1 = esl_zext<64,13>(tmp_2_3_fu_647_p2.read());
}

void digitrec::thread_tmp_3_4_fu_664_p1() {
    tmp_3_4_fu_664_p1 = esl_zext<64,14>(tmp_2_4_fu_658_p2.read());
}

void digitrec::thread_tmp_3_5_fu_675_p1() {
    tmp_3_5_fu_675_p1 = esl_zext<64,14>(tmp_2_5_fu_669_p2.read());
}

void digitrec::thread_tmp_3_6_fu_686_p1() {
    tmp_3_6_fu_686_p1 = esl_zext<64,14>(tmp_2_6_fu_680_p2.read());
}

void digitrec::thread_tmp_3_7_fu_701_p1() {
    tmp_3_7_fu_701_p1 = esl_zext<64,14>(tmp_2_7_cast6_fu_697_p1.read());
}

void digitrec::thread_tmp_3_8_fu_716_p1() {
    tmp_3_8_fu_716_p1 = esl_zext<64,14>(tmp_2_8_cast5_fu_712_p1.read());
}

void digitrec::thread_tmp_3_9_fu_727_p1() {
    tmp_3_9_fu_727_p1 = esl_zext<64,15>(tmp_2_9_fu_721_p2.read());
}

void digitrec::thread_tmp_3_fu_620_p1() {
    tmp_3_fu_620_p1 = esl_zext<64,11>(i4_reg_307.read());
}

void digitrec::thread_training_data_V_address0() {
    training_data_V_address0 =  (sc_lv<15>) (tmp_3_fu_620_p1.read());
}

void digitrec::thread_training_data_V_address1() {
    training_data_V_address1 =  (sc_lv<15>) (tmp_3_1_fu_631_p1.read());
}

void digitrec::thread_training_data_V_address2() {
    training_data_V_address2 =  (sc_lv<15>) (tmp_3_2_fu_642_p1.read());
}

void digitrec::thread_training_data_V_address3() {
    training_data_V_address3 =  (sc_lv<15>) (tmp_3_3_fu_653_p1.read());
}

void digitrec::thread_training_data_V_address4() {
    training_data_V_address4 =  (sc_lv<15>) (tmp_3_4_fu_664_p1.read());
}

void digitrec::thread_training_data_V_address5() {
    training_data_V_address5 =  (sc_lv<15>) (tmp_3_5_fu_675_p1.read());
}

void digitrec::thread_training_data_V_address6() {
    training_data_V_address6 =  (sc_lv<15>) (tmp_3_6_fu_686_p1.read());
}

void digitrec::thread_training_data_V_address7() {
    training_data_V_address7 =  (sc_lv<15>) (tmp_3_7_fu_701_p1.read());
}

void digitrec::thread_training_data_V_address8() {
    training_data_V_address8 =  (sc_lv<15>) (tmp_3_8_fu_716_p1.read());
}

void digitrec::thread_training_data_V_address9() {
    training_data_V_address9 =  (sc_lv<15>) (tmp_3_9_fu_727_p1.read());
}

void digitrec::thread_training_data_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()))) {
        training_data_V_ce0 = ap_const_logic_1;
    } else {
        training_data_V_ce0 = ap_const_logic_0;
    }
}

void digitrec::thread_training_data_V_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()))) {
        training_data_V_ce1 = ap_const_logic_1;
    } else {
        training_data_V_ce1 = ap_const_logic_0;
    }
}

void digitrec::thread_training_data_V_ce2() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()))) {
        training_data_V_ce2 = ap_const_logic_1;
    } else {
        training_data_V_ce2 = ap_const_logic_0;
    }
}

void digitrec::thread_training_data_V_ce3() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()))) {
        training_data_V_ce3 = ap_const_logic_1;
    } else {
        training_data_V_ce3 = ap_const_logic_0;
    }
}

void digitrec::thread_training_data_V_ce4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()))) {
        training_data_V_ce4 = ap_const_logic_1;
    } else {
        training_data_V_ce4 = ap_const_logic_0;
    }
}

void digitrec::thread_training_data_V_ce5() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()))) {
        training_data_V_ce5 = ap_const_logic_1;
    } else {
        training_data_V_ce5 = ap_const_logic_0;
    }
}

void digitrec::thread_training_data_V_ce6() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()))) {
        training_data_V_ce6 = ap_const_logic_1;
    } else {
        training_data_V_ce6 = ap_const_logic_0;
    }
}

void digitrec::thread_training_data_V_ce7() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()))) {
        training_data_V_ce7 = ap_const_logic_1;
    } else {
        training_data_V_ce7 = ap_const_logic_0;
    }
}

void digitrec::thread_training_data_V_ce8() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()))) {
        training_data_V_ce8 = ap_const_logic_1;
    } else {
        training_data_V_ce8 = ap_const_logic_0;
    }
}

void digitrec::thread_training_data_V_ce9() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()))) {
        training_data_V_ce9 = ap_const_logic_1;
    } else {
        training_data_V_ce9 = ap_const_logic_0;
    }
}

void digitrec::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) {
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 2 : 
            if ((!(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && !esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && !esl_seteq<1,1,1>(exitcond3_fu_592_p2.read(), ap_const_lv1_0) && !esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_1;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && !esl_seteq<1,1,1>(exitcond3_fu_592_p2.read(), ap_const_lv1_0) && !esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()))) {
                ap_NS_fsm = ap_ST_st5_fsm_2;
            } else {
                ap_NS_fsm = ap_ST_st5_fsm_2;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_st6_fsm_3;
            break;
        case 8 : 
            if (!esl_seteq<1,1,1>(ap_const_logic_0, grp_digitrec_knn_vote_fu_318_ap_done.read())) {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            } else {
                ap_NS_fsm = ap_ST_st6_fsm_3;
            }
            break;
        default : 
            ap_NS_fsm = "XXXX";
            break;
    }
}

void digitrec::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"input_V\" :  \"" << input_V.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_return\" :  \"" << ap_return.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

