// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="digitrec,hls_ip_2016_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=10.652600,HLS_SYN_LAT=1807,HLS_SYN_TPT=none,HLS_SYN_MEM=480,HLS_SYN_DSP=0,HLS_SYN_FF=595,HLS_SYN_LUT=2129}" *)

module digitrec (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input_V,
        ap_return
);

parameter    ap_ST_st1_fsm_0 = 4'b1;
parameter    ap_ST_pp0_stg0_fsm_1 = 4'b10;
parameter    ap_ST_st5_fsm_2 = 4'b100;
parameter    ap_ST_st6_fsm_3 = 4'b1000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv11_0 = 11'b00000000000;
parameter    ap_const_lv32_3 = 32'b11;
parameter    ap_const_lv6_32 = 6'b110010;
parameter    ap_const_lv11_708 = 11'b11100001000;
parameter    ap_const_lv11_1 = 11'b1;
parameter    ap_const_lv12_708 = 12'b11100001000;
parameter    ap_const_lv13_E10 = 13'b111000010000;
parameter    ap_const_lv13_1518 = 13'b1010100011000;
parameter    ap_const_lv14_1C20 = 14'b1110000100000;
parameter    ap_const_lv14_2328 = 14'b10001100101000;
parameter    ap_const_lv14_2A30 = 14'b10101000110000;
parameter    ap_const_lv13_1138 = 13'b1000100111000;
parameter    ap_const_lv12_840 = 12'b100001000000;
parameter    ap_const_lv15_3F48 = 15'b11111101001000;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [48:0] input_V;
output  [3:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
reg    ap_sig_cseq_ST_st1_fsm_0;
reg    ap_sig_19;
wire   [14:0] training_data_V_address0;
reg    training_data_V_ce0;
wire   [47:0] training_data_V_q0;
wire   [14:0] training_data_V_address1;
reg    training_data_V_ce1;
wire   [47:0] training_data_V_q1;
wire   [14:0] training_data_V_address2;
reg    training_data_V_ce2;
wire   [47:0] training_data_V_q2;
wire   [14:0] training_data_V_address3;
reg    training_data_V_ce3;
wire   [47:0] training_data_V_q3;
wire   [14:0] training_data_V_address4;
reg    training_data_V_ce4;
wire   [47:0] training_data_V_q4;
wire   [14:0] training_data_V_address5;
reg    training_data_V_ce5;
wire   [47:0] training_data_V_q5;
wire   [14:0] training_data_V_address6;
reg    training_data_V_ce6;
wire   [47:0] training_data_V_q6;
wire   [14:0] training_data_V_address7;
reg    training_data_V_ce7;
wire   [47:0] training_data_V_q7;
wire   [14:0] training_data_V_address8;
reg    training_data_V_ce8;
wire   [47:0] training_data_V_q8;
wire   [14:0] training_data_V_address9;
reg    training_data_V_ce9;
wire   [47:0] training_data_V_q9;
reg   [10:0] i4_reg_227;
wire   [0:0] exitcond2_fu_372_p2;
reg   [0:0] exitcond2_reg_636;
reg    ap_sig_cseq_ST_pp0_stg0_fsm_1;
reg    ap_sig_85;
reg    ap_reg_ppiten_pp0_it0;
reg    ap_reg_ppiten_pp0_it1;
reg    ap_reg_ppiten_pp0_it2;
reg   [0:0] ap_reg_ppstg_exitcond2_reg_636_pp0_iter1;
wire   [10:0] i_fu_378_p2;
reg   [47:0] training_data_V_load_reg_695;
reg   [47:0] training_data_V_load_1_reg_700;
reg   [47:0] training_data_V_load_2_reg_705;
reg   [47:0] training_data_V_load_3_reg_710;
reg   [47:0] training_data_V_load_4_reg_715;
reg   [47:0] training_data_V_load_5_reg_720;
reg   [47:0] training_data_V_load_6_reg_725;
reg   [47:0] training_data_V_load_7_reg_730;
reg   [47:0] training_data_V_load_8_reg_735;
reg   [47:0] training_data_V_load_9_reg_740;
reg    ap_sig_cseq_ST_st5_fsm_2;
reg    ap_sig_141;
wire   [5:0] stg_95_digitrec_update_knn_fu_238_min_distances_V_o;
wire    stg_95_digitrec_update_knn_fu_238_min_distances_V_o_ap_vld;
wire   [5:0] stg_96_digitrec_update_knn_fu_245_min_distances_V_o;
wire    stg_96_digitrec_update_knn_fu_245_min_distances_V_o_ap_vld;
wire   [5:0] stg_97_digitrec_update_knn_fu_252_min_distances_V_o;
wire    stg_97_digitrec_update_knn_fu_252_min_distances_V_o_ap_vld;
wire   [5:0] stg_98_digitrec_update_knn_fu_259_min_distances_V_o;
wire    stg_98_digitrec_update_knn_fu_259_min_distances_V_o_ap_vld;
wire   [5:0] stg_99_digitrec_update_knn_fu_266_min_distances_V_o;
wire    stg_99_digitrec_update_knn_fu_266_min_distances_V_o_ap_vld;
wire   [5:0] stg_100_digitrec_update_knn_fu_273_min_distances_V_o;
wire    stg_100_digitrec_update_knn_fu_273_min_distances_V_o_ap_vld;
wire   [5:0] stg_101_digitrec_update_knn_fu_280_min_distances_V_o;
wire    stg_101_digitrec_update_knn_fu_280_min_distances_V_o_ap_vld;
wire   [5:0] stg_102_digitrec_update_knn_fu_287_min_distances_V_o;
wire    stg_102_digitrec_update_knn_fu_287_min_distances_V_o_ap_vld;
wire   [5:0] stg_103_digitrec_update_knn_fu_294_min_distances_V_o;
wire    stg_103_digitrec_update_knn_fu_294_min_distances_V_o_ap_vld;
wire   [5:0] stg_104_digitrec_update_knn_fu_301_min_distances_V_o;
wire    stg_104_digitrec_update_knn_fu_301_min_distances_V_o_ap_vld;
wire    grp_digitrec_knn_vote_fu_308_ap_start;
wire    grp_digitrec_knn_vote_fu_308_ap_done;
wire    grp_digitrec_knn_vote_fu_308_ap_idle;
wire    grp_digitrec_knn_vote_fu_308_ap_ready;
wire   [3:0] grp_digitrec_knn_vote_fu_308_ap_return;
reg   [5:0] knn_set_V_0_0_fu_70;
reg   [5:0] knn_set_V_1_0_fu_74;
reg   [5:0] knn_set_V_2_0_fu_78;
reg   [5:0] knn_set_V_3_0_fu_82;
reg   [5:0] knn_set_V_4_0_fu_86;
reg   [5:0] knn_set_V_5_0_fu_90;
reg   [5:0] knn_set_V_6_0_fu_94;
reg   [5:0] knn_set_V_7_0_fu_98;
reg   [5:0] knn_set_V_8_0_fu_102;
reg   [5:0] knn_set_V_9_0_fu_106;
reg    ap_reg_grp_digitrec_knn_vote_fu_308_ap_start;
reg    ap_sig_cseq_ST_st6_fsm_3;
reg    ap_sig_284;
wire   [63:0] tmp_9_fu_400_p1;
wire   [63:0] tmp_9_1_fu_411_p1;
wire   [63:0] tmp_9_2_fu_422_p1;
wire   [63:0] tmp_9_3_fu_433_p1;
wire   [63:0] tmp_9_4_fu_444_p1;
wire   [63:0] tmp_9_5_fu_455_p1;
wire   [63:0] tmp_9_6_fu_466_p1;
wire   [63:0] tmp_9_7_fu_481_p1;
wire   [63:0] tmp_9_8_fu_496_p1;
wire   [63:0] tmp_9_9_fu_507_p1;
wire   [11:0] i4_cast3_cast7_fu_392_p1;
wire   [11:0] tmp_8_1_fu_405_p2;
wire   [12:0] i4_cast3_cast_fu_396_p1;
wire   [12:0] tmp_8_2_fu_416_p2;
wire   [12:0] tmp_8_3_fu_427_p2;
wire   [13:0] i4_cast3_fu_388_p1;
wire   [13:0] tmp_8_4_fu_438_p2;
wire   [13:0] tmp_8_5_fu_449_p2;
wire   [13:0] tmp_8_6_fu_460_p2;
wire   [12:0] tmp_8_7_fu_471_p2;
wire  signed [13:0] tmp_8_7_cast6_fu_477_p1;
wire   [11:0] tmp_8_8_fu_486_p2;
wire  signed [13:0] tmp_8_8_cast5_fu_492_p1;
wire   [14:0] i4_cast4_fu_384_p1;
wire   [14:0] tmp_8_9_fu_501_p2;
reg   [3:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'b1;
#0 ap_reg_ppiten_pp0_it0 = 1'b0;
#0 ap_reg_ppiten_pp0_it1 = 1'b0;
#0 ap_reg_ppiten_pp0_it2 = 1'b0;
#0 ap_reg_grp_digitrec_knn_vote_fu_308_ap_start = 1'b0;
end

digitrec_training_data_V #(
    .DataWidth( 48 ),
    .AddressRange( 18000 ),
    .AddressWidth( 15 ))
training_data_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(training_data_V_address0),
    .ce0(training_data_V_ce0),
    .q0(training_data_V_q0),
    .address1(training_data_V_address1),
    .ce1(training_data_V_ce1),
    .q1(training_data_V_q1),
    .address2(training_data_V_address2),
    .ce2(training_data_V_ce2),
    .q2(training_data_V_q2),
    .address3(training_data_V_address3),
    .ce3(training_data_V_ce3),
    .q3(training_data_V_q3),
    .address4(training_data_V_address4),
    .ce4(training_data_V_ce4),
    .q4(training_data_V_q4),
    .address5(training_data_V_address5),
    .ce5(training_data_V_ce5),
    .q5(training_data_V_q5),
    .address6(training_data_V_address6),
    .ce6(training_data_V_ce6),
    .q6(training_data_V_q6),
    .address7(training_data_V_address7),
    .ce7(training_data_V_ce7),
    .q7(training_data_V_q7),
    .address8(training_data_V_address8),
    .ce8(training_data_V_ce8),
    .q8(training_data_V_q8),
    .address9(training_data_V_address9),
    .ce9(training_data_V_ce9),
    .q9(training_data_V_q9)
);

digitrec_update_knn stg_95_digitrec_update_knn_fu_238(
    .test_inst_V(input_V),
    .train_inst_V(training_data_V_load_reg_695),
    .min_distances_V_i(knn_set_V_0_0_fu_70),
    .min_distances_V_o(stg_95_digitrec_update_knn_fu_238_min_distances_V_o),
    .min_distances_V_o_ap_vld(stg_95_digitrec_update_knn_fu_238_min_distances_V_o_ap_vld)
);

digitrec_update_knn stg_96_digitrec_update_knn_fu_245(
    .test_inst_V(input_V),
    .train_inst_V(training_data_V_load_1_reg_700),
    .min_distances_V_i(knn_set_V_1_0_fu_74),
    .min_distances_V_o(stg_96_digitrec_update_knn_fu_245_min_distances_V_o),
    .min_distances_V_o_ap_vld(stg_96_digitrec_update_knn_fu_245_min_distances_V_o_ap_vld)
);

digitrec_update_knn stg_97_digitrec_update_knn_fu_252(
    .test_inst_V(input_V),
    .train_inst_V(training_data_V_load_2_reg_705),
    .min_distances_V_i(knn_set_V_2_0_fu_78),
    .min_distances_V_o(stg_97_digitrec_update_knn_fu_252_min_distances_V_o),
    .min_distances_V_o_ap_vld(stg_97_digitrec_update_knn_fu_252_min_distances_V_o_ap_vld)
);

digitrec_update_knn stg_98_digitrec_update_knn_fu_259(
    .test_inst_V(input_V),
    .train_inst_V(training_data_V_load_3_reg_710),
    .min_distances_V_i(knn_set_V_3_0_fu_82),
    .min_distances_V_o(stg_98_digitrec_update_knn_fu_259_min_distances_V_o),
    .min_distances_V_o_ap_vld(stg_98_digitrec_update_knn_fu_259_min_distances_V_o_ap_vld)
);

digitrec_update_knn stg_99_digitrec_update_knn_fu_266(
    .test_inst_V(input_V),
    .train_inst_V(training_data_V_load_4_reg_715),
    .min_distances_V_i(knn_set_V_4_0_fu_86),
    .min_distances_V_o(stg_99_digitrec_update_knn_fu_266_min_distances_V_o),
    .min_distances_V_o_ap_vld(stg_99_digitrec_update_knn_fu_266_min_distances_V_o_ap_vld)
);

digitrec_update_knn stg_100_digitrec_update_knn_fu_273(
    .test_inst_V(input_V),
    .train_inst_V(training_data_V_load_5_reg_720),
    .min_distances_V_i(knn_set_V_5_0_fu_90),
    .min_distances_V_o(stg_100_digitrec_update_knn_fu_273_min_distances_V_o),
    .min_distances_V_o_ap_vld(stg_100_digitrec_update_knn_fu_273_min_distances_V_o_ap_vld)
);

digitrec_update_knn stg_101_digitrec_update_knn_fu_280(
    .test_inst_V(input_V),
    .train_inst_V(training_data_V_load_6_reg_725),
    .min_distances_V_i(knn_set_V_6_0_fu_94),
    .min_distances_V_o(stg_101_digitrec_update_knn_fu_280_min_distances_V_o),
    .min_distances_V_o_ap_vld(stg_101_digitrec_update_knn_fu_280_min_distances_V_o_ap_vld)
);

digitrec_update_knn stg_102_digitrec_update_knn_fu_287(
    .test_inst_V(input_V),
    .train_inst_V(training_data_V_load_7_reg_730),
    .min_distances_V_i(knn_set_V_7_0_fu_98),
    .min_distances_V_o(stg_102_digitrec_update_knn_fu_287_min_distances_V_o),
    .min_distances_V_o_ap_vld(stg_102_digitrec_update_knn_fu_287_min_distances_V_o_ap_vld)
);

digitrec_update_knn stg_103_digitrec_update_knn_fu_294(
    .test_inst_V(input_V),
    .train_inst_V(training_data_V_load_8_reg_735),
    .min_distances_V_i(knn_set_V_8_0_fu_102),
    .min_distances_V_o(stg_103_digitrec_update_knn_fu_294_min_distances_V_o),
    .min_distances_V_o_ap_vld(stg_103_digitrec_update_knn_fu_294_min_distances_V_o_ap_vld)
);

digitrec_update_knn stg_104_digitrec_update_knn_fu_301(
    .test_inst_V(input_V),
    .train_inst_V(training_data_V_load_9_reg_740),
    .min_distances_V_i(knn_set_V_9_0_fu_106),
    .min_distances_V_o(stg_104_digitrec_update_knn_fu_301_min_distances_V_o),
    .min_distances_V_o_ap_vld(stg_104_digitrec_update_knn_fu_301_min_distances_V_o_ap_vld)
);

digitrec_knn_vote grp_digitrec_knn_vote_fu_308(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_digitrec_knn_vote_fu_308_ap_start),
    .ap_done(grp_digitrec_knn_vote_fu_308_ap_done),
    .ap_idle(grp_digitrec_knn_vote_fu_308_ap_idle),
    .ap_ready(grp_digitrec_knn_vote_fu_308_ap_ready),
    .p_read(knn_set_V_0_0_fu_70),
    .p_read1(knn_set_V_1_0_fu_74),
    .p_read2(knn_set_V_2_0_fu_78),
    .p_read3(knn_set_V_3_0_fu_82),
    .p_read4(knn_set_V_4_0_fu_86),
    .p_read5(knn_set_V_5_0_fu_90),
    .p_read6(knn_set_V_6_0_fu_94),
    .p_read7(knn_set_V_7_0_fu_98),
    .p_read8(knn_set_V_8_0_fu_102),
    .p_read9(knn_set_V_9_0_fu_106),
    .ap_return(grp_digitrec_knn_vote_fu_308_ap_return)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_grp_digitrec_knn_vote_fu_308_ap_start <= 1'b0;
    end else begin
        if ((1'b1 == ap_sig_cseq_ST_st5_fsm_2)) begin
            ap_reg_grp_digitrec_knn_vote_fu_308_ap_start <= 1'b1;
        end else if ((1'b1 == grp_digitrec_knn_vote_fu_308_ap_ready)) begin
            ap_reg_grp_digitrec_knn_vote_fu_308_ap_start <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & ~(exitcond2_fu_372_p2 == 1'b0))) begin
            ap_reg_ppiten_pp0_it0 <= 1'b0;
        end else if (((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == 1'b0))) begin
            ap_reg_ppiten_pp0_it0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (exitcond2_fu_372_p2 == 1'b0))) begin
            ap_reg_ppiten_pp0_it1 <= 1'b1;
        end else if ((((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == 1'b0)) | ((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & ~(exitcond2_fu_372_p2 == 1'b0)))) begin
            ap_reg_ppiten_pp0_it1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it2 <= 1'b0;
    end else begin
        ap_reg_ppiten_pp0_it2 <= ap_reg_ppiten_pp0_it1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == 1'b0))) begin
        i4_reg_227 <= ap_const_lv11_0;
    end else if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (1'b1 == ap_reg_ppiten_pp0_it0) & (exitcond2_fu_372_p2 == 1'b0))) begin
        i4_reg_227 <= i_fu_378_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == 1'b0))) begin
        knn_set_V_0_0_fu_70 <= ap_const_lv6_32;
    end else if (((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond2_reg_636_pp0_iter1 == 1'b0) & (1'b1 == stg_95_digitrec_update_knn_fu_238_min_distances_V_o_ap_vld))) begin
        knn_set_V_0_0_fu_70 <= stg_95_digitrec_update_knn_fu_238_min_distances_V_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == 1'b0))) begin
        knn_set_V_1_0_fu_74 <= ap_const_lv6_32;
    end else if (((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond2_reg_636_pp0_iter1 == 1'b0) & (1'b1 == stg_96_digitrec_update_knn_fu_245_min_distances_V_o_ap_vld))) begin
        knn_set_V_1_0_fu_74 <= stg_96_digitrec_update_knn_fu_245_min_distances_V_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == 1'b0))) begin
        knn_set_V_2_0_fu_78 <= ap_const_lv6_32;
    end else if (((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond2_reg_636_pp0_iter1 == 1'b0) & (1'b1 == stg_97_digitrec_update_knn_fu_252_min_distances_V_o_ap_vld))) begin
        knn_set_V_2_0_fu_78 <= stg_97_digitrec_update_knn_fu_252_min_distances_V_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == 1'b0))) begin
        knn_set_V_3_0_fu_82 <= ap_const_lv6_32;
    end else if (((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond2_reg_636_pp0_iter1 == 1'b0) & (1'b1 == stg_98_digitrec_update_knn_fu_259_min_distances_V_o_ap_vld))) begin
        knn_set_V_3_0_fu_82 <= stg_98_digitrec_update_knn_fu_259_min_distances_V_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == 1'b0))) begin
        knn_set_V_4_0_fu_86 <= ap_const_lv6_32;
    end else if (((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond2_reg_636_pp0_iter1 == 1'b0) & (1'b1 == stg_99_digitrec_update_knn_fu_266_min_distances_V_o_ap_vld))) begin
        knn_set_V_4_0_fu_86 <= stg_99_digitrec_update_knn_fu_266_min_distances_V_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == 1'b0))) begin
        knn_set_V_5_0_fu_90 <= ap_const_lv6_32;
    end else if (((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond2_reg_636_pp0_iter1 == 1'b0) & (1'b1 == stg_100_digitrec_update_knn_fu_273_min_distances_V_o_ap_vld))) begin
        knn_set_V_5_0_fu_90 <= stg_100_digitrec_update_knn_fu_273_min_distances_V_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == 1'b0))) begin
        knn_set_V_6_0_fu_94 <= ap_const_lv6_32;
    end else if (((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond2_reg_636_pp0_iter1 == 1'b0) & (1'b1 == stg_101_digitrec_update_knn_fu_280_min_distances_V_o_ap_vld))) begin
        knn_set_V_6_0_fu_94 <= stg_101_digitrec_update_knn_fu_280_min_distances_V_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == 1'b0))) begin
        knn_set_V_7_0_fu_98 <= ap_const_lv6_32;
    end else if (((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond2_reg_636_pp0_iter1 == 1'b0) & (1'b1 == stg_102_digitrec_update_knn_fu_287_min_distances_V_o_ap_vld))) begin
        knn_set_V_7_0_fu_98 <= stg_102_digitrec_update_knn_fu_287_min_distances_V_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == 1'b0))) begin
        knn_set_V_8_0_fu_102 <= ap_const_lv6_32;
    end else if (((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond2_reg_636_pp0_iter1 == 1'b0) & (1'b1 == stg_103_digitrec_update_knn_fu_294_min_distances_V_o_ap_vld))) begin
        knn_set_V_8_0_fu_102 <= stg_103_digitrec_update_knn_fu_294_min_distances_V_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == 1'b0))) begin
        knn_set_V_9_0_fu_106 <= ap_const_lv6_32;
    end else if (((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond2_reg_636_pp0_iter1 == 1'b0) & (1'b1 == stg_104_digitrec_update_knn_fu_301_min_distances_V_o_ap_vld))) begin
        knn_set_V_9_0_fu_106 <= stg_104_digitrec_update_knn_fu_301_min_distances_V_o;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1)) begin
        ap_reg_ppstg_exitcond2_reg_636_pp0_iter1 <= exitcond2_reg_636;
        exitcond2_reg_636 <= exitcond2_fu_372_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (1'b1 == ap_reg_ppiten_pp0_it1) & (exitcond2_reg_636 == 1'b0))) begin
        training_data_V_load_1_reg_700 <= training_data_V_q1;
        training_data_V_load_2_reg_705 <= training_data_V_q2;
        training_data_V_load_3_reg_710 <= training_data_V_q3;
        training_data_V_load_4_reg_715 <= training_data_V_q4;
        training_data_V_load_5_reg_720 <= training_data_V_q5;
        training_data_V_load_6_reg_725 <= training_data_V_q6;
        training_data_V_load_7_reg_730 <= training_data_V_q7;
        training_data_V_load_8_reg_735 <= training_data_V_q8;
        training_data_V_load_9_reg_740 <= training_data_V_q9;
        training_data_V_load_reg_695 <= training_data_V_q0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st6_fsm_3) & ~(1'b0 == grp_digitrec_knn_vote_fu_308_ap_done))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_start) & (1'b1 == ap_sig_cseq_ST_st1_fsm_0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st6_fsm_3) & ~(1'b0 == grp_digitrec_knn_vote_fu_308_ap_done))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_85) begin
        ap_sig_cseq_ST_pp0_stg0_fsm_1 = 1'b1;
    end else begin
        ap_sig_cseq_ST_pp0_stg0_fsm_1 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_19) begin
        ap_sig_cseq_ST_st1_fsm_0 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st1_fsm_0 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_141) begin
        ap_sig_cseq_ST_st5_fsm_2 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st5_fsm_2 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_284) begin
        ap_sig_cseq_ST_st6_fsm_3 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st6_fsm_3 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (1'b1 == ap_reg_ppiten_pp0_it0))) begin
        training_data_V_ce0 = 1'b1;
    end else begin
        training_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (1'b1 == ap_reg_ppiten_pp0_it0))) begin
        training_data_V_ce1 = 1'b1;
    end else begin
        training_data_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (1'b1 == ap_reg_ppiten_pp0_it0))) begin
        training_data_V_ce2 = 1'b1;
    end else begin
        training_data_V_ce2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (1'b1 == ap_reg_ppiten_pp0_it0))) begin
        training_data_V_ce3 = 1'b1;
    end else begin
        training_data_V_ce3 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (1'b1 == ap_reg_ppiten_pp0_it0))) begin
        training_data_V_ce4 = 1'b1;
    end else begin
        training_data_V_ce4 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (1'b1 == ap_reg_ppiten_pp0_it0))) begin
        training_data_V_ce5 = 1'b1;
    end else begin
        training_data_V_ce5 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (1'b1 == ap_reg_ppiten_pp0_it0))) begin
        training_data_V_ce6 = 1'b1;
    end else begin
        training_data_V_ce6 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (1'b1 == ap_reg_ppiten_pp0_it0))) begin
        training_data_V_ce7 = 1'b1;
    end else begin
        training_data_V_ce7 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (1'b1 == ap_reg_ppiten_pp0_it0))) begin
        training_data_V_ce8 = 1'b1;
    end else begin
        training_data_V_ce8 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (1'b1 == ap_reg_ppiten_pp0_it0))) begin
        training_data_V_ce9 = 1'b1;
    end else begin
        training_data_V_ce9 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : begin
            if (~(ap_start == 1'b0)) begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        end
        ap_ST_pp0_stg0_fsm_1 : begin
            if ((~((1'b1 == ap_reg_ppiten_pp0_it2) & ~(1'b1 == ap_reg_ppiten_pp0_it1)) & ~((1'b1 == ap_reg_ppiten_pp0_it0) & ~(exitcond2_fu_372_p2 == 1'b0) & ~(1'b1 == ap_reg_ppiten_pp0_it1)))) begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_1;
            end else if (((1'b1 == ap_reg_ppiten_pp0_it0) & ~(exitcond2_fu_372_p2 == 1'b0) & ~(1'b1 == ap_reg_ppiten_pp0_it1))) begin
                ap_NS_fsm = ap_ST_st5_fsm_2;
            end else begin
                ap_NS_fsm = ap_ST_st5_fsm_2;
            end
        end
        ap_ST_st5_fsm_2 : begin
            ap_NS_fsm = ap_ST_st6_fsm_3;
        end
        ap_ST_st6_fsm_3 : begin
            if (~(1'b0 == grp_digitrec_knn_vote_fu_308_ap_done)) begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end else begin
                ap_NS_fsm = ap_ST_st6_fsm_3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_return = grp_digitrec_knn_vote_fu_308_ap_return;

always @ (*) begin
    ap_sig_141 = (1'b1 == ap_CS_fsm[ap_const_lv32_2]);
end

always @ (*) begin
    ap_sig_19 = (ap_CS_fsm[ap_const_lv32_0] == 1'b1);
end

always @ (*) begin
    ap_sig_284 = (1'b1 == ap_CS_fsm[ap_const_lv32_3]);
end

always @ (*) begin
    ap_sig_85 = (1'b1 == ap_CS_fsm[ap_const_lv32_1]);
end

assign exitcond2_fu_372_p2 = ((i4_reg_227 == ap_const_lv11_708) ? 1'b1 : 1'b0);

assign grp_digitrec_knn_vote_fu_308_ap_start = ap_reg_grp_digitrec_knn_vote_fu_308_ap_start;

assign i4_cast3_cast7_fu_392_p1 = i4_reg_227;

assign i4_cast3_cast_fu_396_p1 = i4_reg_227;

assign i4_cast3_fu_388_p1 = i4_reg_227;

assign i4_cast4_fu_384_p1 = i4_reg_227;

assign i_fu_378_p2 = (i4_reg_227 + ap_const_lv11_1);

assign tmp_8_1_fu_405_p2 = (i4_cast3_cast7_fu_392_p1 + ap_const_lv12_708);

assign tmp_8_2_fu_416_p2 = (i4_cast3_cast_fu_396_p1 + ap_const_lv13_E10);

assign tmp_8_3_fu_427_p2 = ($signed(i4_cast3_cast_fu_396_p1) + $signed(ap_const_lv13_1518));

assign tmp_8_4_fu_438_p2 = (i4_cast3_fu_388_p1 + ap_const_lv14_1C20);

assign tmp_8_5_fu_449_p2 = ($signed(i4_cast3_fu_388_p1) + $signed(ap_const_lv14_2328));

assign tmp_8_6_fu_460_p2 = ($signed(i4_cast3_fu_388_p1) + $signed(ap_const_lv14_2A30));

assign tmp_8_7_cast6_fu_477_p1 = $signed(tmp_8_7_fu_471_p2);

assign tmp_8_7_fu_471_p2 = ($signed(i4_cast3_cast_fu_396_p1) + $signed(ap_const_lv13_1138));

assign tmp_8_8_cast5_fu_492_p1 = $signed(tmp_8_8_fu_486_p2);

assign tmp_8_8_fu_486_p2 = ($signed(i4_cast3_cast7_fu_392_p1) + $signed(ap_const_lv12_840));

assign tmp_8_9_fu_501_p2 = (i4_cast4_fu_384_p1 + ap_const_lv15_3F48);

assign tmp_9_1_fu_411_p1 = tmp_8_1_fu_405_p2;

assign tmp_9_2_fu_422_p1 = tmp_8_2_fu_416_p2;

assign tmp_9_3_fu_433_p1 = tmp_8_3_fu_427_p2;

assign tmp_9_4_fu_444_p1 = tmp_8_4_fu_438_p2;

assign tmp_9_5_fu_455_p1 = tmp_8_5_fu_449_p2;

assign tmp_9_6_fu_466_p1 = tmp_8_6_fu_460_p2;

assign tmp_9_7_fu_481_p1 = $unsigned(tmp_8_7_cast6_fu_477_p1);

assign tmp_9_8_fu_496_p1 = $unsigned(tmp_8_8_cast5_fu_492_p1);

assign tmp_9_9_fu_507_p1 = tmp_8_9_fu_501_p2;

assign tmp_9_fu_400_p1 = i4_reg_227;

assign training_data_V_address0 = tmp_9_fu_400_p1;

assign training_data_V_address1 = tmp_9_1_fu_411_p1;

assign training_data_V_address2 = tmp_9_2_fu_422_p1;

assign training_data_V_address3 = tmp_9_3_fu_433_p1;

assign training_data_V_address4 = tmp_9_4_fu_444_p1;

assign training_data_V_address5 = tmp_9_5_fu_455_p1;

assign training_data_V_address6 = tmp_9_6_fu_466_p1;

assign training_data_V_address7 = tmp_9_7_fu_481_p1;

assign training_data_V_address8 = tmp_9_8_fu_496_p1;

assign training_data_V_address9 = tmp_9_9_fu_507_p1;

endmodule //digitrec
