// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "digitrec_knn_vote.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic digitrec_knn_vote::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic digitrec_knn_vote::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<5> digitrec_knn_vote::ap_ST_st1_fsm_0 = "1";
const sc_lv<5> digitrec_knn_vote::ap_ST_st2_fsm_1 = "10";
const sc_lv<5> digitrec_knn_vote::ap_ST_st3_fsm_2 = "100";
const sc_lv<5> digitrec_knn_vote::ap_ST_st4_fsm_3 = "1000";
const sc_lv<5> digitrec_knn_vote::ap_ST_st5_fsm_4 = "10000";
const sc_lv<32> digitrec_knn_vote::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> digitrec_knn_vote::ap_const_lv1_1 = "1";
const sc_lv<32> digitrec_knn_vote::ap_const_lv32_1 = "1";
const sc_lv<32> digitrec_knn_vote::ap_const_lv32_2 = "10";
const sc_lv<32> digitrec_knn_vote::ap_const_lv32_3 = "11";
const sc_lv<32> digitrec_knn_vote::ap_const_lv32_4 = "100";
const sc_lv<2> digitrec_knn_vote::ap_const_lv2_3 = "11";
const sc_lv<2> digitrec_knn_vote::ap_const_lv2_2 = "10";
const sc_lv<3> digitrec_knn_vote::ap_const_lv3_5 = "101";
const sc_lv<3> digitrec_knn_vote::ap_const_lv3_4 = "100";
const sc_lv<3> digitrec_knn_vote::ap_const_lv3_7 = "111";
const sc_lv<3> digitrec_knn_vote::ap_const_lv3_6 = "110";
const sc_lv<4> digitrec_knn_vote::ap_const_lv4_9 = "1001";
const sc_lv<4> digitrec_knn_vote::ap_const_lv4_8 = "1000";
const sc_lv<4> digitrec_knn_vote::ap_const_lv4_0 = "0000";

digitrec_knn_vote::digitrec_knn_vote(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_agg_result_V_0_agg_result_V_02_1_fu_758_p1);
    sensitive << ( agg_result_V_0_agg_result_V_02_3_fu_750_p3 );

    SC_METHOD(thread_agg_result_V_0_agg_result_V_02_2_fu_739_p3);
    sensitive << ( tmp_6_3_reg_1194 );

    SC_METHOD(thread_agg_result_V_0_agg_result_V_02_3_fu_750_p3);
    sensitive << ( tmp_s_fu_746_p2 );
    sensitive << ( agg_result_V_0_agg_result_V_02_2_fu_739_p3 );
    sensitive << ( agg_result_V_0_agg_result_V_s_fu_736_p1 );

    SC_METHOD(thread_agg_result_V_0_agg_result_V_02_4_fu_834_p3);
    sensitive << ( tmp_6_5_fu_828_p2 );

    SC_METHOD(thread_agg_result_V_0_agg_result_V_02_5_fu_848_p3);
    sensitive << ( tmp_6_fu_842_p2 );
    sensitive << ( agg_result_V_0_agg_result_V_02_4_fu_834_p3 );
    sensitive << ( agg_result_V_0_agg_result_V_02_1_fu_758_p1 );

    SC_METHOD(thread_agg_result_V_0_agg_result_V_02_6_fu_1074_p1);
    sensitive << ( agg_result_V_0_agg_result_V_02_7_fu_1067_p3 );

    SC_METHOD(thread_agg_result_V_0_agg_result_V_02_7_fu_1067_p3);
    sensitive << ( agg_result_V_0_agg_result_V_02_5_reg_1212 );
    sensitive << ( tmp_7_fu_1063_p2 );
    sensitive << ( agg_result_V_0_agg_result_V_02_fu_1056_p3 );

    SC_METHOD(thread_agg_result_V_0_agg_result_V_02_8_fu_1150_p3);
    sensitive << ( tmp_6_9_fu_1144_p2 );

    SC_METHOD(thread_agg_result_V_0_agg_result_V_02_9_fu_1164_p3);
    sensitive << ( tmp_9_fu_1158_p2 );
    sensitive << ( agg_result_V_0_agg_result_V_02_8_fu_1150_p3 );
    sensitive << ( agg_result_V_0_agg_result_V_02_6_fu_1074_p1 );

    SC_METHOD(thread_agg_result_V_0_agg_result_V_02_fu_1056_p3);
    sensitive << ( tmp_6_7_reg_1234 );

    SC_METHOD(thread_agg_result_V_0_agg_result_V_s_fu_736_p1);
    sensitive << ( tmp_6_1_reg_1172 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );

    SC_METHOD(thread_ap_return);
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( agg_result_V_0_agg_result_V_02_9_fu_1164_p3 );
    sensitive << ( ap_return_preg );

    SC_METHOD(thread_ap_sig_109);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_122);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_181);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_22);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_94);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_cseq_ST_st1_fsm_0);
    sensitive << ( ap_sig_22 );

    SC_METHOD(thread_ap_sig_cseq_ST_st2_fsm_1);
    sensitive << ( ap_sig_94 );

    SC_METHOD(thread_ap_sig_cseq_ST_st3_fsm_2);
    sensitive << ( ap_sig_109 );

    SC_METHOD(thread_ap_sig_cseq_ST_st4_fsm_3);
    sensitive << ( ap_sig_122 );

    SC_METHOD(thread_ap_sig_cseq_ST_st5_fsm_4);
    sensitive << ( ap_sig_181 );

    SC_METHOD(thread_min_2_min_1_fu_536_p3);
    sensitive << ( tmp_6_1_fu_530_p2 );
    sensitive << ( sum_1_4_fu_524_p2 );
    sensitive << ( sum_0_4_fu_468_p2 );

    SC_METHOD(thread_min_2_min_2_fu_604_p3);
    sensitive << ( min_2_min_1_reg_1177 );
    sensitive << ( sum_2_4_reg_1183 );
    sensitive << ( tmp_6_2_fu_600_p2 );

    SC_METHOD(thread_min_2_min_3_fu_672_p3);
    sensitive << ( tmp_6_3_fu_666_p2 );
    sensitive << ( sum_3_4_fu_660_p2 );
    sensitive << ( min_2_min_2_fu_604_p3 );

    SC_METHOD(thread_min_2_min_4_fu_766_p3);
    sensitive << ( min_2_min_3_reg_1200 );
    sensitive << ( sum_4_4_reg_1206 );
    sensitive << ( tmp_6_4_fu_762_p2 );

    SC_METHOD(thread_min_2_min_5_fu_856_p3);
    sensitive << ( sum_5_4_fu_822_p2 );
    sensitive << ( min_2_min_4_fu_766_p3 );
    sensitive << ( tmp_6_5_fu_828_p2 );

    SC_METHOD(thread_min_2_min_6_fu_924_p3);
    sensitive << ( min_2_min_5_reg_1217 );
    sensitive << ( sum_6_4_reg_1223 );
    sensitive << ( tmp_6_6_fu_920_p2 );

    SC_METHOD(thread_min_2_min_7_fu_992_p3);
    sensitive << ( tmp_6_7_fu_986_p2 );
    sensitive << ( sum_7_4_fu_980_p2 );
    sensitive << ( min_2_min_6_fu_924_p3 );

    SC_METHOD(thread_min_2_min_8_fu_1082_p3);
    sensitive << ( min_2_min_7_reg_1240 );
    sensitive << ( sum_8_4_reg_1246 );
    sensitive << ( tmp_6_8_fu_1078_p2 );

    SC_METHOD(thread_sum_0_4_fu_468_p2);
    sensitive << ( tmp2_cast_fu_444_p1 );
    sensitive << ( tmp3_cast_fu_464_p1 );

    SC_METHOD(thread_sum_1_4_fu_524_p2);
    sensitive << ( tmp7_cast_fu_500_p1 );
    sensitive << ( tmp8_cast_fu_520_p1 );

    SC_METHOD(thread_sum_2_4_fu_594_p2);
    sensitive << ( tmp12_cast_fu_570_p1 );
    sensitive << ( tmp13_cast_fu_590_p1 );

    SC_METHOD(thread_sum_3_4_fu_660_p2);
    sensitive << ( tmp17_cast_fu_636_p1 );
    sensitive << ( tmp18_cast_fu_656_p1 );

    SC_METHOD(thread_sum_4_4_fu_730_p2);
    sensitive << ( tmp22_cast_fu_706_p1 );
    sensitive << ( tmp23_cast_fu_726_p1 );

    SC_METHOD(thread_sum_5_4_fu_822_p2);
    sensitive << ( tmp27_cast_fu_798_p1 );
    sensitive << ( tmp28_cast_fu_818_p1 );

    SC_METHOD(thread_sum_6_4_fu_914_p2);
    sensitive << ( tmp32_cast_fu_890_p1 );
    sensitive << ( tmp33_cast_fu_910_p1 );

    SC_METHOD(thread_sum_7_4_fu_980_p2);
    sensitive << ( tmp37_cast_fu_956_p1 );
    sensitive << ( tmp38_cast_fu_976_p1 );

    SC_METHOD(thread_sum_8_4_fu_1050_p2);
    sensitive << ( tmp42_cast_fu_1026_p1 );
    sensitive << ( tmp43_cast_fu_1046_p1 );

    SC_METHOD(thread_sum_9_4_fu_1138_p2);
    sensitive << ( tmp45_cast_fu_1114_p1 );
    sensitive << ( tmp46_cast_fu_1134_p1 );

    SC_METHOD(thread_tmp10_fu_640_p2);
    sensitive << ( tmp_8_3_4_cast_fu_626_p1 );
    sensitive << ( tmp_8_3_cast_fu_610_p1 );

    SC_METHOD(thread_tmp11_fu_650_p2);
    sensitive << ( tmp_8_3_1_cast_fu_614_p1 );
    sensitive << ( tmp19_cast_fu_646_p1 );

    SC_METHOD(thread_tmp12_cast_fu_570_p1);
    sensitive << ( tmp_fu_564_p2 );

    SC_METHOD(thread_tmp12_fu_700_p2);
    sensitive << ( tmp_8_4_3_cast_fu_692_p1 );
    sensitive << ( tmp_8_4_2_cast_fu_688_p1 );

    SC_METHOD(thread_tmp13_cast_fu_590_p1);
    sensitive << ( tmp5_fu_584_p2 );

    SC_METHOD(thread_tmp13_fu_710_p2);
    sensitive << ( tmp_8_4_4_cast_fu_696_p1 );
    sensitive << ( tmp_8_4_cast_fu_680_p1 );

    SC_METHOD(thread_tmp14_cast_fu_580_p1);
    sensitive << ( tmp1_fu_574_p2 );

    SC_METHOD(thread_tmp14_fu_720_p2);
    sensitive << ( tmp_8_4_1_cast_fu_684_p1 );
    sensitive << ( tmp24_cast_fu_716_p1 );

    SC_METHOD(thread_tmp15_fu_792_p2);
    sensitive << ( tmp_8_5_3_cast_fu_784_p1 );
    sensitive << ( tmp_8_5_2_cast_fu_780_p1 );

    SC_METHOD(thread_tmp16_fu_802_p2);
    sensitive << ( tmp_8_5_4_cast_fu_788_p1 );
    sensitive << ( tmp_8_5_cast_fu_772_p1 );

    SC_METHOD(thread_tmp17_cast_fu_636_p1);
    sensitive << ( tmp6_fu_630_p2 );

    SC_METHOD(thread_tmp17_fu_812_p2);
    sensitive << ( tmp_8_5_1_cast_fu_776_p1 );
    sensitive << ( tmp29_cast_fu_808_p1 );

    SC_METHOD(thread_tmp18_cast_fu_656_p1);
    sensitive << ( tmp11_fu_650_p2 );

    SC_METHOD(thread_tmp18_fu_884_p2);
    sensitive << ( tmp_8_6_3_cast_fu_876_p1 );
    sensitive << ( tmp_8_6_2_cast_fu_872_p1 );

    SC_METHOD(thread_tmp19_cast_fu_646_p1);
    sensitive << ( tmp10_fu_640_p2 );

    SC_METHOD(thread_tmp19_fu_894_p2);
    sensitive << ( tmp_8_6_4_cast_fu_880_p1 );
    sensitive << ( tmp_8_6_cast_fu_864_p1 );

    SC_METHOD(thread_tmp1_fu_574_p2);
    sensitive << ( tmp_8_2_4_cast_fu_560_p1 );
    sensitive << ( tmp_8_2_cast_fu_544_p1 );

    SC_METHOD(thread_tmp20_fu_904_p2);
    sensitive << ( tmp_8_6_1_cast_fu_868_p1 );
    sensitive << ( tmp34_cast_fu_900_p1 );

    SC_METHOD(thread_tmp21_fu_950_p2);
    sensitive << ( tmp_8_7_3_cast_fu_942_p1 );
    sensitive << ( tmp_8_7_2_cast_fu_938_p1 );

    SC_METHOD(thread_tmp22_cast_fu_706_p1);
    sensitive << ( tmp12_fu_700_p2 );

    SC_METHOD(thread_tmp22_fu_960_p2);
    sensitive << ( tmp_8_7_4_cast_fu_946_p1 );
    sensitive << ( tmp_8_7_cast_fu_930_p1 );

    SC_METHOD(thread_tmp23_cast_fu_726_p1);
    sensitive << ( tmp14_fu_720_p2 );

    SC_METHOD(thread_tmp23_fu_970_p2);
    sensitive << ( tmp_8_7_1_cast_fu_934_p1 );
    sensitive << ( tmp39_cast_fu_966_p1 );

    SC_METHOD(thread_tmp24_cast_fu_716_p1);
    sensitive << ( tmp13_fu_710_p2 );

    SC_METHOD(thread_tmp24_fu_1020_p2);
    sensitive << ( tmp_8_8_3_cast_fu_1012_p1 );
    sensitive << ( tmp_8_8_2_cast_fu_1008_p1 );

    SC_METHOD(thread_tmp25_fu_1030_p2);
    sensitive << ( tmp_8_8_4_cast_fu_1016_p1 );
    sensitive << ( tmp_8_8_cast_fu_1000_p1 );

    SC_METHOD(thread_tmp26_fu_1040_p2);
    sensitive << ( tmp_8_8_1_cast_fu_1004_p1 );
    sensitive << ( tmp44_cast_fu_1036_p1 );

    SC_METHOD(thread_tmp27_cast_fu_798_p1);
    sensitive << ( tmp15_fu_792_p2 );

    SC_METHOD(thread_tmp27_fu_1108_p2);
    sensitive << ( tmp_8_9_1_cast_fu_1092_p1 );
    sensitive << ( tmp_8_9_cast_fu_1088_p1 );

    SC_METHOD(thread_tmp28_cast_fu_818_p1);
    sensitive << ( tmp17_fu_812_p2 );

    SC_METHOD(thread_tmp28_fu_1118_p2);
    sensitive << ( tmp_8_9_4_cast_fu_1104_p1 );
    sensitive << ( tmp_8_9_3_cast_fu_1100_p1 );

    SC_METHOD(thread_tmp29_cast_fu_808_p1);
    sensitive << ( tmp16_fu_802_p2 );

    SC_METHOD(thread_tmp29_fu_1128_p2);
    sensitive << ( tmp_8_9_2_cast_fu_1096_p1 );
    sensitive << ( tmp47_cast_fu_1124_p1 );

    SC_METHOD(thread_tmp2_cast_fu_444_p1);
    sensitive << ( tmp2_fu_438_p2 );

    SC_METHOD(thread_tmp2_fu_438_p2);
    sensitive << ( tmp_8_0_3_cast_fu_430_p1 );
    sensitive << ( tmp_8_0_2_cast_fu_426_p1 );

    SC_METHOD(thread_tmp32_cast_fu_890_p1);
    sensitive << ( tmp18_fu_884_p2 );

    SC_METHOD(thread_tmp33_cast_fu_910_p1);
    sensitive << ( tmp20_fu_904_p2 );

    SC_METHOD(thread_tmp34_cast_fu_900_p1);
    sensitive << ( tmp19_fu_894_p2 );

    SC_METHOD(thread_tmp37_cast_fu_956_p1);
    sensitive << ( tmp21_fu_950_p2 );

    SC_METHOD(thread_tmp38_cast_fu_976_p1);
    sensitive << ( tmp23_fu_970_p2 );

    SC_METHOD(thread_tmp39_cast_fu_966_p1);
    sensitive << ( tmp22_fu_960_p2 );

    SC_METHOD(thread_tmp3_cast_fu_464_p1);
    sensitive << ( tmp3_fu_458_p2 );

    SC_METHOD(thread_tmp3_fu_458_p2);
    sensitive << ( tmp_8_0_1_cast_fu_422_p1 );
    sensitive << ( tmp4_cast_fu_454_p1 );

    SC_METHOD(thread_tmp42_cast_fu_1026_p1);
    sensitive << ( tmp24_fu_1020_p2 );

    SC_METHOD(thread_tmp43_cast_fu_1046_p1);
    sensitive << ( tmp26_fu_1040_p2 );

    SC_METHOD(thread_tmp44_cast_fu_1036_p1);
    sensitive << ( tmp25_fu_1030_p2 );

    SC_METHOD(thread_tmp45_cast_fu_1114_p1);
    sensitive << ( tmp27_fu_1108_p2 );

    SC_METHOD(thread_tmp46_cast_fu_1134_p1);
    sensitive << ( tmp29_fu_1128_p2 );

    SC_METHOD(thread_tmp47_cast_fu_1124_p1);
    sensitive << ( tmp28_fu_1118_p2 );

    SC_METHOD(thread_tmp4_cast_fu_454_p1);
    sensitive << ( tmp4_fu_448_p2 );

    SC_METHOD(thread_tmp4_fu_448_p2);
    sensitive << ( tmp_8_0_4_cast_fu_434_p1 );
    sensitive << ( tmp_8_cast_fu_418_p1 );

    SC_METHOD(thread_tmp5_fu_584_p2);
    sensitive << ( tmp_8_2_1_cast_fu_548_p1 );
    sensitive << ( tmp14_cast_fu_580_p1 );

    SC_METHOD(thread_tmp6_fu_630_p2);
    sensitive << ( tmp_8_3_3_cast_fu_622_p1 );
    sensitive << ( tmp_8_3_2_cast_fu_618_p1 );

    SC_METHOD(thread_tmp7_cast_fu_500_p1);
    sensitive << ( tmp7_fu_494_p2 );

    SC_METHOD(thread_tmp7_fu_494_p2);
    sensitive << ( tmp_8_1_3_cast_fu_486_p1 );
    sensitive << ( tmp_8_1_2_cast_fu_482_p1 );

    SC_METHOD(thread_tmp8_cast_fu_520_p1);
    sensitive << ( tmp8_fu_514_p2 );

    SC_METHOD(thread_tmp8_fu_514_p2);
    sensitive << ( tmp_8_1_1_cast_fu_478_p1 );
    sensitive << ( tmp9_cast_fu_510_p1 );

    SC_METHOD(thread_tmp9_cast_fu_510_p1);
    sensitive << ( tmp9_fu_504_p2 );

    SC_METHOD(thread_tmp9_fu_504_p2);
    sensitive << ( tmp_8_1_4_cast_fu_490_p1 );
    sensitive << ( tmp_8_1_cast_fu_474_p1 );

    SC_METHOD(thread_tmp_6_1_fu_530_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( sum_1_4_fu_524_p2 );
    sensitive << ( sum_0_4_fu_468_p2 );

    SC_METHOD(thread_tmp_6_2_fu_600_p2);
    sensitive << ( min_2_min_1_reg_1177 );
    sensitive << ( sum_2_4_reg_1183 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_tmp_6_3_fu_666_p2);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( sum_3_4_fu_660_p2 );
    sensitive << ( min_2_min_2_fu_604_p3 );

    SC_METHOD(thread_tmp_6_4_fu_762_p2);
    sensitive << ( min_2_min_3_reg_1200 );
    sensitive << ( sum_4_4_reg_1206 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );

    SC_METHOD(thread_tmp_6_5_fu_828_p2);
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( sum_5_4_fu_822_p2 );
    sensitive << ( min_2_min_4_fu_766_p3 );

    SC_METHOD(thread_tmp_6_6_fu_920_p2);
    sensitive << ( min_2_min_5_reg_1217 );
    sensitive << ( sum_6_4_reg_1223 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );

    SC_METHOD(thread_tmp_6_7_fu_986_p2);
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( sum_7_4_fu_980_p2 );
    sensitive << ( min_2_min_6_fu_924_p3 );

    SC_METHOD(thread_tmp_6_8_fu_1078_p2);
    sensitive << ( min_2_min_7_reg_1240 );
    sensitive << ( sum_8_4_reg_1246 );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );

    SC_METHOD(thread_tmp_6_9_fu_1144_p2);
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( sum_9_4_fu_1138_p2 );
    sensitive << ( min_2_min_8_fu_1082_p3 );

    SC_METHOD(thread_tmp_6_fu_842_p2);
    sensitive << ( tmp_6_4_fu_762_p2 );
    sensitive << ( tmp_6_5_fu_828_p2 );

    SC_METHOD(thread_tmp_7_fu_1063_p2);
    sensitive << ( tmp_6_6_reg_1229 );
    sensitive << ( tmp_6_7_reg_1234 );

    SC_METHOD(thread_tmp_8_0_1_cast_fu_422_p1);
    sensitive << ( knn_set_0_1_V_read );

    SC_METHOD(thread_tmp_8_0_2_cast_fu_426_p1);
    sensitive << ( knn_set_0_2_V_read );

    SC_METHOD(thread_tmp_8_0_3_cast_fu_430_p1);
    sensitive << ( knn_set_0_3_V_read );

    SC_METHOD(thread_tmp_8_0_4_cast_fu_434_p1);
    sensitive << ( knn_set_0_4_V_read );

    SC_METHOD(thread_tmp_8_1_1_cast_fu_478_p1);
    sensitive << ( knn_set_1_1_V_read );

    SC_METHOD(thread_tmp_8_1_2_cast_fu_482_p1);
    sensitive << ( knn_set_1_2_V_read );

    SC_METHOD(thread_tmp_8_1_3_cast_fu_486_p1);
    sensitive << ( knn_set_1_3_V_read );

    SC_METHOD(thread_tmp_8_1_4_cast_fu_490_p1);
    sensitive << ( knn_set_1_4_V_read );

    SC_METHOD(thread_tmp_8_1_cast_fu_474_p1);
    sensitive << ( knn_set_1_0_V_read );

    SC_METHOD(thread_tmp_8_2_1_cast_fu_548_p1);
    sensitive << ( knn_set_2_1_V_read );

    SC_METHOD(thread_tmp_8_2_2_cast_fu_552_p1);
    sensitive << ( knn_set_2_2_V_read );

    SC_METHOD(thread_tmp_8_2_3_cast_fu_556_p1);
    sensitive << ( knn_set_2_3_V_read );

    SC_METHOD(thread_tmp_8_2_4_cast_fu_560_p1);
    sensitive << ( knn_set_2_4_V_read );

    SC_METHOD(thread_tmp_8_2_cast_fu_544_p1);
    sensitive << ( knn_set_2_0_V_read );

    SC_METHOD(thread_tmp_8_3_1_cast_fu_614_p1);
    sensitive << ( knn_set_3_1_V_read );

    SC_METHOD(thread_tmp_8_3_2_cast_fu_618_p1);
    sensitive << ( knn_set_3_2_V_read );

    SC_METHOD(thread_tmp_8_3_3_cast_fu_622_p1);
    sensitive << ( knn_set_3_3_V_read );

    SC_METHOD(thread_tmp_8_3_4_cast_fu_626_p1);
    sensitive << ( knn_set_3_4_V_read );

    SC_METHOD(thread_tmp_8_3_cast_fu_610_p1);
    sensitive << ( knn_set_3_0_V_read );

    SC_METHOD(thread_tmp_8_4_1_cast_fu_684_p1);
    sensitive << ( knn_set_4_1_V_read );

    SC_METHOD(thread_tmp_8_4_2_cast_fu_688_p1);
    sensitive << ( knn_set_4_2_V_read );

    SC_METHOD(thread_tmp_8_4_3_cast_fu_692_p1);
    sensitive << ( knn_set_4_3_V_read );

    SC_METHOD(thread_tmp_8_4_4_cast_fu_696_p1);
    sensitive << ( knn_set_4_4_V_read );

    SC_METHOD(thread_tmp_8_4_cast_fu_680_p1);
    sensitive << ( knn_set_4_0_V_read );

    SC_METHOD(thread_tmp_8_5_1_cast_fu_776_p1);
    sensitive << ( knn_set_5_1_V_read );

    SC_METHOD(thread_tmp_8_5_2_cast_fu_780_p1);
    sensitive << ( knn_set_5_2_V_read );

    SC_METHOD(thread_tmp_8_5_3_cast_fu_784_p1);
    sensitive << ( knn_set_5_3_V_read );

    SC_METHOD(thread_tmp_8_5_4_cast_fu_788_p1);
    sensitive << ( knn_set_5_4_V_read );

    SC_METHOD(thread_tmp_8_5_cast_fu_772_p1);
    sensitive << ( knn_set_5_0_V_read );

    SC_METHOD(thread_tmp_8_6_1_cast_fu_868_p1);
    sensitive << ( knn_set_6_1_V_read );

    SC_METHOD(thread_tmp_8_6_2_cast_fu_872_p1);
    sensitive << ( knn_set_6_2_V_read );

    SC_METHOD(thread_tmp_8_6_3_cast_fu_876_p1);
    sensitive << ( knn_set_6_3_V_read );

    SC_METHOD(thread_tmp_8_6_4_cast_fu_880_p1);
    sensitive << ( knn_set_6_4_V_read );

    SC_METHOD(thread_tmp_8_6_cast_fu_864_p1);
    sensitive << ( knn_set_6_0_V_read );

    SC_METHOD(thread_tmp_8_7_1_cast_fu_934_p1);
    sensitive << ( knn_set_7_1_V_read );

    SC_METHOD(thread_tmp_8_7_2_cast_fu_938_p1);
    sensitive << ( knn_set_7_2_V_read );

    SC_METHOD(thread_tmp_8_7_3_cast_fu_942_p1);
    sensitive << ( knn_set_7_3_V_read );

    SC_METHOD(thread_tmp_8_7_4_cast_fu_946_p1);
    sensitive << ( knn_set_7_4_V_read );

    SC_METHOD(thread_tmp_8_7_cast_fu_930_p1);
    sensitive << ( knn_set_7_0_V_read );

    SC_METHOD(thread_tmp_8_8_1_cast_fu_1004_p1);
    sensitive << ( knn_set_8_1_V_read );

    SC_METHOD(thread_tmp_8_8_2_cast_fu_1008_p1);
    sensitive << ( knn_set_8_2_V_read );

    SC_METHOD(thread_tmp_8_8_3_cast_fu_1012_p1);
    sensitive << ( knn_set_8_3_V_read );

    SC_METHOD(thread_tmp_8_8_4_cast_fu_1016_p1);
    sensitive << ( knn_set_8_4_V_read );

    SC_METHOD(thread_tmp_8_8_cast_fu_1000_p1);
    sensitive << ( knn_set_8_0_V_read );

    SC_METHOD(thread_tmp_8_9_1_cast_fu_1092_p1);
    sensitive << ( knn_set_9_1_V_read );

    SC_METHOD(thread_tmp_8_9_2_cast_fu_1096_p1);
    sensitive << ( knn_set_9_2_V_read );

    SC_METHOD(thread_tmp_8_9_3_cast_fu_1100_p1);
    sensitive << ( knn_set_9_3_V_read );

    SC_METHOD(thread_tmp_8_9_4_cast_fu_1104_p1);
    sensitive << ( knn_set_9_4_V_read );

    SC_METHOD(thread_tmp_8_9_cast_fu_1088_p1);
    sensitive << ( knn_set_9_0_V_read );

    SC_METHOD(thread_tmp_8_cast_fu_418_p1);
    sensitive << ( knn_set_0_0_V_read );

    SC_METHOD(thread_tmp_9_fu_1158_p2);
    sensitive << ( tmp_6_8_fu_1078_p2 );
    sensitive << ( tmp_6_9_fu_1144_p2 );

    SC_METHOD(thread_tmp_fu_564_p2);
    sensitive << ( tmp_8_2_3_cast_fu_556_p1 );
    sensitive << ( tmp_8_2_2_cast_fu_552_p1 );

    SC_METHOD(thread_tmp_s_fu_746_p2);
    sensitive << ( tmp_6_2_reg_1189 );
    sensitive << ( tmp_6_3_reg_1194 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );

    ap_CS_fsm = "00001";
    ap_return_preg = "0000";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "digitrec_knn_vote_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, knn_set_0_0_V_read, "(port)knn_set_0_0_V_read");
    sc_trace(mVcdFile, knn_set_0_1_V_read, "(port)knn_set_0_1_V_read");
    sc_trace(mVcdFile, knn_set_0_2_V_read, "(port)knn_set_0_2_V_read");
    sc_trace(mVcdFile, knn_set_0_3_V_read, "(port)knn_set_0_3_V_read");
    sc_trace(mVcdFile, knn_set_0_4_V_read, "(port)knn_set_0_4_V_read");
    sc_trace(mVcdFile, knn_set_1_0_V_read, "(port)knn_set_1_0_V_read");
    sc_trace(mVcdFile, knn_set_1_1_V_read, "(port)knn_set_1_1_V_read");
    sc_trace(mVcdFile, knn_set_1_2_V_read, "(port)knn_set_1_2_V_read");
    sc_trace(mVcdFile, knn_set_1_3_V_read, "(port)knn_set_1_3_V_read");
    sc_trace(mVcdFile, knn_set_1_4_V_read, "(port)knn_set_1_4_V_read");
    sc_trace(mVcdFile, knn_set_2_0_V_read, "(port)knn_set_2_0_V_read");
    sc_trace(mVcdFile, knn_set_2_1_V_read, "(port)knn_set_2_1_V_read");
    sc_trace(mVcdFile, knn_set_2_2_V_read, "(port)knn_set_2_2_V_read");
    sc_trace(mVcdFile, knn_set_2_3_V_read, "(port)knn_set_2_3_V_read");
    sc_trace(mVcdFile, knn_set_2_4_V_read, "(port)knn_set_2_4_V_read");
    sc_trace(mVcdFile, knn_set_3_0_V_read, "(port)knn_set_3_0_V_read");
    sc_trace(mVcdFile, knn_set_3_1_V_read, "(port)knn_set_3_1_V_read");
    sc_trace(mVcdFile, knn_set_3_2_V_read, "(port)knn_set_3_2_V_read");
    sc_trace(mVcdFile, knn_set_3_3_V_read, "(port)knn_set_3_3_V_read");
    sc_trace(mVcdFile, knn_set_3_4_V_read, "(port)knn_set_3_4_V_read");
    sc_trace(mVcdFile, knn_set_4_0_V_read, "(port)knn_set_4_0_V_read");
    sc_trace(mVcdFile, knn_set_4_1_V_read, "(port)knn_set_4_1_V_read");
    sc_trace(mVcdFile, knn_set_4_2_V_read, "(port)knn_set_4_2_V_read");
    sc_trace(mVcdFile, knn_set_4_3_V_read, "(port)knn_set_4_3_V_read");
    sc_trace(mVcdFile, knn_set_4_4_V_read, "(port)knn_set_4_4_V_read");
    sc_trace(mVcdFile, knn_set_5_0_V_read, "(port)knn_set_5_0_V_read");
    sc_trace(mVcdFile, knn_set_5_1_V_read, "(port)knn_set_5_1_V_read");
    sc_trace(mVcdFile, knn_set_5_2_V_read, "(port)knn_set_5_2_V_read");
    sc_trace(mVcdFile, knn_set_5_3_V_read, "(port)knn_set_5_3_V_read");
    sc_trace(mVcdFile, knn_set_5_4_V_read, "(port)knn_set_5_4_V_read");
    sc_trace(mVcdFile, knn_set_6_0_V_read, "(port)knn_set_6_0_V_read");
    sc_trace(mVcdFile, knn_set_6_1_V_read, "(port)knn_set_6_1_V_read");
    sc_trace(mVcdFile, knn_set_6_2_V_read, "(port)knn_set_6_2_V_read");
    sc_trace(mVcdFile, knn_set_6_3_V_read, "(port)knn_set_6_3_V_read");
    sc_trace(mVcdFile, knn_set_6_4_V_read, "(port)knn_set_6_4_V_read");
    sc_trace(mVcdFile, knn_set_7_0_V_read, "(port)knn_set_7_0_V_read");
    sc_trace(mVcdFile, knn_set_7_1_V_read, "(port)knn_set_7_1_V_read");
    sc_trace(mVcdFile, knn_set_7_2_V_read, "(port)knn_set_7_2_V_read");
    sc_trace(mVcdFile, knn_set_7_3_V_read, "(port)knn_set_7_3_V_read");
    sc_trace(mVcdFile, knn_set_7_4_V_read, "(port)knn_set_7_4_V_read");
    sc_trace(mVcdFile, knn_set_8_0_V_read, "(port)knn_set_8_0_V_read");
    sc_trace(mVcdFile, knn_set_8_1_V_read, "(port)knn_set_8_1_V_read");
    sc_trace(mVcdFile, knn_set_8_2_V_read, "(port)knn_set_8_2_V_read");
    sc_trace(mVcdFile, knn_set_8_3_V_read, "(port)knn_set_8_3_V_read");
    sc_trace(mVcdFile, knn_set_8_4_V_read, "(port)knn_set_8_4_V_read");
    sc_trace(mVcdFile, knn_set_9_0_V_read, "(port)knn_set_9_0_V_read");
    sc_trace(mVcdFile, knn_set_9_1_V_read, "(port)knn_set_9_1_V_read");
    sc_trace(mVcdFile, knn_set_9_2_V_read, "(port)knn_set_9_2_V_read");
    sc_trace(mVcdFile, knn_set_9_3_V_read, "(port)knn_set_9_3_V_read");
    sc_trace(mVcdFile, knn_set_9_4_V_read, "(port)knn_set_9_4_V_read");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st1_fsm_0, "ap_sig_cseq_ST_st1_fsm_0");
    sc_trace(mVcdFile, ap_sig_22, "ap_sig_22");
    sc_trace(mVcdFile, tmp_6_1_fu_530_p2, "tmp_6_1_fu_530_p2");
    sc_trace(mVcdFile, tmp_6_1_reg_1172, "tmp_6_1_reg_1172");
    sc_trace(mVcdFile, min_2_min_1_fu_536_p3, "min_2_min_1_fu_536_p3");
    sc_trace(mVcdFile, min_2_min_1_reg_1177, "min_2_min_1_reg_1177");
    sc_trace(mVcdFile, sum_2_4_fu_594_p2, "sum_2_4_fu_594_p2");
    sc_trace(mVcdFile, sum_2_4_reg_1183, "sum_2_4_reg_1183");
    sc_trace(mVcdFile, tmp_6_2_fu_600_p2, "tmp_6_2_fu_600_p2");
    sc_trace(mVcdFile, tmp_6_2_reg_1189, "tmp_6_2_reg_1189");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st2_fsm_1, "ap_sig_cseq_ST_st2_fsm_1");
    sc_trace(mVcdFile, ap_sig_94, "ap_sig_94");
    sc_trace(mVcdFile, tmp_6_3_fu_666_p2, "tmp_6_3_fu_666_p2");
    sc_trace(mVcdFile, tmp_6_3_reg_1194, "tmp_6_3_reg_1194");
    sc_trace(mVcdFile, min_2_min_3_fu_672_p3, "min_2_min_3_fu_672_p3");
    sc_trace(mVcdFile, min_2_min_3_reg_1200, "min_2_min_3_reg_1200");
    sc_trace(mVcdFile, sum_4_4_fu_730_p2, "sum_4_4_fu_730_p2");
    sc_trace(mVcdFile, sum_4_4_reg_1206, "sum_4_4_reg_1206");
    sc_trace(mVcdFile, agg_result_V_0_agg_result_V_02_5_fu_848_p3, "agg_result_V_0_agg_result_V_02_5_fu_848_p3");
    sc_trace(mVcdFile, agg_result_V_0_agg_result_V_02_5_reg_1212, "agg_result_V_0_agg_result_V_02_5_reg_1212");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st3_fsm_2, "ap_sig_cseq_ST_st3_fsm_2");
    sc_trace(mVcdFile, ap_sig_109, "ap_sig_109");
    sc_trace(mVcdFile, min_2_min_5_fu_856_p3, "min_2_min_5_fu_856_p3");
    sc_trace(mVcdFile, min_2_min_5_reg_1217, "min_2_min_5_reg_1217");
    sc_trace(mVcdFile, sum_6_4_fu_914_p2, "sum_6_4_fu_914_p2");
    sc_trace(mVcdFile, sum_6_4_reg_1223, "sum_6_4_reg_1223");
    sc_trace(mVcdFile, tmp_6_6_fu_920_p2, "tmp_6_6_fu_920_p2");
    sc_trace(mVcdFile, tmp_6_6_reg_1229, "tmp_6_6_reg_1229");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st4_fsm_3, "ap_sig_cseq_ST_st4_fsm_3");
    sc_trace(mVcdFile, ap_sig_122, "ap_sig_122");
    sc_trace(mVcdFile, tmp_6_7_fu_986_p2, "tmp_6_7_fu_986_p2");
    sc_trace(mVcdFile, tmp_6_7_reg_1234, "tmp_6_7_reg_1234");
    sc_trace(mVcdFile, min_2_min_7_fu_992_p3, "min_2_min_7_fu_992_p3");
    sc_trace(mVcdFile, min_2_min_7_reg_1240, "min_2_min_7_reg_1240");
    sc_trace(mVcdFile, sum_8_4_fu_1050_p2, "sum_8_4_fu_1050_p2");
    sc_trace(mVcdFile, sum_8_4_reg_1246, "sum_8_4_reg_1246");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st5_fsm_4, "ap_sig_cseq_ST_st5_fsm_4");
    sc_trace(mVcdFile, ap_sig_181, "ap_sig_181");
    sc_trace(mVcdFile, tmp_8_0_3_cast_fu_430_p1, "tmp_8_0_3_cast_fu_430_p1");
    sc_trace(mVcdFile, tmp_8_0_2_cast_fu_426_p1, "tmp_8_0_2_cast_fu_426_p1");
    sc_trace(mVcdFile, tmp2_fu_438_p2, "tmp2_fu_438_p2");
    sc_trace(mVcdFile, tmp_8_0_4_cast_fu_434_p1, "tmp_8_0_4_cast_fu_434_p1");
    sc_trace(mVcdFile, tmp_8_cast_fu_418_p1, "tmp_8_cast_fu_418_p1");
    sc_trace(mVcdFile, tmp4_fu_448_p2, "tmp4_fu_448_p2");
    sc_trace(mVcdFile, tmp_8_0_1_cast_fu_422_p1, "tmp_8_0_1_cast_fu_422_p1");
    sc_trace(mVcdFile, tmp4_cast_fu_454_p1, "tmp4_cast_fu_454_p1");
    sc_trace(mVcdFile, tmp3_fu_458_p2, "tmp3_fu_458_p2");
    sc_trace(mVcdFile, tmp2_cast_fu_444_p1, "tmp2_cast_fu_444_p1");
    sc_trace(mVcdFile, tmp3_cast_fu_464_p1, "tmp3_cast_fu_464_p1");
    sc_trace(mVcdFile, tmp_8_1_3_cast_fu_486_p1, "tmp_8_1_3_cast_fu_486_p1");
    sc_trace(mVcdFile, tmp_8_1_2_cast_fu_482_p1, "tmp_8_1_2_cast_fu_482_p1");
    sc_trace(mVcdFile, tmp7_fu_494_p2, "tmp7_fu_494_p2");
    sc_trace(mVcdFile, tmp_8_1_4_cast_fu_490_p1, "tmp_8_1_4_cast_fu_490_p1");
    sc_trace(mVcdFile, tmp_8_1_cast_fu_474_p1, "tmp_8_1_cast_fu_474_p1");
    sc_trace(mVcdFile, tmp9_fu_504_p2, "tmp9_fu_504_p2");
    sc_trace(mVcdFile, tmp_8_1_1_cast_fu_478_p1, "tmp_8_1_1_cast_fu_478_p1");
    sc_trace(mVcdFile, tmp9_cast_fu_510_p1, "tmp9_cast_fu_510_p1");
    sc_trace(mVcdFile, tmp8_fu_514_p2, "tmp8_fu_514_p2");
    sc_trace(mVcdFile, tmp7_cast_fu_500_p1, "tmp7_cast_fu_500_p1");
    sc_trace(mVcdFile, tmp8_cast_fu_520_p1, "tmp8_cast_fu_520_p1");
    sc_trace(mVcdFile, sum_1_4_fu_524_p2, "sum_1_4_fu_524_p2");
    sc_trace(mVcdFile, sum_0_4_fu_468_p2, "sum_0_4_fu_468_p2");
    sc_trace(mVcdFile, tmp_8_2_3_cast_fu_556_p1, "tmp_8_2_3_cast_fu_556_p1");
    sc_trace(mVcdFile, tmp_8_2_2_cast_fu_552_p1, "tmp_8_2_2_cast_fu_552_p1");
    sc_trace(mVcdFile, tmp_fu_564_p2, "tmp_fu_564_p2");
    sc_trace(mVcdFile, tmp_8_2_4_cast_fu_560_p1, "tmp_8_2_4_cast_fu_560_p1");
    sc_trace(mVcdFile, tmp_8_2_cast_fu_544_p1, "tmp_8_2_cast_fu_544_p1");
    sc_trace(mVcdFile, tmp1_fu_574_p2, "tmp1_fu_574_p2");
    sc_trace(mVcdFile, tmp_8_2_1_cast_fu_548_p1, "tmp_8_2_1_cast_fu_548_p1");
    sc_trace(mVcdFile, tmp14_cast_fu_580_p1, "tmp14_cast_fu_580_p1");
    sc_trace(mVcdFile, tmp5_fu_584_p2, "tmp5_fu_584_p2");
    sc_trace(mVcdFile, tmp12_cast_fu_570_p1, "tmp12_cast_fu_570_p1");
    sc_trace(mVcdFile, tmp13_cast_fu_590_p1, "tmp13_cast_fu_590_p1");
    sc_trace(mVcdFile, tmp_8_3_3_cast_fu_622_p1, "tmp_8_3_3_cast_fu_622_p1");
    sc_trace(mVcdFile, tmp_8_3_2_cast_fu_618_p1, "tmp_8_3_2_cast_fu_618_p1");
    sc_trace(mVcdFile, tmp6_fu_630_p2, "tmp6_fu_630_p2");
    sc_trace(mVcdFile, tmp_8_3_4_cast_fu_626_p1, "tmp_8_3_4_cast_fu_626_p1");
    sc_trace(mVcdFile, tmp_8_3_cast_fu_610_p1, "tmp_8_3_cast_fu_610_p1");
    sc_trace(mVcdFile, tmp10_fu_640_p2, "tmp10_fu_640_p2");
    sc_trace(mVcdFile, tmp_8_3_1_cast_fu_614_p1, "tmp_8_3_1_cast_fu_614_p1");
    sc_trace(mVcdFile, tmp19_cast_fu_646_p1, "tmp19_cast_fu_646_p1");
    sc_trace(mVcdFile, tmp11_fu_650_p2, "tmp11_fu_650_p2");
    sc_trace(mVcdFile, tmp17_cast_fu_636_p1, "tmp17_cast_fu_636_p1");
    sc_trace(mVcdFile, tmp18_cast_fu_656_p1, "tmp18_cast_fu_656_p1");
    sc_trace(mVcdFile, sum_3_4_fu_660_p2, "sum_3_4_fu_660_p2");
    sc_trace(mVcdFile, min_2_min_2_fu_604_p3, "min_2_min_2_fu_604_p3");
    sc_trace(mVcdFile, tmp_8_4_3_cast_fu_692_p1, "tmp_8_4_3_cast_fu_692_p1");
    sc_trace(mVcdFile, tmp_8_4_2_cast_fu_688_p1, "tmp_8_4_2_cast_fu_688_p1");
    sc_trace(mVcdFile, tmp12_fu_700_p2, "tmp12_fu_700_p2");
    sc_trace(mVcdFile, tmp_8_4_4_cast_fu_696_p1, "tmp_8_4_4_cast_fu_696_p1");
    sc_trace(mVcdFile, tmp_8_4_cast_fu_680_p1, "tmp_8_4_cast_fu_680_p1");
    sc_trace(mVcdFile, tmp13_fu_710_p2, "tmp13_fu_710_p2");
    sc_trace(mVcdFile, tmp_8_4_1_cast_fu_684_p1, "tmp_8_4_1_cast_fu_684_p1");
    sc_trace(mVcdFile, tmp24_cast_fu_716_p1, "tmp24_cast_fu_716_p1");
    sc_trace(mVcdFile, tmp14_fu_720_p2, "tmp14_fu_720_p2");
    sc_trace(mVcdFile, tmp22_cast_fu_706_p1, "tmp22_cast_fu_706_p1");
    sc_trace(mVcdFile, tmp23_cast_fu_726_p1, "tmp23_cast_fu_726_p1");
    sc_trace(mVcdFile, tmp_s_fu_746_p2, "tmp_s_fu_746_p2");
    sc_trace(mVcdFile, agg_result_V_0_agg_result_V_02_2_fu_739_p3, "agg_result_V_0_agg_result_V_02_2_fu_739_p3");
    sc_trace(mVcdFile, agg_result_V_0_agg_result_V_s_fu_736_p1, "agg_result_V_0_agg_result_V_s_fu_736_p1");
    sc_trace(mVcdFile, agg_result_V_0_agg_result_V_02_3_fu_750_p3, "agg_result_V_0_agg_result_V_02_3_fu_750_p3");
    sc_trace(mVcdFile, tmp_6_4_fu_762_p2, "tmp_6_4_fu_762_p2");
    sc_trace(mVcdFile, tmp_8_5_3_cast_fu_784_p1, "tmp_8_5_3_cast_fu_784_p1");
    sc_trace(mVcdFile, tmp_8_5_2_cast_fu_780_p1, "tmp_8_5_2_cast_fu_780_p1");
    sc_trace(mVcdFile, tmp15_fu_792_p2, "tmp15_fu_792_p2");
    sc_trace(mVcdFile, tmp_8_5_4_cast_fu_788_p1, "tmp_8_5_4_cast_fu_788_p1");
    sc_trace(mVcdFile, tmp_8_5_cast_fu_772_p1, "tmp_8_5_cast_fu_772_p1");
    sc_trace(mVcdFile, tmp16_fu_802_p2, "tmp16_fu_802_p2");
    sc_trace(mVcdFile, tmp_8_5_1_cast_fu_776_p1, "tmp_8_5_1_cast_fu_776_p1");
    sc_trace(mVcdFile, tmp29_cast_fu_808_p1, "tmp29_cast_fu_808_p1");
    sc_trace(mVcdFile, tmp17_fu_812_p2, "tmp17_fu_812_p2");
    sc_trace(mVcdFile, tmp27_cast_fu_798_p1, "tmp27_cast_fu_798_p1");
    sc_trace(mVcdFile, tmp28_cast_fu_818_p1, "tmp28_cast_fu_818_p1");
    sc_trace(mVcdFile, sum_5_4_fu_822_p2, "sum_5_4_fu_822_p2");
    sc_trace(mVcdFile, min_2_min_4_fu_766_p3, "min_2_min_4_fu_766_p3");
    sc_trace(mVcdFile, tmp_6_5_fu_828_p2, "tmp_6_5_fu_828_p2");
    sc_trace(mVcdFile, tmp_6_fu_842_p2, "tmp_6_fu_842_p2");
    sc_trace(mVcdFile, agg_result_V_0_agg_result_V_02_4_fu_834_p3, "agg_result_V_0_agg_result_V_02_4_fu_834_p3");
    sc_trace(mVcdFile, agg_result_V_0_agg_result_V_02_1_fu_758_p1, "agg_result_V_0_agg_result_V_02_1_fu_758_p1");
    sc_trace(mVcdFile, tmp_8_6_3_cast_fu_876_p1, "tmp_8_6_3_cast_fu_876_p1");
    sc_trace(mVcdFile, tmp_8_6_2_cast_fu_872_p1, "tmp_8_6_2_cast_fu_872_p1");
    sc_trace(mVcdFile, tmp18_fu_884_p2, "tmp18_fu_884_p2");
    sc_trace(mVcdFile, tmp_8_6_4_cast_fu_880_p1, "tmp_8_6_4_cast_fu_880_p1");
    sc_trace(mVcdFile, tmp_8_6_cast_fu_864_p1, "tmp_8_6_cast_fu_864_p1");
    sc_trace(mVcdFile, tmp19_fu_894_p2, "tmp19_fu_894_p2");
    sc_trace(mVcdFile, tmp_8_6_1_cast_fu_868_p1, "tmp_8_6_1_cast_fu_868_p1");
    sc_trace(mVcdFile, tmp34_cast_fu_900_p1, "tmp34_cast_fu_900_p1");
    sc_trace(mVcdFile, tmp20_fu_904_p2, "tmp20_fu_904_p2");
    sc_trace(mVcdFile, tmp32_cast_fu_890_p1, "tmp32_cast_fu_890_p1");
    sc_trace(mVcdFile, tmp33_cast_fu_910_p1, "tmp33_cast_fu_910_p1");
    sc_trace(mVcdFile, tmp_8_7_3_cast_fu_942_p1, "tmp_8_7_3_cast_fu_942_p1");
    sc_trace(mVcdFile, tmp_8_7_2_cast_fu_938_p1, "tmp_8_7_2_cast_fu_938_p1");
    sc_trace(mVcdFile, tmp21_fu_950_p2, "tmp21_fu_950_p2");
    sc_trace(mVcdFile, tmp_8_7_4_cast_fu_946_p1, "tmp_8_7_4_cast_fu_946_p1");
    sc_trace(mVcdFile, tmp_8_7_cast_fu_930_p1, "tmp_8_7_cast_fu_930_p1");
    sc_trace(mVcdFile, tmp22_fu_960_p2, "tmp22_fu_960_p2");
    sc_trace(mVcdFile, tmp_8_7_1_cast_fu_934_p1, "tmp_8_7_1_cast_fu_934_p1");
    sc_trace(mVcdFile, tmp39_cast_fu_966_p1, "tmp39_cast_fu_966_p1");
    sc_trace(mVcdFile, tmp23_fu_970_p2, "tmp23_fu_970_p2");
    sc_trace(mVcdFile, tmp37_cast_fu_956_p1, "tmp37_cast_fu_956_p1");
    sc_trace(mVcdFile, tmp38_cast_fu_976_p1, "tmp38_cast_fu_976_p1");
    sc_trace(mVcdFile, sum_7_4_fu_980_p2, "sum_7_4_fu_980_p2");
    sc_trace(mVcdFile, min_2_min_6_fu_924_p3, "min_2_min_6_fu_924_p3");
    sc_trace(mVcdFile, tmp_8_8_3_cast_fu_1012_p1, "tmp_8_8_3_cast_fu_1012_p1");
    sc_trace(mVcdFile, tmp_8_8_2_cast_fu_1008_p1, "tmp_8_8_2_cast_fu_1008_p1");
    sc_trace(mVcdFile, tmp24_fu_1020_p2, "tmp24_fu_1020_p2");
    sc_trace(mVcdFile, tmp_8_8_4_cast_fu_1016_p1, "tmp_8_8_4_cast_fu_1016_p1");
    sc_trace(mVcdFile, tmp_8_8_cast_fu_1000_p1, "tmp_8_8_cast_fu_1000_p1");
    sc_trace(mVcdFile, tmp25_fu_1030_p2, "tmp25_fu_1030_p2");
    sc_trace(mVcdFile, tmp_8_8_1_cast_fu_1004_p1, "tmp_8_8_1_cast_fu_1004_p1");
    sc_trace(mVcdFile, tmp44_cast_fu_1036_p1, "tmp44_cast_fu_1036_p1");
    sc_trace(mVcdFile, tmp26_fu_1040_p2, "tmp26_fu_1040_p2");
    sc_trace(mVcdFile, tmp42_cast_fu_1026_p1, "tmp42_cast_fu_1026_p1");
    sc_trace(mVcdFile, tmp43_cast_fu_1046_p1, "tmp43_cast_fu_1046_p1");
    sc_trace(mVcdFile, tmp_7_fu_1063_p2, "tmp_7_fu_1063_p2");
    sc_trace(mVcdFile, agg_result_V_0_agg_result_V_02_fu_1056_p3, "agg_result_V_0_agg_result_V_02_fu_1056_p3");
    sc_trace(mVcdFile, agg_result_V_0_agg_result_V_02_7_fu_1067_p3, "agg_result_V_0_agg_result_V_02_7_fu_1067_p3");
    sc_trace(mVcdFile, tmp_6_8_fu_1078_p2, "tmp_6_8_fu_1078_p2");
    sc_trace(mVcdFile, tmp_8_9_1_cast_fu_1092_p1, "tmp_8_9_1_cast_fu_1092_p1");
    sc_trace(mVcdFile, tmp_8_9_cast_fu_1088_p1, "tmp_8_9_cast_fu_1088_p1");
    sc_trace(mVcdFile, tmp27_fu_1108_p2, "tmp27_fu_1108_p2");
    sc_trace(mVcdFile, tmp_8_9_4_cast_fu_1104_p1, "tmp_8_9_4_cast_fu_1104_p1");
    sc_trace(mVcdFile, tmp_8_9_3_cast_fu_1100_p1, "tmp_8_9_3_cast_fu_1100_p1");
    sc_trace(mVcdFile, tmp28_fu_1118_p2, "tmp28_fu_1118_p2");
    sc_trace(mVcdFile, tmp_8_9_2_cast_fu_1096_p1, "tmp_8_9_2_cast_fu_1096_p1");
    sc_trace(mVcdFile, tmp47_cast_fu_1124_p1, "tmp47_cast_fu_1124_p1");
    sc_trace(mVcdFile, tmp29_fu_1128_p2, "tmp29_fu_1128_p2");
    sc_trace(mVcdFile, tmp45_cast_fu_1114_p1, "tmp45_cast_fu_1114_p1");
    sc_trace(mVcdFile, tmp46_cast_fu_1134_p1, "tmp46_cast_fu_1134_p1");
    sc_trace(mVcdFile, sum_9_4_fu_1138_p2, "sum_9_4_fu_1138_p2");
    sc_trace(mVcdFile, min_2_min_8_fu_1082_p3, "min_2_min_8_fu_1082_p3");
    sc_trace(mVcdFile, tmp_6_9_fu_1144_p2, "tmp_6_9_fu_1144_p2");
    sc_trace(mVcdFile, tmp_9_fu_1158_p2, "tmp_9_fu_1158_p2");
    sc_trace(mVcdFile, agg_result_V_0_agg_result_V_02_8_fu_1150_p3, "agg_result_V_0_agg_result_V_02_8_fu_1150_p3");
    sc_trace(mVcdFile, agg_result_V_0_agg_result_V_02_6_fu_1074_p1, "agg_result_V_0_agg_result_V_02_6_fu_1074_p1");
    sc_trace(mVcdFile, agg_result_V_0_agg_result_V_02_9_fu_1164_p3, "agg_result_V_0_agg_result_V_02_9_fu_1164_p3");
    sc_trace(mVcdFile, ap_return_preg, "ap_return_preg");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

digitrec_knn_vote::~digitrec_knn_vote() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void digitrec_knn_vote::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_preg = ap_const_lv4_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
            ap_return_preg = agg_result_V_0_agg_result_V_02_9_fu_1164_p3.read();
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        agg_result_V_0_agg_result_V_02_5_reg_1212 = agg_result_V_0_agg_result_V_02_5_fu_848_p3.read();
        min_2_min_5_reg_1217 = min_2_min_5_fu_856_p3.read();
        sum_6_4_reg_1223 = sum_6_4_fu_914_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        min_2_min_1_reg_1177 = min_2_min_1_fu_536_p3.read();
        sum_2_4_reg_1183 = sum_2_4_fu_594_p2.read();
        tmp_6_1_reg_1172 = tmp_6_1_fu_530_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        min_2_min_3_reg_1200 = min_2_min_3_fu_672_p3.read();
        sum_4_4_reg_1206 = sum_4_4_fu_730_p2.read();
        tmp_6_2_reg_1189 = tmp_6_2_fu_600_p2.read();
        tmp_6_3_reg_1194 = tmp_6_3_fu_666_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        min_2_min_7_reg_1240 = min_2_min_7_fu_992_p3.read();
        sum_8_4_reg_1246 = sum_8_4_fu_1050_p2.read();
        tmp_6_6_reg_1229 = tmp_6_6_fu_920_p2.read();
        tmp_6_7_reg_1234 = tmp_6_7_fu_986_p2.read();
    }
}

void digitrec_knn_vote::thread_agg_result_V_0_agg_result_V_02_1_fu_758_p1() {
    agg_result_V_0_agg_result_V_02_1_fu_758_p1 = esl_zext<3,2>(agg_result_V_0_agg_result_V_02_3_fu_750_p3.read());
}

void digitrec_knn_vote::thread_agg_result_V_0_agg_result_V_02_2_fu_739_p3() {
    agg_result_V_0_agg_result_V_02_2_fu_739_p3 = (!tmp_6_3_reg_1194.read()[0].is_01())? sc_lv<2>(): ((tmp_6_3_reg_1194.read()[0].to_bool())? ap_const_lv2_3: ap_const_lv2_2);
}

void digitrec_knn_vote::thread_agg_result_V_0_agg_result_V_02_3_fu_750_p3() {
    agg_result_V_0_agg_result_V_02_3_fu_750_p3 = (!tmp_s_fu_746_p2.read()[0].is_01())? sc_lv<2>(): ((tmp_s_fu_746_p2.read()[0].to_bool())? agg_result_V_0_agg_result_V_02_2_fu_739_p3.read(): agg_result_V_0_agg_result_V_s_fu_736_p1.read());
}

void digitrec_knn_vote::thread_agg_result_V_0_agg_result_V_02_4_fu_834_p3() {
    agg_result_V_0_agg_result_V_02_4_fu_834_p3 = (!tmp_6_5_fu_828_p2.read()[0].is_01())? sc_lv<3>(): ((tmp_6_5_fu_828_p2.read()[0].to_bool())? ap_const_lv3_5: ap_const_lv3_4);
}

void digitrec_knn_vote::thread_agg_result_V_0_agg_result_V_02_5_fu_848_p3() {
    agg_result_V_0_agg_result_V_02_5_fu_848_p3 = (!tmp_6_fu_842_p2.read()[0].is_01())? sc_lv<3>(): ((tmp_6_fu_842_p2.read()[0].to_bool())? agg_result_V_0_agg_result_V_02_4_fu_834_p3.read(): agg_result_V_0_agg_result_V_02_1_fu_758_p1.read());
}

void digitrec_knn_vote::thread_agg_result_V_0_agg_result_V_02_6_fu_1074_p1() {
    agg_result_V_0_agg_result_V_02_6_fu_1074_p1 = esl_zext<4,3>(agg_result_V_0_agg_result_V_02_7_fu_1067_p3.read());
}

void digitrec_knn_vote::thread_agg_result_V_0_agg_result_V_02_7_fu_1067_p3() {
    agg_result_V_0_agg_result_V_02_7_fu_1067_p3 = (!tmp_7_fu_1063_p2.read()[0].is_01())? sc_lv<3>(): ((tmp_7_fu_1063_p2.read()[0].to_bool())? agg_result_V_0_agg_result_V_02_fu_1056_p3.read(): agg_result_V_0_agg_result_V_02_5_reg_1212.read());
}

void digitrec_knn_vote::thread_agg_result_V_0_agg_result_V_02_8_fu_1150_p3() {
    agg_result_V_0_agg_result_V_02_8_fu_1150_p3 = (!tmp_6_9_fu_1144_p2.read()[0].is_01())? sc_lv<4>(): ((tmp_6_9_fu_1144_p2.read()[0].to_bool())? ap_const_lv4_9: ap_const_lv4_8);
}

void digitrec_knn_vote::thread_agg_result_V_0_agg_result_V_02_9_fu_1164_p3() {
    agg_result_V_0_agg_result_V_02_9_fu_1164_p3 = (!tmp_9_fu_1158_p2.read()[0].is_01())? sc_lv<4>(): ((tmp_9_fu_1158_p2.read()[0].to_bool())? agg_result_V_0_agg_result_V_02_8_fu_1150_p3.read(): agg_result_V_0_agg_result_V_02_6_fu_1074_p1.read());
}

void digitrec_knn_vote::thread_agg_result_V_0_agg_result_V_02_fu_1056_p3() {
    agg_result_V_0_agg_result_V_02_fu_1056_p3 = (!tmp_6_7_reg_1234.read()[0].is_01())? sc_lv<3>(): ((tmp_6_7_reg_1234.read()[0].to_bool())? ap_const_lv3_7: ap_const_lv3_6);
}

void digitrec_knn_vote::thread_agg_result_V_0_agg_result_V_s_fu_736_p1() {
    agg_result_V_0_agg_result_V_s_fu_736_p1 = esl_zext<2,1>(tmp_6_1_reg_1172.read());
}

void digitrec_knn_vote::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void digitrec_knn_vote::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void digitrec_knn_vote::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void digitrec_knn_vote::thread_ap_return() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        ap_return = agg_result_V_0_agg_result_V_02_9_fu_1164_p3.read();
    } else {
        ap_return = ap_return_preg.read();
    }
}

void digitrec_knn_vote::thread_ap_sig_109() {
    ap_sig_109 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(2, 2));
}

void digitrec_knn_vote::thread_ap_sig_122() {
    ap_sig_122 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(3, 3));
}

void digitrec_knn_vote::thread_ap_sig_181() {
    ap_sig_181 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(4, 4));
}

void digitrec_knn_vote::thread_ap_sig_22() {
    ap_sig_22 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void digitrec_knn_vote::thread_ap_sig_94() {
    ap_sig_94 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(1, 1));
}

void digitrec_knn_vote::thread_ap_sig_cseq_ST_st1_fsm_0() {
    if (ap_sig_22.read()) {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    }
}

void digitrec_knn_vote::thread_ap_sig_cseq_ST_st2_fsm_1() {
    if (ap_sig_94.read()) {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    }
}

void digitrec_knn_vote::thread_ap_sig_cseq_ST_st3_fsm_2() {
    if (ap_sig_109.read()) {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_0;
    }
}

void digitrec_knn_vote::thread_ap_sig_cseq_ST_st4_fsm_3() {
    if (ap_sig_122.read()) {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_0;
    }
}

void digitrec_knn_vote::thread_ap_sig_cseq_ST_st5_fsm_4() {
    if (ap_sig_181.read()) {
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_0;
    }
}

void digitrec_knn_vote::thread_min_2_min_1_fu_536_p3() {
    min_2_min_1_fu_536_p3 = (!tmp_6_1_fu_530_p2.read()[0].is_01())? sc_lv<9>(): ((tmp_6_1_fu_530_p2.read()[0].to_bool())? sum_1_4_fu_524_p2.read(): sum_0_4_fu_468_p2.read());
}

void digitrec_knn_vote::thread_min_2_min_2_fu_604_p3() {
    min_2_min_2_fu_604_p3 = (!tmp_6_2_fu_600_p2.read()[0].is_01())? sc_lv<9>(): ((tmp_6_2_fu_600_p2.read()[0].to_bool())? sum_2_4_reg_1183.read(): min_2_min_1_reg_1177.read());
}

void digitrec_knn_vote::thread_min_2_min_3_fu_672_p3() {
    min_2_min_3_fu_672_p3 = (!tmp_6_3_fu_666_p2.read()[0].is_01())? sc_lv<9>(): ((tmp_6_3_fu_666_p2.read()[0].to_bool())? sum_3_4_fu_660_p2.read(): min_2_min_2_fu_604_p3.read());
}

void digitrec_knn_vote::thread_min_2_min_4_fu_766_p3() {
    min_2_min_4_fu_766_p3 = (!tmp_6_4_fu_762_p2.read()[0].is_01())? sc_lv<9>(): ((tmp_6_4_fu_762_p2.read()[0].to_bool())? sum_4_4_reg_1206.read(): min_2_min_3_reg_1200.read());
}

void digitrec_knn_vote::thread_min_2_min_5_fu_856_p3() {
    min_2_min_5_fu_856_p3 = (!tmp_6_5_fu_828_p2.read()[0].is_01())? sc_lv<9>(): ((tmp_6_5_fu_828_p2.read()[0].to_bool())? sum_5_4_fu_822_p2.read(): min_2_min_4_fu_766_p3.read());
}

void digitrec_knn_vote::thread_min_2_min_6_fu_924_p3() {
    min_2_min_6_fu_924_p3 = (!tmp_6_6_fu_920_p2.read()[0].is_01())? sc_lv<9>(): ((tmp_6_6_fu_920_p2.read()[0].to_bool())? sum_6_4_reg_1223.read(): min_2_min_5_reg_1217.read());
}

void digitrec_knn_vote::thread_min_2_min_7_fu_992_p3() {
    min_2_min_7_fu_992_p3 = (!tmp_6_7_fu_986_p2.read()[0].is_01())? sc_lv<9>(): ((tmp_6_7_fu_986_p2.read()[0].to_bool())? sum_7_4_fu_980_p2.read(): min_2_min_6_fu_924_p3.read());
}

void digitrec_knn_vote::thread_min_2_min_8_fu_1082_p3() {
    min_2_min_8_fu_1082_p3 = (!tmp_6_8_fu_1078_p2.read()[0].is_01())? sc_lv<9>(): ((tmp_6_8_fu_1078_p2.read()[0].to_bool())? sum_8_4_reg_1246.read(): min_2_min_7_reg_1240.read());
}

void digitrec_knn_vote::thread_sum_0_4_fu_468_p2() {
    sum_0_4_fu_468_p2 = (!tmp2_cast_fu_444_p1.read().is_01() || !tmp3_cast_fu_464_p1.read().is_01())? sc_lv<9>(): (sc_biguint<9>(tmp2_cast_fu_444_p1.read()) + sc_biguint<9>(tmp3_cast_fu_464_p1.read()));
}

void digitrec_knn_vote::thread_sum_1_4_fu_524_p2() {
    sum_1_4_fu_524_p2 = (!tmp7_cast_fu_500_p1.read().is_01() || !tmp8_cast_fu_520_p1.read().is_01())? sc_lv<9>(): (sc_biguint<9>(tmp7_cast_fu_500_p1.read()) + sc_biguint<9>(tmp8_cast_fu_520_p1.read()));
}

void digitrec_knn_vote::thread_sum_2_4_fu_594_p2() {
    sum_2_4_fu_594_p2 = (!tmp12_cast_fu_570_p1.read().is_01() || !tmp13_cast_fu_590_p1.read().is_01())? sc_lv<9>(): (sc_biguint<9>(tmp12_cast_fu_570_p1.read()) + sc_biguint<9>(tmp13_cast_fu_590_p1.read()));
}

void digitrec_knn_vote::thread_sum_3_4_fu_660_p2() {
    sum_3_4_fu_660_p2 = (!tmp17_cast_fu_636_p1.read().is_01() || !tmp18_cast_fu_656_p1.read().is_01())? sc_lv<9>(): (sc_biguint<9>(tmp17_cast_fu_636_p1.read()) + sc_biguint<9>(tmp18_cast_fu_656_p1.read()));
}

void digitrec_knn_vote::thread_sum_4_4_fu_730_p2() {
    sum_4_4_fu_730_p2 = (!tmp22_cast_fu_706_p1.read().is_01() || !tmp23_cast_fu_726_p1.read().is_01())? sc_lv<9>(): (sc_biguint<9>(tmp22_cast_fu_706_p1.read()) + sc_biguint<9>(tmp23_cast_fu_726_p1.read()));
}

void digitrec_knn_vote::thread_sum_5_4_fu_822_p2() {
    sum_5_4_fu_822_p2 = (!tmp27_cast_fu_798_p1.read().is_01() || !tmp28_cast_fu_818_p1.read().is_01())? sc_lv<9>(): (sc_biguint<9>(tmp27_cast_fu_798_p1.read()) + sc_biguint<9>(tmp28_cast_fu_818_p1.read()));
}

void digitrec_knn_vote::thread_sum_6_4_fu_914_p2() {
    sum_6_4_fu_914_p2 = (!tmp32_cast_fu_890_p1.read().is_01() || !tmp33_cast_fu_910_p1.read().is_01())? sc_lv<9>(): (sc_biguint<9>(tmp32_cast_fu_890_p1.read()) + sc_biguint<9>(tmp33_cast_fu_910_p1.read()));
}

void digitrec_knn_vote::thread_sum_7_4_fu_980_p2() {
    sum_7_4_fu_980_p2 = (!tmp37_cast_fu_956_p1.read().is_01() || !tmp38_cast_fu_976_p1.read().is_01())? sc_lv<9>(): (sc_biguint<9>(tmp37_cast_fu_956_p1.read()) + sc_biguint<9>(tmp38_cast_fu_976_p1.read()));
}

void digitrec_knn_vote::thread_sum_8_4_fu_1050_p2() {
    sum_8_4_fu_1050_p2 = (!tmp42_cast_fu_1026_p1.read().is_01() || !tmp43_cast_fu_1046_p1.read().is_01())? sc_lv<9>(): (sc_biguint<9>(tmp42_cast_fu_1026_p1.read()) + sc_biguint<9>(tmp43_cast_fu_1046_p1.read()));
}

void digitrec_knn_vote::thread_sum_9_4_fu_1138_p2() {
    sum_9_4_fu_1138_p2 = (!tmp45_cast_fu_1114_p1.read().is_01() || !tmp46_cast_fu_1134_p1.read().is_01())? sc_lv<9>(): (sc_biguint<9>(tmp45_cast_fu_1114_p1.read()) + sc_biguint<9>(tmp46_cast_fu_1134_p1.read()));
}

void digitrec_knn_vote::thread_tmp10_fu_640_p2() {
    tmp10_fu_640_p2 = (!tmp_8_3_4_cast_fu_626_p1.read().is_01() || !tmp_8_3_cast_fu_610_p1.read().is_01())? sc_lv<7>(): (sc_biguint<7>(tmp_8_3_4_cast_fu_626_p1.read()) + sc_biguint<7>(tmp_8_3_cast_fu_610_p1.read()));
}

void digitrec_knn_vote::thread_tmp11_fu_650_p2() {
    tmp11_fu_650_p2 = (!tmp_8_3_1_cast_fu_614_p1.read().is_01() || !tmp19_cast_fu_646_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(tmp_8_3_1_cast_fu_614_p1.read()) + sc_biguint<8>(tmp19_cast_fu_646_p1.read()));
}

void digitrec_knn_vote::thread_tmp12_cast_fu_570_p1() {
    tmp12_cast_fu_570_p1 = esl_zext<9,7>(tmp_fu_564_p2.read());
}

void digitrec_knn_vote::thread_tmp12_fu_700_p2() {
    tmp12_fu_700_p2 = (!tmp_8_4_3_cast_fu_692_p1.read().is_01() || !tmp_8_4_2_cast_fu_688_p1.read().is_01())? sc_lv<7>(): (sc_biguint<7>(tmp_8_4_3_cast_fu_692_p1.read()) + sc_biguint<7>(tmp_8_4_2_cast_fu_688_p1.read()));
}

void digitrec_knn_vote::thread_tmp13_cast_fu_590_p1() {
    tmp13_cast_fu_590_p1 = esl_zext<9,8>(tmp5_fu_584_p2.read());
}

void digitrec_knn_vote::thread_tmp13_fu_710_p2() {
    tmp13_fu_710_p2 = (!tmp_8_4_4_cast_fu_696_p1.read().is_01() || !tmp_8_4_cast_fu_680_p1.read().is_01())? sc_lv<7>(): (sc_biguint<7>(tmp_8_4_4_cast_fu_696_p1.read()) + sc_biguint<7>(tmp_8_4_cast_fu_680_p1.read()));
}

void digitrec_knn_vote::thread_tmp14_cast_fu_580_p1() {
    tmp14_cast_fu_580_p1 = esl_zext<8,7>(tmp1_fu_574_p2.read());
}

void digitrec_knn_vote::thread_tmp14_fu_720_p2() {
    tmp14_fu_720_p2 = (!tmp_8_4_1_cast_fu_684_p1.read().is_01() || !tmp24_cast_fu_716_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(tmp_8_4_1_cast_fu_684_p1.read()) + sc_biguint<8>(tmp24_cast_fu_716_p1.read()));
}

void digitrec_knn_vote::thread_tmp15_fu_792_p2() {
    tmp15_fu_792_p2 = (!tmp_8_5_3_cast_fu_784_p1.read().is_01() || !tmp_8_5_2_cast_fu_780_p1.read().is_01())? sc_lv<7>(): (sc_biguint<7>(tmp_8_5_3_cast_fu_784_p1.read()) + sc_biguint<7>(tmp_8_5_2_cast_fu_780_p1.read()));
}

void digitrec_knn_vote::thread_tmp16_fu_802_p2() {
    tmp16_fu_802_p2 = (!tmp_8_5_4_cast_fu_788_p1.read().is_01() || !tmp_8_5_cast_fu_772_p1.read().is_01())? sc_lv<7>(): (sc_biguint<7>(tmp_8_5_4_cast_fu_788_p1.read()) + sc_biguint<7>(tmp_8_5_cast_fu_772_p1.read()));
}

void digitrec_knn_vote::thread_tmp17_cast_fu_636_p1() {
    tmp17_cast_fu_636_p1 = esl_zext<9,7>(tmp6_fu_630_p2.read());
}

void digitrec_knn_vote::thread_tmp17_fu_812_p2() {
    tmp17_fu_812_p2 = (!tmp_8_5_1_cast_fu_776_p1.read().is_01() || !tmp29_cast_fu_808_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(tmp_8_5_1_cast_fu_776_p1.read()) + sc_biguint<8>(tmp29_cast_fu_808_p1.read()));
}

void digitrec_knn_vote::thread_tmp18_cast_fu_656_p1() {
    tmp18_cast_fu_656_p1 = esl_zext<9,8>(tmp11_fu_650_p2.read());
}

void digitrec_knn_vote::thread_tmp18_fu_884_p2() {
    tmp18_fu_884_p2 = (!tmp_8_6_3_cast_fu_876_p1.read().is_01() || !tmp_8_6_2_cast_fu_872_p1.read().is_01())? sc_lv<7>(): (sc_biguint<7>(tmp_8_6_3_cast_fu_876_p1.read()) + sc_biguint<7>(tmp_8_6_2_cast_fu_872_p1.read()));
}

void digitrec_knn_vote::thread_tmp19_cast_fu_646_p1() {
    tmp19_cast_fu_646_p1 = esl_zext<8,7>(tmp10_fu_640_p2.read());
}

void digitrec_knn_vote::thread_tmp19_fu_894_p2() {
    tmp19_fu_894_p2 = (!tmp_8_6_4_cast_fu_880_p1.read().is_01() || !tmp_8_6_cast_fu_864_p1.read().is_01())? sc_lv<7>(): (sc_biguint<7>(tmp_8_6_4_cast_fu_880_p1.read()) + sc_biguint<7>(tmp_8_6_cast_fu_864_p1.read()));
}

void digitrec_knn_vote::thread_tmp1_fu_574_p2() {
    tmp1_fu_574_p2 = (!tmp_8_2_4_cast_fu_560_p1.read().is_01() || !tmp_8_2_cast_fu_544_p1.read().is_01())? sc_lv<7>(): (sc_biguint<7>(tmp_8_2_4_cast_fu_560_p1.read()) + sc_biguint<7>(tmp_8_2_cast_fu_544_p1.read()));
}

void digitrec_knn_vote::thread_tmp20_fu_904_p2() {
    tmp20_fu_904_p2 = (!tmp_8_6_1_cast_fu_868_p1.read().is_01() || !tmp34_cast_fu_900_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(tmp_8_6_1_cast_fu_868_p1.read()) + sc_biguint<8>(tmp34_cast_fu_900_p1.read()));
}

void digitrec_knn_vote::thread_tmp21_fu_950_p2() {
    tmp21_fu_950_p2 = (!tmp_8_7_3_cast_fu_942_p1.read().is_01() || !tmp_8_7_2_cast_fu_938_p1.read().is_01())? sc_lv<7>(): (sc_biguint<7>(tmp_8_7_3_cast_fu_942_p1.read()) + sc_biguint<7>(tmp_8_7_2_cast_fu_938_p1.read()));
}

void digitrec_knn_vote::thread_tmp22_cast_fu_706_p1() {
    tmp22_cast_fu_706_p1 = esl_zext<9,7>(tmp12_fu_700_p2.read());
}

void digitrec_knn_vote::thread_tmp22_fu_960_p2() {
    tmp22_fu_960_p2 = (!tmp_8_7_4_cast_fu_946_p1.read().is_01() || !tmp_8_7_cast_fu_930_p1.read().is_01())? sc_lv<7>(): (sc_biguint<7>(tmp_8_7_4_cast_fu_946_p1.read()) + sc_biguint<7>(tmp_8_7_cast_fu_930_p1.read()));
}

void digitrec_knn_vote::thread_tmp23_cast_fu_726_p1() {
    tmp23_cast_fu_726_p1 = esl_zext<9,8>(tmp14_fu_720_p2.read());
}

void digitrec_knn_vote::thread_tmp23_fu_970_p2() {
    tmp23_fu_970_p2 = (!tmp_8_7_1_cast_fu_934_p1.read().is_01() || !tmp39_cast_fu_966_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(tmp_8_7_1_cast_fu_934_p1.read()) + sc_biguint<8>(tmp39_cast_fu_966_p1.read()));
}

void digitrec_knn_vote::thread_tmp24_cast_fu_716_p1() {
    tmp24_cast_fu_716_p1 = esl_zext<8,7>(tmp13_fu_710_p2.read());
}

void digitrec_knn_vote::thread_tmp24_fu_1020_p2() {
    tmp24_fu_1020_p2 = (!tmp_8_8_3_cast_fu_1012_p1.read().is_01() || !tmp_8_8_2_cast_fu_1008_p1.read().is_01())? sc_lv<7>(): (sc_biguint<7>(tmp_8_8_3_cast_fu_1012_p1.read()) + sc_biguint<7>(tmp_8_8_2_cast_fu_1008_p1.read()));
}

void digitrec_knn_vote::thread_tmp25_fu_1030_p2() {
    tmp25_fu_1030_p2 = (!tmp_8_8_4_cast_fu_1016_p1.read().is_01() || !tmp_8_8_cast_fu_1000_p1.read().is_01())? sc_lv<7>(): (sc_biguint<7>(tmp_8_8_4_cast_fu_1016_p1.read()) + sc_biguint<7>(tmp_8_8_cast_fu_1000_p1.read()));
}

void digitrec_knn_vote::thread_tmp26_fu_1040_p2() {
    tmp26_fu_1040_p2 = (!tmp_8_8_1_cast_fu_1004_p1.read().is_01() || !tmp44_cast_fu_1036_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(tmp_8_8_1_cast_fu_1004_p1.read()) + sc_biguint<8>(tmp44_cast_fu_1036_p1.read()));
}

void digitrec_knn_vote::thread_tmp27_cast_fu_798_p1() {
    tmp27_cast_fu_798_p1 = esl_zext<9,7>(tmp15_fu_792_p2.read());
}

void digitrec_knn_vote::thread_tmp27_fu_1108_p2() {
    tmp27_fu_1108_p2 = (!tmp_8_9_1_cast_fu_1092_p1.read().is_01() || !tmp_8_9_cast_fu_1088_p1.read().is_01())? sc_lv<7>(): (sc_biguint<7>(tmp_8_9_1_cast_fu_1092_p1.read()) + sc_biguint<7>(tmp_8_9_cast_fu_1088_p1.read()));
}

void digitrec_knn_vote::thread_tmp28_cast_fu_818_p1() {
    tmp28_cast_fu_818_p1 = esl_zext<9,8>(tmp17_fu_812_p2.read());
}

void digitrec_knn_vote::thread_tmp28_fu_1118_p2() {
    tmp28_fu_1118_p2 = (!tmp_8_9_4_cast_fu_1104_p1.read().is_01() || !tmp_8_9_3_cast_fu_1100_p1.read().is_01())? sc_lv<7>(): (sc_biguint<7>(tmp_8_9_4_cast_fu_1104_p1.read()) + sc_biguint<7>(tmp_8_9_3_cast_fu_1100_p1.read()));
}

void digitrec_knn_vote::thread_tmp29_cast_fu_808_p1() {
    tmp29_cast_fu_808_p1 = esl_zext<8,7>(tmp16_fu_802_p2.read());
}

void digitrec_knn_vote::thread_tmp29_fu_1128_p2() {
    tmp29_fu_1128_p2 = (!tmp_8_9_2_cast_fu_1096_p1.read().is_01() || !tmp47_cast_fu_1124_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(tmp_8_9_2_cast_fu_1096_p1.read()) + sc_biguint<8>(tmp47_cast_fu_1124_p1.read()));
}

void digitrec_knn_vote::thread_tmp2_cast_fu_444_p1() {
    tmp2_cast_fu_444_p1 = esl_zext<9,7>(tmp2_fu_438_p2.read());
}

void digitrec_knn_vote::thread_tmp2_fu_438_p2() {
    tmp2_fu_438_p2 = (!tmp_8_0_3_cast_fu_430_p1.read().is_01() || !tmp_8_0_2_cast_fu_426_p1.read().is_01())? sc_lv<7>(): (sc_biguint<7>(tmp_8_0_3_cast_fu_430_p1.read()) + sc_biguint<7>(tmp_8_0_2_cast_fu_426_p1.read()));
}

void digitrec_knn_vote::thread_tmp32_cast_fu_890_p1() {
    tmp32_cast_fu_890_p1 = esl_zext<9,7>(tmp18_fu_884_p2.read());
}

void digitrec_knn_vote::thread_tmp33_cast_fu_910_p1() {
    tmp33_cast_fu_910_p1 = esl_zext<9,8>(tmp20_fu_904_p2.read());
}

void digitrec_knn_vote::thread_tmp34_cast_fu_900_p1() {
    tmp34_cast_fu_900_p1 = esl_zext<8,7>(tmp19_fu_894_p2.read());
}

void digitrec_knn_vote::thread_tmp37_cast_fu_956_p1() {
    tmp37_cast_fu_956_p1 = esl_zext<9,7>(tmp21_fu_950_p2.read());
}

void digitrec_knn_vote::thread_tmp38_cast_fu_976_p1() {
    tmp38_cast_fu_976_p1 = esl_zext<9,8>(tmp23_fu_970_p2.read());
}

void digitrec_knn_vote::thread_tmp39_cast_fu_966_p1() {
    tmp39_cast_fu_966_p1 = esl_zext<8,7>(tmp22_fu_960_p2.read());
}

void digitrec_knn_vote::thread_tmp3_cast_fu_464_p1() {
    tmp3_cast_fu_464_p1 = esl_zext<9,8>(tmp3_fu_458_p2.read());
}

void digitrec_knn_vote::thread_tmp3_fu_458_p2() {
    tmp3_fu_458_p2 = (!tmp_8_0_1_cast_fu_422_p1.read().is_01() || !tmp4_cast_fu_454_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(tmp_8_0_1_cast_fu_422_p1.read()) + sc_biguint<8>(tmp4_cast_fu_454_p1.read()));
}

void digitrec_knn_vote::thread_tmp42_cast_fu_1026_p1() {
    tmp42_cast_fu_1026_p1 = esl_zext<9,7>(tmp24_fu_1020_p2.read());
}

void digitrec_knn_vote::thread_tmp43_cast_fu_1046_p1() {
    tmp43_cast_fu_1046_p1 = esl_zext<9,8>(tmp26_fu_1040_p2.read());
}

void digitrec_knn_vote::thread_tmp44_cast_fu_1036_p1() {
    tmp44_cast_fu_1036_p1 = esl_zext<8,7>(tmp25_fu_1030_p2.read());
}

void digitrec_knn_vote::thread_tmp45_cast_fu_1114_p1() {
    tmp45_cast_fu_1114_p1 = esl_zext<9,7>(tmp27_fu_1108_p2.read());
}

void digitrec_knn_vote::thread_tmp46_cast_fu_1134_p1() {
    tmp46_cast_fu_1134_p1 = esl_zext<9,8>(tmp29_fu_1128_p2.read());
}

void digitrec_knn_vote::thread_tmp47_cast_fu_1124_p1() {
    tmp47_cast_fu_1124_p1 = esl_zext<8,7>(tmp28_fu_1118_p2.read());
}

void digitrec_knn_vote::thread_tmp4_cast_fu_454_p1() {
    tmp4_cast_fu_454_p1 = esl_zext<8,7>(tmp4_fu_448_p2.read());
}

void digitrec_knn_vote::thread_tmp4_fu_448_p2() {
    tmp4_fu_448_p2 = (!tmp_8_0_4_cast_fu_434_p1.read().is_01() || !tmp_8_cast_fu_418_p1.read().is_01())? sc_lv<7>(): (sc_biguint<7>(tmp_8_0_4_cast_fu_434_p1.read()) + sc_biguint<7>(tmp_8_cast_fu_418_p1.read()));
}

void digitrec_knn_vote::thread_tmp5_fu_584_p2() {
    tmp5_fu_584_p2 = (!tmp_8_2_1_cast_fu_548_p1.read().is_01() || !tmp14_cast_fu_580_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(tmp_8_2_1_cast_fu_548_p1.read()) + sc_biguint<8>(tmp14_cast_fu_580_p1.read()));
}

void digitrec_knn_vote::thread_tmp6_fu_630_p2() {
    tmp6_fu_630_p2 = (!tmp_8_3_3_cast_fu_622_p1.read().is_01() || !tmp_8_3_2_cast_fu_618_p1.read().is_01())? sc_lv<7>(): (sc_biguint<7>(tmp_8_3_3_cast_fu_622_p1.read()) + sc_biguint<7>(tmp_8_3_2_cast_fu_618_p1.read()));
}

void digitrec_knn_vote::thread_tmp7_cast_fu_500_p1() {
    tmp7_cast_fu_500_p1 = esl_zext<9,7>(tmp7_fu_494_p2.read());
}

void digitrec_knn_vote::thread_tmp7_fu_494_p2() {
    tmp7_fu_494_p2 = (!tmp_8_1_3_cast_fu_486_p1.read().is_01() || !tmp_8_1_2_cast_fu_482_p1.read().is_01())? sc_lv<7>(): (sc_biguint<7>(tmp_8_1_3_cast_fu_486_p1.read()) + sc_biguint<7>(tmp_8_1_2_cast_fu_482_p1.read()));
}

void digitrec_knn_vote::thread_tmp8_cast_fu_520_p1() {
    tmp8_cast_fu_520_p1 = esl_zext<9,8>(tmp8_fu_514_p2.read());
}

void digitrec_knn_vote::thread_tmp8_fu_514_p2() {
    tmp8_fu_514_p2 = (!tmp_8_1_1_cast_fu_478_p1.read().is_01() || !tmp9_cast_fu_510_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(tmp_8_1_1_cast_fu_478_p1.read()) + sc_biguint<8>(tmp9_cast_fu_510_p1.read()));
}

void digitrec_knn_vote::thread_tmp9_cast_fu_510_p1() {
    tmp9_cast_fu_510_p1 = esl_zext<8,7>(tmp9_fu_504_p2.read());
}

void digitrec_knn_vote::thread_tmp9_fu_504_p2() {
    tmp9_fu_504_p2 = (!tmp_8_1_4_cast_fu_490_p1.read().is_01() || !tmp_8_1_cast_fu_474_p1.read().is_01())? sc_lv<7>(): (sc_biguint<7>(tmp_8_1_4_cast_fu_490_p1.read()) + sc_biguint<7>(tmp_8_1_cast_fu_474_p1.read()));
}

void digitrec_knn_vote::thread_tmp_6_1_fu_530_p2() {
    tmp_6_1_fu_530_p2 = (!sum_1_4_fu_524_p2.read().is_01() || !sum_0_4_fu_468_p2.read().is_01())? sc_lv<1>(): (sc_biguint<9>(sum_1_4_fu_524_p2.read()) < sc_biguint<9>(sum_0_4_fu_468_p2.read()));
}

void digitrec_knn_vote::thread_tmp_6_2_fu_600_p2() {
    tmp_6_2_fu_600_p2 = (!sum_2_4_reg_1183.read().is_01() || !min_2_min_1_reg_1177.read().is_01())? sc_lv<1>(): (sc_biguint<9>(sum_2_4_reg_1183.read()) < sc_biguint<9>(min_2_min_1_reg_1177.read()));
}

void digitrec_knn_vote::thread_tmp_6_3_fu_666_p2() {
    tmp_6_3_fu_666_p2 = (!sum_3_4_fu_660_p2.read().is_01() || !min_2_min_2_fu_604_p3.read().is_01())? sc_lv<1>(): (sc_biguint<9>(sum_3_4_fu_660_p2.read()) < sc_biguint<9>(min_2_min_2_fu_604_p3.read()));
}

void digitrec_knn_vote::thread_tmp_6_4_fu_762_p2() {
    tmp_6_4_fu_762_p2 = (!sum_4_4_reg_1206.read().is_01() || !min_2_min_3_reg_1200.read().is_01())? sc_lv<1>(): (sc_biguint<9>(sum_4_4_reg_1206.read()) < sc_biguint<9>(min_2_min_3_reg_1200.read()));
}

void digitrec_knn_vote::thread_tmp_6_5_fu_828_p2() {
    tmp_6_5_fu_828_p2 = (!sum_5_4_fu_822_p2.read().is_01() || !min_2_min_4_fu_766_p3.read().is_01())? sc_lv<1>(): (sc_biguint<9>(sum_5_4_fu_822_p2.read()) < sc_biguint<9>(min_2_min_4_fu_766_p3.read()));
}

void digitrec_knn_vote::thread_tmp_6_6_fu_920_p2() {
    tmp_6_6_fu_920_p2 = (!sum_6_4_reg_1223.read().is_01() || !min_2_min_5_reg_1217.read().is_01())? sc_lv<1>(): (sc_biguint<9>(sum_6_4_reg_1223.read()) < sc_biguint<9>(min_2_min_5_reg_1217.read()));
}

void digitrec_knn_vote::thread_tmp_6_7_fu_986_p2() {
    tmp_6_7_fu_986_p2 = (!sum_7_4_fu_980_p2.read().is_01() || !min_2_min_6_fu_924_p3.read().is_01())? sc_lv<1>(): (sc_biguint<9>(sum_7_4_fu_980_p2.read()) < sc_biguint<9>(min_2_min_6_fu_924_p3.read()));
}

void digitrec_knn_vote::thread_tmp_6_8_fu_1078_p2() {
    tmp_6_8_fu_1078_p2 = (!sum_8_4_reg_1246.read().is_01() || !min_2_min_7_reg_1240.read().is_01())? sc_lv<1>(): (sc_biguint<9>(sum_8_4_reg_1246.read()) < sc_biguint<9>(min_2_min_7_reg_1240.read()));
}

void digitrec_knn_vote::thread_tmp_6_9_fu_1144_p2() {
    tmp_6_9_fu_1144_p2 = (!sum_9_4_fu_1138_p2.read().is_01() || !min_2_min_8_fu_1082_p3.read().is_01())? sc_lv<1>(): (sc_biguint<9>(sum_9_4_fu_1138_p2.read()) < sc_biguint<9>(min_2_min_8_fu_1082_p3.read()));
}

void digitrec_knn_vote::thread_tmp_6_fu_842_p2() {
    tmp_6_fu_842_p2 = (tmp_6_5_fu_828_p2.read() | tmp_6_4_fu_762_p2.read());
}

void digitrec_knn_vote::thread_tmp_7_fu_1063_p2() {
    tmp_7_fu_1063_p2 = (tmp_6_7_reg_1234.read() | tmp_6_6_reg_1229.read());
}

void digitrec_knn_vote::thread_tmp_8_0_1_cast_fu_422_p1() {
    tmp_8_0_1_cast_fu_422_p1 = esl_zext<8,6>(knn_set_0_1_V_read.read());
}

void digitrec_knn_vote::thread_tmp_8_0_2_cast_fu_426_p1() {
    tmp_8_0_2_cast_fu_426_p1 = esl_zext<7,6>(knn_set_0_2_V_read.read());
}

void digitrec_knn_vote::thread_tmp_8_0_3_cast_fu_430_p1() {
    tmp_8_0_3_cast_fu_430_p1 = esl_zext<7,6>(knn_set_0_3_V_read.read());
}

void digitrec_knn_vote::thread_tmp_8_0_4_cast_fu_434_p1() {
    tmp_8_0_4_cast_fu_434_p1 = esl_zext<7,6>(knn_set_0_4_V_read.read());
}

void digitrec_knn_vote::thread_tmp_8_1_1_cast_fu_478_p1() {
    tmp_8_1_1_cast_fu_478_p1 = esl_zext<8,6>(knn_set_1_1_V_read.read());
}

void digitrec_knn_vote::thread_tmp_8_1_2_cast_fu_482_p1() {
    tmp_8_1_2_cast_fu_482_p1 = esl_zext<7,6>(knn_set_1_2_V_read.read());
}

void digitrec_knn_vote::thread_tmp_8_1_3_cast_fu_486_p1() {
    tmp_8_1_3_cast_fu_486_p1 = esl_zext<7,6>(knn_set_1_3_V_read.read());
}

void digitrec_knn_vote::thread_tmp_8_1_4_cast_fu_490_p1() {
    tmp_8_1_4_cast_fu_490_p1 = esl_zext<7,6>(knn_set_1_4_V_read.read());
}

void digitrec_knn_vote::thread_tmp_8_1_cast_fu_474_p1() {
    tmp_8_1_cast_fu_474_p1 = esl_zext<7,6>(knn_set_1_0_V_read.read());
}

void digitrec_knn_vote::thread_tmp_8_2_1_cast_fu_548_p1() {
    tmp_8_2_1_cast_fu_548_p1 = esl_zext<8,6>(knn_set_2_1_V_read.read());
}

void digitrec_knn_vote::thread_tmp_8_2_2_cast_fu_552_p1() {
    tmp_8_2_2_cast_fu_552_p1 = esl_zext<7,6>(knn_set_2_2_V_read.read());
}

void digitrec_knn_vote::thread_tmp_8_2_3_cast_fu_556_p1() {
    tmp_8_2_3_cast_fu_556_p1 = esl_zext<7,6>(knn_set_2_3_V_read.read());
}

void digitrec_knn_vote::thread_tmp_8_2_4_cast_fu_560_p1() {
    tmp_8_2_4_cast_fu_560_p1 = esl_zext<7,6>(knn_set_2_4_V_read.read());
}

void digitrec_knn_vote::thread_tmp_8_2_cast_fu_544_p1() {
    tmp_8_2_cast_fu_544_p1 = esl_zext<7,6>(knn_set_2_0_V_read.read());
}

void digitrec_knn_vote::thread_tmp_8_3_1_cast_fu_614_p1() {
    tmp_8_3_1_cast_fu_614_p1 = esl_zext<8,6>(knn_set_3_1_V_read.read());
}

void digitrec_knn_vote::thread_tmp_8_3_2_cast_fu_618_p1() {
    tmp_8_3_2_cast_fu_618_p1 = esl_zext<7,6>(knn_set_3_2_V_read.read());
}

void digitrec_knn_vote::thread_tmp_8_3_3_cast_fu_622_p1() {
    tmp_8_3_3_cast_fu_622_p1 = esl_zext<7,6>(knn_set_3_3_V_read.read());
}

void digitrec_knn_vote::thread_tmp_8_3_4_cast_fu_626_p1() {
    tmp_8_3_4_cast_fu_626_p1 = esl_zext<7,6>(knn_set_3_4_V_read.read());
}

void digitrec_knn_vote::thread_tmp_8_3_cast_fu_610_p1() {
    tmp_8_3_cast_fu_610_p1 = esl_zext<7,6>(knn_set_3_0_V_read.read());
}

void digitrec_knn_vote::thread_tmp_8_4_1_cast_fu_684_p1() {
    tmp_8_4_1_cast_fu_684_p1 = esl_zext<8,6>(knn_set_4_1_V_read.read());
}

void digitrec_knn_vote::thread_tmp_8_4_2_cast_fu_688_p1() {
    tmp_8_4_2_cast_fu_688_p1 = esl_zext<7,6>(knn_set_4_2_V_read.read());
}

void digitrec_knn_vote::thread_tmp_8_4_3_cast_fu_692_p1() {
    tmp_8_4_3_cast_fu_692_p1 = esl_zext<7,6>(knn_set_4_3_V_read.read());
}

void digitrec_knn_vote::thread_tmp_8_4_4_cast_fu_696_p1() {
    tmp_8_4_4_cast_fu_696_p1 = esl_zext<7,6>(knn_set_4_4_V_read.read());
}

void digitrec_knn_vote::thread_tmp_8_4_cast_fu_680_p1() {
    tmp_8_4_cast_fu_680_p1 = esl_zext<7,6>(knn_set_4_0_V_read.read());
}

void digitrec_knn_vote::thread_tmp_8_5_1_cast_fu_776_p1() {
    tmp_8_5_1_cast_fu_776_p1 = esl_zext<8,6>(knn_set_5_1_V_read.read());
}

void digitrec_knn_vote::thread_tmp_8_5_2_cast_fu_780_p1() {
    tmp_8_5_2_cast_fu_780_p1 = esl_zext<7,6>(knn_set_5_2_V_read.read());
}

void digitrec_knn_vote::thread_tmp_8_5_3_cast_fu_784_p1() {
    tmp_8_5_3_cast_fu_784_p1 = esl_zext<7,6>(knn_set_5_3_V_read.read());
}

void digitrec_knn_vote::thread_tmp_8_5_4_cast_fu_788_p1() {
    tmp_8_5_4_cast_fu_788_p1 = esl_zext<7,6>(knn_set_5_4_V_read.read());
}

void digitrec_knn_vote::thread_tmp_8_5_cast_fu_772_p1() {
    tmp_8_5_cast_fu_772_p1 = esl_zext<7,6>(knn_set_5_0_V_read.read());
}

void digitrec_knn_vote::thread_tmp_8_6_1_cast_fu_868_p1() {
    tmp_8_6_1_cast_fu_868_p1 = esl_zext<8,6>(knn_set_6_1_V_read.read());
}

void digitrec_knn_vote::thread_tmp_8_6_2_cast_fu_872_p1() {
    tmp_8_6_2_cast_fu_872_p1 = esl_zext<7,6>(knn_set_6_2_V_read.read());
}

void digitrec_knn_vote::thread_tmp_8_6_3_cast_fu_876_p1() {
    tmp_8_6_3_cast_fu_876_p1 = esl_zext<7,6>(knn_set_6_3_V_read.read());
}

void digitrec_knn_vote::thread_tmp_8_6_4_cast_fu_880_p1() {
    tmp_8_6_4_cast_fu_880_p1 = esl_zext<7,6>(knn_set_6_4_V_read.read());
}

void digitrec_knn_vote::thread_tmp_8_6_cast_fu_864_p1() {
    tmp_8_6_cast_fu_864_p1 = esl_zext<7,6>(knn_set_6_0_V_read.read());
}

void digitrec_knn_vote::thread_tmp_8_7_1_cast_fu_934_p1() {
    tmp_8_7_1_cast_fu_934_p1 = esl_zext<8,6>(knn_set_7_1_V_read.read());
}

void digitrec_knn_vote::thread_tmp_8_7_2_cast_fu_938_p1() {
    tmp_8_7_2_cast_fu_938_p1 = esl_zext<7,6>(knn_set_7_2_V_read.read());
}

void digitrec_knn_vote::thread_tmp_8_7_3_cast_fu_942_p1() {
    tmp_8_7_3_cast_fu_942_p1 = esl_zext<7,6>(knn_set_7_3_V_read.read());
}

void digitrec_knn_vote::thread_tmp_8_7_4_cast_fu_946_p1() {
    tmp_8_7_4_cast_fu_946_p1 = esl_zext<7,6>(knn_set_7_4_V_read.read());
}

void digitrec_knn_vote::thread_tmp_8_7_cast_fu_930_p1() {
    tmp_8_7_cast_fu_930_p1 = esl_zext<7,6>(knn_set_7_0_V_read.read());
}

void digitrec_knn_vote::thread_tmp_8_8_1_cast_fu_1004_p1() {
    tmp_8_8_1_cast_fu_1004_p1 = esl_zext<8,6>(knn_set_8_1_V_read.read());
}

void digitrec_knn_vote::thread_tmp_8_8_2_cast_fu_1008_p1() {
    tmp_8_8_2_cast_fu_1008_p1 = esl_zext<7,6>(knn_set_8_2_V_read.read());
}

void digitrec_knn_vote::thread_tmp_8_8_3_cast_fu_1012_p1() {
    tmp_8_8_3_cast_fu_1012_p1 = esl_zext<7,6>(knn_set_8_3_V_read.read());
}

void digitrec_knn_vote::thread_tmp_8_8_4_cast_fu_1016_p1() {
    tmp_8_8_4_cast_fu_1016_p1 = esl_zext<7,6>(knn_set_8_4_V_read.read());
}

void digitrec_knn_vote::thread_tmp_8_8_cast_fu_1000_p1() {
    tmp_8_8_cast_fu_1000_p1 = esl_zext<7,6>(knn_set_8_0_V_read.read());
}

void digitrec_knn_vote::thread_tmp_8_9_1_cast_fu_1092_p1() {
    tmp_8_9_1_cast_fu_1092_p1 = esl_zext<7,6>(knn_set_9_1_V_read.read());
}

void digitrec_knn_vote::thread_tmp_8_9_2_cast_fu_1096_p1() {
    tmp_8_9_2_cast_fu_1096_p1 = esl_zext<8,6>(knn_set_9_2_V_read.read());
}

void digitrec_knn_vote::thread_tmp_8_9_3_cast_fu_1100_p1() {
    tmp_8_9_3_cast_fu_1100_p1 = esl_zext<7,6>(knn_set_9_3_V_read.read());
}

void digitrec_knn_vote::thread_tmp_8_9_4_cast_fu_1104_p1() {
    tmp_8_9_4_cast_fu_1104_p1 = esl_zext<7,6>(knn_set_9_4_V_read.read());
}

void digitrec_knn_vote::thread_tmp_8_9_cast_fu_1088_p1() {
    tmp_8_9_cast_fu_1088_p1 = esl_zext<7,6>(knn_set_9_0_V_read.read());
}

void digitrec_knn_vote::thread_tmp_8_cast_fu_418_p1() {
    tmp_8_cast_fu_418_p1 = esl_zext<7,6>(knn_set_0_0_V_read.read());
}

void digitrec_knn_vote::thread_tmp_9_fu_1158_p2() {
    tmp_9_fu_1158_p2 = (tmp_6_9_fu_1144_p2.read() | tmp_6_8_fu_1078_p2.read());
}

void digitrec_knn_vote::thread_tmp_fu_564_p2() {
    tmp_fu_564_p2 = (!tmp_8_2_3_cast_fu_556_p1.read().is_01() || !tmp_8_2_2_cast_fu_552_p1.read().is_01())? sc_lv<7>(): (sc_biguint<7>(tmp_8_2_3_cast_fu_556_p1.read()) + sc_biguint<7>(tmp_8_2_2_cast_fu_552_p1.read()));
}

void digitrec_knn_vote::thread_tmp_s_fu_746_p2() {
    tmp_s_fu_746_p2 = (tmp_6_3_reg_1194.read() | tmp_6_2_reg_1189.read());
}

void digitrec_knn_vote::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 2 : 
            ap_NS_fsm = ap_ST_st3_fsm_2;
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_st4_fsm_3;
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_st5_fsm_4;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_st1_fsm_0;
            break;
        default : 
            ap_NS_fsm = "XXXXX";
            break;
    }
}

}

