// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "digitrec_knn_vote.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic digitrec_knn_vote::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic digitrec_knn_vote::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<4> digitrec_knn_vote::ap_ST_st1_fsm_0 = "1";
const sc_lv<4> digitrec_knn_vote::ap_ST_st2_fsm_1 = "10";
const sc_lv<4> digitrec_knn_vote::ap_ST_st3_fsm_2 = "100";
const sc_lv<4> digitrec_knn_vote::ap_ST_st4_fsm_3 = "1000";
const sc_lv<32> digitrec_knn_vote::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> digitrec_knn_vote::ap_const_lv1_1 = "1";
const sc_lv<32> digitrec_knn_vote::ap_const_lv32_1 = "1";
const sc_lv<1> digitrec_knn_vote::ap_const_lv1_0 = "0";
const sc_lv<32> digitrec_knn_vote::ap_const_lv32_2 = "10";
const sc_lv<32> digitrec_knn_vote::ap_const_lv32_3 = "11";
const sc_lv<4> digitrec_knn_vote::ap_const_lv4_0 = "0000";
const sc_lv<32> digitrec_knn_vote::ap_const_lv32_7FFFFFFF = "1111111111111111111111111111111";
const sc_lv<3> digitrec_knn_vote::ap_const_lv3_0 = "000";
const sc_lv<9> digitrec_knn_vote::ap_const_lv9_0 = "000000000";
const sc_lv<4> digitrec_knn_vote::ap_const_lv4_A = "1010";
const sc_lv<4> digitrec_knn_vote::ap_const_lv4_1 = "1";
const sc_lv<2> digitrec_knn_vote::ap_const_lv2_0 = "00";
const sc_lv<3> digitrec_knn_vote::ap_const_lv3_5 = "101";
const sc_lv<3> digitrec_knn_vote::ap_const_lv3_1 = "1";

digitrec_knn_vote::digitrec_knn_vote(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_agg_result_V_0_agg_result_V_s_fu_183_p3);
    sensitive << ( agg_result_V_s_reg_54 );
    sensitive << ( i_val_V_reg_66 );
    sensitive << ( tmp_6_fu_177_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( exitcond1_fu_113_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( exitcond1_fu_113_p2 );

    SC_METHOD(thread_ap_return);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( exitcond1_fu_113_p2 );
    sensitive << ( agg_result_V_s_reg_54 );
    sensitive << ( ap_return_preg );

    SC_METHOD(thread_ap_sig_21);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_40);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_55);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_75);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_cseq_ST_st1_fsm_0);
    sensitive << ( ap_sig_21 );

    SC_METHOD(thread_ap_sig_cseq_ST_st2_fsm_1);
    sensitive << ( ap_sig_40 );

    SC_METHOD(thread_ap_sig_cseq_ST_st3_fsm_2);
    sensitive << ( ap_sig_55 );

    SC_METHOD(thread_ap_sig_cseq_ST_st4_fsm_3);
    sensitive << ( ap_sig_75 );

    SC_METHOD(thread_exitcond1_fu_113_p2);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( i_val_V_reg_66 );

    SC_METHOD(thread_exitcond_fu_147_p2);
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( p_1_reg_90 );

    SC_METHOD(thread_i_V_fu_119_p2);
    sensitive << ( i_val_V_reg_66 );

    SC_METHOD(thread_j_V_fu_153_p2);
    sensitive << ( p_1_reg_90 );

    SC_METHOD(thread_knn_set_V_address0);
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( tmp_12_cast_fu_168_p1 );

    SC_METHOD(thread_knn_set_V_ce0);
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );

    SC_METHOD(thread_min_1_cast_fu_173_p1);
    sensitive << ( min_1_reg_101 );

    SC_METHOD(thread_min_2_min_fu_191_p3);
    sensitive << ( min_reg_78 );
    sensitive << ( min_1_cast_fu_173_p1 );
    sensitive << ( tmp_6_fu_177_p2 );

    SC_METHOD(thread_p_shl_cast_fu_137_p1);
    sensitive << ( tmp_s_fu_129_p3 );

    SC_METHOD(thread_sum_fu_203_p2);
    sensitive << ( min_1_reg_101 );
    sensitive << ( tmp_8_cast_fu_199_p1 );

    SC_METHOD(thread_tmp_12_cast_fu_168_p1);
    sensitive << ( tmp_2_fu_163_p2 );

    SC_METHOD(thread_tmp_1_fu_141_p2);
    sensitive << ( tmp_cast_fu_125_p1 );
    sensitive << ( p_shl_cast_fu_137_p1 );

    SC_METHOD(thread_tmp_2_fu_163_p2);
    sensitive << ( tmp_1_reg_217 );
    sensitive << ( tmp_7_cast_fu_159_p1 );

    SC_METHOD(thread_tmp_6_fu_177_p2);
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( exitcond_fu_147_p2 );
    sensitive << ( min_reg_78 );
    sensitive << ( min_1_cast_fu_173_p1 );

    SC_METHOD(thread_tmp_7_cast_fu_159_p1);
    sensitive << ( p_1_reg_90 );

    SC_METHOD(thread_tmp_8_cast_fu_199_p1);
    sensitive << ( knn_set_V_q0 );

    SC_METHOD(thread_tmp_cast_fu_125_p1);
    sensitive << ( i_val_V_reg_66 );

    SC_METHOD(thread_tmp_s_fu_129_p3);
    sensitive << ( i_val_V_reg_66 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond1_fu_113_p2 );
    sensitive << ( exitcond_fu_147_p2 );

    ap_CS_fsm = "0001";
    ap_return_preg = "0000";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "digitrec_knn_vote_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, knn_set_V_address0, "(port)knn_set_V_address0");
    sc_trace(mVcdFile, knn_set_V_ce0, "(port)knn_set_V_ce0");
    sc_trace(mVcdFile, knn_set_V_q0, "(port)knn_set_V_q0");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st1_fsm_0, "ap_sig_cseq_ST_st1_fsm_0");
    sc_trace(mVcdFile, ap_sig_21, "ap_sig_21");
    sc_trace(mVcdFile, i_V_fu_119_p2, "i_V_fu_119_p2");
    sc_trace(mVcdFile, i_V_reg_212, "i_V_reg_212");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st2_fsm_1, "ap_sig_cseq_ST_st2_fsm_1");
    sc_trace(mVcdFile, ap_sig_40, "ap_sig_40");
    sc_trace(mVcdFile, tmp_1_fu_141_p2, "tmp_1_fu_141_p2");
    sc_trace(mVcdFile, tmp_1_reg_217, "tmp_1_reg_217");
    sc_trace(mVcdFile, exitcond1_fu_113_p2, "exitcond1_fu_113_p2");
    sc_trace(mVcdFile, j_V_fu_153_p2, "j_V_fu_153_p2");
    sc_trace(mVcdFile, j_V_reg_225, "j_V_reg_225");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st3_fsm_2, "ap_sig_cseq_ST_st3_fsm_2");
    sc_trace(mVcdFile, ap_sig_55, "ap_sig_55");
    sc_trace(mVcdFile, exitcond_fu_147_p2, "exitcond_fu_147_p2");
    sc_trace(mVcdFile, agg_result_V_0_agg_result_V_s_fu_183_p3, "agg_result_V_0_agg_result_V_s_fu_183_p3");
    sc_trace(mVcdFile, min_2_min_fu_191_p3, "min_2_min_fu_191_p3");
    sc_trace(mVcdFile, sum_fu_203_p2, "sum_fu_203_p2");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st4_fsm_3, "ap_sig_cseq_ST_st4_fsm_3");
    sc_trace(mVcdFile, ap_sig_75, "ap_sig_75");
    sc_trace(mVcdFile, agg_result_V_s_reg_54, "agg_result_V_s_reg_54");
    sc_trace(mVcdFile, i_val_V_reg_66, "i_val_V_reg_66");
    sc_trace(mVcdFile, min_reg_78, "min_reg_78");
    sc_trace(mVcdFile, p_1_reg_90, "p_1_reg_90");
    sc_trace(mVcdFile, min_1_reg_101, "min_1_reg_101");
    sc_trace(mVcdFile, tmp_12_cast_fu_168_p1, "tmp_12_cast_fu_168_p1");
    sc_trace(mVcdFile, tmp_s_fu_129_p3, "tmp_s_fu_129_p3");
    sc_trace(mVcdFile, tmp_cast_fu_125_p1, "tmp_cast_fu_125_p1");
    sc_trace(mVcdFile, p_shl_cast_fu_137_p1, "p_shl_cast_fu_137_p1");
    sc_trace(mVcdFile, tmp_7_cast_fu_159_p1, "tmp_7_cast_fu_159_p1");
    sc_trace(mVcdFile, tmp_2_fu_163_p2, "tmp_2_fu_163_p2");
    sc_trace(mVcdFile, min_1_cast_fu_173_p1, "min_1_cast_fu_173_p1");
    sc_trace(mVcdFile, tmp_6_fu_177_p2, "tmp_6_fu_177_p2");
    sc_trace(mVcdFile, tmp_8_cast_fu_199_p1, "tmp_8_cast_fu_199_p1");
    sc_trace(mVcdFile, ap_return_preg, "ap_return_preg");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

digitrec_knn_vote::~digitrec_knn_vote() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void digitrec_knn_vote::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_preg = ap_const_lv4_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
             !esl_seteq<1,1,1>(exitcond1_fu_113_p2.read(), ap_const_lv1_0))) {
            ap_return_preg = agg_result_V_s_reg_54.read();
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_147_p2.read()))) {
        i_val_V_reg_66 = i_V_reg_212.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        i_val_V_reg_66 = ap_const_lv4_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        min_1_reg_101 = sum_fu_203_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                esl_seteq<1,1,1>(exitcond1_fu_113_p2.read(), ap_const_lv1_0))) {
        min_1_reg_101 = ap_const_lv9_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_147_p2.read()))) {
        min_reg_78 = min_2_min_fu_191_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        min_reg_78 = ap_const_lv32_7FFFFFFF;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        p_1_reg_90 = j_V_reg_225.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                esl_seteq<1,1,1>(exitcond1_fu_113_p2.read(), ap_const_lv1_0))) {
        p_1_reg_90 = ap_const_lv3_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_147_p2.read()))) {
        agg_result_V_s_reg_54 = agg_result_V_0_agg_result_V_s_fu_183_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        i_V_reg_212 = i_V_fu_119_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        j_V_reg_225 = j_V_fu_153_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && esl_seteq<1,1,1>(exitcond1_fu_113_p2.read(), ap_const_lv1_0))) {
        tmp_1_reg_217 = tmp_1_fu_141_p2.read();
    }
}

void digitrec_knn_vote::thread_agg_result_V_0_agg_result_V_s_fu_183_p3() {
    agg_result_V_0_agg_result_V_s_fu_183_p3 = (!tmp_6_fu_177_p2.read()[0].is_01())? sc_lv<4>(): ((tmp_6_fu_177_p2.read()[0].to_bool())? i_val_V_reg_66.read(): agg_result_V_s_reg_54.read());
}

void digitrec_knn_vote::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
          !esl_seteq<1,1,1>(exitcond1_fu_113_p2.read(), ap_const_lv1_0)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void digitrec_knn_vote::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void digitrec_knn_vote::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
         !esl_seteq<1,1,1>(exitcond1_fu_113_p2.read(), ap_const_lv1_0))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void digitrec_knn_vote::thread_ap_return() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
         !esl_seteq<1,1,1>(exitcond1_fu_113_p2.read(), ap_const_lv1_0))) {
        ap_return = agg_result_V_s_reg_54.read();
    } else {
        ap_return = ap_return_preg.read();
    }
}

void digitrec_knn_vote::thread_ap_sig_21() {
    ap_sig_21 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void digitrec_knn_vote::thread_ap_sig_40() {
    ap_sig_40 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(1, 1));
}

void digitrec_knn_vote::thread_ap_sig_55() {
    ap_sig_55 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(2, 2));
}

void digitrec_knn_vote::thread_ap_sig_75() {
    ap_sig_75 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(3, 3));
}

void digitrec_knn_vote::thread_ap_sig_cseq_ST_st1_fsm_0() {
    if (ap_sig_21.read()) {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    }
}

void digitrec_knn_vote::thread_ap_sig_cseq_ST_st2_fsm_1() {
    if (ap_sig_40.read()) {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    }
}

void digitrec_knn_vote::thread_ap_sig_cseq_ST_st3_fsm_2() {
    if (ap_sig_55.read()) {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_0;
    }
}

void digitrec_knn_vote::thread_ap_sig_cseq_ST_st4_fsm_3() {
    if (ap_sig_75.read()) {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_0;
    }
}

void digitrec_knn_vote::thread_exitcond1_fu_113_p2() {
    exitcond1_fu_113_p2 = (!i_val_V_reg_66.read().is_01() || !ap_const_lv4_A.is_01())? sc_lv<1>(): sc_lv<1>(i_val_V_reg_66.read() == ap_const_lv4_A);
}

void digitrec_knn_vote::thread_exitcond_fu_147_p2() {
    exitcond_fu_147_p2 = (!p_1_reg_90.read().is_01() || !ap_const_lv3_5.is_01())? sc_lv<1>(): sc_lv<1>(p_1_reg_90.read() == ap_const_lv3_5);
}

void digitrec_knn_vote::thread_i_V_fu_119_p2() {
    i_V_fu_119_p2 = (!i_val_V_reg_66.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(i_val_V_reg_66.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void digitrec_knn_vote::thread_j_V_fu_153_p2() {
    j_V_fu_153_p2 = (!p_1_reg_90.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(p_1_reg_90.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void digitrec_knn_vote::thread_knn_set_V_address0() {
    knn_set_V_address0 =  (sc_lv<6>) (tmp_12_cast_fu_168_p1.read());
}

void digitrec_knn_vote::thread_knn_set_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        knn_set_V_ce0 = ap_const_logic_1;
    } else {
        knn_set_V_ce0 = ap_const_logic_0;
    }
}

void digitrec_knn_vote::thread_min_1_cast_fu_173_p1() {
    min_1_cast_fu_173_p1 = esl_zext<32,9>(min_1_reg_101.read());
}

void digitrec_knn_vote::thread_min_2_min_fu_191_p3() {
    min_2_min_fu_191_p3 = (!tmp_6_fu_177_p2.read()[0].is_01())? sc_lv<32>(): ((tmp_6_fu_177_p2.read()[0].to_bool())? min_1_cast_fu_173_p1.read(): min_reg_78.read());
}

void digitrec_knn_vote::thread_p_shl_cast_fu_137_p1() {
    p_shl_cast_fu_137_p1 = esl_zext<7,6>(tmp_s_fu_129_p3.read());
}

void digitrec_knn_vote::thread_sum_fu_203_p2() {
    sum_fu_203_p2 = (!min_1_reg_101.read().is_01() || !tmp_8_cast_fu_199_p1.read().is_01())? sc_lv<9>(): (sc_biguint<9>(min_1_reg_101.read()) + sc_biguint<9>(tmp_8_cast_fu_199_p1.read()));
}

void digitrec_knn_vote::thread_tmp_12_cast_fu_168_p1() {
    tmp_12_cast_fu_168_p1 = esl_zext<64,7>(tmp_2_fu_163_p2.read());
}

void digitrec_knn_vote::thread_tmp_1_fu_141_p2() {
    tmp_1_fu_141_p2 = (!tmp_cast_fu_125_p1.read().is_01() || !p_shl_cast_fu_137_p1.read().is_01())? sc_lv<7>(): (sc_biguint<7>(tmp_cast_fu_125_p1.read()) + sc_biguint<7>(p_shl_cast_fu_137_p1.read()));
}

void digitrec_knn_vote::thread_tmp_2_fu_163_p2() {
    tmp_2_fu_163_p2 = (!tmp_1_reg_217.read().is_01() || !tmp_7_cast_fu_159_p1.read().is_01())? sc_lv<7>(): (sc_biguint<7>(tmp_1_reg_217.read()) + sc_biguint<7>(tmp_7_cast_fu_159_p1.read()));
}

void digitrec_knn_vote::thread_tmp_6_fu_177_p2() {
    tmp_6_fu_177_p2 = (!min_1_cast_fu_173_p1.read().is_01() || !min_reg_78.read().is_01())? sc_lv<1>(): (sc_bigint<32>(min_1_cast_fu_173_p1.read()) < sc_bigint<32>(min_reg_78.read()));
}

void digitrec_knn_vote::thread_tmp_7_cast_fu_159_p1() {
    tmp_7_cast_fu_159_p1 = esl_zext<7,3>(p_1_reg_90.read());
}

void digitrec_knn_vote::thread_tmp_8_cast_fu_199_p1() {
    tmp_8_cast_fu_199_p1 = esl_zext<9,6>(knn_set_V_q0.read());
}

void digitrec_knn_vote::thread_tmp_cast_fu_125_p1() {
    tmp_cast_fu_125_p1 = esl_zext<7,4>(i_val_V_reg_66.read());
}

void digitrec_knn_vote::thread_tmp_s_fu_129_p3() {
    tmp_s_fu_129_p3 = esl_concat<4,2>(i_val_V_reg_66.read(), ap_const_lv2_0);
}

void digitrec_knn_vote::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 2 : 
            if (!esl_seteq<1,1,1>(exitcond1_fu_113_p2.read(), ap_const_lv1_0)) {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            } else {
                ap_NS_fsm = ap_ST_st3_fsm_2;
            }
            break;
        case 4 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_147_p2.read())) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st4_fsm_3;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_st3_fsm_2;
            break;
        default : 
            ap_NS_fsm = "XXXX";
            break;
    }
}

}

