// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "digitrec_update_knn.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic digitrec_update_knn::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic digitrec_update_knn::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<5> digitrec_update_knn::ap_ST_st1_fsm_0 = "1";
const sc_lv<5> digitrec_update_knn::ap_ST_st2_fsm_1 = "10";
const sc_lv<5> digitrec_update_knn::ap_ST_st3_fsm_2 = "100";
const sc_lv<5> digitrec_update_knn::ap_ST_st4_fsm_3 = "1000";
const sc_lv<5> digitrec_update_knn::ap_ST_st5_fsm_4 = "10000";
const sc_lv<32> digitrec_update_knn::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> digitrec_update_knn::ap_const_lv1_1 = "1";
const sc_lv<32> digitrec_update_knn::ap_const_lv32_1 = "1";
const sc_lv<1> digitrec_update_knn::ap_const_lv1_0 = "0";
const sc_lv<32> digitrec_update_knn::ap_const_lv32_2 = "10";
const sc_lv<32> digitrec_update_knn::ap_const_lv32_3 = "11";
const sc_lv<6> digitrec_update_knn::ap_const_lv6_0 = "000000";
const sc_lv<2> digitrec_update_knn::ap_const_lv2_0 = "00";
const sc_lv<32> digitrec_update_knn::ap_const_lv32_4 = "100";
const sc_lv<49> digitrec_update_knn::ap_const_lv49_0 = "0000000000000000000000000000000000000000000000000";
const sc_lv<6> digitrec_update_knn::ap_const_lv6_1 = "1";
const sc_lv<49> digitrec_update_knn::ap_const_lv49_1FFFFFFFFFFFF = "1111111111111111111111111111111111111111111111111";
const sc_lv<2> digitrec_update_knn::ap_const_lv2_3 = "11";
const sc_lv<2> digitrec_update_knn::ap_const_lv2_1 = "1";

digitrec_update_knn::digitrec_update_knn(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );

    SC_METHOD(thread_ap_sig_114);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_22);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_52);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_67);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_85);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_cseq_ST_st1_fsm_0);
    sensitive << ( ap_sig_22 );

    SC_METHOD(thread_ap_sig_cseq_ST_st2_fsm_1);
    sensitive << ( ap_sig_52 );

    SC_METHOD(thread_ap_sig_cseq_ST_st3_fsm_2);
    sensitive << ( ap_sig_67 );

    SC_METHOD(thread_ap_sig_cseq_ST_st4_fsm_3);
    sensitive << ( ap_sig_85 );

    SC_METHOD(thread_ap_sig_cseq_ST_st5_fsm_4);
    sensitive << ( ap_sig_114 );

    SC_METHOD(thread_count_V_fu_174_p2);
    sensitive << ( distance_V_reg_82 );

    SC_METHOD(thread_exitcond_fu_192_p2);
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( val_assign_reg_128 );

    SC_METHOD(thread_i_fu_198_p2);
    sensitive << ( val_assign_reg_128 );

    SC_METHOD(thread_i_val_V_026_s_fu_250_p3);
    sensitive << ( p_026_s_reg_116 );
    sensitive << ( tmp_3_fu_232_p2 );
    sensitive << ( i_val_V_fu_238_p1 );

    SC_METHOD(thread_i_val_V_fu_238_p1);
    sensitive << ( val_assign_reg_128 );

    SC_METHOD(thread_max_V_s_fu_242_p3);
    sensitive << ( min_distances_V_q0 );
    sensitive << ( p_s_reg_104 );
    sensitive << ( tmp_3_fu_232_p2 );

    SC_METHOD(thread_min_distances_V_address0);
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( exitcond_fu_192_p2 );
    sensitive << ( min_distances_V_addr_reg_301 );
    sensitive << ( tmp_8_cast_fu_213_p1 );
    sensitive << ( tmp_7_cast_fu_227_p1 );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );

    SC_METHOD(thread_min_distances_V_ce0);
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( exitcond_fu_192_p2 );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );

    SC_METHOD(thread_min_distances_V_d0);
    sensitive << ( distance_V_reg_82 );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );

    SC_METHOD(thread_min_distances_V_we0);
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( tmp_1_fu_258_p2 );

    SC_METHOD(thread_r_V_fu_162_p2);
    sensitive << ( test_inst_V );
    sensitive << ( train_inst_V_cast_fu_158_p1 );

    SC_METHOD(thread_tmp_1_fu_258_p2);
    sensitive << ( min_distances_V_q0 );
    sensitive << ( distance_V_reg_82 );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );

    SC_METHOD(thread_tmp_2_cast_fu_204_p1);
    sensitive << ( val_assign_reg_128 );

    SC_METHOD(thread_tmp_3_fu_232_p2);
    sensitive << ( min_distances_V_q0 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( p_s_reg_104 );

    SC_METHOD(thread_tmp_4_cast_cast_fu_140_p1);
    sensitive << ( tmp_4 );

    SC_METHOD(thread_tmp_5_fu_144_p3);
    sensitive << ( tmp_4 );

    SC_METHOD(thread_tmp_5_i_fu_180_p2);
    sensitive << ( n_V_buf_i_reg_95 );

    SC_METHOD(thread_tmp_6_fu_152_p2);
    sensitive << ( tmp_5_fu_144_p3 );
    sensitive << ( tmp_4_cast_cast_fu_140_p1 );

    SC_METHOD(thread_tmp_6_i_fu_186_p2);
    sensitive << ( n_V_buf_i_reg_95 );
    sensitive << ( tmp_5_i_fu_180_p2 );

    SC_METHOD(thread_tmp_7_cast_fu_227_p1);
    sensitive << ( tmp_7_fu_222_p2 );

    SC_METHOD(thread_tmp_7_fu_222_p2);
    sensitive << ( tmp_6_reg_264 );
    sensitive << ( tmp_cast_fu_218_p1 );

    SC_METHOD(thread_tmp_8_cast_fu_213_p1);
    sensitive << ( tmp_8_fu_208_p2 );

    SC_METHOD(thread_tmp_8_fu_208_p2);
    sensitive << ( tmp_6_reg_264 );
    sensitive << ( tmp_2_cast_fu_204_p1 );

    SC_METHOD(thread_tmp_cast_fu_218_p1);
    sensitive << ( p_026_s_reg_116 );

    SC_METHOD(thread_tmp_i_fu_168_p2);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( n_V_buf_i_reg_95 );

    SC_METHOD(thread_train_inst_V_cast_fu_158_p1);
    sensitive << ( train_inst_V );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( tmp_i_fu_168_p2 );
    sensitive << ( exitcond_fu_192_p2 );

    ap_CS_fsm = "00001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "digitrec_update_knn_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, test_inst_V, "(port)test_inst_V");
    sc_trace(mVcdFile, train_inst_V, "(port)train_inst_V");
    sc_trace(mVcdFile, min_distances_V_address0, "(port)min_distances_V_address0");
    sc_trace(mVcdFile, min_distances_V_ce0, "(port)min_distances_V_ce0");
    sc_trace(mVcdFile, min_distances_V_we0, "(port)min_distances_V_we0");
    sc_trace(mVcdFile, min_distances_V_d0, "(port)min_distances_V_d0");
    sc_trace(mVcdFile, min_distances_V_q0, "(port)min_distances_V_q0");
    sc_trace(mVcdFile, tmp_4, "(port)tmp_4");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st1_fsm_0, "ap_sig_cseq_ST_st1_fsm_0");
    sc_trace(mVcdFile, ap_sig_22, "ap_sig_22");
    sc_trace(mVcdFile, tmp_6_fu_152_p2, "tmp_6_fu_152_p2");
    sc_trace(mVcdFile, tmp_6_reg_264, "tmp_6_reg_264");
    sc_trace(mVcdFile, r_V_fu_162_p2, "r_V_fu_162_p2");
    sc_trace(mVcdFile, count_V_fu_174_p2, "count_V_fu_174_p2");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st2_fsm_1, "ap_sig_cseq_ST_st2_fsm_1");
    sc_trace(mVcdFile, ap_sig_52, "ap_sig_52");
    sc_trace(mVcdFile, tmp_6_i_fu_186_p2, "tmp_6_i_fu_186_p2");
    sc_trace(mVcdFile, tmp_i_fu_168_p2, "tmp_i_fu_168_p2");
    sc_trace(mVcdFile, i_fu_198_p2, "i_fu_198_p2");
    sc_trace(mVcdFile, i_reg_291, "i_reg_291");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st3_fsm_2, "ap_sig_cseq_ST_st3_fsm_2");
    sc_trace(mVcdFile, ap_sig_67, "ap_sig_67");
    sc_trace(mVcdFile, exitcond_fu_192_p2, "exitcond_fu_192_p2");
    sc_trace(mVcdFile, min_distances_V_addr_reg_301, "min_distances_V_addr_reg_301");
    sc_trace(mVcdFile, max_V_s_fu_242_p3, "max_V_s_fu_242_p3");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st4_fsm_3, "ap_sig_cseq_ST_st4_fsm_3");
    sc_trace(mVcdFile, ap_sig_85, "ap_sig_85");
    sc_trace(mVcdFile, i_val_V_026_s_fu_250_p3, "i_val_V_026_s_fu_250_p3");
    sc_trace(mVcdFile, distance_V_reg_82, "distance_V_reg_82");
    sc_trace(mVcdFile, n_V_buf_i_reg_95, "n_V_buf_i_reg_95");
    sc_trace(mVcdFile, p_s_reg_104, "p_s_reg_104");
    sc_trace(mVcdFile, p_026_s_reg_116, "p_026_s_reg_116");
    sc_trace(mVcdFile, val_assign_reg_128, "val_assign_reg_128");
    sc_trace(mVcdFile, tmp_8_cast_fu_213_p1, "tmp_8_cast_fu_213_p1");
    sc_trace(mVcdFile, tmp_7_cast_fu_227_p1, "tmp_7_cast_fu_227_p1");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st5_fsm_4, "ap_sig_cseq_ST_st5_fsm_4");
    sc_trace(mVcdFile, ap_sig_114, "ap_sig_114");
    sc_trace(mVcdFile, tmp_1_fu_258_p2, "tmp_1_fu_258_p2");
    sc_trace(mVcdFile, tmp_5_fu_144_p3, "tmp_5_fu_144_p3");
    sc_trace(mVcdFile, tmp_4_cast_cast_fu_140_p1, "tmp_4_cast_cast_fu_140_p1");
    sc_trace(mVcdFile, train_inst_V_cast_fu_158_p1, "train_inst_V_cast_fu_158_p1");
    sc_trace(mVcdFile, tmp_5_i_fu_180_p2, "tmp_5_i_fu_180_p2");
    sc_trace(mVcdFile, tmp_2_cast_fu_204_p1, "tmp_2_cast_fu_204_p1");
    sc_trace(mVcdFile, tmp_8_fu_208_p2, "tmp_8_fu_208_p2");
    sc_trace(mVcdFile, tmp_cast_fu_218_p1, "tmp_cast_fu_218_p1");
    sc_trace(mVcdFile, tmp_7_fu_222_p2, "tmp_7_fu_222_p2");
    sc_trace(mVcdFile, tmp_3_fu_232_p2, "tmp_3_fu_232_p2");
    sc_trace(mVcdFile, i_val_V_fu_238_p1, "i_val_V_fu_238_p1");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

digitrec_update_knn::~digitrec_update_knn() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void digitrec_update_knn::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
         esl_seteq<1,1,1>(tmp_i_fu_168_p2.read(), ap_const_lv1_0))) {
        distance_V_reg_82 = count_V_fu_174_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        distance_V_reg_82 = ap_const_lv6_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
         esl_seteq<1,1,1>(tmp_i_fu_168_p2.read(), ap_const_lv1_0))) {
        n_V_buf_i_reg_95 = tmp_6_i_fu_186_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        n_V_buf_i_reg_95 = r_V_fu_162_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
         !esl_seteq<1,1,1>(tmp_i_fu_168_p2.read(), ap_const_lv1_0))) {
        p_s_reg_104 = ap_const_lv6_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        p_s_reg_104 = max_V_s_fu_242_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
         !esl_seteq<1,1,1>(tmp_i_fu_168_p2.read(), ap_const_lv1_0))) {
        val_assign_reg_128 = ap_const_lv2_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        val_assign_reg_128 = i_reg_291.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        i_reg_291 = i_fu_198_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_192_p2.read()))) {
        min_distances_V_addr_reg_301 =  (sc_lv<5>) (tmp_7_cast_fu_227_p1.read());
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        p_026_s_reg_116 = i_val_V_026_s_fu_250_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        tmp_6_reg_264 = tmp_6_fu_152_p2.read();
    }
}

void digitrec_update_knn::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void digitrec_update_knn::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void digitrec_update_knn::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void digitrec_update_knn::thread_ap_sig_114() {
    ap_sig_114 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(4, 4));
}

void digitrec_update_knn::thread_ap_sig_22() {
    ap_sig_22 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void digitrec_update_knn::thread_ap_sig_52() {
    ap_sig_52 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(1, 1));
}

void digitrec_update_knn::thread_ap_sig_67() {
    ap_sig_67 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(2, 2));
}

void digitrec_update_knn::thread_ap_sig_85() {
    ap_sig_85 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(3, 3));
}

void digitrec_update_knn::thread_ap_sig_cseq_ST_st1_fsm_0() {
    if (ap_sig_22.read()) {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    }
}

void digitrec_update_knn::thread_ap_sig_cseq_ST_st2_fsm_1() {
    if (ap_sig_52.read()) {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    }
}

void digitrec_update_knn::thread_ap_sig_cseq_ST_st3_fsm_2() {
    if (ap_sig_67.read()) {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_0;
    }
}

void digitrec_update_knn::thread_ap_sig_cseq_ST_st4_fsm_3() {
    if (ap_sig_85.read()) {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_0;
    }
}

void digitrec_update_knn::thread_ap_sig_cseq_ST_st5_fsm_4() {
    if (ap_sig_114.read()) {
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_0;
    }
}

void digitrec_update_knn::thread_count_V_fu_174_p2() {
    count_V_fu_174_p2 = (!distance_V_reg_82.read().is_01() || !ap_const_lv6_1.is_01())? sc_lv<6>(): (sc_biguint<6>(distance_V_reg_82.read()) + sc_biguint<6>(ap_const_lv6_1));
}

void digitrec_update_knn::thread_exitcond_fu_192_p2() {
    exitcond_fu_192_p2 = (!val_assign_reg_128.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(val_assign_reg_128.read() == ap_const_lv2_3);
}

void digitrec_update_knn::thread_i_fu_198_p2() {
    i_fu_198_p2 = (!val_assign_reg_128.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(val_assign_reg_128.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void digitrec_update_knn::thread_i_val_V_026_s_fu_250_p3() {
    i_val_V_026_s_fu_250_p3 = (!tmp_3_fu_232_p2.read()[0].is_01())? sc_lv<4>(): ((tmp_3_fu_232_p2.read()[0].to_bool())? i_val_V_fu_238_p1.read(): p_026_s_reg_116.read());
}

void digitrec_update_knn::thread_i_val_V_fu_238_p1() {
    i_val_V_fu_238_p1 = esl_zext<4,2>(val_assign_reg_128.read());
}

void digitrec_update_knn::thread_max_V_s_fu_242_p3() {
    max_V_s_fu_242_p3 = (!tmp_3_fu_232_p2.read()[0].is_01())? sc_lv<6>(): ((tmp_3_fu_232_p2.read()[0].to_bool())? min_distances_V_q0.read(): p_s_reg_104.read());
}

void digitrec_update_knn::thread_min_distances_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        min_distances_V_address0 = min_distances_V_addr_reg_301.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && 
                !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_192_p2.read()))) {
        min_distances_V_address0 =  (sc_lv<5>) (tmp_7_cast_fu_227_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_192_p2.read()))) {
        min_distances_V_address0 =  (sc_lv<5>) (tmp_8_cast_fu_213_p1.read());
    } else {
        min_distances_V_address0 = "XXXXX";
    }
}

void digitrec_update_knn::thread_min_distances_V_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_192_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_192_p2.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read()))) {
        min_distances_V_ce0 = ap_const_logic_1;
    } else {
        min_distances_V_ce0 = ap_const_logic_0;
    }
}

void digitrec_update_knn::thread_min_distances_V_d0() {
    min_distances_V_d0 = distance_V_reg_82.read();
}

void digitrec_update_knn::thread_min_distances_V_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_1_fu_258_p2.read())))) {
        min_distances_V_we0 = ap_const_logic_1;
    } else {
        min_distances_V_we0 = ap_const_logic_0;
    }
}

void digitrec_update_knn::thread_r_V_fu_162_p2() {
    r_V_fu_162_p2 = (train_inst_V_cast_fu_158_p1.read() ^ test_inst_V.read());
}

void digitrec_update_knn::thread_tmp_1_fu_258_p2() {
    tmp_1_fu_258_p2 = (!distance_V_reg_82.read().is_01() || !min_distances_V_q0.read().is_01())? sc_lv<1>(): (sc_biguint<6>(distance_V_reg_82.read()) < sc_biguint<6>(min_distances_V_q0.read()));
}

void digitrec_update_knn::thread_tmp_2_cast_fu_204_p1() {
    tmp_2_cast_fu_204_p1 = esl_zext<6,2>(val_assign_reg_128.read());
}

void digitrec_update_knn::thread_tmp_3_fu_232_p2() {
    tmp_3_fu_232_p2 = (!min_distances_V_q0.read().is_01() || !p_s_reg_104.read().is_01())? sc_lv<1>(): (sc_biguint<6>(min_distances_V_q0.read()) > sc_biguint<6>(p_s_reg_104.read()));
}

void digitrec_update_knn::thread_tmp_4_cast_cast_fu_140_p1() {
    tmp_4_cast_cast_fu_140_p1 = esl_zext<6,4>(tmp_4.read());
}

void digitrec_update_knn::thread_tmp_5_fu_144_p3() {
    tmp_5_fu_144_p3 = esl_concat<4,2>(tmp_4.read(), ap_const_lv2_0);
}

void digitrec_update_knn::thread_tmp_5_i_fu_180_p2() {
    tmp_5_i_fu_180_p2 = (!n_V_buf_i_reg_95.read().is_01() || !ap_const_lv49_1FFFFFFFFFFFF.is_01())? sc_lv<49>(): (sc_biguint<49>(n_V_buf_i_reg_95.read()) + sc_bigint<49>(ap_const_lv49_1FFFFFFFFFFFF));
}

void digitrec_update_knn::thread_tmp_6_fu_152_p2() {
    tmp_6_fu_152_p2 = (!tmp_5_fu_144_p3.read().is_01() || !tmp_4_cast_cast_fu_140_p1.read().is_01())? sc_lv<6>(): (sc_biguint<6>(tmp_5_fu_144_p3.read()) - sc_biguint<6>(tmp_4_cast_cast_fu_140_p1.read()));
}

void digitrec_update_knn::thread_tmp_6_i_fu_186_p2() {
    tmp_6_i_fu_186_p2 = (tmp_5_i_fu_180_p2.read() & n_V_buf_i_reg_95.read());
}

void digitrec_update_knn::thread_tmp_7_cast_fu_227_p1() {
    tmp_7_cast_fu_227_p1 = esl_sext<64,6>(tmp_7_fu_222_p2.read());
}

void digitrec_update_knn::thread_tmp_7_fu_222_p2() {
    tmp_7_fu_222_p2 = (!tmp_6_reg_264.read().is_01() || !tmp_cast_fu_218_p1.read().is_01())? sc_lv<6>(): (sc_biguint<6>(tmp_6_reg_264.read()) + sc_biguint<6>(tmp_cast_fu_218_p1.read()));
}

void digitrec_update_knn::thread_tmp_8_cast_fu_213_p1() {
    tmp_8_cast_fu_213_p1 = esl_sext<64,6>(tmp_8_fu_208_p2.read());
}

void digitrec_update_knn::thread_tmp_8_fu_208_p2() {
    tmp_8_fu_208_p2 = (!tmp_6_reg_264.read().is_01() || !tmp_2_cast_fu_204_p1.read().is_01())? sc_lv<6>(): (sc_biguint<6>(tmp_6_reg_264.read()) + sc_biguint<6>(tmp_2_cast_fu_204_p1.read()));
}

void digitrec_update_knn::thread_tmp_cast_fu_218_p1() {
    tmp_cast_fu_218_p1 = esl_zext<6,4>(p_026_s_reg_116.read());
}

void digitrec_update_knn::thread_tmp_i_fu_168_p2() {
    tmp_i_fu_168_p2 = (!n_V_buf_i_reg_95.read().is_01() || !ap_const_lv49_0.is_01())? sc_lv<1>(): sc_lv<1>(n_V_buf_i_reg_95.read() == ap_const_lv49_0);
}

void digitrec_update_knn::thread_train_inst_V_cast_fu_158_p1() {
    train_inst_V_cast_fu_158_p1 = esl_zext<49,48>(train_inst_V.read());
}

void digitrec_update_knn::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 2 : 
            if (esl_seteq<1,1,1>(tmp_i_fu_168_p2.read(), ap_const_lv1_0)) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st3_fsm_2;
            }
            break;
        case 4 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_192_p2.read())) {
                ap_NS_fsm = ap_ST_st5_fsm_4;
            } else {
                ap_NS_fsm = ap_ST_st4_fsm_3;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_st3_fsm_2;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_st1_fsm_0;
            break;
        default : 
            ap_NS_fsm = "XXXXX";
            break;
    }
}

}

