// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "digitrec_bitcount.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const bool digitrec_bitcount::ap_true = true;
const sc_lv<32> digitrec_bitcount::ap_const_lv32_1 = "1";
const sc_lv<32> digitrec_bitcount::ap_const_lv32_2 = "10";
const sc_lv<32> digitrec_bitcount::ap_const_lv32_3 = "11";
const sc_lv<32> digitrec_bitcount::ap_const_lv32_4 = "100";
const sc_lv<32> digitrec_bitcount::ap_const_lv32_5 = "101";
const sc_lv<32> digitrec_bitcount::ap_const_lv32_6 = "110";
const sc_lv<32> digitrec_bitcount::ap_const_lv32_7 = "111";
const sc_lv<32> digitrec_bitcount::ap_const_lv32_8 = "1000";
const sc_lv<32> digitrec_bitcount::ap_const_lv32_9 = "1001";
const sc_lv<32> digitrec_bitcount::ap_const_lv32_A = "1010";
const sc_lv<32> digitrec_bitcount::ap_const_lv32_B = "1011";
const sc_lv<32> digitrec_bitcount::ap_const_lv32_C = "1100";
const sc_lv<32> digitrec_bitcount::ap_const_lv32_D = "1101";
const sc_lv<32> digitrec_bitcount::ap_const_lv32_E = "1110";
const sc_lv<32> digitrec_bitcount::ap_const_lv32_F = "1111";
const sc_lv<32> digitrec_bitcount::ap_const_lv32_10 = "10000";
const sc_lv<32> digitrec_bitcount::ap_const_lv32_11 = "10001";
const sc_lv<32> digitrec_bitcount::ap_const_lv32_12 = "10010";
const sc_lv<32> digitrec_bitcount::ap_const_lv32_13 = "10011";
const sc_lv<32> digitrec_bitcount::ap_const_lv32_14 = "10100";
const sc_lv<32> digitrec_bitcount::ap_const_lv32_15 = "10101";
const sc_lv<32> digitrec_bitcount::ap_const_lv32_16 = "10110";
const sc_lv<32> digitrec_bitcount::ap_const_lv32_17 = "10111";
const sc_lv<32> digitrec_bitcount::ap_const_lv32_18 = "11000";
const sc_lv<32> digitrec_bitcount::ap_const_lv32_19 = "11001";
const sc_lv<32> digitrec_bitcount::ap_const_lv32_1A = "11010";
const sc_lv<32> digitrec_bitcount::ap_const_lv32_1B = "11011";
const sc_lv<32> digitrec_bitcount::ap_const_lv32_1C = "11100";
const sc_lv<32> digitrec_bitcount::ap_const_lv32_1D = "11101";
const sc_lv<32> digitrec_bitcount::ap_const_lv32_1E = "11110";
const sc_lv<32> digitrec_bitcount::ap_const_lv32_1F = "11111";
const sc_lv<32> digitrec_bitcount::ap_const_lv32_20 = "100000";
const sc_lv<32> digitrec_bitcount::ap_const_lv32_21 = "100001";
const sc_lv<32> digitrec_bitcount::ap_const_lv32_22 = "100010";
const sc_lv<32> digitrec_bitcount::ap_const_lv32_23 = "100011";
const sc_lv<32> digitrec_bitcount::ap_const_lv32_24 = "100100";
const sc_lv<32> digitrec_bitcount::ap_const_lv32_25 = "100101";
const sc_lv<32> digitrec_bitcount::ap_const_lv32_26 = "100110";
const sc_lv<32> digitrec_bitcount::ap_const_lv32_27 = "100111";
const sc_lv<32> digitrec_bitcount::ap_const_lv32_28 = "101000";
const sc_lv<32> digitrec_bitcount::ap_const_lv32_29 = "101001";
const sc_lv<32> digitrec_bitcount::ap_const_lv32_2A = "101010";
const sc_lv<32> digitrec_bitcount::ap_const_lv32_2B = "101011";
const sc_lv<32> digitrec_bitcount::ap_const_lv32_2C = "101100";
const sc_lv<32> digitrec_bitcount::ap_const_lv32_2D = "101101";
const sc_lv<32> digitrec_bitcount::ap_const_lv32_2E = "101110";
const sc_lv<32> digitrec_bitcount::ap_const_lv32_2F = "101111";
const sc_lv<32> digitrec_bitcount::ap_const_lv32_30 = "110000";
const sc_logic digitrec_bitcount::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic digitrec_bitcount::ap_const_logic_0 = sc_dt::Log_0;

digitrec_bitcount::digitrec_bitcount(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_return);
    sensitive << ( tmp_cast_fu_886_p1 );
    sensitive << ( tmp23_cast_fu_1094_p1 );

    SC_METHOD(thread_tmp10_cast_fu_762_p1);
    sensitive << ( tmp10_fu_756_p2 );

    SC_METHOD(thread_tmp10_fu_756_p2);
    sensitive << ( tmp_1_9_cast_fu_220_p1 );
    sensitive << ( tmp11_fu_750_p2 );

    SC_METHOD(thread_tmp11_fu_750_p2);
    sensitive << ( tmp_1_10_cast_fu_244_p1 );
    sensitive << ( tmp_1_cast_3_fu_232_p1 );

    SC_METHOD(thread_tmp12_cast_fu_876_p1);
    sensitive << ( tmp12_fu_870_p2 );

    SC_METHOD(thread_tmp12_fu_870_p2);
    sensitive << ( tmp13_cast_fu_824_p1 );
    sensitive << ( tmp18_cast_fu_866_p1 );

    SC_METHOD(thread_tmp13_cast_fu_824_p1);
    sensitive << ( tmp13_fu_818_p2 );

    SC_METHOD(thread_tmp13_fu_818_p2);
    sensitive << ( tmp14_cast_fu_798_p1 );
    sensitive << ( tmp16_cast_fu_814_p1 );

    SC_METHOD(thread_tmp14_cast_fu_798_p1);
    sensitive << ( tmp14_fu_792_p2 );

    SC_METHOD(thread_tmp14_fu_792_p2);
    sensitive << ( tmp_1_11_cast_fu_256_p1 );
    sensitive << ( tmp15_fu_786_p2 );

    SC_METHOD(thread_tmp15_fu_786_p2);
    sensitive << ( tmp_1_13_cast_fu_280_p1 );
    sensitive << ( tmp_1_12_cast_fu_268_p1 );

    SC_METHOD(thread_tmp16_cast_fu_814_p1);
    sensitive << ( tmp16_fu_808_p2 );

    SC_METHOD(thread_tmp16_fu_808_p2);
    sensitive << ( tmp_1_14_cast_fu_292_p1 );
    sensitive << ( tmp17_fu_802_p2 );

    SC_METHOD(thread_tmp17_fu_802_p2);
    sensitive << ( tmp_1_16_cast_fu_316_p1 );
    sensitive << ( tmp_1_15_cast_fu_304_p1 );

    SC_METHOD(thread_tmp18_cast_fu_866_p1);
    sensitive << ( tmp18_fu_860_p2 );

    SC_METHOD(thread_tmp18_fu_860_p2);
    sensitive << ( tmp19_cast_fu_840_p1 );
    sensitive << ( tmp21_cast_fu_856_p1 );

    SC_METHOD(thread_tmp19_cast_fu_840_p1);
    sensitive << ( tmp19_fu_834_p2 );

    SC_METHOD(thread_tmp19_fu_834_p2);
    sensitive << ( tmp_1_17_cast_fu_328_p1 );
    sensitive << ( tmp20_fu_828_p2 );

    SC_METHOD(thread_tmp1_cast_fu_782_p1);
    sensitive << ( tmp1_fu_776_p2 );

    SC_METHOD(thread_tmp1_fu_776_p2);
    sensitive << ( tmp2_cast_fu_730_p1 );
    sensitive << ( tmp7_cast_fu_772_p1 );

    SC_METHOD(thread_tmp20_fu_828_p2);
    sensitive << ( tmp_1_19_cast_fu_352_p1 );
    sensitive << ( tmp_1_18_cast_fu_340_p1 );

    SC_METHOD(thread_tmp21_cast_fu_856_p1);
    sensitive << ( tmp21_fu_850_p2 );

    SC_METHOD(thread_tmp21_fu_850_p2);
    sensitive << ( tmp_1_20_cast_fu_364_p1 );
    sensitive << ( tmp22_fu_844_p2 );

    SC_METHOD(thread_tmp22_fu_844_p2);
    sensitive << ( tmp_1_22_cast_fu_388_p1 );
    sensitive << ( tmp_1_21_cast_fu_376_p1 );

    SC_METHOD(thread_tmp23_cast_fu_1094_p1);
    sensitive << ( tmp23_fu_1088_p2 );

    SC_METHOD(thread_tmp23_fu_1088_p2);
    sensitive << ( tmp24_cast_fu_980_p1 );
    sensitive << ( tmp35_cast_fu_1084_p1 );

    SC_METHOD(thread_tmp24_cast_fu_980_p1);
    sensitive << ( tmp24_fu_974_p2 );

    SC_METHOD(thread_tmp24_fu_974_p2);
    sensitive << ( tmp25_cast_fu_928_p1 );
    sensitive << ( tmp30_cast_fu_970_p1 );

    SC_METHOD(thread_tmp25_cast_fu_928_p1);
    sensitive << ( tmp25_fu_922_p2 );

    SC_METHOD(thread_tmp25_fu_922_p2);
    sensitive << ( tmp26_cast_fu_902_p1 );
    sensitive << ( tmp28_cast_fu_918_p1 );

    SC_METHOD(thread_tmp26_cast_fu_902_p1);
    sensitive << ( tmp26_fu_896_p2 );

    SC_METHOD(thread_tmp26_fu_896_p2);
    sensitive << ( tmp_1_23_cast_fu_400_p1 );
    sensitive << ( tmp27_fu_890_p2 );

    SC_METHOD(thread_tmp27_fu_890_p2);
    sensitive << ( tmp_1_25_cast_fu_424_p1 );
    sensitive << ( tmp_1_24_cast_fu_412_p1 );

    SC_METHOD(thread_tmp28_cast_fu_918_p1);
    sensitive << ( tmp28_fu_912_p2 );

    SC_METHOD(thread_tmp28_fu_912_p2);
    sensitive << ( tmp_1_26_cast_fu_436_p1 );
    sensitive << ( tmp29_fu_906_p2 );

    SC_METHOD(thread_tmp29_fu_906_p2);
    sensitive << ( tmp_1_28_cast_fu_460_p1 );
    sensitive << ( tmp_1_27_cast_fu_448_p1 );

    SC_METHOD(thread_tmp2_cast_fu_730_p1);
    sensitive << ( tmp2_fu_724_p2 );

    SC_METHOD(thread_tmp2_fu_724_p2);
    sensitive << ( tmp3_cast_fu_704_p1 );
    sensitive << ( tmp5_cast_fu_720_p1 );

    SC_METHOD(thread_tmp30_cast_fu_970_p1);
    sensitive << ( tmp30_fu_964_p2 );

    SC_METHOD(thread_tmp30_fu_964_p2);
    sensitive << ( tmp31_cast_fu_944_p1 );
    sensitive << ( tmp33_cast_fu_960_p1 );

    SC_METHOD(thread_tmp31_cast_fu_944_p1);
    sensitive << ( tmp31_fu_938_p2 );

    SC_METHOD(thread_tmp31_fu_938_p2);
    sensitive << ( tmp_1_29_cast_fu_472_p1 );
    sensitive << ( tmp32_fu_932_p2 );

    SC_METHOD(thread_tmp32_fu_932_p2);
    sensitive << ( tmp_1_31_cast_fu_496_p1 );
    sensitive << ( tmp_1_30_cast_fu_484_p1 );

    SC_METHOD(thread_tmp33_cast_fu_960_p1);
    sensitive << ( tmp33_fu_954_p2 );

    SC_METHOD(thread_tmp33_fu_954_p2);
    sensitive << ( tmp_1_32_cast_fu_508_p1 );
    sensitive << ( tmp34_fu_948_p2 );

    SC_METHOD(thread_tmp34_fu_948_p2);
    sensitive << ( tmp_1_34_cast_fu_532_p1 );
    sensitive << ( tmp_1_33_cast_fu_520_p1 );

    SC_METHOD(thread_tmp35_cast_fu_1084_p1);
    sensitive << ( tmp35_fu_1078_p2 );

    SC_METHOD(thread_tmp35_fu_1078_p2);
    sensitive << ( tmp36_cast_fu_1022_p1 );
    sensitive << ( tmp41_cast_fu_1074_p1 );

    SC_METHOD(thread_tmp36_cast_fu_1022_p1);
    sensitive << ( tmp36_fu_1016_p2 );

    SC_METHOD(thread_tmp36_fu_1016_p2);
    sensitive << ( tmp37_cast_fu_996_p1 );
    sensitive << ( tmp39_cast_fu_1012_p1 );

    SC_METHOD(thread_tmp37_cast_fu_996_p1);
    sensitive << ( tmp37_fu_990_p2 );

    SC_METHOD(thread_tmp37_fu_990_p2);
    sensitive << ( tmp_1_35_cast_fu_544_p1 );
    sensitive << ( tmp38_fu_984_p2 );

    SC_METHOD(thread_tmp38_fu_984_p2);
    sensitive << ( tmp_1_37_cast_fu_568_p1 );
    sensitive << ( tmp_1_36_cast_fu_556_p1 );

    SC_METHOD(thread_tmp39_cast_fu_1012_p1);
    sensitive << ( tmp39_fu_1006_p2 );

    SC_METHOD(thread_tmp39_fu_1006_p2);
    sensitive << ( tmp_1_38_cast_fu_580_p1 );
    sensitive << ( tmp40_fu_1000_p2 );

    SC_METHOD(thread_tmp3_cast_fu_704_p1);
    sensitive << ( tmp3_fu_698_p2 );

    SC_METHOD(thread_tmp3_fu_698_p2);
    sensitive << ( tmp_1_cast_fu_112_p1 );
    sensitive << ( tmp4_fu_692_p2 );

    SC_METHOD(thread_tmp40_fu_1000_p2);
    sensitive << ( tmp_1_40_cast_fu_604_p1 );
    sensitive << ( tmp_1_39_cast_fu_592_p1 );

    SC_METHOD(thread_tmp41_cast_fu_1074_p1);
    sensitive << ( tmp41_fu_1068_p2 );

    SC_METHOD(thread_tmp41_fu_1068_p2);
    sensitive << ( tmp42_cast_fu_1038_p1 );
    sensitive << ( tmp44_fu_1062_p2 );

    SC_METHOD(thread_tmp42_cast_fu_1038_p1);
    sensitive << ( tmp42_fu_1032_p2 );

    SC_METHOD(thread_tmp42_fu_1032_p2);
    sensitive << ( tmp_1_41_cast_fu_616_p1 );
    sensitive << ( tmp43_fu_1026_p2 );

    SC_METHOD(thread_tmp43_fu_1026_p2);
    sensitive << ( tmp_1_43_cast_fu_640_p1 );
    sensitive << ( tmp_1_42_cast_fu_628_p1 );

    SC_METHOD(thread_tmp44_fu_1062_p2);
    sensitive << ( tmp45_cast_fu_1048_p1 );
    sensitive << ( tmp46_cast_fu_1058_p1 );

    SC_METHOD(thread_tmp45_cast_fu_1048_p1);
    sensitive << ( tmp45_fu_1042_p2 );

    SC_METHOD(thread_tmp45_fu_1042_p2);
    sensitive << ( tmp_1_45_cast_fu_664_p1 );
    sensitive << ( tmp_1_44_cast_fu_652_p1 );

    SC_METHOD(thread_tmp46_cast_fu_1058_p1);
    sensitive << ( tmp46_fu_1052_p2 );

    SC_METHOD(thread_tmp46_fu_1052_p2);
    sensitive << ( tmp_47_cast_fu_688_p1 );
    sensitive << ( tmp_1_46_cast_fu_676_p1 );

    SC_METHOD(thread_tmp4_fu_692_p2);
    sensitive << ( tmp_1_2_cast_fu_136_p1 );
    sensitive << ( tmp_1_1_cast_fu_124_p1 );

    SC_METHOD(thread_tmp5_cast_fu_720_p1);
    sensitive << ( tmp5_fu_714_p2 );

    SC_METHOD(thread_tmp5_fu_714_p2);
    sensitive << ( tmp_1_3_cast_fu_148_p1 );
    sensitive << ( tmp6_fu_708_p2 );

    SC_METHOD(thread_tmp6_fu_708_p2);
    sensitive << ( tmp_1_5_cast_fu_172_p1 );
    sensitive << ( tmp_1_4_cast_fu_160_p1 );

    SC_METHOD(thread_tmp7_cast_fu_772_p1);
    sensitive << ( tmp7_fu_766_p2 );

    SC_METHOD(thread_tmp7_fu_766_p2);
    sensitive << ( tmp8_cast_fu_746_p1 );
    sensitive << ( tmp10_cast_fu_762_p1 );

    SC_METHOD(thread_tmp8_cast_fu_746_p1);
    sensitive << ( tmp8_fu_740_p2 );

    SC_METHOD(thread_tmp8_fu_740_p2);
    sensitive << ( tmp_1_6_cast_fu_184_p1 );
    sensitive << ( tmp9_fu_734_p2 );

    SC_METHOD(thread_tmp9_fu_734_p2);
    sensitive << ( tmp_1_8_cast_fu_208_p1 );
    sensitive << ( tmp_1_7_cast_fu_196_p1 );

    SC_METHOD(thread_tmp_10_fu_212_p3);
    sensitive << ( n_V );

    SC_METHOD(thread_tmp_11_fu_224_p3);
    sensitive << ( n_V );

    SC_METHOD(thread_tmp_12_fu_236_p3);
    sensitive << ( n_V );

    SC_METHOD(thread_tmp_13_fu_248_p3);
    sensitive << ( n_V );

    SC_METHOD(thread_tmp_14_fu_260_p3);
    sensitive << ( n_V );

    SC_METHOD(thread_tmp_15_fu_272_p3);
    sensitive << ( n_V );

    SC_METHOD(thread_tmp_16_fu_284_p3);
    sensitive << ( n_V );

    SC_METHOD(thread_tmp_17_fu_296_p3);
    sensitive << ( n_V );

    SC_METHOD(thread_tmp_18_fu_308_p3);
    sensitive << ( n_V );

    SC_METHOD(thread_tmp_19_fu_320_p3);
    sensitive << ( n_V );

    SC_METHOD(thread_tmp_1_10_cast_fu_244_p1);
    sensitive << ( tmp_12_fu_236_p3 );

    SC_METHOD(thread_tmp_1_11_cast_fu_256_p1);
    sensitive << ( tmp_13_fu_248_p3 );

    SC_METHOD(thread_tmp_1_12_cast_fu_268_p1);
    sensitive << ( tmp_14_fu_260_p3 );

    SC_METHOD(thread_tmp_1_13_cast_fu_280_p1);
    sensitive << ( tmp_15_fu_272_p3 );

    SC_METHOD(thread_tmp_1_14_cast_fu_292_p1);
    sensitive << ( tmp_16_fu_284_p3 );

    SC_METHOD(thread_tmp_1_15_cast_fu_304_p1);
    sensitive << ( tmp_17_fu_296_p3 );

    SC_METHOD(thread_tmp_1_16_cast_fu_316_p1);
    sensitive << ( tmp_18_fu_308_p3 );

    SC_METHOD(thread_tmp_1_17_cast_fu_328_p1);
    sensitive << ( tmp_19_fu_320_p3 );

    SC_METHOD(thread_tmp_1_18_cast_fu_340_p1);
    sensitive << ( tmp_20_fu_332_p3 );

    SC_METHOD(thread_tmp_1_19_cast_fu_352_p1);
    sensitive << ( tmp_21_fu_344_p3 );

    SC_METHOD(thread_tmp_1_1_cast_fu_124_p1);
    sensitive << ( tmp_2_fu_116_p3 );

    SC_METHOD(thread_tmp_1_20_cast_fu_364_p1);
    sensitive << ( tmp_22_fu_356_p3 );

    SC_METHOD(thread_tmp_1_21_cast_fu_376_p1);
    sensitive << ( tmp_23_fu_368_p3 );

    SC_METHOD(thread_tmp_1_22_cast_fu_388_p1);
    sensitive << ( tmp_24_fu_380_p3 );

    SC_METHOD(thread_tmp_1_23_cast_fu_400_p1);
    sensitive << ( tmp_25_fu_392_p3 );

    SC_METHOD(thread_tmp_1_24_cast_fu_412_p1);
    sensitive << ( tmp_26_fu_404_p3 );

    SC_METHOD(thread_tmp_1_25_cast_fu_424_p1);
    sensitive << ( tmp_27_fu_416_p3 );

    SC_METHOD(thread_tmp_1_26_cast_fu_436_p1);
    sensitive << ( tmp_28_fu_428_p3 );

    SC_METHOD(thread_tmp_1_27_cast_fu_448_p1);
    sensitive << ( tmp_29_fu_440_p3 );

    SC_METHOD(thread_tmp_1_28_cast_fu_460_p1);
    sensitive << ( tmp_30_fu_452_p3 );

    SC_METHOD(thread_tmp_1_29_cast_fu_472_p1);
    sensitive << ( tmp_31_fu_464_p3 );

    SC_METHOD(thread_tmp_1_2_cast_fu_136_p1);
    sensitive << ( tmp_3_fu_128_p3 );

    SC_METHOD(thread_tmp_1_30_cast_fu_484_p1);
    sensitive << ( tmp_32_fu_476_p3 );

    SC_METHOD(thread_tmp_1_31_cast_fu_496_p1);
    sensitive << ( tmp_33_fu_488_p3 );

    SC_METHOD(thread_tmp_1_32_cast_fu_508_p1);
    sensitive << ( tmp_34_fu_500_p3 );

    SC_METHOD(thread_tmp_1_33_cast_fu_520_p1);
    sensitive << ( tmp_35_fu_512_p3 );

    SC_METHOD(thread_tmp_1_34_cast_fu_532_p1);
    sensitive << ( tmp_36_fu_524_p3 );

    SC_METHOD(thread_tmp_1_35_cast_fu_544_p1);
    sensitive << ( tmp_37_fu_536_p3 );

    SC_METHOD(thread_tmp_1_36_cast_fu_556_p1);
    sensitive << ( tmp_38_fu_548_p3 );

    SC_METHOD(thread_tmp_1_37_cast_fu_568_p1);
    sensitive << ( tmp_39_fu_560_p3 );

    SC_METHOD(thread_tmp_1_38_cast_fu_580_p1);
    sensitive << ( tmp_40_fu_572_p3 );

    SC_METHOD(thread_tmp_1_39_cast_fu_592_p1);
    sensitive << ( tmp_41_fu_584_p3 );

    SC_METHOD(thread_tmp_1_3_cast_fu_148_p1);
    sensitive << ( tmp_4_fu_140_p3 );

    SC_METHOD(thread_tmp_1_40_cast_fu_604_p1);
    sensitive << ( tmp_42_fu_596_p3 );

    SC_METHOD(thread_tmp_1_41_cast_fu_616_p1);
    sensitive << ( tmp_43_fu_608_p3 );

    SC_METHOD(thread_tmp_1_42_cast_fu_628_p1);
    sensitive << ( tmp_44_fu_620_p3 );

    SC_METHOD(thread_tmp_1_43_cast_fu_640_p1);
    sensitive << ( tmp_45_fu_632_p3 );

    SC_METHOD(thread_tmp_1_44_cast_fu_652_p1);
    sensitive << ( tmp_46_fu_644_p3 );

    SC_METHOD(thread_tmp_1_45_cast_fu_664_p1);
    sensitive << ( tmp_47_fu_656_p3 );

    SC_METHOD(thread_tmp_1_46_cast_fu_676_p1);
    sensitive << ( tmp_48_fu_668_p3 );

    SC_METHOD(thread_tmp_1_4_cast_fu_160_p1);
    sensitive << ( tmp_5_fu_152_p3 );

    SC_METHOD(thread_tmp_1_5_cast_fu_172_p1);
    sensitive << ( tmp_6_fu_164_p3 );

    SC_METHOD(thread_tmp_1_6_cast_fu_184_p1);
    sensitive << ( tmp_7_fu_176_p3 );

    SC_METHOD(thread_tmp_1_7_cast_fu_196_p1);
    sensitive << ( tmp_8_fu_188_p3 );

    SC_METHOD(thread_tmp_1_8_cast_fu_208_p1);
    sensitive << ( tmp_9_fu_200_p3 );

    SC_METHOD(thread_tmp_1_9_cast_fu_220_p1);
    sensitive << ( tmp_10_fu_212_p3 );

    SC_METHOD(thread_tmp_1_cast_3_fu_232_p1);
    sensitive << ( tmp_11_fu_224_p3 );

    SC_METHOD(thread_tmp_1_cast_fu_112_p1);
    sensitive << ( tmp_1_fu_108_p1 );

    SC_METHOD(thread_tmp_1_fu_108_p1);
    sensitive << ( n_V );

    SC_METHOD(thread_tmp_20_fu_332_p3);
    sensitive << ( n_V );

    SC_METHOD(thread_tmp_21_fu_344_p3);
    sensitive << ( n_V );

    SC_METHOD(thread_tmp_22_fu_356_p3);
    sensitive << ( n_V );

    SC_METHOD(thread_tmp_23_fu_368_p3);
    sensitive << ( n_V );

    SC_METHOD(thread_tmp_24_fu_380_p3);
    sensitive << ( n_V );

    SC_METHOD(thread_tmp_25_fu_392_p3);
    sensitive << ( n_V );

    SC_METHOD(thread_tmp_26_fu_404_p3);
    sensitive << ( n_V );

    SC_METHOD(thread_tmp_27_fu_416_p3);
    sensitive << ( n_V );

    SC_METHOD(thread_tmp_28_fu_428_p3);
    sensitive << ( n_V );

    SC_METHOD(thread_tmp_29_fu_440_p3);
    sensitive << ( n_V );

    SC_METHOD(thread_tmp_2_fu_116_p3);
    sensitive << ( n_V );

    SC_METHOD(thread_tmp_30_fu_452_p3);
    sensitive << ( n_V );

    SC_METHOD(thread_tmp_31_fu_464_p3);
    sensitive << ( n_V );

    SC_METHOD(thread_tmp_32_fu_476_p3);
    sensitive << ( n_V );

    SC_METHOD(thread_tmp_33_fu_488_p3);
    sensitive << ( n_V );

    SC_METHOD(thread_tmp_34_fu_500_p3);
    sensitive << ( n_V );

    SC_METHOD(thread_tmp_35_fu_512_p3);
    sensitive << ( n_V );

    SC_METHOD(thread_tmp_36_fu_524_p3);
    sensitive << ( n_V );

    SC_METHOD(thread_tmp_37_fu_536_p3);
    sensitive << ( n_V );

    SC_METHOD(thread_tmp_38_fu_548_p3);
    sensitive << ( n_V );

    SC_METHOD(thread_tmp_39_fu_560_p3);
    sensitive << ( n_V );

    SC_METHOD(thread_tmp_3_fu_128_p3);
    sensitive << ( n_V );

    SC_METHOD(thread_tmp_40_fu_572_p3);
    sensitive << ( n_V );

    SC_METHOD(thread_tmp_41_fu_584_p3);
    sensitive << ( n_V );

    SC_METHOD(thread_tmp_42_fu_596_p3);
    sensitive << ( n_V );

    SC_METHOD(thread_tmp_43_fu_608_p3);
    sensitive << ( n_V );

    SC_METHOD(thread_tmp_44_fu_620_p3);
    sensitive << ( n_V );

    SC_METHOD(thread_tmp_45_fu_632_p3);
    sensitive << ( n_V );

    SC_METHOD(thread_tmp_46_fu_644_p3);
    sensitive << ( n_V );

    SC_METHOD(thread_tmp_47_cast_fu_688_p1);
    sensitive << ( tmp_49_fu_680_p3 );

    SC_METHOD(thread_tmp_47_fu_656_p3);
    sensitive << ( n_V );

    SC_METHOD(thread_tmp_48_fu_668_p3);
    sensitive << ( n_V );

    SC_METHOD(thread_tmp_49_fu_680_p3);
    sensitive << ( n_V );

    SC_METHOD(thread_tmp_4_fu_140_p3);
    sensitive << ( n_V );

    SC_METHOD(thread_tmp_5_fu_152_p3);
    sensitive << ( n_V );

    SC_METHOD(thread_tmp_6_fu_164_p3);
    sensitive << ( n_V );

    SC_METHOD(thread_tmp_7_fu_176_p3);
    sensitive << ( n_V );

    SC_METHOD(thread_tmp_8_fu_188_p3);
    sensitive << ( n_V );

    SC_METHOD(thread_tmp_9_fu_200_p3);
    sensitive << ( n_V );

    SC_METHOD(thread_tmp_cast_fu_886_p1);
    sensitive << ( tmp_fu_880_p2 );

    SC_METHOD(thread_tmp_fu_880_p2);
    sensitive << ( tmp1_cast_fu_782_p1 );
    sensitive << ( tmp12_cast_fu_876_p1 );

    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "digitrec_bitcount_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, n_V, "(port)n_V");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, tmp_1_fu_108_p1, "tmp_1_fu_108_p1");
    sc_trace(mVcdFile, tmp_2_fu_116_p3, "tmp_2_fu_116_p3");
    sc_trace(mVcdFile, tmp_3_fu_128_p3, "tmp_3_fu_128_p3");
    sc_trace(mVcdFile, tmp_4_fu_140_p3, "tmp_4_fu_140_p3");
    sc_trace(mVcdFile, tmp_5_fu_152_p3, "tmp_5_fu_152_p3");
    sc_trace(mVcdFile, tmp_6_fu_164_p3, "tmp_6_fu_164_p3");
    sc_trace(mVcdFile, tmp_7_fu_176_p3, "tmp_7_fu_176_p3");
    sc_trace(mVcdFile, tmp_8_fu_188_p3, "tmp_8_fu_188_p3");
    sc_trace(mVcdFile, tmp_9_fu_200_p3, "tmp_9_fu_200_p3");
    sc_trace(mVcdFile, tmp_10_fu_212_p3, "tmp_10_fu_212_p3");
    sc_trace(mVcdFile, tmp_11_fu_224_p3, "tmp_11_fu_224_p3");
    sc_trace(mVcdFile, tmp_12_fu_236_p3, "tmp_12_fu_236_p3");
    sc_trace(mVcdFile, tmp_13_fu_248_p3, "tmp_13_fu_248_p3");
    sc_trace(mVcdFile, tmp_14_fu_260_p3, "tmp_14_fu_260_p3");
    sc_trace(mVcdFile, tmp_15_fu_272_p3, "tmp_15_fu_272_p3");
    sc_trace(mVcdFile, tmp_16_fu_284_p3, "tmp_16_fu_284_p3");
    sc_trace(mVcdFile, tmp_17_fu_296_p3, "tmp_17_fu_296_p3");
    sc_trace(mVcdFile, tmp_18_fu_308_p3, "tmp_18_fu_308_p3");
    sc_trace(mVcdFile, tmp_19_fu_320_p3, "tmp_19_fu_320_p3");
    sc_trace(mVcdFile, tmp_20_fu_332_p3, "tmp_20_fu_332_p3");
    sc_trace(mVcdFile, tmp_21_fu_344_p3, "tmp_21_fu_344_p3");
    sc_trace(mVcdFile, tmp_22_fu_356_p3, "tmp_22_fu_356_p3");
    sc_trace(mVcdFile, tmp_23_fu_368_p3, "tmp_23_fu_368_p3");
    sc_trace(mVcdFile, tmp_24_fu_380_p3, "tmp_24_fu_380_p3");
    sc_trace(mVcdFile, tmp_25_fu_392_p3, "tmp_25_fu_392_p3");
    sc_trace(mVcdFile, tmp_26_fu_404_p3, "tmp_26_fu_404_p3");
    sc_trace(mVcdFile, tmp_27_fu_416_p3, "tmp_27_fu_416_p3");
    sc_trace(mVcdFile, tmp_28_fu_428_p3, "tmp_28_fu_428_p3");
    sc_trace(mVcdFile, tmp_29_fu_440_p3, "tmp_29_fu_440_p3");
    sc_trace(mVcdFile, tmp_30_fu_452_p3, "tmp_30_fu_452_p3");
    sc_trace(mVcdFile, tmp_31_fu_464_p3, "tmp_31_fu_464_p3");
    sc_trace(mVcdFile, tmp_32_fu_476_p3, "tmp_32_fu_476_p3");
    sc_trace(mVcdFile, tmp_33_fu_488_p3, "tmp_33_fu_488_p3");
    sc_trace(mVcdFile, tmp_34_fu_500_p3, "tmp_34_fu_500_p3");
    sc_trace(mVcdFile, tmp_35_fu_512_p3, "tmp_35_fu_512_p3");
    sc_trace(mVcdFile, tmp_36_fu_524_p3, "tmp_36_fu_524_p3");
    sc_trace(mVcdFile, tmp_37_fu_536_p3, "tmp_37_fu_536_p3");
    sc_trace(mVcdFile, tmp_38_fu_548_p3, "tmp_38_fu_548_p3");
    sc_trace(mVcdFile, tmp_39_fu_560_p3, "tmp_39_fu_560_p3");
    sc_trace(mVcdFile, tmp_40_fu_572_p3, "tmp_40_fu_572_p3");
    sc_trace(mVcdFile, tmp_41_fu_584_p3, "tmp_41_fu_584_p3");
    sc_trace(mVcdFile, tmp_42_fu_596_p3, "tmp_42_fu_596_p3");
    sc_trace(mVcdFile, tmp_43_fu_608_p3, "tmp_43_fu_608_p3");
    sc_trace(mVcdFile, tmp_44_fu_620_p3, "tmp_44_fu_620_p3");
    sc_trace(mVcdFile, tmp_45_fu_632_p3, "tmp_45_fu_632_p3");
    sc_trace(mVcdFile, tmp_46_fu_644_p3, "tmp_46_fu_644_p3");
    sc_trace(mVcdFile, tmp_47_fu_656_p3, "tmp_47_fu_656_p3");
    sc_trace(mVcdFile, tmp_48_fu_668_p3, "tmp_48_fu_668_p3");
    sc_trace(mVcdFile, tmp_49_fu_680_p3, "tmp_49_fu_680_p3");
    sc_trace(mVcdFile, tmp_1_2_cast_fu_136_p1, "tmp_1_2_cast_fu_136_p1");
    sc_trace(mVcdFile, tmp_1_1_cast_fu_124_p1, "tmp_1_1_cast_fu_124_p1");
    sc_trace(mVcdFile, tmp_1_cast_fu_112_p1, "tmp_1_cast_fu_112_p1");
    sc_trace(mVcdFile, tmp4_fu_692_p2, "tmp4_fu_692_p2");
    sc_trace(mVcdFile, tmp3_fu_698_p2, "tmp3_fu_698_p2");
    sc_trace(mVcdFile, tmp_1_5_cast_fu_172_p1, "tmp_1_5_cast_fu_172_p1");
    sc_trace(mVcdFile, tmp_1_4_cast_fu_160_p1, "tmp_1_4_cast_fu_160_p1");
    sc_trace(mVcdFile, tmp_1_3_cast_fu_148_p1, "tmp_1_3_cast_fu_148_p1");
    sc_trace(mVcdFile, tmp6_fu_708_p2, "tmp6_fu_708_p2");
    sc_trace(mVcdFile, tmp5_fu_714_p2, "tmp5_fu_714_p2");
    sc_trace(mVcdFile, tmp3_cast_fu_704_p1, "tmp3_cast_fu_704_p1");
    sc_trace(mVcdFile, tmp5_cast_fu_720_p1, "tmp5_cast_fu_720_p1");
    sc_trace(mVcdFile, tmp2_fu_724_p2, "tmp2_fu_724_p2");
    sc_trace(mVcdFile, tmp_1_8_cast_fu_208_p1, "tmp_1_8_cast_fu_208_p1");
    sc_trace(mVcdFile, tmp_1_7_cast_fu_196_p1, "tmp_1_7_cast_fu_196_p1");
    sc_trace(mVcdFile, tmp_1_6_cast_fu_184_p1, "tmp_1_6_cast_fu_184_p1");
    sc_trace(mVcdFile, tmp9_fu_734_p2, "tmp9_fu_734_p2");
    sc_trace(mVcdFile, tmp8_fu_740_p2, "tmp8_fu_740_p2");
    sc_trace(mVcdFile, tmp_1_10_cast_fu_244_p1, "tmp_1_10_cast_fu_244_p1");
    sc_trace(mVcdFile, tmp_1_cast_3_fu_232_p1, "tmp_1_cast_3_fu_232_p1");
    sc_trace(mVcdFile, tmp_1_9_cast_fu_220_p1, "tmp_1_9_cast_fu_220_p1");
    sc_trace(mVcdFile, tmp11_fu_750_p2, "tmp11_fu_750_p2");
    sc_trace(mVcdFile, tmp10_fu_756_p2, "tmp10_fu_756_p2");
    sc_trace(mVcdFile, tmp8_cast_fu_746_p1, "tmp8_cast_fu_746_p1");
    sc_trace(mVcdFile, tmp10_cast_fu_762_p1, "tmp10_cast_fu_762_p1");
    sc_trace(mVcdFile, tmp7_fu_766_p2, "tmp7_fu_766_p2");
    sc_trace(mVcdFile, tmp2_cast_fu_730_p1, "tmp2_cast_fu_730_p1");
    sc_trace(mVcdFile, tmp7_cast_fu_772_p1, "tmp7_cast_fu_772_p1");
    sc_trace(mVcdFile, tmp1_fu_776_p2, "tmp1_fu_776_p2");
    sc_trace(mVcdFile, tmp_1_13_cast_fu_280_p1, "tmp_1_13_cast_fu_280_p1");
    sc_trace(mVcdFile, tmp_1_12_cast_fu_268_p1, "tmp_1_12_cast_fu_268_p1");
    sc_trace(mVcdFile, tmp_1_11_cast_fu_256_p1, "tmp_1_11_cast_fu_256_p1");
    sc_trace(mVcdFile, tmp15_fu_786_p2, "tmp15_fu_786_p2");
    sc_trace(mVcdFile, tmp14_fu_792_p2, "tmp14_fu_792_p2");
    sc_trace(mVcdFile, tmp_1_16_cast_fu_316_p1, "tmp_1_16_cast_fu_316_p1");
    sc_trace(mVcdFile, tmp_1_15_cast_fu_304_p1, "tmp_1_15_cast_fu_304_p1");
    sc_trace(mVcdFile, tmp_1_14_cast_fu_292_p1, "tmp_1_14_cast_fu_292_p1");
    sc_trace(mVcdFile, tmp17_fu_802_p2, "tmp17_fu_802_p2");
    sc_trace(mVcdFile, tmp16_fu_808_p2, "tmp16_fu_808_p2");
    sc_trace(mVcdFile, tmp14_cast_fu_798_p1, "tmp14_cast_fu_798_p1");
    sc_trace(mVcdFile, tmp16_cast_fu_814_p1, "tmp16_cast_fu_814_p1");
    sc_trace(mVcdFile, tmp13_fu_818_p2, "tmp13_fu_818_p2");
    sc_trace(mVcdFile, tmp_1_19_cast_fu_352_p1, "tmp_1_19_cast_fu_352_p1");
    sc_trace(mVcdFile, tmp_1_18_cast_fu_340_p1, "tmp_1_18_cast_fu_340_p1");
    sc_trace(mVcdFile, tmp_1_17_cast_fu_328_p1, "tmp_1_17_cast_fu_328_p1");
    sc_trace(mVcdFile, tmp20_fu_828_p2, "tmp20_fu_828_p2");
    sc_trace(mVcdFile, tmp19_fu_834_p2, "tmp19_fu_834_p2");
    sc_trace(mVcdFile, tmp_1_22_cast_fu_388_p1, "tmp_1_22_cast_fu_388_p1");
    sc_trace(mVcdFile, tmp_1_21_cast_fu_376_p1, "tmp_1_21_cast_fu_376_p1");
    sc_trace(mVcdFile, tmp_1_20_cast_fu_364_p1, "tmp_1_20_cast_fu_364_p1");
    sc_trace(mVcdFile, tmp22_fu_844_p2, "tmp22_fu_844_p2");
    sc_trace(mVcdFile, tmp21_fu_850_p2, "tmp21_fu_850_p2");
    sc_trace(mVcdFile, tmp19_cast_fu_840_p1, "tmp19_cast_fu_840_p1");
    sc_trace(mVcdFile, tmp21_cast_fu_856_p1, "tmp21_cast_fu_856_p1");
    sc_trace(mVcdFile, tmp18_fu_860_p2, "tmp18_fu_860_p2");
    sc_trace(mVcdFile, tmp13_cast_fu_824_p1, "tmp13_cast_fu_824_p1");
    sc_trace(mVcdFile, tmp18_cast_fu_866_p1, "tmp18_cast_fu_866_p1");
    sc_trace(mVcdFile, tmp12_fu_870_p2, "tmp12_fu_870_p2");
    sc_trace(mVcdFile, tmp1_cast_fu_782_p1, "tmp1_cast_fu_782_p1");
    sc_trace(mVcdFile, tmp12_cast_fu_876_p1, "tmp12_cast_fu_876_p1");
    sc_trace(mVcdFile, tmp_fu_880_p2, "tmp_fu_880_p2");
    sc_trace(mVcdFile, tmp_1_25_cast_fu_424_p1, "tmp_1_25_cast_fu_424_p1");
    sc_trace(mVcdFile, tmp_1_24_cast_fu_412_p1, "tmp_1_24_cast_fu_412_p1");
    sc_trace(mVcdFile, tmp_1_23_cast_fu_400_p1, "tmp_1_23_cast_fu_400_p1");
    sc_trace(mVcdFile, tmp27_fu_890_p2, "tmp27_fu_890_p2");
    sc_trace(mVcdFile, tmp26_fu_896_p2, "tmp26_fu_896_p2");
    sc_trace(mVcdFile, tmp_1_28_cast_fu_460_p1, "tmp_1_28_cast_fu_460_p1");
    sc_trace(mVcdFile, tmp_1_27_cast_fu_448_p1, "tmp_1_27_cast_fu_448_p1");
    sc_trace(mVcdFile, tmp_1_26_cast_fu_436_p1, "tmp_1_26_cast_fu_436_p1");
    sc_trace(mVcdFile, tmp29_fu_906_p2, "tmp29_fu_906_p2");
    sc_trace(mVcdFile, tmp28_fu_912_p2, "tmp28_fu_912_p2");
    sc_trace(mVcdFile, tmp26_cast_fu_902_p1, "tmp26_cast_fu_902_p1");
    sc_trace(mVcdFile, tmp28_cast_fu_918_p1, "tmp28_cast_fu_918_p1");
    sc_trace(mVcdFile, tmp25_fu_922_p2, "tmp25_fu_922_p2");
    sc_trace(mVcdFile, tmp_1_31_cast_fu_496_p1, "tmp_1_31_cast_fu_496_p1");
    sc_trace(mVcdFile, tmp_1_30_cast_fu_484_p1, "tmp_1_30_cast_fu_484_p1");
    sc_trace(mVcdFile, tmp_1_29_cast_fu_472_p1, "tmp_1_29_cast_fu_472_p1");
    sc_trace(mVcdFile, tmp32_fu_932_p2, "tmp32_fu_932_p2");
    sc_trace(mVcdFile, tmp31_fu_938_p2, "tmp31_fu_938_p2");
    sc_trace(mVcdFile, tmp_1_34_cast_fu_532_p1, "tmp_1_34_cast_fu_532_p1");
    sc_trace(mVcdFile, tmp_1_33_cast_fu_520_p1, "tmp_1_33_cast_fu_520_p1");
    sc_trace(mVcdFile, tmp_1_32_cast_fu_508_p1, "tmp_1_32_cast_fu_508_p1");
    sc_trace(mVcdFile, tmp34_fu_948_p2, "tmp34_fu_948_p2");
    sc_trace(mVcdFile, tmp33_fu_954_p2, "tmp33_fu_954_p2");
    sc_trace(mVcdFile, tmp31_cast_fu_944_p1, "tmp31_cast_fu_944_p1");
    sc_trace(mVcdFile, tmp33_cast_fu_960_p1, "tmp33_cast_fu_960_p1");
    sc_trace(mVcdFile, tmp30_fu_964_p2, "tmp30_fu_964_p2");
    sc_trace(mVcdFile, tmp25_cast_fu_928_p1, "tmp25_cast_fu_928_p1");
    sc_trace(mVcdFile, tmp30_cast_fu_970_p1, "tmp30_cast_fu_970_p1");
    sc_trace(mVcdFile, tmp24_fu_974_p2, "tmp24_fu_974_p2");
    sc_trace(mVcdFile, tmp_1_37_cast_fu_568_p1, "tmp_1_37_cast_fu_568_p1");
    sc_trace(mVcdFile, tmp_1_36_cast_fu_556_p1, "tmp_1_36_cast_fu_556_p1");
    sc_trace(mVcdFile, tmp_1_35_cast_fu_544_p1, "tmp_1_35_cast_fu_544_p1");
    sc_trace(mVcdFile, tmp38_fu_984_p2, "tmp38_fu_984_p2");
    sc_trace(mVcdFile, tmp37_fu_990_p2, "tmp37_fu_990_p2");
    sc_trace(mVcdFile, tmp_1_40_cast_fu_604_p1, "tmp_1_40_cast_fu_604_p1");
    sc_trace(mVcdFile, tmp_1_39_cast_fu_592_p1, "tmp_1_39_cast_fu_592_p1");
    sc_trace(mVcdFile, tmp_1_38_cast_fu_580_p1, "tmp_1_38_cast_fu_580_p1");
    sc_trace(mVcdFile, tmp40_fu_1000_p2, "tmp40_fu_1000_p2");
    sc_trace(mVcdFile, tmp39_fu_1006_p2, "tmp39_fu_1006_p2");
    sc_trace(mVcdFile, tmp37_cast_fu_996_p1, "tmp37_cast_fu_996_p1");
    sc_trace(mVcdFile, tmp39_cast_fu_1012_p1, "tmp39_cast_fu_1012_p1");
    sc_trace(mVcdFile, tmp36_fu_1016_p2, "tmp36_fu_1016_p2");
    sc_trace(mVcdFile, tmp_1_43_cast_fu_640_p1, "tmp_1_43_cast_fu_640_p1");
    sc_trace(mVcdFile, tmp_1_42_cast_fu_628_p1, "tmp_1_42_cast_fu_628_p1");
    sc_trace(mVcdFile, tmp_1_41_cast_fu_616_p1, "tmp_1_41_cast_fu_616_p1");
    sc_trace(mVcdFile, tmp43_fu_1026_p2, "tmp43_fu_1026_p2");
    sc_trace(mVcdFile, tmp42_fu_1032_p2, "tmp42_fu_1032_p2");
    sc_trace(mVcdFile, tmp_1_45_cast_fu_664_p1, "tmp_1_45_cast_fu_664_p1");
    sc_trace(mVcdFile, tmp_1_44_cast_fu_652_p1, "tmp_1_44_cast_fu_652_p1");
    sc_trace(mVcdFile, tmp45_fu_1042_p2, "tmp45_fu_1042_p2");
    sc_trace(mVcdFile, tmp_47_cast_fu_688_p1, "tmp_47_cast_fu_688_p1");
    sc_trace(mVcdFile, tmp_1_46_cast_fu_676_p1, "tmp_1_46_cast_fu_676_p1");
    sc_trace(mVcdFile, tmp46_fu_1052_p2, "tmp46_fu_1052_p2");
    sc_trace(mVcdFile, tmp45_cast_fu_1048_p1, "tmp45_cast_fu_1048_p1");
    sc_trace(mVcdFile, tmp46_cast_fu_1058_p1, "tmp46_cast_fu_1058_p1");
    sc_trace(mVcdFile, tmp42_cast_fu_1038_p1, "tmp42_cast_fu_1038_p1");
    sc_trace(mVcdFile, tmp44_fu_1062_p2, "tmp44_fu_1062_p2");
    sc_trace(mVcdFile, tmp41_fu_1068_p2, "tmp41_fu_1068_p2");
    sc_trace(mVcdFile, tmp36_cast_fu_1022_p1, "tmp36_cast_fu_1022_p1");
    sc_trace(mVcdFile, tmp41_cast_fu_1074_p1, "tmp41_cast_fu_1074_p1");
    sc_trace(mVcdFile, tmp35_fu_1078_p2, "tmp35_fu_1078_p2");
    sc_trace(mVcdFile, tmp24_cast_fu_980_p1, "tmp24_cast_fu_980_p1");
    sc_trace(mVcdFile, tmp35_cast_fu_1084_p1, "tmp35_cast_fu_1084_p1");
    sc_trace(mVcdFile, tmp23_fu_1088_p2, "tmp23_fu_1088_p2");
    sc_trace(mVcdFile, tmp_cast_fu_886_p1, "tmp_cast_fu_886_p1");
    sc_trace(mVcdFile, tmp23_cast_fu_1094_p1, "tmp23_cast_fu_1094_p1");
#endif

    }
}

digitrec_bitcount::~digitrec_bitcount() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void digitrec_bitcount::thread_ap_return() {
    ap_return = (!tmp_cast_fu_886_p1.read().is_01() || !tmp23_cast_fu_1094_p1.read().is_01())? sc_lv<6>(): (sc_biguint<6>(tmp_cast_fu_886_p1.read()) + sc_biguint<6>(tmp23_cast_fu_1094_p1.read()));
}

void digitrec_bitcount::thread_tmp10_cast_fu_762_p1() {
    tmp10_cast_fu_762_p1 = esl_zext<3,2>(tmp10_fu_756_p2.read());
}

void digitrec_bitcount::thread_tmp10_fu_756_p2() {
    tmp10_fu_756_p2 = (!tmp_1_9_cast_fu_220_p1.read().is_01() || !tmp11_fu_750_p2.read().is_01())? sc_lv<2>(): (sc_biguint<2>(tmp_1_9_cast_fu_220_p1.read()) + sc_biguint<2>(tmp11_fu_750_p2.read()));
}

void digitrec_bitcount::thread_tmp11_fu_750_p2() {
    tmp11_fu_750_p2 = (!tmp_1_10_cast_fu_244_p1.read().is_01() || !tmp_1_cast_3_fu_232_p1.read().is_01())? sc_lv<2>(): (sc_biguint<2>(tmp_1_10_cast_fu_244_p1.read()) + sc_biguint<2>(tmp_1_cast_3_fu_232_p1.read()));
}

void digitrec_bitcount::thread_tmp12_cast_fu_876_p1() {
    tmp12_cast_fu_876_p1 = esl_zext<5,4>(tmp12_fu_870_p2.read());
}

void digitrec_bitcount::thread_tmp12_fu_870_p2() {
    tmp12_fu_870_p2 = (!tmp13_cast_fu_824_p1.read().is_01() || !tmp18_cast_fu_866_p1.read().is_01())? sc_lv<4>(): (sc_biguint<4>(tmp13_cast_fu_824_p1.read()) + sc_biguint<4>(tmp18_cast_fu_866_p1.read()));
}

void digitrec_bitcount::thread_tmp13_cast_fu_824_p1() {
    tmp13_cast_fu_824_p1 = esl_zext<4,3>(tmp13_fu_818_p2.read());
}

void digitrec_bitcount::thread_tmp13_fu_818_p2() {
    tmp13_fu_818_p2 = (!tmp14_cast_fu_798_p1.read().is_01() || !tmp16_cast_fu_814_p1.read().is_01())? sc_lv<3>(): (sc_biguint<3>(tmp14_cast_fu_798_p1.read()) + sc_biguint<3>(tmp16_cast_fu_814_p1.read()));
}

void digitrec_bitcount::thread_tmp14_cast_fu_798_p1() {
    tmp14_cast_fu_798_p1 = esl_zext<3,2>(tmp14_fu_792_p2.read());
}

void digitrec_bitcount::thread_tmp14_fu_792_p2() {
    tmp14_fu_792_p2 = (!tmp_1_11_cast_fu_256_p1.read().is_01() || !tmp15_fu_786_p2.read().is_01())? sc_lv<2>(): (sc_biguint<2>(tmp_1_11_cast_fu_256_p1.read()) + sc_biguint<2>(tmp15_fu_786_p2.read()));
}

void digitrec_bitcount::thread_tmp15_fu_786_p2() {
    tmp15_fu_786_p2 = (!tmp_1_13_cast_fu_280_p1.read().is_01() || !tmp_1_12_cast_fu_268_p1.read().is_01())? sc_lv<2>(): (sc_biguint<2>(tmp_1_13_cast_fu_280_p1.read()) + sc_biguint<2>(tmp_1_12_cast_fu_268_p1.read()));
}

void digitrec_bitcount::thread_tmp16_cast_fu_814_p1() {
    tmp16_cast_fu_814_p1 = esl_zext<3,2>(tmp16_fu_808_p2.read());
}

void digitrec_bitcount::thread_tmp16_fu_808_p2() {
    tmp16_fu_808_p2 = (!tmp_1_14_cast_fu_292_p1.read().is_01() || !tmp17_fu_802_p2.read().is_01())? sc_lv<2>(): (sc_biguint<2>(tmp_1_14_cast_fu_292_p1.read()) + sc_biguint<2>(tmp17_fu_802_p2.read()));
}

void digitrec_bitcount::thread_tmp17_fu_802_p2() {
    tmp17_fu_802_p2 = (!tmp_1_16_cast_fu_316_p1.read().is_01() || !tmp_1_15_cast_fu_304_p1.read().is_01())? sc_lv<2>(): (sc_biguint<2>(tmp_1_16_cast_fu_316_p1.read()) + sc_biguint<2>(tmp_1_15_cast_fu_304_p1.read()));
}

void digitrec_bitcount::thread_tmp18_cast_fu_866_p1() {
    tmp18_cast_fu_866_p1 = esl_zext<4,3>(tmp18_fu_860_p2.read());
}

void digitrec_bitcount::thread_tmp18_fu_860_p2() {
    tmp18_fu_860_p2 = (!tmp19_cast_fu_840_p1.read().is_01() || !tmp21_cast_fu_856_p1.read().is_01())? sc_lv<3>(): (sc_biguint<3>(tmp19_cast_fu_840_p1.read()) + sc_biguint<3>(tmp21_cast_fu_856_p1.read()));
}

void digitrec_bitcount::thread_tmp19_cast_fu_840_p1() {
    tmp19_cast_fu_840_p1 = esl_zext<3,2>(tmp19_fu_834_p2.read());
}

void digitrec_bitcount::thread_tmp19_fu_834_p2() {
    tmp19_fu_834_p2 = (!tmp_1_17_cast_fu_328_p1.read().is_01() || !tmp20_fu_828_p2.read().is_01())? sc_lv<2>(): (sc_biguint<2>(tmp_1_17_cast_fu_328_p1.read()) + sc_biguint<2>(tmp20_fu_828_p2.read()));
}

void digitrec_bitcount::thread_tmp1_cast_fu_782_p1() {
    tmp1_cast_fu_782_p1 = esl_zext<5,4>(tmp1_fu_776_p2.read());
}

void digitrec_bitcount::thread_tmp1_fu_776_p2() {
    tmp1_fu_776_p2 = (!tmp2_cast_fu_730_p1.read().is_01() || !tmp7_cast_fu_772_p1.read().is_01())? sc_lv<4>(): (sc_biguint<4>(tmp2_cast_fu_730_p1.read()) + sc_biguint<4>(tmp7_cast_fu_772_p1.read()));
}

void digitrec_bitcount::thread_tmp20_fu_828_p2() {
    tmp20_fu_828_p2 = (!tmp_1_19_cast_fu_352_p1.read().is_01() || !tmp_1_18_cast_fu_340_p1.read().is_01())? sc_lv<2>(): (sc_biguint<2>(tmp_1_19_cast_fu_352_p1.read()) + sc_biguint<2>(tmp_1_18_cast_fu_340_p1.read()));
}

void digitrec_bitcount::thread_tmp21_cast_fu_856_p1() {
    tmp21_cast_fu_856_p1 = esl_zext<3,2>(tmp21_fu_850_p2.read());
}

void digitrec_bitcount::thread_tmp21_fu_850_p2() {
    tmp21_fu_850_p2 = (!tmp_1_20_cast_fu_364_p1.read().is_01() || !tmp22_fu_844_p2.read().is_01())? sc_lv<2>(): (sc_biguint<2>(tmp_1_20_cast_fu_364_p1.read()) + sc_biguint<2>(tmp22_fu_844_p2.read()));
}

void digitrec_bitcount::thread_tmp22_fu_844_p2() {
    tmp22_fu_844_p2 = (!tmp_1_22_cast_fu_388_p1.read().is_01() || !tmp_1_21_cast_fu_376_p1.read().is_01())? sc_lv<2>(): (sc_biguint<2>(tmp_1_22_cast_fu_388_p1.read()) + sc_biguint<2>(tmp_1_21_cast_fu_376_p1.read()));
}

void digitrec_bitcount::thread_tmp23_cast_fu_1094_p1() {
    tmp23_cast_fu_1094_p1 = esl_zext<6,5>(tmp23_fu_1088_p2.read());
}

void digitrec_bitcount::thread_tmp23_fu_1088_p2() {
    tmp23_fu_1088_p2 = (!tmp24_cast_fu_980_p1.read().is_01() || !tmp35_cast_fu_1084_p1.read().is_01())? sc_lv<5>(): (sc_biguint<5>(tmp24_cast_fu_980_p1.read()) + sc_biguint<5>(tmp35_cast_fu_1084_p1.read()));
}

void digitrec_bitcount::thread_tmp24_cast_fu_980_p1() {
    tmp24_cast_fu_980_p1 = esl_zext<5,4>(tmp24_fu_974_p2.read());
}

void digitrec_bitcount::thread_tmp24_fu_974_p2() {
    tmp24_fu_974_p2 = (!tmp25_cast_fu_928_p1.read().is_01() || !tmp30_cast_fu_970_p1.read().is_01())? sc_lv<4>(): (sc_biguint<4>(tmp25_cast_fu_928_p1.read()) + sc_biguint<4>(tmp30_cast_fu_970_p1.read()));
}

void digitrec_bitcount::thread_tmp25_cast_fu_928_p1() {
    tmp25_cast_fu_928_p1 = esl_zext<4,3>(tmp25_fu_922_p2.read());
}

void digitrec_bitcount::thread_tmp25_fu_922_p2() {
    tmp25_fu_922_p2 = (!tmp26_cast_fu_902_p1.read().is_01() || !tmp28_cast_fu_918_p1.read().is_01())? sc_lv<3>(): (sc_biguint<3>(tmp26_cast_fu_902_p1.read()) + sc_biguint<3>(tmp28_cast_fu_918_p1.read()));
}

void digitrec_bitcount::thread_tmp26_cast_fu_902_p1() {
    tmp26_cast_fu_902_p1 = esl_zext<3,2>(tmp26_fu_896_p2.read());
}

void digitrec_bitcount::thread_tmp26_fu_896_p2() {
    tmp26_fu_896_p2 = (!tmp_1_23_cast_fu_400_p1.read().is_01() || !tmp27_fu_890_p2.read().is_01())? sc_lv<2>(): (sc_biguint<2>(tmp_1_23_cast_fu_400_p1.read()) + sc_biguint<2>(tmp27_fu_890_p2.read()));
}

void digitrec_bitcount::thread_tmp27_fu_890_p2() {
    tmp27_fu_890_p2 = (!tmp_1_25_cast_fu_424_p1.read().is_01() || !tmp_1_24_cast_fu_412_p1.read().is_01())? sc_lv<2>(): (sc_biguint<2>(tmp_1_25_cast_fu_424_p1.read()) + sc_biguint<2>(tmp_1_24_cast_fu_412_p1.read()));
}

void digitrec_bitcount::thread_tmp28_cast_fu_918_p1() {
    tmp28_cast_fu_918_p1 = esl_zext<3,2>(tmp28_fu_912_p2.read());
}

void digitrec_bitcount::thread_tmp28_fu_912_p2() {
    tmp28_fu_912_p2 = (!tmp_1_26_cast_fu_436_p1.read().is_01() || !tmp29_fu_906_p2.read().is_01())? sc_lv<2>(): (sc_biguint<2>(tmp_1_26_cast_fu_436_p1.read()) + sc_biguint<2>(tmp29_fu_906_p2.read()));
}

void digitrec_bitcount::thread_tmp29_fu_906_p2() {
    tmp29_fu_906_p2 = (!tmp_1_28_cast_fu_460_p1.read().is_01() || !tmp_1_27_cast_fu_448_p1.read().is_01())? sc_lv<2>(): (sc_biguint<2>(tmp_1_28_cast_fu_460_p1.read()) + sc_biguint<2>(tmp_1_27_cast_fu_448_p1.read()));
}

void digitrec_bitcount::thread_tmp2_cast_fu_730_p1() {
    tmp2_cast_fu_730_p1 = esl_zext<4,3>(tmp2_fu_724_p2.read());
}

void digitrec_bitcount::thread_tmp2_fu_724_p2() {
    tmp2_fu_724_p2 = (!tmp3_cast_fu_704_p1.read().is_01() || !tmp5_cast_fu_720_p1.read().is_01())? sc_lv<3>(): (sc_biguint<3>(tmp3_cast_fu_704_p1.read()) + sc_biguint<3>(tmp5_cast_fu_720_p1.read()));
}

void digitrec_bitcount::thread_tmp30_cast_fu_970_p1() {
    tmp30_cast_fu_970_p1 = esl_zext<4,3>(tmp30_fu_964_p2.read());
}

void digitrec_bitcount::thread_tmp30_fu_964_p2() {
    tmp30_fu_964_p2 = (!tmp31_cast_fu_944_p1.read().is_01() || !tmp33_cast_fu_960_p1.read().is_01())? sc_lv<3>(): (sc_biguint<3>(tmp31_cast_fu_944_p1.read()) + sc_biguint<3>(tmp33_cast_fu_960_p1.read()));
}

void digitrec_bitcount::thread_tmp31_cast_fu_944_p1() {
    tmp31_cast_fu_944_p1 = esl_zext<3,2>(tmp31_fu_938_p2.read());
}

void digitrec_bitcount::thread_tmp31_fu_938_p2() {
    tmp31_fu_938_p2 = (!tmp_1_29_cast_fu_472_p1.read().is_01() || !tmp32_fu_932_p2.read().is_01())? sc_lv<2>(): (sc_biguint<2>(tmp_1_29_cast_fu_472_p1.read()) + sc_biguint<2>(tmp32_fu_932_p2.read()));
}

void digitrec_bitcount::thread_tmp32_fu_932_p2() {
    tmp32_fu_932_p2 = (!tmp_1_31_cast_fu_496_p1.read().is_01() || !tmp_1_30_cast_fu_484_p1.read().is_01())? sc_lv<2>(): (sc_biguint<2>(tmp_1_31_cast_fu_496_p1.read()) + sc_biguint<2>(tmp_1_30_cast_fu_484_p1.read()));
}

void digitrec_bitcount::thread_tmp33_cast_fu_960_p1() {
    tmp33_cast_fu_960_p1 = esl_zext<3,2>(tmp33_fu_954_p2.read());
}

void digitrec_bitcount::thread_tmp33_fu_954_p2() {
    tmp33_fu_954_p2 = (!tmp_1_32_cast_fu_508_p1.read().is_01() || !tmp34_fu_948_p2.read().is_01())? sc_lv<2>(): (sc_biguint<2>(tmp_1_32_cast_fu_508_p1.read()) + sc_biguint<2>(tmp34_fu_948_p2.read()));
}

void digitrec_bitcount::thread_tmp34_fu_948_p2() {
    tmp34_fu_948_p2 = (!tmp_1_34_cast_fu_532_p1.read().is_01() || !tmp_1_33_cast_fu_520_p1.read().is_01())? sc_lv<2>(): (sc_biguint<2>(tmp_1_34_cast_fu_532_p1.read()) + sc_biguint<2>(tmp_1_33_cast_fu_520_p1.read()));
}

void digitrec_bitcount::thread_tmp35_cast_fu_1084_p1() {
    tmp35_cast_fu_1084_p1 = esl_zext<5,4>(tmp35_fu_1078_p2.read());
}

void digitrec_bitcount::thread_tmp35_fu_1078_p2() {
    tmp35_fu_1078_p2 = (!tmp36_cast_fu_1022_p1.read().is_01() || !tmp41_cast_fu_1074_p1.read().is_01())? sc_lv<4>(): (sc_biguint<4>(tmp36_cast_fu_1022_p1.read()) + sc_biguint<4>(tmp41_cast_fu_1074_p1.read()));
}

void digitrec_bitcount::thread_tmp36_cast_fu_1022_p1() {
    tmp36_cast_fu_1022_p1 = esl_zext<4,3>(tmp36_fu_1016_p2.read());
}

void digitrec_bitcount::thread_tmp36_fu_1016_p2() {
    tmp36_fu_1016_p2 = (!tmp37_cast_fu_996_p1.read().is_01() || !tmp39_cast_fu_1012_p1.read().is_01())? sc_lv<3>(): (sc_biguint<3>(tmp37_cast_fu_996_p1.read()) + sc_biguint<3>(tmp39_cast_fu_1012_p1.read()));
}

void digitrec_bitcount::thread_tmp37_cast_fu_996_p1() {
    tmp37_cast_fu_996_p1 = esl_zext<3,2>(tmp37_fu_990_p2.read());
}

void digitrec_bitcount::thread_tmp37_fu_990_p2() {
    tmp37_fu_990_p2 = (!tmp_1_35_cast_fu_544_p1.read().is_01() || !tmp38_fu_984_p2.read().is_01())? sc_lv<2>(): (sc_biguint<2>(tmp_1_35_cast_fu_544_p1.read()) + sc_biguint<2>(tmp38_fu_984_p2.read()));
}

void digitrec_bitcount::thread_tmp38_fu_984_p2() {
    tmp38_fu_984_p2 = (!tmp_1_37_cast_fu_568_p1.read().is_01() || !tmp_1_36_cast_fu_556_p1.read().is_01())? sc_lv<2>(): (sc_biguint<2>(tmp_1_37_cast_fu_568_p1.read()) + sc_biguint<2>(tmp_1_36_cast_fu_556_p1.read()));
}

void digitrec_bitcount::thread_tmp39_cast_fu_1012_p1() {
    tmp39_cast_fu_1012_p1 = esl_zext<3,2>(tmp39_fu_1006_p2.read());
}

void digitrec_bitcount::thread_tmp39_fu_1006_p2() {
    tmp39_fu_1006_p2 = (!tmp_1_38_cast_fu_580_p1.read().is_01() || !tmp40_fu_1000_p2.read().is_01())? sc_lv<2>(): (sc_biguint<2>(tmp_1_38_cast_fu_580_p1.read()) + sc_biguint<2>(tmp40_fu_1000_p2.read()));
}

void digitrec_bitcount::thread_tmp3_cast_fu_704_p1() {
    tmp3_cast_fu_704_p1 = esl_zext<3,2>(tmp3_fu_698_p2.read());
}

void digitrec_bitcount::thread_tmp3_fu_698_p2() {
    tmp3_fu_698_p2 = (!tmp_1_cast_fu_112_p1.read().is_01() || !tmp4_fu_692_p2.read().is_01())? sc_lv<2>(): (sc_biguint<2>(tmp_1_cast_fu_112_p1.read()) + sc_biguint<2>(tmp4_fu_692_p2.read()));
}

void digitrec_bitcount::thread_tmp40_fu_1000_p2() {
    tmp40_fu_1000_p2 = (!tmp_1_40_cast_fu_604_p1.read().is_01() || !tmp_1_39_cast_fu_592_p1.read().is_01())? sc_lv<2>(): (sc_biguint<2>(tmp_1_40_cast_fu_604_p1.read()) + sc_biguint<2>(tmp_1_39_cast_fu_592_p1.read()));
}

void digitrec_bitcount::thread_tmp41_cast_fu_1074_p1() {
    tmp41_cast_fu_1074_p1 = esl_zext<4,3>(tmp41_fu_1068_p2.read());
}

void digitrec_bitcount::thread_tmp41_fu_1068_p2() {
    tmp41_fu_1068_p2 = (!tmp42_cast_fu_1038_p1.read().is_01() || !tmp44_fu_1062_p2.read().is_01())? sc_lv<3>(): (sc_biguint<3>(tmp42_cast_fu_1038_p1.read()) + sc_biguint<3>(tmp44_fu_1062_p2.read()));
}

void digitrec_bitcount::thread_tmp42_cast_fu_1038_p1() {
    tmp42_cast_fu_1038_p1 = esl_zext<3,2>(tmp42_fu_1032_p2.read());
}

void digitrec_bitcount::thread_tmp42_fu_1032_p2() {
    tmp42_fu_1032_p2 = (!tmp_1_41_cast_fu_616_p1.read().is_01() || !tmp43_fu_1026_p2.read().is_01())? sc_lv<2>(): (sc_biguint<2>(tmp_1_41_cast_fu_616_p1.read()) + sc_biguint<2>(tmp43_fu_1026_p2.read()));
}

void digitrec_bitcount::thread_tmp43_fu_1026_p2() {
    tmp43_fu_1026_p2 = (!tmp_1_43_cast_fu_640_p1.read().is_01() || !tmp_1_42_cast_fu_628_p1.read().is_01())? sc_lv<2>(): (sc_biguint<2>(tmp_1_43_cast_fu_640_p1.read()) + sc_biguint<2>(tmp_1_42_cast_fu_628_p1.read()));
}

void digitrec_bitcount::thread_tmp44_fu_1062_p2() {
    tmp44_fu_1062_p2 = (!tmp45_cast_fu_1048_p1.read().is_01() || !tmp46_cast_fu_1058_p1.read().is_01())? sc_lv<3>(): (sc_biguint<3>(tmp45_cast_fu_1048_p1.read()) + sc_biguint<3>(tmp46_cast_fu_1058_p1.read()));
}

void digitrec_bitcount::thread_tmp45_cast_fu_1048_p1() {
    tmp45_cast_fu_1048_p1 = esl_zext<3,2>(tmp45_fu_1042_p2.read());
}

void digitrec_bitcount::thread_tmp45_fu_1042_p2() {
    tmp45_fu_1042_p2 = (!tmp_1_45_cast_fu_664_p1.read().is_01() || !tmp_1_44_cast_fu_652_p1.read().is_01())? sc_lv<2>(): (sc_biguint<2>(tmp_1_45_cast_fu_664_p1.read()) + sc_biguint<2>(tmp_1_44_cast_fu_652_p1.read()));
}

void digitrec_bitcount::thread_tmp46_cast_fu_1058_p1() {
    tmp46_cast_fu_1058_p1 = esl_zext<3,2>(tmp46_fu_1052_p2.read());
}

void digitrec_bitcount::thread_tmp46_fu_1052_p2() {
    tmp46_fu_1052_p2 = (!tmp_47_cast_fu_688_p1.read().is_01() || !tmp_1_46_cast_fu_676_p1.read().is_01())? sc_lv<2>(): (sc_biguint<2>(tmp_47_cast_fu_688_p1.read()) + sc_biguint<2>(tmp_1_46_cast_fu_676_p1.read()));
}

void digitrec_bitcount::thread_tmp4_fu_692_p2() {
    tmp4_fu_692_p2 = (!tmp_1_2_cast_fu_136_p1.read().is_01() || !tmp_1_1_cast_fu_124_p1.read().is_01())? sc_lv<2>(): (sc_biguint<2>(tmp_1_2_cast_fu_136_p1.read()) + sc_biguint<2>(tmp_1_1_cast_fu_124_p1.read()));
}

void digitrec_bitcount::thread_tmp5_cast_fu_720_p1() {
    tmp5_cast_fu_720_p1 = esl_zext<3,2>(tmp5_fu_714_p2.read());
}

void digitrec_bitcount::thread_tmp5_fu_714_p2() {
    tmp5_fu_714_p2 = (!tmp_1_3_cast_fu_148_p1.read().is_01() || !tmp6_fu_708_p2.read().is_01())? sc_lv<2>(): (sc_biguint<2>(tmp_1_3_cast_fu_148_p1.read()) + sc_biguint<2>(tmp6_fu_708_p2.read()));
}

void digitrec_bitcount::thread_tmp6_fu_708_p2() {
    tmp6_fu_708_p2 = (!tmp_1_5_cast_fu_172_p1.read().is_01() || !tmp_1_4_cast_fu_160_p1.read().is_01())? sc_lv<2>(): (sc_biguint<2>(tmp_1_5_cast_fu_172_p1.read()) + sc_biguint<2>(tmp_1_4_cast_fu_160_p1.read()));
}

void digitrec_bitcount::thread_tmp7_cast_fu_772_p1() {
    tmp7_cast_fu_772_p1 = esl_zext<4,3>(tmp7_fu_766_p2.read());
}

void digitrec_bitcount::thread_tmp7_fu_766_p2() {
    tmp7_fu_766_p2 = (!tmp8_cast_fu_746_p1.read().is_01() || !tmp10_cast_fu_762_p1.read().is_01())? sc_lv<3>(): (sc_biguint<3>(tmp8_cast_fu_746_p1.read()) + sc_biguint<3>(tmp10_cast_fu_762_p1.read()));
}

void digitrec_bitcount::thread_tmp8_cast_fu_746_p1() {
    tmp8_cast_fu_746_p1 = esl_zext<3,2>(tmp8_fu_740_p2.read());
}

void digitrec_bitcount::thread_tmp8_fu_740_p2() {
    tmp8_fu_740_p2 = (!tmp_1_6_cast_fu_184_p1.read().is_01() || !tmp9_fu_734_p2.read().is_01())? sc_lv<2>(): (sc_biguint<2>(tmp_1_6_cast_fu_184_p1.read()) + sc_biguint<2>(tmp9_fu_734_p2.read()));
}

void digitrec_bitcount::thread_tmp9_fu_734_p2() {
    tmp9_fu_734_p2 = (!tmp_1_8_cast_fu_208_p1.read().is_01() || !tmp_1_7_cast_fu_196_p1.read().is_01())? sc_lv<2>(): (sc_biguint<2>(tmp_1_8_cast_fu_208_p1.read()) + sc_biguint<2>(tmp_1_7_cast_fu_196_p1.read()));
}

void digitrec_bitcount::thread_tmp_10_fu_212_p3() {
    tmp_10_fu_212_p3 = n_V.read().range(9, 9);
}

void digitrec_bitcount::thread_tmp_11_fu_224_p3() {
    tmp_11_fu_224_p3 = n_V.read().range(10, 10);
}

void digitrec_bitcount::thread_tmp_12_fu_236_p3() {
    tmp_12_fu_236_p3 = n_V.read().range(11, 11);
}

void digitrec_bitcount::thread_tmp_13_fu_248_p3() {
    tmp_13_fu_248_p3 = n_V.read().range(12, 12);
}

void digitrec_bitcount::thread_tmp_14_fu_260_p3() {
    tmp_14_fu_260_p3 = n_V.read().range(13, 13);
}

void digitrec_bitcount::thread_tmp_15_fu_272_p3() {
    tmp_15_fu_272_p3 = n_V.read().range(14, 14);
}

void digitrec_bitcount::thread_tmp_16_fu_284_p3() {
    tmp_16_fu_284_p3 = n_V.read().range(15, 15);
}

void digitrec_bitcount::thread_tmp_17_fu_296_p3() {
    tmp_17_fu_296_p3 = n_V.read().range(16, 16);
}

void digitrec_bitcount::thread_tmp_18_fu_308_p3() {
    tmp_18_fu_308_p3 = n_V.read().range(17, 17);
}

void digitrec_bitcount::thread_tmp_19_fu_320_p3() {
    tmp_19_fu_320_p3 = n_V.read().range(18, 18);
}

void digitrec_bitcount::thread_tmp_1_10_cast_fu_244_p1() {
    tmp_1_10_cast_fu_244_p1 = esl_zext<2,1>(tmp_12_fu_236_p3.read());
}

void digitrec_bitcount::thread_tmp_1_11_cast_fu_256_p1() {
    tmp_1_11_cast_fu_256_p1 = esl_zext<2,1>(tmp_13_fu_248_p3.read());
}

void digitrec_bitcount::thread_tmp_1_12_cast_fu_268_p1() {
    tmp_1_12_cast_fu_268_p1 = esl_zext<2,1>(tmp_14_fu_260_p3.read());
}

void digitrec_bitcount::thread_tmp_1_13_cast_fu_280_p1() {
    tmp_1_13_cast_fu_280_p1 = esl_zext<2,1>(tmp_15_fu_272_p3.read());
}

void digitrec_bitcount::thread_tmp_1_14_cast_fu_292_p1() {
    tmp_1_14_cast_fu_292_p1 = esl_zext<2,1>(tmp_16_fu_284_p3.read());
}

void digitrec_bitcount::thread_tmp_1_15_cast_fu_304_p1() {
    tmp_1_15_cast_fu_304_p1 = esl_zext<2,1>(tmp_17_fu_296_p3.read());
}

void digitrec_bitcount::thread_tmp_1_16_cast_fu_316_p1() {
    tmp_1_16_cast_fu_316_p1 = esl_zext<2,1>(tmp_18_fu_308_p3.read());
}

void digitrec_bitcount::thread_tmp_1_17_cast_fu_328_p1() {
    tmp_1_17_cast_fu_328_p1 = esl_zext<2,1>(tmp_19_fu_320_p3.read());
}

void digitrec_bitcount::thread_tmp_1_18_cast_fu_340_p1() {
    tmp_1_18_cast_fu_340_p1 = esl_zext<2,1>(tmp_20_fu_332_p3.read());
}

void digitrec_bitcount::thread_tmp_1_19_cast_fu_352_p1() {
    tmp_1_19_cast_fu_352_p1 = esl_zext<2,1>(tmp_21_fu_344_p3.read());
}

void digitrec_bitcount::thread_tmp_1_1_cast_fu_124_p1() {
    tmp_1_1_cast_fu_124_p1 = esl_zext<2,1>(tmp_2_fu_116_p3.read());
}

void digitrec_bitcount::thread_tmp_1_20_cast_fu_364_p1() {
    tmp_1_20_cast_fu_364_p1 = esl_zext<2,1>(tmp_22_fu_356_p3.read());
}

void digitrec_bitcount::thread_tmp_1_21_cast_fu_376_p1() {
    tmp_1_21_cast_fu_376_p1 = esl_zext<2,1>(tmp_23_fu_368_p3.read());
}

void digitrec_bitcount::thread_tmp_1_22_cast_fu_388_p1() {
    tmp_1_22_cast_fu_388_p1 = esl_zext<2,1>(tmp_24_fu_380_p3.read());
}

void digitrec_bitcount::thread_tmp_1_23_cast_fu_400_p1() {
    tmp_1_23_cast_fu_400_p1 = esl_zext<2,1>(tmp_25_fu_392_p3.read());
}

void digitrec_bitcount::thread_tmp_1_24_cast_fu_412_p1() {
    tmp_1_24_cast_fu_412_p1 = esl_zext<2,1>(tmp_26_fu_404_p3.read());
}

void digitrec_bitcount::thread_tmp_1_25_cast_fu_424_p1() {
    tmp_1_25_cast_fu_424_p1 = esl_zext<2,1>(tmp_27_fu_416_p3.read());
}

void digitrec_bitcount::thread_tmp_1_26_cast_fu_436_p1() {
    tmp_1_26_cast_fu_436_p1 = esl_zext<2,1>(tmp_28_fu_428_p3.read());
}

void digitrec_bitcount::thread_tmp_1_27_cast_fu_448_p1() {
    tmp_1_27_cast_fu_448_p1 = esl_zext<2,1>(tmp_29_fu_440_p3.read());
}

void digitrec_bitcount::thread_tmp_1_28_cast_fu_460_p1() {
    tmp_1_28_cast_fu_460_p1 = esl_zext<2,1>(tmp_30_fu_452_p3.read());
}

void digitrec_bitcount::thread_tmp_1_29_cast_fu_472_p1() {
    tmp_1_29_cast_fu_472_p1 = esl_zext<2,1>(tmp_31_fu_464_p3.read());
}

void digitrec_bitcount::thread_tmp_1_2_cast_fu_136_p1() {
    tmp_1_2_cast_fu_136_p1 = esl_zext<2,1>(tmp_3_fu_128_p3.read());
}

void digitrec_bitcount::thread_tmp_1_30_cast_fu_484_p1() {
    tmp_1_30_cast_fu_484_p1 = esl_zext<2,1>(tmp_32_fu_476_p3.read());
}

void digitrec_bitcount::thread_tmp_1_31_cast_fu_496_p1() {
    tmp_1_31_cast_fu_496_p1 = esl_zext<2,1>(tmp_33_fu_488_p3.read());
}

void digitrec_bitcount::thread_tmp_1_32_cast_fu_508_p1() {
    tmp_1_32_cast_fu_508_p1 = esl_zext<2,1>(tmp_34_fu_500_p3.read());
}

void digitrec_bitcount::thread_tmp_1_33_cast_fu_520_p1() {
    tmp_1_33_cast_fu_520_p1 = esl_zext<2,1>(tmp_35_fu_512_p3.read());
}

void digitrec_bitcount::thread_tmp_1_34_cast_fu_532_p1() {
    tmp_1_34_cast_fu_532_p1 = esl_zext<2,1>(tmp_36_fu_524_p3.read());
}

void digitrec_bitcount::thread_tmp_1_35_cast_fu_544_p1() {
    tmp_1_35_cast_fu_544_p1 = esl_zext<2,1>(tmp_37_fu_536_p3.read());
}

void digitrec_bitcount::thread_tmp_1_36_cast_fu_556_p1() {
    tmp_1_36_cast_fu_556_p1 = esl_zext<2,1>(tmp_38_fu_548_p3.read());
}

void digitrec_bitcount::thread_tmp_1_37_cast_fu_568_p1() {
    tmp_1_37_cast_fu_568_p1 = esl_zext<2,1>(tmp_39_fu_560_p3.read());
}

void digitrec_bitcount::thread_tmp_1_38_cast_fu_580_p1() {
    tmp_1_38_cast_fu_580_p1 = esl_zext<2,1>(tmp_40_fu_572_p3.read());
}

void digitrec_bitcount::thread_tmp_1_39_cast_fu_592_p1() {
    tmp_1_39_cast_fu_592_p1 = esl_zext<2,1>(tmp_41_fu_584_p3.read());
}

void digitrec_bitcount::thread_tmp_1_3_cast_fu_148_p1() {
    tmp_1_3_cast_fu_148_p1 = esl_zext<2,1>(tmp_4_fu_140_p3.read());
}

void digitrec_bitcount::thread_tmp_1_40_cast_fu_604_p1() {
    tmp_1_40_cast_fu_604_p1 = esl_zext<2,1>(tmp_42_fu_596_p3.read());
}

void digitrec_bitcount::thread_tmp_1_41_cast_fu_616_p1() {
    tmp_1_41_cast_fu_616_p1 = esl_zext<2,1>(tmp_43_fu_608_p3.read());
}

void digitrec_bitcount::thread_tmp_1_42_cast_fu_628_p1() {
    tmp_1_42_cast_fu_628_p1 = esl_zext<2,1>(tmp_44_fu_620_p3.read());
}

void digitrec_bitcount::thread_tmp_1_43_cast_fu_640_p1() {
    tmp_1_43_cast_fu_640_p1 = esl_zext<2,1>(tmp_45_fu_632_p3.read());
}

void digitrec_bitcount::thread_tmp_1_44_cast_fu_652_p1() {
    tmp_1_44_cast_fu_652_p1 = esl_zext<2,1>(tmp_46_fu_644_p3.read());
}

void digitrec_bitcount::thread_tmp_1_45_cast_fu_664_p1() {
    tmp_1_45_cast_fu_664_p1 = esl_zext<2,1>(tmp_47_fu_656_p3.read());
}

void digitrec_bitcount::thread_tmp_1_46_cast_fu_676_p1() {
    tmp_1_46_cast_fu_676_p1 = esl_zext<2,1>(tmp_48_fu_668_p3.read());
}

void digitrec_bitcount::thread_tmp_1_4_cast_fu_160_p1() {
    tmp_1_4_cast_fu_160_p1 = esl_zext<2,1>(tmp_5_fu_152_p3.read());
}

void digitrec_bitcount::thread_tmp_1_5_cast_fu_172_p1() {
    tmp_1_5_cast_fu_172_p1 = esl_zext<2,1>(tmp_6_fu_164_p3.read());
}

void digitrec_bitcount::thread_tmp_1_6_cast_fu_184_p1() {
    tmp_1_6_cast_fu_184_p1 = esl_zext<2,1>(tmp_7_fu_176_p3.read());
}

void digitrec_bitcount::thread_tmp_1_7_cast_fu_196_p1() {
    tmp_1_7_cast_fu_196_p1 = esl_zext<2,1>(tmp_8_fu_188_p3.read());
}

void digitrec_bitcount::thread_tmp_1_8_cast_fu_208_p1() {
    tmp_1_8_cast_fu_208_p1 = esl_zext<2,1>(tmp_9_fu_200_p3.read());
}

void digitrec_bitcount::thread_tmp_1_9_cast_fu_220_p1() {
    tmp_1_9_cast_fu_220_p1 = esl_zext<2,1>(tmp_10_fu_212_p3.read());
}

void digitrec_bitcount::thread_tmp_1_cast_3_fu_232_p1() {
    tmp_1_cast_3_fu_232_p1 = esl_zext<2,1>(tmp_11_fu_224_p3.read());
}

void digitrec_bitcount::thread_tmp_1_cast_fu_112_p1() {
    tmp_1_cast_fu_112_p1 = esl_zext<2,1>(tmp_1_fu_108_p1.read());
}

void digitrec_bitcount::thread_tmp_1_fu_108_p1() {
    tmp_1_fu_108_p1 = n_V.read().range(1-1, 0);
}

void digitrec_bitcount::thread_tmp_20_fu_332_p3() {
    tmp_20_fu_332_p3 = n_V.read().range(19, 19);
}

void digitrec_bitcount::thread_tmp_21_fu_344_p3() {
    tmp_21_fu_344_p3 = n_V.read().range(20, 20);
}

void digitrec_bitcount::thread_tmp_22_fu_356_p3() {
    tmp_22_fu_356_p3 = n_V.read().range(21, 21);
}

void digitrec_bitcount::thread_tmp_23_fu_368_p3() {
    tmp_23_fu_368_p3 = n_V.read().range(22, 22);
}

void digitrec_bitcount::thread_tmp_24_fu_380_p3() {
    tmp_24_fu_380_p3 = n_V.read().range(23, 23);
}

void digitrec_bitcount::thread_tmp_25_fu_392_p3() {
    tmp_25_fu_392_p3 = n_V.read().range(24, 24);
}

void digitrec_bitcount::thread_tmp_26_fu_404_p3() {
    tmp_26_fu_404_p3 = n_V.read().range(25, 25);
}

void digitrec_bitcount::thread_tmp_27_fu_416_p3() {
    tmp_27_fu_416_p3 = n_V.read().range(26, 26);
}

void digitrec_bitcount::thread_tmp_28_fu_428_p3() {
    tmp_28_fu_428_p3 = n_V.read().range(27, 27);
}

void digitrec_bitcount::thread_tmp_29_fu_440_p3() {
    tmp_29_fu_440_p3 = n_V.read().range(28, 28);
}

void digitrec_bitcount::thread_tmp_2_fu_116_p3() {
    tmp_2_fu_116_p3 = n_V.read().range(1, 1);
}

void digitrec_bitcount::thread_tmp_30_fu_452_p3() {
    tmp_30_fu_452_p3 = n_V.read().range(29, 29);
}

void digitrec_bitcount::thread_tmp_31_fu_464_p3() {
    tmp_31_fu_464_p3 = n_V.read().range(30, 30);
}

void digitrec_bitcount::thread_tmp_32_fu_476_p3() {
    tmp_32_fu_476_p3 = n_V.read().range(31, 31);
}

void digitrec_bitcount::thread_tmp_33_fu_488_p3() {
    tmp_33_fu_488_p3 = n_V.read().range(32, 32);
}

void digitrec_bitcount::thread_tmp_34_fu_500_p3() {
    tmp_34_fu_500_p3 = n_V.read().range(33, 33);
}

void digitrec_bitcount::thread_tmp_35_fu_512_p3() {
    tmp_35_fu_512_p3 = n_V.read().range(34, 34);
}

void digitrec_bitcount::thread_tmp_36_fu_524_p3() {
    tmp_36_fu_524_p3 = n_V.read().range(35, 35);
}

void digitrec_bitcount::thread_tmp_37_fu_536_p3() {
    tmp_37_fu_536_p3 = n_V.read().range(36, 36);
}

void digitrec_bitcount::thread_tmp_38_fu_548_p3() {
    tmp_38_fu_548_p3 = n_V.read().range(37, 37);
}

void digitrec_bitcount::thread_tmp_39_fu_560_p3() {
    tmp_39_fu_560_p3 = n_V.read().range(38, 38);
}

void digitrec_bitcount::thread_tmp_3_fu_128_p3() {
    tmp_3_fu_128_p3 = n_V.read().range(2, 2);
}

void digitrec_bitcount::thread_tmp_40_fu_572_p3() {
    tmp_40_fu_572_p3 = n_V.read().range(39, 39);
}

void digitrec_bitcount::thread_tmp_41_fu_584_p3() {
    tmp_41_fu_584_p3 = n_V.read().range(40, 40);
}

void digitrec_bitcount::thread_tmp_42_fu_596_p3() {
    tmp_42_fu_596_p3 = n_V.read().range(41, 41);
}

void digitrec_bitcount::thread_tmp_43_fu_608_p3() {
    tmp_43_fu_608_p3 = n_V.read().range(42, 42);
}

void digitrec_bitcount::thread_tmp_44_fu_620_p3() {
    tmp_44_fu_620_p3 = n_V.read().range(43, 43);
}

void digitrec_bitcount::thread_tmp_45_fu_632_p3() {
    tmp_45_fu_632_p3 = n_V.read().range(44, 44);
}

void digitrec_bitcount::thread_tmp_46_fu_644_p3() {
    tmp_46_fu_644_p3 = n_V.read().range(45, 45);
}

void digitrec_bitcount::thread_tmp_47_cast_fu_688_p1() {
    tmp_47_cast_fu_688_p1 = esl_zext<2,1>(tmp_49_fu_680_p3.read());
}

void digitrec_bitcount::thread_tmp_47_fu_656_p3() {
    tmp_47_fu_656_p3 = n_V.read().range(46, 46);
}

void digitrec_bitcount::thread_tmp_48_fu_668_p3() {
    tmp_48_fu_668_p3 = n_V.read().range(47, 47);
}

void digitrec_bitcount::thread_tmp_49_fu_680_p3() {
    tmp_49_fu_680_p3 = n_V.read().range(48, 48);
}

void digitrec_bitcount::thread_tmp_4_fu_140_p3() {
    tmp_4_fu_140_p3 = n_V.read().range(3, 3);
}

void digitrec_bitcount::thread_tmp_5_fu_152_p3() {
    tmp_5_fu_152_p3 = n_V.read().range(4, 4);
}

void digitrec_bitcount::thread_tmp_6_fu_164_p3() {
    tmp_6_fu_164_p3 = n_V.read().range(5, 5);
}

void digitrec_bitcount::thread_tmp_7_fu_176_p3() {
    tmp_7_fu_176_p3 = n_V.read().range(6, 6);
}

void digitrec_bitcount::thread_tmp_8_fu_188_p3() {
    tmp_8_fu_188_p3 = n_V.read().range(7, 7);
}

void digitrec_bitcount::thread_tmp_9_fu_200_p3() {
    tmp_9_fu_200_p3 = n_V.read().range(8, 8);
}

void digitrec_bitcount::thread_tmp_cast_fu_886_p1() {
    tmp_cast_fu_886_p1 = esl_zext<6,5>(tmp_fu_880_p2.read());
}

void digitrec_bitcount::thread_tmp_fu_880_p2() {
    tmp_fu_880_p2 = (!tmp1_cast_fu_782_p1.read().is_01() || !tmp12_cast_fu_876_p1.read().is_01())? sc_lv<5>(): (sc_biguint<5>(tmp1_cast_fu_782_p1.read()) + sc_biguint<5>(tmp12_cast_fu_876_p1.read()));
}

}

