// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="digitrec,hls_ip_2016_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=5.697500,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=96,HLS_SYN_DSP=0,HLS_SYN_FF=322,HLS_SYN_LUT=589}" *)

module digitrec (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input_V,
        ap_return
);

parameter    ap_ST_st1_fsm_0 = 8'b1;
parameter    ap_ST_st2_fsm_1 = 8'b10;
parameter    ap_ST_st3_fsm_2 = 8'b100;
parameter    ap_ST_st4_fsm_3 = 8'b1000;
parameter    ap_ST_st5_fsm_4 = 8'b10000;
parameter    ap_ST_st6_fsm_5 = 8'b100000;
parameter    ap_ST_st7_fsm_6 = 8'b1000000;
parameter    ap_ST_st8_fsm_7 = 8'b10000000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv32_3 = 32'b11;
parameter    ap_const_lv32_4 = 32'b100;
parameter    ap_const_lv32_5 = 32'b101;
parameter    ap_const_lv4_0 = 4'b0000;
parameter    ap_const_lv3_0 = 3'b000;
parameter    ap_const_lv11_0 = 11'b00000000000;
parameter    ap_const_lv32_6 = 32'b110;
parameter    ap_const_lv15_0 = 15'b000000000000000;
parameter    ap_const_lv32_7 = 32'b111;
parameter    ap_const_lv6_32 = 6'b110010;
parameter    ap_const_lv4_A = 4'b1010;
parameter    ap_const_lv4_1 = 4'b1;
parameter    ap_const_lv2_0 = 2'b00;
parameter    ap_const_lv3_5 = 3'b101;
parameter    ap_const_lv3_1 = 3'b1;
parameter    ap_const_lv11_708 = 11'b11100001000;
parameter    ap_const_lv11_1 = 11'b1;
parameter    ap_const_lv15_708 = 15'b11100001000;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [48:0] input_V;
output  [3:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
reg    ap_sig_cseq_ST_st1_fsm_0;
reg    ap_sig_23;
wire   [14:0] training_data_V_address0;
reg    training_data_V_ce0;
wire   [47:0] training_data_V_q0;
wire   [3:0] i_1_fu_181_p2;
reg   [3:0] i_1_reg_287;
reg    ap_sig_cseq_ST_st2_fsm_1;
reg    ap_sig_51;
wire   [6:0] tmp_4_fu_203_p2;
reg   [6:0] tmp_4_reg_292;
wire   [0:0] exitcond2_fu_175_p2;
wire   [2:0] k_1_fu_215_p2;
reg    ap_sig_cseq_ST_st3_fsm_2;
reg    ap_sig_66;
wire   [14:0] i4_cast3_fu_235_p1;
reg   [14:0] i4_cast3_reg_305;
reg    ap_sig_cseq_ST_st4_fsm_3;
reg    ap_sig_75;
wire   [10:0] i_2_fu_245_p2;
reg   [10:0] i_2_reg_313;
wire   [3:0] j_1_fu_257_p2;
reg   [3:0] j_1_reg_321;
reg    ap_sig_cseq_ST_st5_fsm_4;
reg    ap_sig_86;
wire   [14:0] next_mul_fu_263_p2;
reg   [14:0] next_mul_reg_326;
wire   [0:0] exitcond_fu_251_p2;
reg   [47:0] training_instance_V_reg_336;
reg    ap_sig_cseq_ST_st6_fsm_5;
reg    ap_sig_101;
reg   [5:0] knn_set_V_address0;
reg    knn_set_V_ce0;
reg    knn_set_V_we0;
reg   [5:0] knn_set_V_d0;
wire   [5:0] knn_set_V_q0;
wire    grp_digitrec_update_knn_fu_160_ap_start;
wire    grp_digitrec_update_knn_fu_160_ap_done;
wire    grp_digitrec_update_knn_fu_160_ap_idle;
wire    grp_digitrec_update_knn_fu_160_ap_ready;
wire   [5:0] grp_digitrec_update_knn_fu_160_min_distances_V_address0;
wire    grp_digitrec_update_knn_fu_160_min_distances_V_ce0;
wire    grp_digitrec_update_knn_fu_160_min_distances_V_we0;
wire   [5:0] grp_digitrec_update_knn_fu_160_min_distances_V_d0;
wire    grp_digitrec_knn_vote_fu_170_ap_start;
wire    grp_digitrec_knn_vote_fu_170_ap_done;
wire    grp_digitrec_knn_vote_fu_170_ap_idle;
wire    grp_digitrec_knn_vote_fu_170_ap_ready;
wire   [5:0] grp_digitrec_knn_vote_fu_170_knn_set_V_address0;
wire    grp_digitrec_knn_vote_fu_170_knn_set_V_ce0;
wire   [3:0] grp_digitrec_knn_vote_fu_170_ap_return;
reg   [3:0] i_reg_104;
wire   [0:0] exitcond4_fu_209_p2;
reg   [2:0] k_reg_115;
reg   [10:0] i4_reg_126;
reg   [3:0] j_reg_137;
wire   [0:0] exitcond3_fu_239_p2;
reg    ap_sig_cseq_ST_st7_fsm_6;
reg    ap_sig_165;
reg   [14:0] phi_mul_reg_149;
reg    ap_reg_grp_digitrec_update_knn_fu_160_ap_start;
reg    ap_reg_grp_digitrec_knn_vote_fu_170_ap_start;
reg    ap_sig_cseq_ST_st8_fsm_7;
reg    ap_sig_184;
wire   [63:0] tmp_15_cast_fu_230_p1;
wire   [63:0] tmp_3_fu_274_p1;
wire   [5:0] tmp_s_fu_191_p3;
wire   [6:0] tmp_cast_fu_187_p1;
wire   [6:0] p_shl_cast_fu_199_p1;
wire   [6:0] tmp_cast_6_fu_221_p1;
wire   [6:0] tmp_7_fu_225_p2;
wire   [14:0] tmp_2_fu_269_p2;
reg   [7:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 8'b1;
#0 ap_reg_grp_digitrec_update_knn_fu_160_ap_start = 1'b0;
#0 ap_reg_grp_digitrec_knn_vote_fu_170_ap_start = 1'b0;
end

digitrec_training_data_V #(
    .DataWidth( 48 ),
    .AddressRange( 18000 ),
    .AddressWidth( 15 ))
training_data_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(training_data_V_address0),
    .ce0(training_data_V_ce0),
    .q0(training_data_V_q0)
);

digitrec_knn_set_V #(
    .DataWidth( 6 ),
    .AddressRange( 50 ),
    .AddressWidth( 6 ))
knn_set_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(knn_set_V_address0),
    .ce0(knn_set_V_ce0),
    .we0(knn_set_V_we0),
    .d0(knn_set_V_d0),
    .q0(knn_set_V_q0)
);

digitrec_update_knn grp_digitrec_update_knn_fu_160(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_digitrec_update_knn_fu_160_ap_start),
    .ap_done(grp_digitrec_update_knn_fu_160_ap_done),
    .ap_idle(grp_digitrec_update_knn_fu_160_ap_idle),
    .ap_ready(grp_digitrec_update_knn_fu_160_ap_ready),
    .test_inst_V(input_V),
    .train_inst_V(training_instance_V_reg_336),
    .min_distances_V_address0(grp_digitrec_update_knn_fu_160_min_distances_V_address0),
    .min_distances_V_ce0(grp_digitrec_update_knn_fu_160_min_distances_V_ce0),
    .min_distances_V_we0(grp_digitrec_update_knn_fu_160_min_distances_V_we0),
    .min_distances_V_d0(grp_digitrec_update_knn_fu_160_min_distances_V_d0),
    .min_distances_V_q0(knn_set_V_q0),
    .tmp_4(j_reg_137)
);

digitrec_knn_vote grp_digitrec_knn_vote_fu_170(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_digitrec_knn_vote_fu_170_ap_start),
    .ap_done(grp_digitrec_knn_vote_fu_170_ap_done),
    .ap_idle(grp_digitrec_knn_vote_fu_170_ap_idle),
    .ap_ready(grp_digitrec_knn_vote_fu_170_ap_ready),
    .knn_set_V_address0(grp_digitrec_knn_vote_fu_170_knn_set_V_address0),
    .knn_set_V_ce0(grp_digitrec_knn_vote_fu_170_knn_set_V_ce0),
    .knn_set_V_q0(knn_set_V_q0),
    .ap_return(grp_digitrec_knn_vote_fu_170_ap_return)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_grp_digitrec_knn_vote_fu_170_ap_start <= 1'b0;
    end else begin
        if (((1'b1 == ap_sig_cseq_ST_st4_fsm_3) & ~(1'b0 == exitcond3_fu_239_p2))) begin
            ap_reg_grp_digitrec_knn_vote_fu_170_ap_start <= 1'b1;
        end else if ((1'b1 == grp_digitrec_knn_vote_fu_170_ap_ready)) begin
            ap_reg_grp_digitrec_knn_vote_fu_170_ap_start <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_grp_digitrec_update_knn_fu_160_ap_start <= 1'b0;
    end else begin
        if ((1'b1 == ap_sig_cseq_ST_st6_fsm_5)) begin
            ap_reg_grp_digitrec_update_knn_fu_160_ap_start <= 1'b1;
        end else if ((1'b1 == grp_digitrec_update_knn_fu_160_ap_ready)) begin
            ap_reg_grp_digitrec_update_knn_fu_160_ap_start <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & ~(exitcond2_fu_175_p2 == 1'b0))) begin
        i4_reg_126 <= ap_const_lv11_0;
    end else if (((1'b1 == ap_sig_cseq_ST_st5_fsm_4) & ~(1'b0 == exitcond_fu_251_p2))) begin
        i4_reg_126 <= i_2_reg_313;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == 1'b0))) begin
        i_reg_104 <= ap_const_lv4_0;
    end else if (((1'b1 == ap_sig_cseq_ST_st3_fsm_2) & ~(1'b0 == exitcond4_fu_209_p2))) begin
        i_reg_104 <= i_1_reg_287;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st7_fsm_6) & ~(1'b0 == grp_digitrec_update_knn_fu_160_ap_done))) begin
        j_reg_137 <= j_1_reg_321;
    end else if (((1'b1 == ap_sig_cseq_ST_st4_fsm_3) & (1'b0 == exitcond3_fu_239_p2))) begin
        j_reg_137 <= ap_const_lv4_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st3_fsm_2) & (1'b0 == exitcond4_fu_209_p2))) begin
        k_reg_115 <= k_1_fu_215_p2;
    end else if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & (exitcond2_fu_175_p2 == 1'b0))) begin
        k_reg_115 <= ap_const_lv3_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st7_fsm_6) & ~(1'b0 == grp_digitrec_update_knn_fu_160_ap_done))) begin
        phi_mul_reg_149 <= next_mul_reg_326;
    end else if (((1'b1 == ap_sig_cseq_ST_st4_fsm_3) & (1'b0 == exitcond3_fu_239_p2))) begin
        phi_mul_reg_149 <= ap_const_lv15_0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        i4_cast3_reg_305[10 : 0] <= i4_cast3_fu_235_p1[10 : 0];
        i_2_reg_313 <= i_2_fu_245_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        i_1_reg_287 <= i_1_fu_181_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        j_1_reg_321 <= j_1_fu_257_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st5_fsm_4) & (1'b0 == exitcond_fu_251_p2))) begin
        next_mul_reg_326 <= next_mul_fu_263_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & (exitcond2_fu_175_p2 == 1'b0))) begin
        tmp_4_reg_292 <= tmp_4_fu_203_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_sig_cseq_ST_st6_fsm_5)) begin
        training_instance_V_reg_336 <= training_data_V_q0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st8_fsm_7) & ~(1'b0 == grp_digitrec_knn_vote_fu_170_ap_done))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_start) & (1'b1 == ap_sig_cseq_ST_st1_fsm_0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st8_fsm_7) & ~(1'b0 == grp_digitrec_knn_vote_fu_170_ap_done))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_23) begin
        ap_sig_cseq_ST_st1_fsm_0 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st1_fsm_0 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_51) begin
        ap_sig_cseq_ST_st2_fsm_1 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st2_fsm_1 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_66) begin
        ap_sig_cseq_ST_st3_fsm_2 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st3_fsm_2 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_75) begin
        ap_sig_cseq_ST_st4_fsm_3 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st4_fsm_3 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_86) begin
        ap_sig_cseq_ST_st5_fsm_4 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st5_fsm_4 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_101) begin
        ap_sig_cseq_ST_st6_fsm_5 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st6_fsm_5 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_165) begin
        ap_sig_cseq_ST_st7_fsm_6 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st7_fsm_6 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_184) begin
        ap_sig_cseq_ST_st8_fsm_7 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st8_fsm_7 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        knn_set_V_address0 = tmp_15_cast_fu_230_p1;
    end else if ((1'b1 == ap_sig_cseq_ST_st8_fsm_7)) begin
        knn_set_V_address0 = grp_digitrec_knn_vote_fu_170_knn_set_V_address0;
    end else if ((1'b1 == ap_sig_cseq_ST_st7_fsm_6)) begin
        knn_set_V_address0 = grp_digitrec_update_knn_fu_160_min_distances_V_address0;
    end else begin
        knn_set_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        knn_set_V_ce0 = 1'b1;
    end else if ((1'b1 == ap_sig_cseq_ST_st8_fsm_7)) begin
        knn_set_V_ce0 = grp_digitrec_knn_vote_fu_170_knn_set_V_ce0;
    end else if ((1'b1 == ap_sig_cseq_ST_st7_fsm_6)) begin
        knn_set_V_ce0 = grp_digitrec_update_knn_fu_160_min_distances_V_ce0;
    end else begin
        knn_set_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        knn_set_V_d0 = ap_const_lv6_32;
    end else if ((1'b1 == ap_sig_cseq_ST_st7_fsm_6)) begin
        knn_set_V_d0 = grp_digitrec_update_knn_fu_160_min_distances_V_d0;
    end else begin
        knn_set_V_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st3_fsm_2) & (1'b0 == exitcond4_fu_209_p2))) begin
        knn_set_V_we0 = 1'b1;
    end else if ((1'b1 == ap_sig_cseq_ST_st7_fsm_6)) begin
        knn_set_V_we0 = grp_digitrec_update_knn_fu_160_min_distances_V_we0;
    end else begin
        knn_set_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        training_data_V_ce0 = 1'b1;
    end else begin
        training_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : begin
            if (~(ap_start == 1'b0)) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        end
        ap_ST_st2_fsm_1 : begin
            if ((exitcond2_fu_175_p2 == 1'b0)) begin
                ap_NS_fsm = ap_ST_st3_fsm_2;
            end else begin
                ap_NS_fsm = ap_ST_st4_fsm_3;
            end
        end
        ap_ST_st3_fsm_2 : begin
            if (~(1'b0 == exitcond4_fu_209_p2)) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st3_fsm_2;
            end
        end
        ap_ST_st4_fsm_3 : begin
            if ((1'b0 == exitcond3_fu_239_p2)) begin
                ap_NS_fsm = ap_ST_st5_fsm_4;
            end else begin
                ap_NS_fsm = ap_ST_st8_fsm_7;
            end
        end
        ap_ST_st5_fsm_4 : begin
            if (~(1'b0 == exitcond_fu_251_p2)) begin
                ap_NS_fsm = ap_ST_st4_fsm_3;
            end else begin
                ap_NS_fsm = ap_ST_st6_fsm_5;
            end
        end
        ap_ST_st6_fsm_5 : begin
            ap_NS_fsm = ap_ST_st7_fsm_6;
        end
        ap_ST_st7_fsm_6 : begin
            if (~(1'b0 == grp_digitrec_update_knn_fu_160_ap_done)) begin
                ap_NS_fsm = ap_ST_st5_fsm_4;
            end else begin
                ap_NS_fsm = ap_ST_st7_fsm_6;
            end
        end
        ap_ST_st8_fsm_7 : begin
            if (~(1'b0 == grp_digitrec_knn_vote_fu_170_ap_done)) begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end else begin
                ap_NS_fsm = ap_ST_st8_fsm_7;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_return = grp_digitrec_knn_vote_fu_170_ap_return;

always @ (*) begin
    ap_sig_101 = (1'b1 == ap_CS_fsm[ap_const_lv32_5]);
end

always @ (*) begin
    ap_sig_165 = (1'b1 == ap_CS_fsm[ap_const_lv32_6]);
end

always @ (*) begin
    ap_sig_184 = (1'b1 == ap_CS_fsm[ap_const_lv32_7]);
end

always @ (*) begin
    ap_sig_23 = (ap_CS_fsm[ap_const_lv32_0] == 1'b1);
end

always @ (*) begin
    ap_sig_51 = (1'b1 == ap_CS_fsm[ap_const_lv32_1]);
end

always @ (*) begin
    ap_sig_66 = (1'b1 == ap_CS_fsm[ap_const_lv32_2]);
end

always @ (*) begin
    ap_sig_75 = (1'b1 == ap_CS_fsm[ap_const_lv32_3]);
end

always @ (*) begin
    ap_sig_86 = (1'b1 == ap_CS_fsm[ap_const_lv32_4]);
end

assign exitcond2_fu_175_p2 = ((i_reg_104 == ap_const_lv4_A) ? 1'b1 : 1'b0);

assign exitcond3_fu_239_p2 = ((i4_reg_126 == ap_const_lv11_708) ? 1'b1 : 1'b0);

assign exitcond4_fu_209_p2 = ((k_reg_115 == ap_const_lv3_5) ? 1'b1 : 1'b0);

assign exitcond_fu_251_p2 = ((j_reg_137 == ap_const_lv4_A) ? 1'b1 : 1'b0);

assign grp_digitrec_knn_vote_fu_170_ap_start = ap_reg_grp_digitrec_knn_vote_fu_170_ap_start;

assign grp_digitrec_update_knn_fu_160_ap_start = ap_reg_grp_digitrec_update_knn_fu_160_ap_start;

assign i4_cast3_fu_235_p1 = i4_reg_126;

assign i_1_fu_181_p2 = (i_reg_104 + ap_const_lv4_1);

assign i_2_fu_245_p2 = (i4_reg_126 + ap_const_lv11_1);

assign j_1_fu_257_p2 = (j_reg_137 + ap_const_lv4_1);

assign k_1_fu_215_p2 = (k_reg_115 + ap_const_lv3_1);

assign next_mul_fu_263_p2 = (phi_mul_reg_149 + ap_const_lv15_708);

assign p_shl_cast_fu_199_p1 = tmp_s_fu_191_p3;

assign tmp_15_cast_fu_230_p1 = tmp_7_fu_225_p2;

assign tmp_2_fu_269_p2 = (i4_cast3_reg_305 + phi_mul_reg_149);

assign tmp_3_fu_274_p1 = tmp_2_fu_269_p2;

assign tmp_4_fu_203_p2 = (tmp_cast_fu_187_p1 + p_shl_cast_fu_199_p1);

assign tmp_7_fu_225_p2 = (tmp_4_reg_292 + tmp_cast_6_fu_221_p1);

assign tmp_cast_6_fu_221_p1 = k_reg_115;

assign tmp_cast_fu_187_p1 = i_reg_104;

assign tmp_s_fu_191_p3 = {{i_reg_104}, {ap_const_lv2_0}};

assign training_data_V_address0 = tmp_3_fu_274_p1;

always @ (posedge ap_clk) begin
    i4_cast3_reg_305[14:11] <= 4'b0000;
end

endmodule //digitrec
